#!/usr/bin/env python3
"""
FP16 Flash Attention K14: Cache Configuration  — RTX 3060 SM86
Auto-generated by gen_inline.py from kernels/src_14

Run (WSL):
  cd /mnt/d/GITHUB/Mini-Attention
  LD_LIBRARY_PATH=/root/fa_env/lib/python3.12/site-packages/torch/lib \
    /root/fa_env/bin/python kernels/flash_attn/cuda/inline/fp16_k14_sm86.py
"""

import base64, bz2, os, sys, time
from pathlib import Path

os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")

import torch
import torch.nn.functional as F
from torch.utils.cpp_extension import load

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "py"))
from flash_helpers.kernel_configs import (
    DType, FlashForwardKernelConfig, get_kernel_progression_configs,
)
from flash_helpers.kernel_configs import get_kernel_configs

# ── Embedded CUDA source (bzip2 + base64) ────────────────────────────────
_CUDA_B64 = (
    "QlpoOTFBWSZTWR+T9MQALjj/gG/f//7//////+///7////5gaL7zw9sCH2BXet99vTbPX2312eja"
    "ze0qqbYq9gUDBW2DoOLoL2Boit7r3t77N96+efGepQ8PoA1u45C333cve3nuwA719tyE7OvrOy8v"
    "HXznlu+4+h73bd6XWeeve9c+88fGeu33Oue119ccuAn0ve5Vt913Pe9d53Z3eee92922ded93se6"
    "u33vDp33eue2N9V9ge+X0q+5OT6160a2te24UYgatT24Pgg+G+949HV3u+7321Ur2z3jupK9bbd2"
    "247St03UJ052RmM1Gtpq1uCd1j77velfI4bt2aMbNuZlFwjdM62tia+HKhsdq3cd2ymFEQmg2VaZ"
    "5GZuvreSt5c621unbuCU0ggAQAmEAETaIaek0pvJDEQxGnqGjTRoyGjRkDRiCU0TQTQQgJk0qfkK"
    "eRqe0U9pNT0mZTTQAaA9QA0AaaAxGhoJNJEhASbJqYmhTzSNMmqflTwk/Sm1PSaDNJ7VGTymnqNN"
    "qGgyNB6mmhoCT1UkSKn7U1T9MqP0FG1NNNBptRhPUGI9QGgHqAAAaaDIAaaaAiSIRpNDENCU/TFK"
    "e9VT/aJ6Eps0aJoYU2qb9U9MkZT2U0yTxIG1G1AM0CJEggCARpqYm0mqeTNTExNEybUyT9U/Sn6o"
    "8FG0yg9IeoNAABnUIIj++CCieHxJ/rGQT+UColo1BJSaxYUBdLjaZvotcYsYrtzjKkiQTUUFdnFW"
    "mIqkqSsGo2iIidXLT+E/F+7f/HLn+595/nJ5M7ezlhtYjmcrq5FHFHkmQxrjMENENvczjYu7afWm"
    "a53egrBVQTnxQMYuuMyCME6f0/zP69GosVQnJDqTFYkDoSCIiHFSv4vsXek/g/0P/a4q0TapX8P4"
    "Z69PvGeF1et6ec4jsvF0gvGcURbtmKaZxHx89ExtUqVDoZcs3wW4Q1J/Wwqx1zyZBcE3ZmCJ/zra"
    "hqJRx1msCmWVqsyllTFxpeX8chqJ2Gw6/CnLsOcMXnDoq0WlWy23tLmFACiQhTv3r9e+7jhlEWbH"
    "VjEpzzWtYiv+jqoGJRrFltiLFEtCmqVUMpmWszKROqNSYcv251dMiuMSzbnOAEQQ12c0TTJumwmu"
    "DnHFzmiMdKHXLp5GvNNQSElY1Gkc5cwmUJFXlL+s8gC6QF01lyQnLTtu9K1zprSVgIRufXqhLoze"
    "gzbJh13eUo8Wx3aarwdTo8A2kewdByMkx5WWJx0zMVrDSZLSwrVERii97yZJgahuzgegR2ze8cKh"
    "bLEUZJxU1RwzCojDn2+jya1rWta1rWta1rWta1rWta1rWtbGta1rWtt0c2EYgKQF63rSTcvhED+2"
    "zg9pwHi3RR+fKwtmOeKIXz5lFw1SXhAS/Y4B57YHIeMoLBOA7jqw1BJcgQkfpscMzBKGA0u4OhxT"
    "guF4etVSVlcwImhVhBOZDlQmYliA7IrpkQhCDJce4VGa7FYaz65M0SKMzaC/asaBh1ngFAmGpTgo"
    "fZ/VrzIdcQWQ5BlHssPvoZj7zICwTMWN3LJLv/y80f19HVAp3o3nns651weM+V8f3e/W/AgRNQlE"
    "vf8fkXX/vXb3mqMCajxVKlWkqST5fLOgzoCxJjKlTCWPJ4ebv5f/XfWi/otp1VlVY9cHiGERYwCB"
    "xy9kr3tigC4dLZFUlQsCoDE9xnP/3TtylSKE+rjphOT0Tq9AxSCMRYsak0yOajXNcAJCUfPpRABs"
    "oqnbFBFuVQqKtRBYgHJCT7TKwFMtFGU41wEh5mAPK/QMCIwhwwLBQFh2oSUZF6DdrmAnO4f9d0Ny"
    "4mG+KIMsG55DjcH829ygxwd+iZM49RSIybYHmYGQEYCiQZ2ff6XRwjCJy2ZB014zaeHot1e479wU"
    "QBhDnkUFWOS3AbiYBnO3k2vwLhihmWjPCfsUeth7Ag4UAsfvMA+2h3d5IQvzfsNKlBDeU3N/AQCD"
    "gm8xBsxWNgCtcxp49Z1CdUc4DH6aboyM8qdodfOEh9XKLyTmamm5pf9Vo9DWBcovdxptUIRYjQH8"
    "lP3vGsfJRWdHMgWdcOiyTMKdkJhw9EF3mtjqNRm1kSVAkJJx4j0kY5yM26tk4nWKwQ45XQCn0+KS"
    "vpIq0n+/v75UrtMSB91z4IW4T/pa8uIcqd/6ioc4bUNoXTBgyTatJnaDMJbca9KG0FLz2oeE3dpZ"
    "zOfmMYzlS9A+J6QAfMGJP41jhpgfsn3a6sIFvSNMXP5yHoYKHxYLS4W7o4ufoj1CRMfiOO3CnaKB"
    "2yjVdCv/TVSES2sp973c79m/8NnZxAPdPHve6ffAK9vgJ8sU2Kxj81NRCCIkSCL71ApRjz1x/+fi"
    "xOv/LgT8N8ttclbfo5mnr0r5jMWpawc4r7CBVlM+j+vKrwICxm6+qJOQnYH+R6VC9WQ2YEHwZvRj"
    "PBEykbYdmPftfcPTZpfabdJ9jd5tTajPVmEaIQgKoghnAAQgBSElQhQCmWvCw7c9Nr+KHPnVxAZZ"
    "1V2alMVZmZmbFbHlvi7l7sADFLdf1duvF/rvi/BwIdJXm6RSrunqzp2fJ+J2+iHb4fwdrnmKvO3n"
    "b1fDFl/70WH7WSqIyFhcunGuvRvbziG+OH6/n39huux9p84MNYgv01Bgb73+d/Z/v/z+HjRYF6Xr"
    "4ive/VJNOzS4JHQQdrscRyB70R2V23FtsNlund9h1y5yWfcGbITaZkFQOkJZ6Dtc9Ou3obLXOo8/"
    "pGyGxsbM/Ju/TUmyzwoiaLxEaxM8oO15uo3RrEbSyXn17luvZteB8xjbBIuz0s1O7P4PPtPVnrxn"
    "OtmavU7FxB5qTDabc993ihJYTEYRlE1opovPqWk3i10aJQKY6J1EdzfNturaoXOiELi8qWC+NI7t"
    "XZnj05iykv5m1CZfs+MJ67s9WedfQZN/B6tYybMddCHtpejSHf3v2CAoyN0F9ezxPHyWw/FKTdvs"
    "30fNpykQPmxpNcWoUckeSFeWjUCI3wYn3gwzlDKl3i6O3b5qPHsLfQuXoKGKA2eS2bZjHmx7LmOQ"
    "Uv2jA7F5xMa/J78nyfBitJETMzS0dQ/Von6pn6Pk3xh+RaMI6sOxRhJCAX1lyVxUCbBSokeRypWr"
    "2RvQLkBsNhmqhoKbZ+v6o5K/DT4ejlY/Q9oVaE7VahWOOj6NGWaadVsUhvWqAVQsPUnXSsMQGiLM"
    "YFAsi7XEPL4elLRUpUSEhEPZEJ3I0zCdLCvdIFrzW0zwjCFVzD4S2uenW/PRXo0c7jqs097DEECC"
    "FGFUKR9BHJtylmvtEYsdnhPUbVKxVZOlp7HmAZca/ZWxVFckCAa5rSSjiZwQJpds2ONn6KPDqs3B"
    "jzkGTV2Ruw7zWtKmwdPVbl0fufS+BMklmK2taKRWzJMtC8xBEdFr5Y7bO6w9WvwPN66CrjDMPz6D"
    "8Yg6+qN7u60HdIWvjuGlJFuWNXHXYxGh1Ue2G9tVL1GeHlwcKJqM2pQnPVFmq3fXsy9OkZDkqs0a"
    "3z13c/Hc5j3l5ZTqEzLFBtUS3ING7A4dWlo3Y5sWn0u7uNnq19JxIRDjwpUISTGgmTpb+zvzFNlu"
    "rJzA0EEGFShYLG8smK1TbJ0yQkkxYvawdjQdZQICShmwQMrj5ibwzgXTDJDFyXKs6SworXxgs6qd"
    "Q1iwehMCSSQkJJJFzSz4+GIOB43mtu6+5mYhqc/DOtRV4E2H5Vd3jmduzY3dmML3GD5oaAt+yMFF"
    "dM2Bxhy5392oxoiOI68oZRMGDP12VXMUDoTDsLmYp+n3yY1084aecjB+gkc2BeQmiKZ+fk5GUoPi"
    "P0lMG2kxqIXsQ+dHkqlX0UcoyEKKij6fexPw9pIzDnsKaWlrw1rCOeEa3w9UI7CjVptg3cbx+Y6m"
    "wy2XYYvC9C4SY4sMMR3doh76zMdQ7Dss6E6Ibn06dLNqSbaUb3xHI6OcJmIQ3dDdV69+kHK1ul0A"
    "iNixZejujVXthCXy78BzeSljTjnPmqzYfFJ0quM8Ig4X5srnzaMFM1RLRMKY93u5L5TsnZz/BSvZ"
    "b1pjFN2Qm97DN1be+4QtPHpnAqhoyhxnEJczuNfx4smYTBnLNuW2mp6qJxjFc9znnkDbemtmSOnQ"
    "BXL0swFgMBS1uDmxXwpwIbTqa2siTGn6mpINEVVMD/PFtOyba4OT5zsIFDdXZhvmzzC6rVUBqW2Y"
    "pHlyqMcUCCjJJhvS/T4dOyLXmzqMnOOROLnTpvyipv1Wu/rcx+3KZhTZrWvdWX0wS+hmYiNBNjiW"
    "2s8BU4KaAUw23w8LXmo0GFwAxCdCdAy2lsTap55XMEmHqkSMbrtM7KX2er4rNlZ7i7ss3pTtpLR8"
    "+jNx0V57Lvn15YB3GvKOXqIc9E5zJJ+exi8ztnZ8lRLd31uxp0ZkHjXXzqYOmV0Hb1WVWVFJyaAX"
    "KzdIC4zcf1evEzggPRe9FL+ve+GWrzRwYxHLCLsnE7J2eORFoMZg7sa8HMb4WtTIOdFNRVvhWUcS"
    "bDl6MkxTCsPSn4b19O8/IevnDp1UUssrVUECslFjWojPktuWXrlxmmWAkQUtHVERMlLbatgpca24"
    "njJk8/g+5fI7jKg4amsaVKLkZqaoTkR6u6PbOqiJBLTgkgPTk2WRQFATUGXF+mkaY5tZnLsdPLTx"
    "9cZv5zvxM6QzKrlcQgAhJLCU+rrQINlbaM5RSK3DGhrqT4LWtaMzVaWaWsOWaNOTd+UO7YOZ2YXh"
    "qlEHUd5qNkNC6tT8jH047GWbcsGpSxWtHRODV6tRUb4S30PKdWfcYN9Hf4eGEaZlQ4YzpJEoN1ca"
    "DgAmN6bNlneFDTGIgGiO9adLOmZXuIsvRGesB5sSrLkGmLRq5QWECjomQRPx91a4cthr1feeVXNi"
    "WFXyk6TB9SkJfW+X4CMNhdT1xKJdUPjSU4iTusuEGe/ZyTnw2dsdM5icNqNirqy4d40fdmhbpz6s"
    "+9JJJJJJJJJJJLNGCHUxWZnhuNrTxpB8kFiagiYlRmJbtOzXPtbM3eVhaYchnGqRTIRjmsvVeacX"
    "L8j01Q+EZijBQ06aqmwKEaYtEyWnz3V0h3Fz0ZMaDS0Wptf/6RgVOL1yjp36I+NzFUDpEhDidDp3"
    "rUCDtkRA1JmlnWZI0UZOapQd92qxoTrY96+0j5Lx7KnKWtbnnPSg0FBKI9WwlYoz3bmtPSnQkMvF"
    "FYHWHM+q3bUnshwm+hwurkULpunyKMzBOj2gxoVnt+YKaaSxhGWSWGbCZGDU0EreRF4Qi9E9Pots"
    "oaOXka8+OopjVdx4u3MmLDZkZbismY36uuuprnD4V7CihJKowkz47yEN3GZ1i+raLX7aU5yiZ0rI"
    "7zWennt2VjFc3xOItYUbG2uqS1QCQvE10NtnqWrh8vWAmkavYQ9LQYUdhc7hfRnuJKGvi93q5zPX"
    "dubK26PKpYjXFi9GZP5IuaLN3Xa/GN7CQwfR6XFtcauRYobt3w7vI30UCL/YoZ6nY8Dc8u/6NvA8"
    "1sUZccqY0ZVgWhD2aJe8Q0KrrlnVBwDPcY4OeVIInOCpIKKmt0CJnlp8fOV28HLoQ0skhGKxCRGR"
    "AkQx3uNfb21kMsznyxtzQnBlsfpOpCaBaCEFtR6dFkzwwmQZ7l5r8mA4IwIUzHbjpObMx1nhY1B4"
    "eFHTAKCLD6CxUSHTJ7ADy7+j/T9Hce/QopefOvtqJ6bZ88NrHaKO9+LGKjYwHtDrMI8c64tbsfzX"
    "802F+xOQAqic/ulgNceqJhJAaqk+OKbI7dK6JzxqXnR2csZQTbGSQWorCAEgQbVxtjJiMZLaJLFo"
    "okJPjAitohyIdhWom6UT093m+HzoP8T8J/Eh76D9n1k/vpCyGxDxIRD50M7iayFGKqdMRu4/wAiF"
    "o+xR8ATsAK3Fh4X8unfjemn0ul0fP29Hl++2zkYO66WBXo5a5/KR+nmylHMipafj8K7fN+qo+Ki+"
    "xMPisOD0ilOkLd07wmN38NefroUF89B6qWdMYaHDgIsWcBLocGPZqcYBCKve5ARPjE6SU58YQP1A"
    "fqDZZn6sDKURBjRg/7LMrYGGrJ87WLIT/XBhWf7SkqjA/ahBKJjEKdKHhawQAhZCqC6eBSF0IXA+"
    "oj9yIQgj6YBS/0EEfqJ/oMrmpVxWkvlwk0bPcty35daNGjRtjRppaW1NL23ayvhWlk1Sqvwlvlrf"
    "Kl6LU1tY1lIsFQRYKCkPX7w+x/GfsM9ufH8uuch+zCQPuDkrRkWoQpbQJfv8pZmGBhVQOfbijBQk"
    "YPgjKgE189QwcbBGIkjb4tD40f3fNGze0vYyqBmZFmMIWIs8zt56eKX+euKFlzF9ojqPjoodMoyK"
    "nzQtZW45Z99temnXxRi6fDtQhnZ0x2UmhvqJF/r0iUaodi1bUU1r2ooJy4wMMzAwzMMthouUM0ou"
    "dThVUQNAz1CSgopDJ7DufK/E8u9+lqxK2w87GvIcveXLJWdED0jW2LUuQRXXFWoh1g0u0GClIIEr"
    "zmgMWRjSOhglCSjs7RgwQY/EWK5JH9OHIEJBflVqVkYGiHBdasqdUuO7DDUxZ7V5IIAmm/OWUSRw"
    "fmWOJUX1/MHDCNjOJ5VNQDvzN7KvrvmvuQhwi0FWVF3HZ+9tjRYOlgjQb7aiQBmGchAPvNzB+mcz"
    "YkKYFs8Do+9rotars64tYAs2i8gUoc0rjM39eMhe7v6rpFlZ1bu6JxEwtrOwTIwOiipyg6QD3PV3"
    "zxw7INkIEAdRndMjkdJWcVJqQrAjAh7kZiyMldncY3zBpjEB8MioGtLSbbDUPZ+I5FLBYEW0T81u"
    "0jRLF3YTISCUbnhmrH2CzzSpI59c5yKjn26ZWSPwHP902FEdXd0XZ7szB3hRtKRbz4OiVPzl8EWB"
    "Lp+pOQDxQfypjh3O1SOQimTnj1yCDNx+t2hXm64l6ZuZMeeTnWeB0F+2WbiJnZsGBDNw0UX/2HLn"
    "0Gxk2XBqt/NdniOZIpx57MdFe+yqUjrF9zRJEHQhGxM/emZ2pYKrYqf9ENGrxh/DfrOWae9TMPDR"
    "ut/g23mUz65xRleWLGRcKshPTCid1La8muvpLSeM0QGrhng4UOHm+uFRXl+OuOzbp11aJ1Z1ZDMf"
    "ucyFbu7vSu0Xt26Q20ZeukVK67VqcEZsTPcIyQVa26mQxdXvg1C7KH6ezPvTRgmpR3JquJmUAZ0N"
    "MSTuEKU6ovhnts41iwO7uzLk+B16JZuvtBoyAHtTl0Q4yQ9EBh3ib22Mq32NNHzjjjjjjnAxNChQ"
    "4IKhZ0w7MN0RFdWnMsezuHaUHAwaMMMeWOzzGx2X8tHPTkx2y2eLQuOp2qqa+ikMFUxjJZKF2Okw"
    "51ZNoLOPOT6m0Sw9FJRFF7+2Si3jTh8nok6i1KioN60OLm5oK4zbZjbCL4ISyRSAFC7yR1Gh0skJ"
    "3d3aTKGkthpjxrWaQ6zDQefvlmJOysQhCOOcHqWngP39XXehk6Js1cf1eTxui03pSUVq3dz0teTs"
    "9HVemtssasdbHR6zCIljlJQ4jkVrYRh/SVxh6pyCREJMt59awIs+XVSBNHdPATKUSojm4w644V6M"
    "DappoHPFDfHVkjp5+fbPIRj1133S/CmYYEhhvsrkHMHQng6CBwAkiCHRkKCBSAyAn5qUTznV0W+g"
    "ip+4iPSImI9SgkE8dRS1zde8AAAAAAXNSihgYcB/iBhjOw0vb57qpHXEXtXJQp6QmLIy4K2LZUFs"
    "rZUFsrZUFtbUX1+UvtwoGnsTknW/eEdRsJ2PRWvF+jt0FG1vGhUhLo6+uIKqw7w7aRvVRot7cN8o"
    "h3XpVlbNGm34cGk1nTwq7PeLd/XLl/Xix09FjNHvmg4/j8Hh15+V+3BmnIHYOaHAbAcdxawBpimw"
    "hYbnIQNMQcOY/7KzxOe5hhimw3+VlqSSQI+CDPixEzD1pKrlaJXKVVyq9GKZRSGKKKPa3q73NyWd"
    "bsoooBQUFBeJ+BJknYcwp4llV5b5Hr4D0fDznKADygDABgAxVHew0SaTQSUa5vOxjGMYxjGMYxjP"
    "PbVubjFGKMYxjFGKMRo9jv4Xsdt3UaKNFFFH0PRzdKNFGijYiu6fJ9i84AAAAAAAAAAAAAAANVdi"
    "IiIiIgICAhbVCIiIiIiIiIiICAiIiAgIQI5VblVLRES2qWoixEJCTMzDf2oe+ss9eDGgePTomxlz"
    "7XHNHXr7OyuwJ8j2kE2sxsqN6WA0E/avEhuQsoBxWWi5KxSqhu6bUqLdfxTGLueTnqMZfh+bq158"
    "9/Q23S5owzu9xvK7Ohy8siTurTZWI27Ksg5YouH083ZZmbTzxw31946MGrM2DQ4s+eCfekmz+Pwf"
    "mPxTgXnvpGW85kazRca6izRMmV2Tr4aqDwNmeY+iMZaL2uDvwSSSSSBhAAAhOTgAAAAAByra8efK"
    "Tya9n0ez8f3ve9v2vVkVs2+vMYvTRNtmrshlo0JKvZzUnsK4/3UPXztcQrG5mxNppHDaS91cYPOB"
    "NtBQPiBxGPZwqDMTGsQyJuw7uxHbiWRQ5ItJnDzGyat85bcanCujFoWR0oRe5G9oSIcHo3izW8D0"
    "0l4wXGgaGQ42ZuiIDGvua8ngAABAAAF1bVrq2rXXQAAFAAMkOeFBOBQcm/i8lnr9NUw+DwaSrNCW"
    "5SQoW9x9tHiqGd3hl1JLmBBALevl2RK/N3baJWrkaibB8YwfdGwH/vTNSumyaFDv6rOoXXVOFkr6"
    "IdmiUjGzo6vcsu/d9vfjOvSXjHn5T5e3ys277c3tl51yoJ0HWLwYTVl1i+O3HdRI9D5scbnjr7Yy"
    "jlU2v5w2mzo9Z70L8pqxcE1WVvZbljfTJozTqy3MrMvT4g9U8Jr3jlB1Qw0viYKWDMZi13czl2no"
    "owo4iafzxft4HCo8vQlNJ36Z8tOfbx2+v3KYtW0UtpW0hIYLBoVKXsRajCsKwk6pbR3qnrdzvB4H"
    "GZ1Q2339rWMrF7WtOw/nSZzu63od/s+vn01Vd9VdvUYJGYilME6s/zZTrA7Juk09/jXy47XrPhl0"
    "GnSlzNGDwcV7J1G1gxGkGAmifGU8NzNv4ETGLW67xn1Gcztn07c3Lnh8cXNSZ6vUdG8MiDSFUbyB"
    "aFlBDyfu+KJ5ilgq2jNbLbWJS2i0zZptMyJorY21GLWNQVfo80Fhix+Q/aiJk0WPqihIsgwhISKS"
    "UV1ZR/4lhvLq2VClSxCslYsiDoazGFVUTVmmaVU/3aW71aINy4jBKAWrGZW12MKCfnPk6gPUfBfx"
    "+70NLv7uHT6tPdr2GquE92/c8qSHORpG85I9TkPBeuaHYA/LPwWiRdoHIfzBSkISavsc6khDb7GP"
    "1thJ5hVNnucGKcUYGkpa4GNj3y//GJ2JtlD8bACxzHAQ2lzUQ1RMMmjabEaQOkgO2HEjuN3ELDQ2"
    "1R+aFdqGajBClVEiHvebnhwo+38OphPq++yZBtIExrCSyNfq/mgAHVVc4AAcqrnAADlVc4AAAAAN"
    "CIYOrLPBrcsiGo+csyZk0ycK4Hg5mYdAYdIx5oocEXj562wD5WEJ4ie4IaKCzTvPNnqLvk/JxRHV"
    "plQRjhk0yd57D2HsEpXvdI0DLhImMcHIIGAILDgDMOwA6lIVBE27t3k5ZKpmaHjpuQAX19nQaOzZ"
    "JXHFj8+v0n1r7YLBEnpJIEg/6BDtPOKLvSHe94BwUN/ZeYuaiTt/msA9g+oz8MvM9oB8zDS36x/a"
    "yaFjMCwwp2sGd10kDcWXGBmEcserLK8ibiKg/clECJxV4FnPG8xkGTy7iFStxtL3V10UZoiZVsMw"
    "RHjFUeEMxETYZ7LC3FaH8qWhdjr8N2HQqEIgCFJtJ+sgqoQnFDClRToiZlw30Gv6LQtAQjEINylV"
    "Ez3XPdN9ZwcUJBiEl9Gw8jZ0H6uXI/yEPw/oCkBB9eOvZVxhbzcD1+mUIQh9k5DnF36C10hJxxxF"
    "plgvcv9kxwRinyoiUfQQPxWuJbM/J66Jbn85zpCB30/R+KrbbqE/KAnYev9sMk/sgIgIw3KMAYhZ"
    "yDpVIRQ3kQ1IgXHXVIUiSioRnOXyZMHegA8Bo0dhoADmmZkyalEpTaFhozdj4Gc/H/FaJkiiWGqv"
    "PbkbTbtb4G9BdcgxWjDWshGZUBwiBGCWbeGWEayYb6ENWHDiYKUOxmAAxqhvd6uqIL8F3ofLwQ5T"
    "UIiBE9kT2Rd8JJpuf1fBniePgsd+jm+Xj10wB5ocYwm92R66e7B9y6c8MOxhMwrP0dfDElOr24My"
    "qrgVQm3WldIGPxV7t7TdS77oA2LXqu1JPqgU+j1eN9k5kTZd2mk+7A0j9MyiHd0l+7KoFUPzURV3"
    "J2vEzWyo3RnzdzQDkvHVptnIGYNiC7hI0Xm/H3Po06JFlaT0muEK9koRe2gB03FBn3NHh2wcHfmc"
    "MmVUpQjYXDYmJrT8ujWR+KfvVzNCdUmzpYJDoodkqdbpFqZsduUHodI5AmauSHdy04QuwNJHV4/X"
    "y3XVROBMb34aziJunK5Fo0QUSTJNzl9kzJMbIwoRjeyRXzP3oqvbc1InXi7CoG7jQeGK4krzVcT0"
    "68CwfQdhS4M0gKjuU00vQKJgwc3ISKeyL876e5pHTN90eHXeQDoQx5ndm28x0FsTLPpjKtgwYPZQ"
    "E0TSQDoGKSC7+LtL7ROEFKRZm4rHflEr7sGD5Wb1MMCJLam2Yre55d44u1X83e24qxYggI8FUuWA"
    "GJ7u7AzsiJoOfHUHj0p0xuFYGRiSQCsG8Ww5IiWxC79BVTPCJSS9EIG5sKivo8DTGXK3MDC+v1EK"
    "ELx8PGYwYhW3baYk3UwhyLFaRuAUwBzAkTyJgHdks6txboCv9JBWPqJ/3llkhdUXCWKAjWQCrMLZ"
    "UpGAkUf0e4YBhuwqALFAmlaDARA0MrJFkkRJMGQqTdLCQ+xlENo6CyKMSEEuQG8AIwANwJrSJEia"
    "UiciRWJdQD1fCAX7yY14tm4788HK9C5fecjqnIefnknD0+Zgdmmm1qmFMA5O/j6/isInKl0oVhPb"
    "8vpxM+frIRlqKgLUVkAj6nb3Z8+H1Ww9V20hR88z/B9+tMrqqrPRnioU9lvVLuknm+XsKMM9g5VY"
    "nDKwHEsBOTHZtyQka4t0zbRNa8SBCCB3M83n4vMdO3pP7AffSn1xGe/LZ7cuUt2q9mzknF27Ll8+"
    "KV6ah59ucMITCi2ieNXhFCRWqBHp+BES2hcERMPkivb5k6rV9V4SQ9f2n5v2ZfuxPYhrt/QIUfiw"
    "H9QnxpiA/T6ygsh/KKpEMShHj+fhb2fibFr17CGHk8CSEkksh8CS/pB2Pyavqgze85N2bfA4zSD0"
    "9hJueK57YU92oGCAMViSEilkZAMeQwMftn9SIy5KBB93kfhIOkmshdbzYhSusjmaHTom8urNZYmI"
    "cOn34lr11TDrqghX0leYOOj/d4RIl1S2uG8hsT+pD5wAyfwwsJJQ8fwjRpf5Hz+5lpbTCKTJKEkL"
    "gH6r67lEAPGyBOhXgA4W1ZJIic/r6Pt2dwcG8l/LSp6REQObFngPhm2+6fTQl7ly4+n8F0Xv2vRT"
    "1eRiZrCEMgFcLQbW2hbS0KFtLdELqInRQeU6sDkl/y/nfV/mJyiqdyHZTgOX32mZFn8qZ+X5JG8n"
    "UECMYwOqD+mB9P8j0aqPaADhp8JhH4vjT/QB6lNDq7tP0iJqKO2K70jT+cR/miZ2bEjwRU0KRWWi"
    "u5NnP9/BPJ6TyF33gaofMAkXHtmorQVAAoCJJGMivaJ67m72uIUDj3pvRShDHUE8CPpl53HzuAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAc9/5PpwAAAAAAAAAAAAAAANAAAAAAAAAABt1b0j8qHlkREiiJR6"
    "l84cxyckAA7yJjwQdwQDvC0o4vfpLBul/P5Aw3pH//ML4CEPfSrSDXu7P8kRER7GKAY2c/H9ZyiS"
    "SS9QZG9B8Zzm8x2HaA/MnlGlfMhgk9Aqlzp4H2vc5wzxT+RZ0vGOCmrzB3QkJINJ4mUToBmjGfmI"
    "fcfsZ5YSdl49Yw6BcW+etrpyrHzq1tAraTw+qrTJsj0l4KIlhzD4eRxWfxmXEY67SKCKHG+KwnRW"
    "ZNiMuHCBnkaN+9mbrkP+wQEconbAOVAQPMdKD3svxLAfL4z+biyEYRSnsTH6Z+chsklQm4o2mzGQ"
    "hyVdwSOKSR+Z9qgegsPonIn0k9OLlEi7wiJQNg7cL2IXlYp7YwaVwO/BxEMhC46ISEhQDpDI7AvB"
    "qA5GTpCcAd/p4+8mcSEGQRiJIJJOk941e0OwpKKnz/zWEoKRhAqFTcRw6NpupNwjt6UVisIB+Lo0"
    "6ZO1yC1AyZMdjZ59Q52wUmrUSS7sKOeRKp3jVGlKNCqzzcpIyW+b3T2PlEYIh15K/CnYZIeRbiyD"
    "wTaBC/8c6+x2Y3io+2+oUxNpBihyFBcjCKVKUC1rWqAkKytZURCSSQ60IeF3mN8v00W70Uo1KvnR"
    "X4woygm2uCMhIevlEp28lHXKg7eOv7sK0k8IcEX7vIc6D0dx4Gdsv56L2lWZOb8XL14rcZryqtVQ"
    "fugnwppnxjIEmmhCFhcYewyq0miQ3wErgELM8hRg5dk7RkSbub2e9hmaf7PhAedDj/+b9wQ+Qfar"
    "EDNOY/Am8D99hKH4zvHQWxgr2iOKaAxEwBDYvyhBYRT5jxYyf22T1qnpVVVWKURcfHXhmZmZmZmX"
    "HMzMzMzM9Hf7VWUC2nAeqM5CUTEfgl/IzL8SJTcJpF7p3SOH9M7PaIzEz4R+yMcy50krBrhOmVVF"
    "VVjL9OLu7u7vc417fWyXxDw8FPBPCB04NCeukmGjVEsKREA6lYqyQ3pSw94KfziTSBWY1DgPGCFE"
    "Dn9c1Ir8AZs/QyRO1s+vMkozOP4KOkh1S5CuevoQ2dGwVGilmgKI/0+4frc8uqUi3Nve6NNYOMIF"
    "87g7IEJnQOsTihkzVg/RoFoZk7FyAcNl99OIgPx/xqGIbXOY1l2yqtl2aEzUB5NKUQQI4gc1Cyud"
    "HJm5FIRDdRVV7MqJ9u71GMAZ/j/BZcLhg9sD/50/GGwIBg+GFJHnbCxrkNAgZqKbInqfEUZMhCGc"
    "scvl1JW53GmFoHvSsHlha8DODp0NBTDJYGYJ/FD6JPRu93QbIcF9J68XLolBD1aClLxpNbmRjj3E"
    "ndHXduG6UgY8MqW+o5B5fvzkHrlaRG/BJiwlNoMdYmJiD765ezUNZpaSTL0Me+4zG3va8rlwvG8L"
    "j9PjD5tL+dLIrgHvmS8Hhqv0F+RwPE0igZN+FdwsZ7Sc5Q5CKrfWvSmZncedLuigb9C8OYOTnME2"
    "O1QYFJY8zjBmQQO2aaWpHSv6CCd9gmloksjMD6uwLEu+fs7oVZ02SgLYBhmZdYn2HxUHUI+o8p8w"
    "W90kj7sL3miT9lHoh4FQle9CK39f6isaK92s9poeTu0BwDeGnQ0ZVoX40VPJiC9ejWMJ4q8ZNQMu"
    "HGBnkeQCxo6k3paUEQN4AHSO3uSlMI/lCBDj9vytm88/d/TXnM2vOn79CiVBpJ3dL2xY/V+j8f5f"
    "1/u4Y6fwfV/X+f3/u+5zdaYPydUEw3xuOwg/PO3wbd0REVq71Lttmvh1eTV/xqxUf3P8V6oBzn9v"
    "3Fv5v0FYT7LhYPttcLJCaeH7/v6A0pe/kYcj+85+zAj5XmGG+n1jOEtKEIZCTZtXmtKpV6cUyiii"
    "iij4s3GMYxjGdbVubjFGKMUZ/Zc3FGijRRoo71Xl0ANk1ZtoKgQd6fsD5j7A5H4UIhEIhy+BcsH6"
    "haMl+JFdAWMCCqfaB85lzcbpJEN2y/nT87YZO0+gPUEryoJt2Fn40/UPqt4TUPbPsAeAiaQd2CUD"
    "NYe9+TTJW06TNPnOOBAoFOjgncJyXGGyHQox3sedFwxAOjnwdB0H8DwQ/ahZ92P8J9cSsvszDDZE"
    "P6BCGYfZf0mfnP0l+ed3vD+YtC20WKqrh6qBrRVEkJJzk5HDnOQg2IvdhOb5Q9LgWT64fWonWfYS"
    "C/fBx1Qkkkn1D9SGh911+c7fV66qjKwVR3thDkE7v2yfXTJISFF0Quh4J8JBPrIiYLgPEcyEVIsT"
    "zagClzObSUU0TttQtkgVRScESRAkT30jkkE85tXca7NxUCcclDwK3SC9hqe2F0LBzgG58XA0HA7B"
    "1iF+pyOkmaF2BmbHSbCz5jWKJoHMxCMIMjCbkPedB2+McmZlwj7EpNNNXLVkLhmVFmpy7vgBISEv"
    "lNRSONaSwTBPcIWr56WnMqC6LABHpCANh5zchw4iHN1BU6Cgo2R6mdj43t12u2q9oAAAJAXW9VbC"
    "JA3wH/d6RPPwyVDQTUIrxbPKhn1EJ4TjSnfdznA9Xvd9tS21tG1o22jRq0tyeIdAPWdJNL2mjFKz"
    "qC6w0GBZND7QdJ1r8yUUsS5zKHYnOjyOkcOghEXvgZjwXhBNAgFQfD3QzIAana7SGbhPYHs6vRbX"
    "3yQOsO0gdJ7vp9WA3BttKqqqqqgx8DvPSdtLZQ7zDD0MJ37k2Ew2mDD3IzU9kaKYdlUIe6qoiB0g"
    "w67yRhCTa0YyRyDlRPEIeMshwYVVK7jrY728haFQtHjDbkiEk4yEQgcQSsjadvH4Y3QTkDxQGSHC"
    "o/jUcHiF85pNfRyNGY1eSIFlJ465VOed73IepFrxSiTgi6aoKKkqY5KYlw2ujMGy6VzA4gDUHj94"
    "h6jqycJyQ/LMHXtvC8obhVTXVNhmrz1Eqaaau9YYYV25EwH4ZkWs+s66axrtZi2k3velL2gQuBt4"
    "ID53Mui0MUdwHHQ9SOIKLwzJHPfFDVyQ2ZMRYlnqQqMzbIJEcuWMXqGK1gt0WeHH4ynTp06dOnTr"
    "XGJpK6GjFIonTqa0ilqkWHGrWlbPUo9EkOJ06dOnUytt9qUQtE9snOhTXFH4xbpm+e0JDEOw4YH6"
    "mRaL6ZjNRh+TjpIu7vA5CA8gKPO5BEfWOA6YPkzuwogFEvNbcytzavh9YAAwur0b1VzXbsAABAAA"
    "EAAkkknqSz3E0UTVsiHkA8Tc8hjA5RyGI93qAphkjKgvZ6vV1hQpQjbJOgzxNETQ3EDbXf8BpQGV"
    "mMbzFgbLE19i+y0DmO4Awdyux9MYnlDyB2i+JFOUBzYVQd3Ow0a6t0YvAfeEE9dCiKP5dTnEgQYJ"
    "mrBopCQFIGxtO8ZtfGQFJEQEPv1aSRE/PZYAhuAHcn1nkxkgb/Ji7ueuDEU6ySSQiQiowikAQllq"
    "bLNSylOvG1dbq1KGWUM2IpJry+u7+7tt31tpa1WxD9fOEiFnkX0AxD3Tmf0j/j+SmrjBJehOEoYD"
    "2xU4zlBOjIdxtPsDWa0s6YZwxSyNHVO0EB2Iq2PAUTsIAhIECDCSESAkisRIoHTQ56kFDV4neKGj"
    "IA7N/NC/GGY6AAEzPI459BgvHLGe+MiqKTQN0NA12JE1BiivSQAey6SW5rmbXfpGtmFSdkTjoZ4A"
    "4bGlV2pAIAyZAE5OMX4dM7QiGaidt3eAhvou7qRE4toXZ8+DuiWwkyXn6EIYpoYCA+jfiwBzIPEb"
    "RhtBA2z71Gx8ZknQ44hvFFaAXmjEnIEn9EZC7vDKSbhwGAX4kU2A79wuQcW91Ds2rIRZ/h0WGWaa"
    "qSiwQoj5Z3K8uIqHIgLzRvwIAf31uQjJBIKSAEACRRKyHsOLw1HZuReVSxb3tBkKR1kMGBEjMqd8"
    "QDrlzAaHA0jTIxzieA2Gj7IFEc2+tUPxX9c1QylUnNhk7zM0OgQxUjZTGG0yST22kUHKv84kIL7Y"
    "QCuig6YN4xIfwRMoiQEPWqWHYEWxP4y26WmRgV5KsJFIH3BAMtgOMMKXMgJlkBKZCEKUtClr3eZ0"
    "7qK76KIZJoIaFR1FElpUYotCPiWzZKYUllzz3n4zQt+08FSktDtSARYISIFcmMHQDoHtx5e98Z+P"
    "RLUiayVtr0enmqvO3NXTTbY46mM1m6H5eAOL/3hRgjct/Fp35V2mt4jvqga4gKkHIC6eYXIuXWch"
    "JAVc+ZkYQOCAd0mVKf0NSHxIXsvumUliyCxIWGFq21GDB/5RPhTBVObNxOJpJUFayUBYRklTTCwQ"
    "nyAF3kjswCLJ/K+jZrP74PbgXUEBBJN+6/Jl/01f3/tyygBgKf6v24Qxj9dFif//hmtvsg3dXCGh"
    "X6OUh3JCGfwBSIyLJRCFS2UTikxEiLKyszt4zaB4vJ2cikyIDJNBRWKeq2PBzXS5vwLDw+9LyegW"
    "hZeDNj6epo6xd+Z3qOF10YzJcGDIsxxjR3pbDR5WZnu5mtvrGrcVUXG9NIQ+Pagh6PbEQOAXA3kk"
    "H2iDtLm5DYzkAq/m/YXvAoh5bNAojN0FWCKoUiTiTEqTgiUy3scyWbpSyHGjWGpjHKs3hhmkRzG2"
    "ZESGGZhC0TJUoFiZMpvgOMAMRNhuAkTFFspsaYWxpRAkKXIUhhEFbJFCZSUkNITUmAYyfM5Ow+6j"
    "uUqOtO4AMKiqDOUGQzQEC3QRbAAKYAYYo06cuEIJ61SpO+X3c3bkkUWzxy1vMOskkOhANoQG0IgQ"
    "SAMCh5PeANzvL0feNxVcDOQsQLh600qGYGaAREPcgoFQBE/r1U1JFi+Eh6KOmBsePy9HHnmeIgZi"
    "ZCGsLhix/dDWMhiq4BpKLh2E0PS18mAVHqT1wIQLJwzUDiIY8ppUyiFiC9CZijsKq2GChmOUsJPb"
    "kknFxeAQZIHdZXukaL5BCBXH8R888eovl15e5nivwhKNcqLTVumfjwDqvS618JpFiMPyfLjOnBz5"
    "k6XsFgqQEBIMgROqLHRqgthzZNYmZktsx0Y2UuZKJEtzB6wz1mBrEwZs0G5otKTigYIZBgLOYkkG"
    "0EIrIUazQJMMoEUCtQlzfUFenXwTiLOY0PtNJrJbLmtH+jAW0WuHaJHJNDNYe9ldWGcSXDAD8Tm+"
    "rocligXzRj97TOFitH3ZSTQumOOTzywoZqiDOtbaaNVya6Gg88S8o1FpNo3V2lxjkJIIY311oabQ"
    "XpYQtt2VqCTco4xyvaNjCZJoLRnRInl6jXWft9OjabsBzq6ITdDWfP3I98gYYgsEFwod94nbQB6m"
    "e5hxKw5Zcle+wqq9HoObZtNPAi6GIFTfnpjNMWGpiccVOkunmleEnITdJxLm0UhdWTc0occks3N0"
    "MsNVgoSWCACGIUkCa1dBoFYzezjUTUzWb793hdUAAAAAMAIAAAABAEdeHe3bruhXbs5u3dGrVrw5"
    "wAAAAAAoAAAASQkkkh6Q7TX6VtjzQmqtWyQcDdDRqAUItFkHX7KT9py/06jRsXFNKRTZFW7ZQpVi"
    "kVikBIIxQIpEGmjdC4Fwrs4Dh3qWy9kuniLqMGRQWDEQYsGDFIMQUhZGpmkuERzDUxdbN0WYdobJ"
    "J3mjSKKKHUlVFUlHXUukEavNd9Jk1eZDK8LtXdFUXGtbRhRolTj3RU5gTcIHBMNmQlZsCJRJ1sFG"
    "TZNjBMIdUZA1J1ZARkBVA6xtLBC2wSSVGEBkEJGQcXQJm7sF4ETg5wMq3H3QUixZVcoUCYkWDZco"
    "WGFgUgwSDAmsQhURkJGehQTtyO3f6LFHVqOwxTap4DzN1oHX+0/tNPOV9uW7tnVnWCiqph/cNKy5"
    "UdAl7Smtdcz4+N74C6rDmIy6EIY6GqYFQhBZA7NRnIYnGpwJxl0HBplNogEwBEwapgIhAGMPv7aa"
    "2M3TvzB2tN0QyKQzNtDOlpB7TCqC0L1Wd5A8AwA89lTdlxZxBSEET2LIEWAkiTbKasprSEUy1g21"
    "LbQAQogil+gawRGN+aIkIAZggdWSeKHi6bNYFN3umqdCCp28ocXJdNhr0BsMx3hIsSBFEiBytXto"
    "qEUhzGgJSlG5wF4E3oMyDFxRB+8huywTkx6DqQdhL8UTfqd0C4hCv2WdvYGM8SvcyTD0xxxEJRpY"
    "ERORQTeWIS4jdA1ZFEHESgdQxUggapJksAybhWW7ExXjPzEhAIIhBRIiIEUOsbQfcIobw2qhGBM+"
    "l3GFtniVKOCrxkthtoxvhlRhPNDXn68HqzXHTgLlh2xIiLCsUERQkDdVZxuJmbiUEiDgvmgGTj0B"
    "UDtaDeg/0xGfvN8LAXQYDYIMdP92edFjVcxDoNCIMhiRxQoIh1ttgg/qAYrV0W3iJOcm8vI0swwG"
    "tgS+TgZFYY8ySSSSSSAAAAAAAAMAAEpJJJJJJJJJJJJJEmJJJIpPTyPD7B6C0R9/AF75R6yDkoEP"
    "IsUok+/e2HnA/gBtURwgaisULOK5wMzpD0SQaaDuT6erMyA12l1Xwn2HmX6oKpCCKYeRu1H5OZRH"
    "nFBuFfz8iIHkH+wIqxFjgYauZAVIcpDxzhECN+aorOoIqnZ8UiIlPtif8IbCPgAfb3bTAlQJCnQI"
    "cr0hMz6j3guEkaoKEn5CNGSronM850Bj1ZNERE+Wsprg3RZEAiQFhBAtQBQdgIHFfD8p3oCZgZjl"
    "uhwQpaIIioiE9TUIJOncShmRGtEKUKSHhUQlLlDZYhGgXISRBGQFsglYBkXFCkK1KuY8X9H5NZgi"
    "p7m5yJOANI8vf12PTCCQwgdNAeC+IWHvXFVeNKg2XX6K3zGM5mQD7Y8dioBxAP5M3g9fhqGCE4jR"
    "vNMCoBgmAVMMEHmgiJp5kfCUxgAG1zhsliicLk0TYwCz7hg+qKBRG0lAMuOSIghCJP58BSlRS5Ab"
    "xBSlaHUJfyUpgXwRqaTSWWtaLYs2zW1dwKSjgb4gWSMn44kFAFFBBAiQRM+BiAyIhIgT65nYe/r9"
    "/Ugb6VdC9jtx/ehoGQb6JHQvPJgEjEjB0CFysilFKjkQpaPyxDw85QhlWVJ8kDv7gxQoLKIc0Vk+"
    "GDm5lCiWiq5P4FT6Q5aJNBqe+B6DStglVilkIUKCQkkSF0zJAoaFDjxpRVrA53WUcZ8Zqydss5/p"
    "1LIiSCxGLtPMHd4QKIR9hQUBMPp+kuKaXRSIlVFViL5ma+wsXMKqPwaQ8RXOu1VEhsN6boJfaRAB"
    "qlTwgkgZ0U4iC0sEYwYiRSz8HmtxrbEmLVEm1qSkkiMJGEFD5RneBkGVifjHgfHrgG8bW0CuSB57"
    "o8Ta7x9XQgHx5j7ID2eSgqM+EokNIAcLCayMk7TwwDfgRFZFB4/00fBdtVJzZ60g5iegVIQ1y6z+"
    "R6h+ueqYdGdyEOlapOSJ6Em2D/whxkGQLEFhFqCqT4xV+6UfL3QwrUwZulk+0WFIg4y8AqiSgwQQ"
    "R2lnFuU5ZJ/Bbtk/l52KHBHlzLMBnGhRW7eTia4Wufa4zOWJtNSlBEErO1xDt2JCFk9NnVJZuos2"
    "oPnLKC2Q2CG80HVQCdBJBWRHyx48tlUB6G4gaJw9KBgHkkJIEZFLSNSKvHhelP88rl6kr5Gtc6Ak"
    "/RGiOEXy+oOvvHhF7ztdLKiYD3XvdL01VOjoMBM0gBVkTxFZmpK6OVPuzNVTgJMT2BrGjlt2WA9u"
    "T8G+QZCQKhGKmsW4EWDIQJCI5bUCleKipwd6Dy+LLZR8DqaLTTTHNWBoTGdPx2aOLpR9k1QOUMix"
    "Q0RPtDKry8DoEEhFFIi3MQoQpgkYZnrmS4ddNHdERK10pUSGROpIsmR8/p9pOphKlVoyqjBnWM0C"
    "LqaoZEgpmXGA1sU1WlMKLnQJNYCwkTW8xPiv7Rs0dcspkTOLpuSmZVmBIYPZtKLEQyoyieWGNCIi"
    "YtSiJFBA09ZGaBfAzpYwzElCUMDUHSHv4hl1khEkGDOWEm6pP7dJoQ9BAWKikRB0ggcWvWAUFI5v"
    "BBIgT/FWaiQsIFUZqYt7+ajlLOw254Kdvs514pwQjlCVKZmGDIs7PK70VM81MPhSSbZyiEVBIBoB"
    "sVMRysFMlKwwacIlIlCFC0CFuDCWQYJCQIyHQgekpmkrGVCELEiiT00rEiG/oi6CWAGpEBDQ53SJ"
    "ntCkP54kHTOZeZb1du6UxiqagRJIQicJQRTkhMw6iHoRE3D5ojcFe0ogH1BVYvAXG0hBpgxkHoQO"
    "mBAUSKu3eKZeHQ0mAT2RFkJFIgREdXjoIfcEOOkdzmekEDwJXwYElYRKqIFJJUQmlIqRVU3L0KDQ"
    "Kt/Jv0ZVJZgqY09cHjfHPriGUdOkB+TeYAkRRcpD2gDo2MoGJOzCFnLlZ6RuuW81jmqEPVRUIEYX"
    "pdwO4wlmRllgyK0ivsHu9N9EZzKtOO8n3TxOCnBOB6xofRaIdzJIAYiqXxNx4uScpmpnKuWlrmYz"
    "lgAYgBEAIKBFYw4uiAIatZ8uZSw6+U53fm6AzHBGB2w0CPYesoJkxHyKJcIufM30F1p1JMGiQE9C"
    "eOrXx8YeUAIKUVotXpaI2GprXn9b4vZumulxpKbnAyTGbgnOVzNyTcTgjlcUzLq3vy2ypJCQaiJN"
    "JlGRFMmS0MTVFjUtXOywEkYdlqhEYK2wK2KypKto2xJGUQQKWUjVFatAJRAGdIfJAeZsj1apSCur"
    "UgGLDXmHQdGFAZgmY2NROKY3CiBqoPz9dO/f7giVpvECG5Q2oRBOxYCBkORUQMMtmsJAIYHaHMmA"
    "Yqzzcydj+8z+ve+h1ngRZquYKcNYKBNzFLHK2DGgooYljGdrTVl1GogkLWsYacyUmsgtg2NeUDvG"
    "QCU3Qv7WN5xAEjj2CiNHe6ZhifhPpCGijGMjMxqrOKt+h9pWPH9z2HU5F3eod80I+iRBluDM1aEF"
    "nR4BmqKRsFQZEOoAgHxmQ8NAI98JEAvNKoQLyKtbRiHcKbY3DOEUC+OQ4CAmwdliGABUjGFIBrUE"
    "1Hd2KiLm5+g1DU0TiQlGaAqQVAkFIIRBIIa4te9mNXekhb/BmqoKzsML4Tqh0NUslnSMhzw4hgqQ"
    "IuyDuQUpSkBbkzlKIEDESOzbWi1bFayaKsXZtrmk14Oa2LZW65tzKqKkkkpQhCOFuwWooLbdmAAj"
    "ah94IgGSGZBDO0QaNENYmzKv7IuxOMPQPOAfVEA92AnvsUD2xS55s0pzgbuLTZH9IR1MIkUT0gfc"
    "RBUhBPIQBV2HHQmoIKAX85bv2YgByoTlTxQAoIHgRqSK9tU1VNUHKgJwBn+ABfz8/Er7InSCSAMi"
    "wRKgsIJQwAwANmWDdkrVJKRVrlaauaaqTW83uaPPbza5GErBQKhTyKYJIgTm0himbi7qbaRYEVkB"
    "QJIpBkFRNaIbsx46gmaIAZxJA2HzoLlqG7oOO7dPp9MubMov5NTe76VIIT/rlwFkLCsVVVg6uCwG"
    "B/aYb3dEWQsKyMKpKEYsR6LW/ArF6YTPa7pf76CaKO2afvRoKJeCcmLIoEHx+4x2kIfpn7VkzRcT"
    "CeJccwpTUGrDaBp2b3hYah6Cxe5B5FkPf3YC4iEYaQMMhwP7YaA2i5KuTAFTcfg8LxUoTd8NWbiB"
    "o6j6ACWHFAQIKpsUMA8ZvTVfe9HDugj9aJ6hePpnDTs3Lqer4nT7qAG/wzsFCPoeoQaodIvrivDF"
    "AKgB3RKIJESALyWabDESUQJKwFBBCB2CTnEPRRv1DUmj6Ljnz5MAUk4GoIgsEHPNMOsTzmQWaamw"
    "BwQADQAyBAtDeQUoVDJgAGI+JQNmzNKvBjIkjIEqGhExSMVok2maUtstKm2tShitKTTaSCSSRECO"
    "CCKm9OQdCoaqazINEkpM+QoHXtqMaJwTYOWzc73IAoJFs4mpMwDVkogZ8KDqTQB2RT1Cxiki8pRA"
    "gfQWO9IqRJEiB8p+sJ7heEbsSRqz8+FcYKKNElVz8KeCHRA9ZArLtOpBKIgdMOkNyOmAUEBoeTuG"
    "j2w4GEjIMugUZC98U+nFk2IwsI8e+Rd0S/+GC/FCwO3w845CfUo3BwID2HroPa00KctUdYU4WEZC"
    "RlxUKBJ4p586neulRIGRs5Bkz5XNSvXcgc1ejaICNYXEMwCgCVDbYK4SAX2ZROjKsiCy5ZiLBGGr"
    "Rf0HuCIiIwLzZzJNwsEJQsKlbOsXWBo+7AdmhDSAjbsgYayQqzAUUVkQWBBbE7v1cLwZLm2TjVyI"
    "4kVkI4ILROJBNoOhopkNhhoU4jgSyPUQcEYQhZAGUEQKSCRRir8HmQT3QiEggySNKVXjvvfPXKvo"
    "S8tvYLIlYyrz/fiHP88QWAQDWoqbAhDwYqilSEyOYtKr2WhdLVahiLtTMgSKnPAqAyHAdnyGexDM"
    "9aEHt/IIeNX5vtozHtXZuoUOh65ADM6DOFvmzCIO3M+GuBdUSrspktoMKZMai2Y4IxSWUsxhcrjM"
    "oXV0XLgXgcZKGw5D/gZIJ0hbA7xiAIeLgdfh4sPGusUU+FxjRcBtqCAauF+wDee/h88++UMk8BnA"
    "YcBHeBdxwsiktsBoP9f3EhISGkOMUJBFwKpIiovC84fH1gnpxgJ2B4J3P7o8d6TzygD3JUjddCxg"
    "5aqqMEGCBghPA1RFmH1Z7TWnIwQED6Z+HkfVsm+jYhv+GnxntoccVFPsai9Z7tMcZdksY20VVEjE"
    "FUGCVxpyglpBD0iqeVBiB6yDBkJ5kD3WnB8pC5EgB4MePsQM7hBA/2RKCLiyI2ruREU4Du1tYgip"
    "lHFhUFg0az5GciTZMrVLblHGn9+fq9/PI+myjBi6ooxVF8XmjVre+iJ9PzYxMvD4ELEUo8e4Ues7"
    "PWGMqaTLwyWdtnxTX32pityttYzuXAqgxLtra0FakRtLVsS21zNHuzCd04qtm5NZsjd6KHNJeEzg"
    "7OqCSc20IfbBEmNDBDfZm18xphztUertGjYrFYqjbWUttK2bNXWltUlhbS2ltbKMOVkuBRbsq1iH"
    "hoh4EQA7JkzOO2a6NtPCpRx8Pqr0bOdd9+8dbuzjltw0LMtu+MOIb5pJJ2rHKWuO7q02vkIGra0O"
    "mpgmSAN2riXDCjjA7jld4xXLERRCEmRuyApCVHe+nMA6A3Y/qQ2M1H2a9DflQhJU/rKG4G1QSVC+"
    "L3q7Phxc1pCq6LA5CrNudbF3mbzSC4QMOxDDjDpSthjVxckSEHGwet4cd6D1vJy4m3YRO1VRkVFe"
    "nTpCHKIT5Q5MBkjkDADpwQPPCHnopYoRX/FmHeeXV0Qtigz/smQ9O+t1NSBxuwAjSkQDq8tbPOto"
    "LIcsMNRxlBCSVIPZKMlEynuAgagFNynBgCoZhpAYQiBIasxELMcNgquqIX2HCXyRuTthRKkjnIED"
    "hgl4BCj/f965ZVXaGQ7xXPhoofIurowLyuvckTBL8MN22qW3SdC1Z1+V/Fxfn4soU68NIyz0SV5s"
    "sfxUgp8I9mVbzDrGzsOMwyEAmpiyFptHnIqEgicyAWCNKctnv0KOUUbNE0QOA8rg73OEHmBSMc9Q"
    "NRU5xCK6aEpVLwaiFKeh+SD3BkIuApEP6ALCJsbDYvZClyQhseWDnB9oQBJBkOSVAizKB/V4XgEP"
    "cJN1O+miG6S6+yNiByS3+V+7o+jyaDY4+1yRLKIEF48byHMJXVQ6xwsgx6J6o9oYAKGWwKgJIyIM"
    "0oK5IyI7gq3waqBAYPfS08lGuQh81yh01jnunqBEg3CRNoZBFRLCJ8xEAsEt8fjv05c+kejIQhCS"
    "SFkDAWlEO4jeGghBXlWbP2IerjaeXdnOcTUNt+e6UNxmM1hQ7EAw3GoMJpDlrs4shd5Kq4kz93jQ"
    "pNRg0siILKIiLCpU3KFhrVnLVwZNhnEpDANUgWcauSLImhUiTtCwsQhoso+LLY78XDRoSqIjDKxN"
    "IiGHb+rVsNqLNc6E67RE6moMGRQtsOLVBEBOd6CUSTIk6xIUFSCMbahqOWX7YeN1Dm0gcRkOrmHT"
    "aXe68CdBmroDmIW6ZbTV0uhlgGwg0EgsEuBZnXty2ZU9tnTeIdOmo4+UKFN0dTR8xG1fgnUQMo7G"
    "DUSQDjgrPDqJAxB3mOSKpedstnA6hJkhJiAxCDiIksBEWIx7e3HWsCVXObvpUNTgDmBCpJTnmAzm"
    "CjJNMgMTAzWtWBgxKsmWzia3IAlFSkFgeRcA1OBBIAkg2HWE1MDo3mgwIswzJwLYW4SMC1g0gdqC"
    "QHMkFYq24Q4NmAdpYLmV01In1mdBpNK5NfO0GBBqCKQUSKrpBDMTWkQpUCr7aptYgQDDy3XDgVU3"
    "VWKB3dHpAfGCyCM+YsDpYEAiFC7uABVcDa3gDEXftDrytB8xnRAoTX6CctlrkogZgC8oGHonxRA4"
    "ggw4YBbB8jJjBs5mQR8xRQkQjRAofxJD1ofrH7Y4UpuIeuSlWdR7GHeHnFFdouGmMCMkmf2Vabsl"
    "zCwyQIEIxdZQaQDuL2qoBR1vG3HTeQpIqxEER2NBOdiQvVJHWGkQIfc0FjqFqlKYFNKASJAhCJEi"
    "ib1MAfgIHmseyedJphpDBWWw1lZiILBCGMBYYjBkj0uSgULnQYj4ICYTYYIbTpKTEwRLSWDGRRVY"
    "wRCjSMrFLBrLIKYDaGDIJARDyciYhogyFJ2DATh8ppkeyPoAEkEUzxU09hrHYIULFSGD5dHLDnnL"
    "gZ8UDQSuaYSGUzLJNItKymTNptGjNq0o0tTaWlAWDJF4wGgA+T9ch5/7zNvFETdAERkBE2dpvqCH"
    "SQSxA5IloiVGr0AVBiQQh7hrBxJ+EgthxHZpzMkQcQfKToA7+3IosQZyg+/AY1ksMwBPgUVRVMMh"
    "DpPm3RRZ9lKJ62fuOIxmGFgqgSYl25bgqFLlzbkxRcWua4Njk4i5BgSSpUy16NQ/7+lPlZ8573Ke"
    "dQMj6Dr8yjriTyID2iBaMuFICITvKSlReH9jViCfmRP1EjESEgBBF0IIbRHkfunN1Okl4CIA4mt8"
    "mKUGdscQPRub802oYO9MAIgYwZBBIlMm6WD8xw6UdR0L6aum5XmX/Gng8M08fqND0hyAMg5CGq9c"
    "VmSINnxJJTZ2iU9GKMR6Fgp6ZCdbP2SqDSEC9q0mYWTyCT+L3+sBfjWtrSIABAYkKCHEgNk4+HA4"
    "AXxRH9JoGh3fcLQ0B1RLTtQ/I3gnwQpqgqfNRZOCf+KL6gWgyWgV64OMNyfgEWFjUssSFJRBpkGM"
    "1+6cz9hAamWXJBMfpWukg4eNJsQccwsdmunYtwPSQuRb3IRMqQ2E2tvXdeNaUqS9DjBVFaamm00K"
    "RWLZs1mlpaVksQiEAWDcMgMqzUFSylIwyiID+IYTEBPep4ZQBVIiQST4OoKE+vVAvx0MGIdbFHPp"
    "gwQIJISKMgmZltjwlqq8VE+gmoE8ZOuwlkCI8kKM0xL4BcMW7gY61hKU0QRA/Hxfw/Z7A/fFHM2w"
    "jqqEi6QzKNIwR4AWwhKR/jboEVUO74/KevZunsLqXWLJMSnJogdVs5ro3pLrZq4/acdWmoF4ORoW"
    "cxMeiVHSBjS0tUqYjecT5EyKwKGPzLZYuMXj+r7yiB1QAxRQOLSfakJFkkLYtlCrNU20lttoXXbb"
    "tq0dT19lSxxO9FXDAs2H9qipFFSwoJ7sUV9uIB5iIbw39yIk4eTFD/5p0HR6bCJDNT0fCpTE//SF"
    "kO4FUikWCkI/4e6342+K/TvDw/IqMTMaNbFONC14ApmOY/5w/iZIOckSQ3aagFlRIprrobEMfJoB"
    "E0jzIif9jm+3u0KlFbEN2Puf8r4zKqKMzJDNETWf7C7kinChID8n6Yg="
)

# ── Extract + compile ────────────────────────────────────────────────────
_BUILD = Path(__file__).resolve().parent.parent / "build" / "inline_k14"
_BUILD.mkdir(parents=True, exist_ok=True)
_CU = _BUILD / "flash_attention.cu"
if not _CU.exists():
    _CU.write_bytes(bz2.decompress(base64.b64decode(
        "".join(_CUDA_B64.replace("\n", "").split()))))

_ext = load(
    name="fp16_k14_sm86",
    sources=[str(_CU)],
    extra_cuda_cflags=['-std=c++20', '--use_fast_math', '--expt-relaxed-constexpr', '-gencode', 'arch=compute_86,code=sm_86', '-O3', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__'],
    extra_cflags=["-O3"],
    build_directory=str(_BUILD),
    verbose=False,
)

# ── Config ───────────────────────────────────────────────────────────────
def _find_best_cfg():
    cfgs = [c for c in get_kernel_configs("all") if c.dtype == DType.FP16][:40]
    B, N, H, D = 4, 2048, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v, o = torch.randn_like(q), torch.randn_like(q), torch.empty_like(q)
    best, best_ms = None, float("inf")
    for c in cfgs:
        try:
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            torch.cuda.synchronize()
            e0, e1 = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
            e0.record()
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            e1.record(); torch.cuda.synchronize()
            ms = e0.elapsed_time(e1) / 3
            if ms < best_ms: best_ms, best = ms, c
        except Exception: pass
    return best

_CFG = _find_best_cfg()

# ── Public API ───────────────────────────────────────────────────────────
def forward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """FP16 flash attention. q/k/v: (B, N, H, D) float16."""
    out = torch.empty_like(q)
    _ext.forward(_CFG, q.contiguous(), k.contiguous(), v.contiguous(), out, False)
    return out

# ── Self-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    torch.manual_seed(0)
    B, N, H, D = 8, 1024, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v = torch.randn_like(q), torch.randn_like(q)

    ref = F.scaled_dot_product_attention(
        q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)
    ).transpose(1,2)
    out = forward(q, k, v)
    err = (out - ref).abs().max().item()
    status = "OK" if err < 0.05 else "FAIL"
    print(f"K14 [Cache Configuration]  max|out-ref|={err:.4e}  {status}")

    # Latency
    for _ in range(10): forward(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200): forward(q, k, v)
    torch.cuda.synchronize()
    ms = (time.perf_counter()-t0)/200*1e3

    for _ in range(10):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    ref_ms = (time.perf_counter()-t0)/200*1e3

    print(f"  latency: {ms:.3f} ms  SDPA: {ref_ms:.3f} ms  rel: {ref_ms/ms*100:.1f}%")
