#!/usr/bin/env python3
"""
FP16 Flash Attention K15: Tiling along d_head  — RTX 3060 SM86
Auto-generated by gen_inline.py from kernels/src_15

Run (WSL):
  cd /mnt/d/GITHUB/Mini-Attention
  LD_LIBRARY_PATH=/root/fa_env/lib/python3.12/site-packages/torch/lib \
    /root/fa_env/bin/python kernels/flash_attn/cuda/inline/fp16_k15_sm86.py
"""

import base64, bz2, os, sys, time
from pathlib import Path

os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")

import torch
import torch.nn.functional as F
from torch.utils.cpp_extension import load

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "py"))
from flash_helpers.kernel_configs import (
    DType, FlashForwardKernelConfig, get_kernel_progression_configs,
)
from flash_helpers.kernel_configs import get_kernel_configs

# ── Embedded CUDA source (bzip2 + base64) ────────────────────────────────
_CUDA_B64 = (
    "QlpoOTFBWSZTWUepwNUAL9b/gG///////////+////////5gbJ7x497AdSB6r49nX3z53a933dt7"
    "NuuUdUBFHoOnTruFsA0HHYFNDQhXNS+fZ3t8e+Fzx6L4dAOmbKgvPvfffOd5oAdqmQjZ6KHO9rvn"
    "l5713l20najVd9m8ve17caePvH0vPp8oI23wF3fdvr3U7573e3X3u3n3PfZfc769GLXvc89d3xzf"
    "W+VWX2+ue33Nd90Otvm9G02ilO2LLFaTVJrCxKt6CDYPDMNa9T23XjfR1X3t1hYPsWX3nvZ995S8"
    "8mocd95u9yNTbVrWbffb0++ic7H33vesvu3VXdjuuRyOJt2Lold2XMZqzb4qI6TJVrOabVRJ2Gqd"
    "BtLa9u7mx3LcjKbcsuyu5sgSmkEAmJkBMIaRk0ajEaBE8jEmTTTRiAAAZABoMmglNBBAiaTIm0Ke"
    "1U9qbJGCPKR+oMkaZA00GgGmQANADIAEmkiIhGieiYmmiYmTKbUyjwkbJtSaPTRo9KekaHlB6E0a"
    "HlAGg9ICT1UohMkZU/I0T0mU9BGJmoHqZpG9UA9QeoAaAAAAANAARJEIySek2kwmgCp+BqYJMynq"
    "YQTxTyemkyI8pp6R6jaajUGyAh7SgiRIICMgCE9BqmTJ6aqfplP1R6m1T9JoE9Tah6hk9QaG0jQA"
    "AAG64AAv7oAAp4/cA/nEYffQVC0CRqOlM1iwjFdFxtM3qa4xGMUM32lcogm0YN1cltmRJriuJxc0"
    "mZLx+Lq+ver5Ofa7vF8f1X9RPSzv7ucNrEczm6yYiCZRHlMhjXGYIaIb+ihxtd20++ma6UN6CoIq"
    "1JTpxZDHXGYREE6+T/g/99Go82qyskUNEQmSZIHQkEQ6FNvy/Lh6pf4H/lYpo/Jexb8/55Z5hZ+Y"
    "tvUCKxd3QkRRZAdISSLIpPAEKKO6TIgrPLahyGebJY4pUqHUy5ZvmW4Q1J/Ywqx11yZBwoy07KU/"
    "VW1hzEo47ymkKZYqzKWVMWJn+kDIw7jUNdp2wycQ8p2nXFdWrS17TMwoEKIBKU73Zp0mrKIs0aYx"
    "KdM1rRi/n7KBiFGsWWlgjEFG0KapUMpmWYko4CwEYrZ+UcMYyVOrcRoq6K4CNgHY5ohgQxCuJijD"
    "G1qWwUpbF/sQ0ucjvW9aVBIJbFopc5yhMoQjV4Nvs3yW9NW3grbxXBPZ7vb6Z0u+BC9rdQEZj11S"
    "QujN3bJTO23KlHdsd2mq8HY6PAI77h0HJkmIxFTXXM6OnGGIYG6URir5XlCZDYcWcj1CO2b3kcKh"
    "WUUQDipqjlTKVRnTxef22ta1rWta1rWta1rWta1rWta1rWxrWta1rbdHRkiIxgsiSaTSC6D1IKfz"
    "saGyMhCb0D1XoNGr3zRgj4zUMIwWIk7meRJjNi2oQyDYUWSSYsCEk+ENiIaEUNer1//LhpNHPa40"
    "7IdmFjw0NcYbGKdkkiJD0odiE2YiGIMgnTETZIwibDUrZjRNBJA2JdzWHHNrjiVRBNkHaT9Nam5M"
    "GRbzLGRcFuRTeuArjBtimAurlbaAuIlAhvwMgHTSQkkKlvMtCXn/v8I/7dfXAp3I/EeVn/U+zLrh"
    "oez295PjFVFGAqIKJ9ft+I+PVM17jAFkJqPFltFaSsknx+jOozoCxiWhUkKmEsdG/c5/B3cP+O5W"
    "u/jtnn4bY/qg74EIisZEPK3xSp5GxYBh1tgLA5SoCBCZhMvcXWm/6tMHCEjaxkgCUDY0dilSNfam"
    "i0mRZqTQhy0VzcgVElHw1qq1bptarfObVV9OIoyBIgq5F0KAAVEBkFNYgHzRqLIXKjIRo0xoKnOK"
    "E01LFd5SwhywKCkFhjJJRkXqN3ddveH/r0w3ycqhvjiDIG/0u8gbkfg4ySMciNPGCJt3DjIgGbF5"
    "RC0IRCQgkeHdtrBmjCAdOaDt8+J0M+apbLeE7tgcQDIRyocHgcpuBtZBVoOLY7PLOg3NOPEkvs7k"
    "4q8yX1BAxkALH0sA95Dv8hIQb778y2lEN86w3OPsGBjgml4kWyaA17K1zGnHuOgnVHWAx/lTdGRD"
    "W5cGuGGY+O4XRglpTxK/CnWSYB1CEt0OwDCLBaHvU+z26v5qKxo2kCxN1G/YwUhjnabeTrw1B0Mz"
    "UQZ5kkJRbGXWSlCQdI7I9wqxUqBBktnIRj8z4klv5DUpYX/3q9WJue8Qfgk/NolHB/bWUyEOxPm+"
    "0qHfyQ5BhMmDJOSGTTaFQfdhXmgEpbUPTLZCDTyNEYLxpeYrzc8PeGAlpDAl7Vhhqgf+T722VYQL"
    "e0aYl1+I/qYKHwYFaXLf2c3P7p90SLeYTQ3mx4hR7z1Od4Tj6fj7cs0m2bpd3niLT5d/22dnEA9h"
    "7fE7Z8QCvp9I6R+qCbFYwPrpqEgxQUgRVfZoQaMuT/b8OB/DRPdtw727T29pp5z7DIWpsD5ZQ6RU"
    "uNXTPj+vKrwICnL3dsSchOwOe56VfGzZeO97HlhSSFQGw7r+/a+4eivU+43Zm7wzbPdTiIyhASKR"
    "kAAhDMwwgdEoBTTfmWHLbV+MO7ZgAGnbjr3GNc1VXfOg6tFVlAADDzO+OeVpb8b1U3l5ByDLQbo0"
    "q7r7Mk7Pi/E7vVDuk0/D5fU54kvHxahnn7/rmy/9Oy39KSUxFttJUCFjZdc3SyiDeuFkMvi0ewuW"
    "T5y4MMNTlcAM35fzW/3/0S/2weyeIWRLzq/kBO1nviJ8C7dHBI6hIQjYOfZQ/K2qwtthrs1c1x5E"
    "cd4aLxNlMgqB2Sr0xRBg+ceYy1XOh4/KNrTcNq+xJDE9mnUTfja8TaZ6iVRN2joUUz7adsa0cgsl"
    "6de6q4hu0Atz7ZHyGOiCRfnGho7XLv+LLneEJhoRojK3Oqdtt0BskFgg3VSgGxDwqPrWo4CNlGby"
    "VMb51Ed4h/k3XVtULnURjcVEpsFddONLStQ0Q52ZVKRZmFTC2esH2TagUrX5FheoGigsLWM3kh6K"
    "9sZBv3vrEBFklgmHBU3azUctUJfZTsZ5Qan6KppAH0EnbQi5DQQ5mmzQ/g5YyFG92n3sMM5Qypd4"
    "uj6N3jR73mLfJc/IoC4e59teLfWM/TsX5BpftGB2L1io19dpPfsev4KvIsxYktabTmOg/TRP0qvl"
    "9e5zKzhHfhwlByVxTYI9gkeWEc3xZ7o3kMEBsGUxDswuq7PzNj2uYQle3Dy5XP2Pqtaw1uYhrjBr"
    "JCtcdH06ss5p1axgO5eGAzGp5068FoCA0RdjIoFqLk4h6yqp01PFQJ1eB7FWkSE+1yJSn2yF27bB"
    "Ujj5GEuEC8PTFcoiM6sPyrxufHNdHEllOKNzR5pPIkxBIREkYiiUYVQ/APfOJyqk7PTBHSVc6ta7"
    "HqAZbdX11sWRbUgQDYblNEuJnZMinbUudqF3dKbcv5iDJo7LYdxyrWqxq3V38Y5rwvpjIiglzzCl"
    "Jb2tjGImLXZJlqGKiGiPArqDfWey7usvdr8h6xbQVsDAuroPyxB4euN8O6yO6Qte7cNJoW5c2cdd"
    "jEaHXexeYdaXWwPdq6XmuRtbJVBIlhiN2YyXfeDB1XdrHisdl56bahgSTSTfM8s9nbazGTMGRQuf"
    "URaXCdiZlkIl3UXUJCI2IJbtDqdYpo6gyFEut3d2LOWEGFcOhJMVJk6V3t3V0WzupdwsZoIINFMl"
    "w0N6ZBVgSEhISCxe2sduDsaxZ0ug4OCzltNSIWhggHGZQPMTiGZwMTqb9oFIzSuOt9fXh212bPeY"
    "CqoopJIs0it8UQ245HOt/Ffc1mIbr7tNaFXITYflZ6q+R29Ls40hsnmh+1bYb/zCGm3XNChKOFV9"
    "/aYURHEd2MMYl7BVYESlCZw3hM+r54h16Utbg/MhB+wttW7f0CERUIkn5IhGMMBcymDbSQ1ENDEP"
    "oR8S7VZ2Uc4xuHJOSR9XzsUeHykisc+Omlq57b9qvImUI2PR68oy3GmrXO6Dd5xH4HRsNO3RgYvC"
    "9C5SDmiJjl8so47Tme4pKY9Tby38+fPR4GZxs+chqdH5JmIQ3hIbrvbxZ+nPPGOveAkbmxt1pL1T"
    "nXxxFe3jgOcSUsacMz5qtN/wSdLne02Vj+MHUPGJASIRcQ7igOQUNsGv1ngrmnI+GL66PeVCCqWh"
    "kJvRWwZ8Q0e2DCC3jPK2viuMsYuQQaGDYOPAccSi47NLr62TMJgts4ZcKanqlCEF23u3lXjQDcO6"
    "wZI7tbBzunyZmDQzMBU23C6H6OC018R+Rya+0iTZp+xrIqLOKxs/y5tv5ybhBynWciBQ3d57+uxq"
    "GhQGW6oDauEhXHx6ajFjFii5JmqEN7IVd3p7tsmpNvMxePOt4jnTVoxipv3Wu/xOYfVKZfTZsWzf"
    "WaKYJfWzMRGgmwzIGJwnBVThTQCmnVjL4XvNpjNAPBPAZrsd0e6eZK5gkw9Uh3kY3Xa5TVjvt9uw"
    "21HzlvdXrSnZeRfLPTxznlXb9rZhoDzmyGv1mnnROc1rsG0GTZM+Ko3d6Y1ZmlHlS9Mg5oIvpi7e"
    "uuqU2qKTk0QvUt8gLTTecf9fdAxGECGFc86H9yuvy8CJcxoHKxCSvkQDaGLGg81l8Dy5QLWqkHWq"
    "aoquFRyIhIvXrWlDQNFZ1E9Tj93Ndnf+6evpDr2URKFWVKoIFQlUUFtqInxllpllO2XGaZSCRBRL"
    "qopkpS2lWpccMSmA1DvCOwaG6da6P4Tg6XDtbRpug2R1Xcp/R6Y9NYwRILPQkgPftj5GLY4EQmCa"
    "Iywr02wtsabVlLHTnXw0Qsp4m2qUq4Mym5PAIAISSvlPzeZAg21tnkUUitvwoa6k9VrWtGZrtLNT"
    "WHXpjTi3oxh4bRzJgXjrgElHga57Y5ru1vzMPfw2stO9YsUpYrYjsdq9dFesVdMThOnhN505vvKz"
    "6/R4+MJyKRwwlQSJQZzpyoOQCY4psL8XhQ0waIBpyaSYVaTW1msCMmI0liBdJJx843ct301lb6Wn"
    "ivfRzOWzZ964s5koFbyUYS8IOl8Pu8iFTVCyZk4nY7XClQZtXKEFFOwvCJexhVrTTkqZw2o2qurH"
    "h4DR+PTC3Xlry86SSSSSSVVVV9rVSvA9vtX0mmb7+QvkYdiHBo7ykxJbrM9mujzti3QsC4w5jONU"
    "imQjHjZevRZnRJy/I9dcPYMzUYKGWuqpp4GuLYtLTyfOjZlhcX0zKE3jF8wxHLibO1S/RExKRxbf"
    "hns42QPeuBypF4mSHTvWoEHbAiBsQEtKzSLc6dbmycHfqsZ5VsfQvtI+xx5lr3U2WW7ee1uSDsLF"
    "RG53q5LPhui09xOUzsn4IeA6qd1Z2UbJEh0EnWaa2RVMddts+sfrabRmU6WB4+4GbNW/N9gaigsY"
    "Rjilhp0TjyCLIKC/DCAU39oneD11a/K/RQ3wlmfSyujdVGwJdcA4Jnr3I3LqvdO7QUDGrsurLd27"
    "ZWVViaztiHsXxlVSSVhjJs4eB9B1M93nueEXfeL4zM9KRVaWo0e17dduyvJpa+JxFrCjfXRJaIBI"
    "PAcZNtnovbd9XtAQ+z2uORckhsp+wweIXza+Eok27nw9nOo+HDdTK/CPbYuRtm5iRsKPIkjcIZrb"
    "d3h+PFjLGHcYPt/JEMP7jsZkS5FKj7dvxm+RIRo+RQqycKdxcbPni+uUKNoO2jlXk0FUCsRdh6fE"
    "Q0J7QuV3cNwrUndrU7AidMFSQUVNboETPX0+BXs3HlojrJIRIrBJAYQAkQzs7rHb8umw48udH7eX"
    "IqUGXY/a3RCCBaCEFth6M7KqD0TVIRxYIZRYiJEjSQy5d+w7dpnwPfZuT3++vGIUEkT8TSkmTpgq"
    "dtAcADXhWvz99/FwcS06Z0d3dCWd9vGFOyMNz4UyGupDoel7Yo42W3Sp2vqp9KyI9oagBOIj4/UW"
    "J5QcQWqoPhFOUdmdHG9C8qO3nxyzhrwYNbiqSqKS0auK0SYiKTbRJtRtBH2Km2LRDpIdorADIrgl"
    "E4u7zoB/E94/iQ9lE+b1k/moCwOlDyQiH7yG3Am4hRmAvKKXLp/mAiFo+aj4gnUAVuLDxv6tO3Hj"
    "HP11J5fP3c/d+q2zj9xPgvd+tGHRgWKPl300U/c40ZTfNFaq2e7xtpSw3j4pX1n0q0TLiCZiZ6Qu"
    "Tp3hMcn8fG/wPJIjFwqBxqk9LDZyAqeukD9nroFIENPvoLIT4BOsognTjCB+gj8lP0BwU1+jPmGY"
    "prRgiDGjB/nsyu8A1LLDl4ZAP5gQP6DCVRgf0QEhR5YFnZA+fMBAEyBVBdPYKQuhC4HqI/UKEII+"
    "SAUB/TNbfnz/y0rmpVxWkvpwk0bPTblX4VUUyiislFNKlVlK+U62V6lTCUay230Fvulvoy8tqa2s"
    "VjY0KRoorfLvmdavSBaNeLvWfwGQntqid8lwqURZKiBVVQrX2atN2WFlSWUfmvCGDIQ+m90sI6/i"
    "6hDo4hey8i/r+/izc9MN0CUn1y6uU1C4iOySbmsQqcx+vjMl+o+YfwH06UOmUain2wti1n4aISZD"
    "8b7dNPByljCfN4aiWdnTHZpe6o42EtO2ipeyc3Q4XunabPazsYQkCIiAgiIIthozKF1l1iPZmGcX"
    "aQ0GsDZocs1eR3PqPy5/Jfot7PSzneFUcyCLS5ZK10QiR61xe2DBFtc2ZTmCHffDOZJdEu0CMPUa"
    "pgLiAzpHUIacifs7RgyQZ/KX61ehefLkCEgx1d81xsgTMoPR5c0eFgExnSy9z+0hk4sb1llEkcX6"
    "lhgVHL5g0cljYDj6Kyln4N9+qA35L3X3YQ5RaCrasu57v1NuaLB0YI0HG2okAZDOQgH4G4B/jOZu"
    "SFMC2d8V2/g2ZyuKRV+fzSa0BZaryFKHNa5zOHm0yF8/h3XSLArO7q8ItqEwtTOBMTIMXHV8XRgP"
    "q9vjPPAbLoYQgRXWAQZ3TI3eR59C050NWFoEIEPnRkXRkr83GOMwaYYJiwkRxyIRLi0Gg242D2/w"
    "HWTYLAi108rC3cSpng47CZCQSjoeGlGsWUkqCNeyc5FJ17o4RPwnX902FsdXf2abcWDwCe0oF1Hq"
    "7JU/aLoIj2otPJB+2g6vO5SuIimTnl2yINemS4fjcOpZ3T7YmCY3oDxl5zwKy/dQZcBM417AmG4a"
    "qNH8h056zcybHi1XDh69Gch9Kqx67cdVnLuqlKC2rVJDuhCIJh+9DO17BTZFT/dhnr8vvXRbnhLg"
    "pmjw07rPl2aDCZKCNFtxYuqZcKsoi85W0QDDaa3NC29kQx3LE9UO2H2Ter78c62N4/AeLavD4v2/"
    "DpWc1ZDNsWdW6NZz1j9tGMGthW86740FFllt1J+1gQvqLbaFsHLyqTXbG6Mhgxt4Qaleah+3zZcE"
    "0YJqUd6aroZy0ag5iSQ7hCCdkU9O2jjV2Ph4bQv6JDWjlVDuvuBosF84abIGdqdiEXoIGWUBJeWB"
    "yT7w445EEEHIYqSSTkQWbpiExABoXDxouadtE2PbsHaaCoYK2GGOdercVmqnnW/W9KGno13FElfk"
    "8k0aH5xiwTTFZJJ1qdIMrDWjZOKjU9W80D1gieaOkejVS3xY5+z4KdS2FKhvgQ7Lq6oLQRy3OBuI"
    "vektKpBg0FxVOMfAgdDsdKUJ3d3btgcsCeN47J81rVKjaGg8Mg0m9O0HDyLvWLHb06umbmRc3JWo"
    "l3+V41VxViYpFrMV2ctMTXmjyX10DUOgdT5xEOUHHKxJymS1i4l5ysYek5BQiO1M9fAsC2eeiZZ2"
    "l3loEFnU9r8wp6HcpRHROwJc+axLDNumq443woHC6puzly3e28xHH7rNFv7k2YYEhhvoXEOAZVs0"
    "WAMQILAga4pQQShCKEPz0CniDvYnQ+74PgMvugp+0gB1BEzXsqCRTtVFBubp74AAAAABcrOsEEoC"
    "viCJ2o5fd8Ks87IfdK9lVll5hAlNFbFsqC2VsqC2tqL7PPL8mFAlepHpRqvYIUsnCQTBtkHDDvB8"
    "eN1VCRRVyb2QXh30B3wPCy49Ra3wU529UL+qgNFyTjdtvsorakec1MqZq4znqyk5TTebqceFJbKV"
    "VqFv7t+fyLXWWB5B5DsQ3HNHProA2RTkQyHB2EDZEKD0H/c2n1Hr4Iia7ju/b3b5JJAh8Ktvj0pg"
    "rmWCQQDAnoEDZlENAwAoBk8sqDEikMUUUL03bvY7rm5LOvZiiiiiiihfF3W5t5Lvrl0uVwUZ8ud6"
    "nZv0Hy9JoADqAMAGADFUe5bxXj8Ny9a5c3RjGMYxjGMYxjGd9tW5uMUYoxjGMUYoxGjw8fN0UaKN"
    "FFFHq8nN0UaKNFGxFd19x63rAAAAAAAAAAAAAAABqrqREREREBAQELaoRERERERERERAQEREQEBC"
    "BHKrcqpaIiW1S1ETJCQkJMAzK3SfFoYqyShHsyThaYnTcaYHUWFHmmyW4VMErlOstwTWAUTOec9M"
    "0NZmnSbWKLdPgmMXd0nPYcrsaPxfj6+zO/PMqK0dmowSu4FcDk9+cCba0qrjb22WmMSg/Xt6PV+T"
    "m79DU4HlHDZf5yxgvBqis00PZiS88iS48FohoFGVFpGpuAXMUtF2a35otErssq5baDvNmmY98cCU"
    "9Nxby6oG7qSSSQBhAAAhOTgAAAAAByra8nPoJ368/n8PDw97Rga8Ctm6q8TB6N0zcazu0whStRq2"
    "nqiYfMU2k6anIFvNtBGQ29sDcWnZBt5P55DzkQNpMhiBzBvl5YBkVDFhNwd3CO/EtihztaZaUHPd"
    "NW+JbcbXCqjBoVx13uOXuSpWho7yBSLk9dFBW5xIyy0WcjytKrV5YvHrp57mvY3SrWvmfUru7QAA"
    "IAAAuttWultWunQAACgAGF4ddq15LleevLuv1PG/H11M6pj8/qaCrNSWGXjZcxKPHT35NFVfPziX"
    "UCCAXZ8vNGrx790S1czYSYPaDH7A14/9SZqV21zQoehV9ouFMa7p9Ib8oxlhZ1+noS23Qv9MLLtM"
    "nhVwjx7b7N1Ptq91OmdZsj8I+eUmia+pbPr15+bFj6D9OW+0+/6ZqOVRt+kN5t6fAfbQv6deA7pO"
    "72u8HZPtZokIqLs7wg6aD1dA3Nk0ZqbDR9bBQwYmJY7uaS3PpRoo7BH0wos8OBwrPi8yUIyrL9L8"
    "LNPTDV5eaNVE6I0VyooCQVFw0LE4uReWFcVxJ1N9HeytGHc8UQO8nG/HbbCxVVUUUSqPqYU1tzbF"
    "re/72Gl3fqd4QbIiyTKKZhwQxlP7kp1geabpNPj79fPnues9suw1akupoweDi0MnUbWDAaT3jtE+"
    "Ep472bhxIleEmptuWo0mlpac92nn1w+GLl6ZdO0xuCQhnYHcuEEGCA4I2fxfA3uJzYq2jTayq2SU"
    "kpLY2zNlS1KSJpmtjbVIyCMgySL/DSBYYsfxn6kRMmyyD8DICkiIosJJRXVlP9ww3lWaYXLi5lca"
    "uNs0iNxrgJNcKp/s0ujHVowblxEEoBasZlorOhxH5DpWBvOWjl9/saXh5+Pf69Xbs2mquE9/De8q"
    "SHWRpHyw7/tXIWAD87+CiiDJhEMT1hChVvEFSVzSyA3nysfnbCTwCqb/h0xT2TolLsss/YMfzx9a"
    "c5Q/cxWztN5DmYNxBxnUJzOSNKc4BCAGycCO028AsNDbVH/mFdqGajBClVEiHc5tt26j4vTqLp+X"
    "zsmAZkJ18SOktfJ+MAAdKq5wAA5VXOAAHKq5wAABVVVUlIQNHhvjR0xwYHQnvGG47lC57jg0yYbQ"
    "luGRrQBagw2vpTB9tkIXUL65A6UMp3nkz1F3z9XjBHVplQRjhhpk2nUOodQhfHkKzCDcjtN8KEAz"
    "MShUSkAdChB2bdvf0ZKpoaHu03IAL59nSaOzZIVxxZ+oh8dn2n9dfhBYok9hJAkT9Yh5Ci7E5npg"
    "G8oadK2AuKiTi9/vD2zHqX5keIA+ww0uGsf5mTQuZgV99O5g63XQgby4vNIjrv6SlDIm4gfqIAD7"
    "7KCJ0K8SzljgY6cwze8k3mhhsrpUUYoiYVrMRBHbFUd7ERE1mOywtmh/VTQC7HX6bsOaoQggIUbS"
    "KqhwAsSop0xMiyG6g0/jtCyAhGIQbkpVRNe6x5jjrODirIC1w4BxGBrJ5csj5xPb+gKEIE5S16nU"
    "pkLRNkOnOrJ7fltmZnT2W1/euHst+A3VFpSgnceXvfwPqYe6nCfmREo/fCMJ+W8AWFhNp/D9tEvv"
    "953jCB8lqf4Potttwh76e4CH8ICd5lk+xICIEImGiIEQfynIOoQhAzIJwIBqWUpDFNagTZCwCa6h"
    "eN+/fW80Np4RR9A3EaEeZBZA4ZBQbiEMw0Zvy/CxOXH9NimCKJYNSu/pgZmebbeNifngkgSCSCbM"
    "wyrVhsrJEmVIcWKxiGJllu442RDSQqqdVKVFkH34NEcsw2pncN/VY2YhlidqqAbDjAPmnX11e3YS"
    "w+PCHabUFQIHKB+wgbFCEtET9n3WzOV11S8K9nT7VeiVjBsg4xYm88h7a+9H3sJzuy7GUBdLklHx"
    "TRXgtIvhfcUA93Ezjg/JXtvZnNto1FN4le67QJP3IFPr93nfZOgjUNl0mk+EDSPxinIz9s2Wa3/R"
    "mYm+Hrjwi1kqN0Z9Xg0G65vVF2BmNaCuJxmbLfsv4aZYX0FnFJ/ZxT27pz0W54+ZDlD6nqOV9n1s"
    "vk1ayZeDDFXKqNVJGw1mqJmaX5cNZH4Z+K09rOOuw4q90Oih2VO6CTWoDDpjAoSRzZDVpKjd54MT"
    "hgxMCJx+jpWTdNmx24bcE/NEeI1VkZVnEwhE3RUt0zJDb8PDuZ53SLeN/cRZfPcyJjsmIB+5wtvc"
    "OcryD8XgmDtqdtAhilBrEMRNVsBqB3J11zLDaHRyyROPXN/ew/TNbo7uzYg90Qx8DuJy9J7Tfg6u"
    "d42IcUPtz0g90EkEqAEdda8ed0Go+kphBTmUKkfSLk778YlfovYPlZvYDMIEQUIjGER5NToEhcD6"
    "8BagDIMiERHZVOWDieHewM7Iiajk0Dt606cc2sDIxJIBWBeJnLjqREvkFw7hBqOMrTGJSTKiEDJs"
    "KisD1+k0vLozUtfP2kKELz/F0Je5eFZ52S8mlMI7TYXFkAjBsLeIFMFMgJE40uDfZFmm6zkIB9TA"
    "WPwiUoqywlgJbIQqk/8NgwGCj/LZLNUCsIsFkI5VoJAUAWEUBEkohKw0yjAJ/GyjPBB0Fk1lkq6z"
    "a6rUzWryVXr0pSKgQZggZBFmAPd8YBHwFN+rG8MjPwtoaqTjNVwcjRPhNKFHpmnD3/FgdmmLciql"
    "wqf2e/8L2Ez0LrVjVy80KfR7/nmkklSXdWwQlBx0DDO3ubP4T1+yD6HLy4+61Yolkwh8K3ty93pP"
    "a7L57MDt4obwKIOwuO7YORZ7ByqxOGNgOJXicmOzbUhI1RbpPOa24EIJiA7wBWY6IXy9/ea4NPKr"
    "VVTnS8a/vTDSIB/xriPybDu9rnGiSERaM0+UlZRzXcMQCeQUJACIjyehETUl0RL+9Fet4E5rV8tr"
    "0SQ9P9xf6Ps1fbkdtDXl6xCj37h/aJ4kvAfP2igsh9wiMQzKFen9/i4t+1svFdZDLz+ckhJJLAe0"
    "kv7AUn+HF8NjpkfeOy+90/QY4yB7/cMHsXnY2W1d3iBCwJmSQkNTDogJ5xBP5Y/DDW/fcMvufPU/"
    "ksqs7cut5s5MK71HHaatbpwnGXXG81E0hy6fZEzV9jv37Q/BTPxF/YDy/W9iJEsqX2w5CHAn50Oc"
    "QLPzJSoFD9k8vky0tpk86YhfCtEA+HBB75J2gTUmSMCAgnP2uj8OzuDg3kv4qVPQIiB4D1pQRltn"
    "tP/L8Fknw+vgyH4RREVnjPmBEERDV9qqjEbCEMgGOLbJWttKDbW2SltW01A1IQg+hnuaPBz6ftfr"
    "IbhEe0oYcUD2I9XB/sG3lA1lPyps7/wyPewqbAgRjGB1oP1QPi+88WyntiBtoOeYQPR+FP5APWU1"
    "Ond1/EImhR7sV5EjT8Yj7sTGxrSPBBHQpUCWqBqO5J0/y8E8Pad5d+gDVD7YEGTX2XoAFCsCFASK"
    "jEZJ8QPhbm7+jaoG/xpxopQhjoE8RHykN6VPqqAAAAAAAAAAAAAAAAAAAAAAAAAAAA5875/mwAAA"
    "AAAAAAAAAAAANAAAAAAAAAABt015l+lq/DNIkURKPOh4w4jh4Yi98iY7IO4IB3wuUdH8FJYdUx8P"
    "mDLuSBi8CELDnDODt+KazD/qh3J7B7k6NSorMog441v2oWT3k+BF6SSSoQqXp/sXsrjCKIQuG5ns"
    "N5uJajtAb6U8A0r4UXASeMRG6dTY9vn6YZ4p95Z1u+OyT8M+uH1kUVJ44eeNH2AA9eX+QT6b7Zdg"
    "k8J+/sGHQLnf7OC5TH2VbN9AvFHzvQrtDUMt9TKUWMT5idQ97oc1n+gy4jHXjIoJIHRfQsJzrMm9"
    "GXDjAzyNG/bmbrJD5QiK5RO5AOJAQOc6iL4WX2rB5+wdx87N/UKwilPuTQ/P/GUczwuydhR1nVpI"
    "Q7cGmcHRLkfabIj2CweebSfhJ2b2lEi6BESlLA7sL2IXrFO6MGlcDw4uIhkIXHVCQkKAa6KO0Ikw"
    "A1FBdLcG27+KPSkkJMJmBGkqalNKa27SKWTUSjlbkIgtAUEd+927OeKdxQqIqfY/1WEoKMRCpXwE"
    "N+r2jwpOoV5+KoEVhAPy+GzZlTwgb4hCD7uv5Urw8emVTaVVheq5yXfTUWnL5By4zvaVYdJMll5u"
    "0d55RWAicOCuoeEwQ82m0geCO4h/8h7fOl9BrqXp/BSaEd4JrRepRbFJCoNWyBYVrWqAkKytZWIk"
    "VGe8hD34oIdZ2S/Ci/mRSjwVfgqB9wUaQTJ7UyQkfLqGHbLJzknQ2nB/45PUenz/KgiaEM34ug4v"
    "BKHHgZyFvHlpe6pk636rmMLqtgZsUqsy4fmSHG+9igvHCjH5yaDTE+scXIPMEWoErgELN5CjBy7J"
    "2jIk3g3zfQzMBOMv+/YBdv7mHXEPKPjVguKb4+FNgH1WCUPlOmOQpYGCh2xXFNQYiYDWkDilQ966"
    "DuX8elsm1+Re92nqVd43pAAWuSXGiKfj+zT0ceLMzMzMzMuOZmZmZmZ6fa+Xi1ZgGHTpd72YHuxn"
    "UWn7+TSPwS/wyM2zS+Rx3TpZ+qI6EHsH9Mz1rfq74iIiIjQaQmXgZR7MXd3d3e5xr2/KyX0B6vUL"
    "6k9KGzMwQ8aFsxqiWHZgJGQoMKRJDG1saeuKmYeoJQh9GlOip4JqHIX/5HyJFAxgjV0nluDuTRGg"
    "mCh4dCoF9M+0M2fmZIntaDfNWJOTKOxzgI9CiIfqf60NqRkKjOlmgKI/yfMz+j2+iok2c+c+04yD"
    "gJl/e7OyZCHTOs5jOlAeWQtDMqguSzt93cchvl9+GvLbvrG1Oaqxq8mMOXZebXVOTessoNE01Ntg"
    "Gr39Cx0CYCJCJjRVV2MaJ8efbL3EcfRQ1Ftzx+LufEs+OdRDZ81oIMv3DYZMFlNQ2CBjEJDQYbA4"
    "999pIRckRL2XLr8OhzIz+t9e/OaDuSYinAgvHFDsQzKdehQsTkFZ2ROuetLhNHp1WDH9X/npnEt2"
    "YcvOWGaa9vaOps3SlIFc1Ya5KSG3hlS2s8RYcXyWue1hkXH1YJfBpD+giahmcNRCBB8XukISDmWD"
    "sejpBlyOEjPIntuMxtibYZJfIcFwhcT4HrfkzfmSyoGAbTIjE1896nOV1JYDpGkUDJv6a7hYz4Cd"
    "Jm9VNE/qf3/TN7L9XR6Qwge6WhMp83fLsTUir3M9c20tt1A2oflENCLBgMYxmRHmo1EZaWGAM8jj"
    "xCAot6ePNDwbvgw4EJBKwo5jH4T77hxGZvYek+0H8Z83WrEzExofqo80PArFWXvSi+Pr/cw6dNHO"
    "s9THn+DUN44mzOq1KLvVfuQR/BaL5a8BhPRXyE2gy4cYGeR3gWNHUm9LT8LYUrvCIbh05EoX1scE"
    "f7QgQ3/l8zY6Adjl+isC8K66fTCkvGpIQ/FSf6/d9X+H8Pv623pfP8Xw/5e/9/8un3GIf0/VxAH7"
    "qUGH+s192TaKKKSQ2QTZAge8hkh/uhio/Y/wXq8lL/dU9Rb08hWE9ZQfuqAhhCejPHr9khpNsaGX"
    "1n+k5+vQ5HzH5wSKbww/yfSNGRCBlAhmaF3Bg8RDgJACAftYplFFFFFH6ObjGMYxjOm1bm4xRijF"
    "GMUaKNFGijv3ZVeDuMvHyuKbbyfOH4D4w3z3EIhEIhx+wXLB9YtGS/iVA1BYwIIj9IHwGXHvuskQ"
    "0129pPkbBg5nth7Qld6CbdhZ96fpHzt4TU9RD8wDvImwHqiw4Mrg+D9epJ9JvK2PqMNrgnEiQSyc"
    "E7hn+cOBo7RXgHWZphPVDYG2wqHPpOZzP1nqQ/rQseSP2T+qJWHyYhdsRD4BCYh8k+0n6z9hXO+P"
    "3R+m0LbRRVVcPVZNaKqoiKiLa0UttVEVkYiCeoIe3+8H2ZYf2oddBOufMSC/tBz0hJJJPUPqQ1Pl"
    "d7xHZ8/pq05wLT5ZhA8xD4/zL+SxVFKahA1A+cfQQH1kVMFwHacSEVIsTw6AFLmcWspZRqEsGWlg"
    "T5QZ8QIHSTqcc9SoTfkJ6CuMh1m19hDCFh3AHN8d7Qb3pHgIY9LoeBNqGGBtPJ2HIt+g4CiajtMw"
    "jBIsR8IH250PF5o5MzLhH3UpNNNXLVkHgiHQk0tx5gSEhL2naXHG2K5Jgt4xC7f3NXPNNib8IDHm"
    "EAbA+Q3Ic+Ih0uoLrzXK5d7exno3jvbrrdfaAAAAkkkt5hsIkDfAf9PrE+ThkqGgmwIrxcPUBx4C"
    "TwnGlO+7nSB6vX321LbW0bWjbaNGrS3J5g6w9w6yaPFry6xF7Qu9a2aClwHtB0+uP5Qqhgcg4HGo"
    "dhOVHQDidBz0IQR8YGg5jwgOgQCoh6fYmZBdTYVpIm0WMQ4V6nd1xGYLAuGCptm3dAE8BPbSqqqq"
    "qoMfA7z0nipbKFLCd+SUxoh5IzU92U7FQD0KiMnoBD39KpAk5NOskNQ7BT0CHyFgazfnVWWDzOpP"
    "TPYdpyHT12dTSrSImIUQ09pOzvPn3kBNwcsBkhqATeUfyKOCYu8geIzMuPc0ajcr81It3nrsp12V"
    "kJXoi15gkEXs7IUWJUz1NQdMgyw7AbXVeQWMDoV2h6vsIfE7sFC8qH8vQPd2Y3LN5MXziwM2emax"
    "jGfUuOONNqAXjGRaz61rnWNdrs19KxjEzi8COBt4D7EmrovDEu4DjoexHEN49ZI58ZJNnKDdkxFy"
    "mexCkZt0FCOfPOcVZs3vB1alhbiQkJCRrfnWh5Bopmszey5Q1c21BEUUzHs7tJlC2y8Roc5J1zL7"
    "5v1a417TgFYIQaBoP0RrezdvvfmJXXQ622WwivVHkBZ6nIIj7h0G/JSejnMIVKOjXMhMiEsgfg6q"
    "qqAwuzreXeeua7OwAACAAAIAAA+bXS7b3q8W1jY4Ih3ge03ugxgdEciKQnHwAostY1Ak2cvLoFBR"
    "QMqgHtGKJiaEDXXT75lQGVmMbjFgcLE181/BaB0juAMHcrs9sYngHeFh2oHuIAdEQtlUHHWkwY25"
    "URkzD8ZAh40FEJCfnw6sEIsEzVg0U0VtK79017lnhvnmrTJUr4eHLTCH6qaVIGCIdCIJ6DijGQOP"
    "v4u7krZia3vxEpLWktZVqllqbLNSylOnjtXTdLUoZZQzYJAhCJr2GXgq5IqRRA5If5e8JELeEfED"
    "AMPKcR9Kfmj++4wSXoToFJAezFTpOwE8NB6jmfpDicEsNkNsM0sjR2gIOooB1jwVU7CKCSBAiQkj"
    "BjIoEFIoHVQ5mpEE14niKGugB6+vtgX3wzHUgiGZ3nHPlMEN+WM+OMiqKTUbImSGwa9aRNwaIL4k"
    "QH14TKeLxXu7B3ZJrRUZCZY63A3hoZYd7evyyIQXkqqHDtF9GudkIhgGaCdnA4QEOKi7wUiJxbQu"
    "z7MdtlGS9J5JiBSVTQxEB8uGLQPER6TmMOkATnMUdL8hb3uXqDuQACgF6IxgjyCT9MZC7vDLANw4"
    "DAK7MFOiDx7hcg28ZoPR4FkIs//cv23GrtH4bmDEmMghRC56J4IE5dIKHIgLzRv5CAH51uQhJBIi"
    "SKwAkQSnMfacvhuPb2IvcpZfx1NESPAyaCJGaU+EQD2TBgNDgaxpkY5xPGNho/RAojmF95UPx329"
    "iVthywyeMzNDoEMVI2Uxh6kyEBQnH68giE+qCBfVQ/rYaYwf+MIcqJAQ7ipZOEIBZSiCQkIFcVWS"
    "RFD5yIN1SkuJZRVIXcpQoq0RKMEXCFrXs4nTtorvoohkmgho7BRLq0uNhSC2geC4bSmFJa7dvYfm"
    "NVx5HiVKSwyPhSARYISIFbWMHIDfHsx3+D5k+ISEQISEBhEVOjlSIcIlEBUjjKCDAzyzAhx2xj4j"
    "wT8ncHf+nKjJHBf/Jp7tK9Zxd589UDXEBUg5CXAp6QqQcut6BJAgQEXPpMhwKZqBxXx69bpNH9TR"
    "Fgs+o1PH6TJkLESCsCwMLWIIMP1IdGYoaNmIGFGiRWQGKUwYEAlqWUK88zuYW/ME2WbpgCDAN+2/"
    "Dl/lfz4/n/i+nnhJOAsPzYQzP8VMU/f4ZlZ7sG1qtAhkV82QO2Ipb9DQwiyQKJCVtlE4pMRBFrKz"
    "N92bYHnedHJhMiAuqRCisU9NseDoulzzCPD5msZrCqCmtZg3ZrgSubqvXQOTR74IXq668pkuLJBk"
    "WYTGmjvhagw1eBmh5MzoN+gNX01RgcU0hD7ulBD4eaCBvMjuJIPtIPAXNwHAzhXuEth4f2F0hDwY"
    "NBIQY4UEigiqjKRJzJiBwRrniHMlm7KUJxrWamMcospS4iNy2GREJhlxIWlpkxN4BgJqapvgnGAG"
    "MTZsBImKLZVdlKONjSjJCFMBMwwBqloQvVKXGgLRfBLBvHPCYI0VCW4yRSJUkkDRClM0BAspWaIA"
    "UAAUwAwxRp04dMR9EA6W++8qqyQlPZVVK1DcKpsANoQG0IgQSAtBQQdvTAG05jJ7xoVWxnSLES4a"
    "/S61CgdaARQOKNQUCRFEyUyJFi80kPEPko5wNj0fVy45HtUCZAZiG8bDJj/RDeGQxAcB1FFw65NT"
    "02vdwaj1U9ECECyd03A5iGfYGxTSIWQXwimnmbNqo6KeW+/d7vKrR964GRQtfKeOqcyB/OQEl8f3"
    "z2L0dYR5ufZa1p+qFnMWdopAmh2UHyppy8y/nJQoIhz9GfLM6dXmBb3CwVIDIJBCSJ1NNlGxpqxa"
    "HLA7tzRrVl3TE0i5GYXMlLcwaXuC+4aOXel2F2M4NhqaLSw6vTCaEMgyCh4hIEbQQisJRrNAwwyr"
    "JMQCpDGoS8dvay21hrMlGYzpK/PLG18bOQvl0Cxrdyy0VFZ0vL5urK4ziXDAC5Vfc1emJC2NaD9r"
    "TXK0tL8MpvJhMctOcc9E7BfesZatCraZHrSnpGotqvHCnAJxjmJJiGNdXUGd8TirbJxRG7cnpjm/"
    "LTGr7mUyTECc1ykRAd5pnS0fa358mzwwHPDGnThjYcZUrgoWJZA6YlJJgpOdaOtAE2yc5OJUjOML"
    "33BmK9XDHdl3ZZHqIuhlsk37VMZpiw3uGuMxOsNYdE2GXhJyJxLA5l2aUUhU0wNxsvGwMJqnNhqs"
    "FCSw1QAoUQSUkCU0GsVLMBWM3vjUTUzWcb28GAqqqqqAABgBAAAAAIAjputunN1K7edVzpuvYjVq"
    "1284AAAAAAUAAAAIgFzr07um7u79h6+Wl5+Cb3dZDoHmbm0wXpdoPD9FJ+s7P4txx2cRL0DaEE5Q"
    "RybAKBYLBIBEYiJAEBBgISUp3JjwwviuE4ulmdOZnil41TgF2QUBlSVtKwRjBFAYg80hhHF3wmZI"
    "jmGpmleca5tFM8YbADoa0qqydiURElGGCYwRq8Ls2MVRirdl0uW1deQXZkTDDJaUQolEqZ6BU5Am"
    "4QMxsyLRqOQDCiKbVyHIjC0B2MYGpOuQESAqkOwGCFtgwkqIqSCEiyATFwHUJm7sQ1BkuxE2cgHZ"
    "fD86KjIpEpiGAGKgyysKUKhStFDBIMCbBCFRGQkZ5FBOzkdnj8lijIdRancqdQeB0Swpv/SfzDLr"
    "FerDTjnXZ5HHd2M1DlDoEo739F521ru7sYzSbChGZ1qIkOtdYZKwJBQO7UZyMTjRxw3G4YmDMXEA"
    "xB1oFgyAdvr5dRm8Ha6vAHdcaFDIpDM20M5tIPaYQUWheqzxIHpQwA8VlTdltzh8kBEogpSERIJA"
    "JqKbKqLKBA0ppNJphVlLTTREwIpm2wTJYhJqjFJrLVm1oKICpfkOC0Y36IiQgBmAJ6tE9EOrfqi0"
    "JjybzK1bgZgbs1hhqiGk0UhpatgtBJYMCADBDptXqoqF0pRyGgJSlGHAu5O9BneGbmKD6UOrTIOz"
    "PsPUg7CX7kTfqdxAuLCqOzrS8sSvTkmDIJyjlwEJRqqFBETcoJxFiEuI3IxX9ORRQ3Y5iYB1GKkd"
    "xFGSTRYBmYCtOrMxXfPnJCAQESCiREQIocKWQfURVN4c0QjAm3xeoyvlJPQqQ304j8kpE263Lza2"
    "ILSfQIK69oMvrNYqwPDthJJHDLjDNyFujRdEzcka2r1nHc3TFEgzQ3ssC6pBMnHJAM3GYVA7Wg3o"
    "nxxGftOOFhugwGwQY6/rzzosaXHEPA1BRkDMmaFBEPJvkoP8oJFdbyHXuyV2r398XxXo22q9vT63"
    "21714W83ywAAAAAAAAABgAAlJJJJJJJJJJJJJIkxJJJISevpPT+keRaI/hwN8JR5kTIJFQkJ3rAa"
    "JPZvbDxAf+gOARXCBoVihZxXOBmcweOSDTQcaejdiYAasyTnPjOYPxRAGHVChFMDfOHYfDxqI8oo"
    "NwrzdJVe8P6QirFEjg4acaqqQ4idfs7QQs4clRWdgIomHpkREp8UT/xDWQOqAerkzLiVAk/4lnoC"
    "eTOiP0dD+8fLBdNVCyKS3QzDWyAaJyPYcxx55NERE/drWcIOEWRAIkBYRALoGg7RV4r6v3j0ICZo"
    "ZjuzDghS0RFIRVZCEB8ZUEhEIOziNDMjW1ohShSQ9lYDZNp1wgMoCYLIIjGChYglYBkXFCkK0Vcx"
    "2/D8W8YIqdrhciTYmscutfZrsJBKENd2eC+YKHu3FVeNKg4Zfy3uda2wXhk8XQBgLgDvm1rZcKQi"
    "IWgp1lSB0BICQDrrq3oWta7/RrfA5kyQG1y5UmgonIuTRNjVFfS6S+VirjCiDQBdXLGCik/HkKUo"
    "A3EFLq0OYl+9SmAfgZAIkYkIMUUI1jArLVRXZa5bk6avQiI7e631VumqbepaNo0UpZpa1jiUMyTD"
    "CQAvuK8B79BpnAhboGDEU2kn4U5DYeKizkzjcYIxGMGJOQSY3KgVKjrmUWNB+6RW/U4pPqgePaGY"
    "0dsMIoVAGT4wDYddCiXEV0fuVPgGmIBoNT2Aec0rYJVYpZJClBEYyJCgwm0kCgsatFOWdCABWYd6"
    "PAoOk/IbtHqlu7b/giyIkgsRi8z53z98Gp+OWUBmHz/slxQ1opjM8gXQmKiqxhJaOP9ZYuYVUTz6"
    "w5muReBFUhy8ByJwwTDcRABqk7cUOswJFJA1UU4QRa2RtSRqZsqstrfcttxVYyltomRtVFlMxlpr"
    "ZSMIKHmGdRcAwsD7o7Tx21Rb3mjZArooG21HaMzYPb4EAw8cTvRUxQDRhMyMqr8B8+yefYgAKQJ4"
    "vzU/a02qwPSyDeqe0SQRL6H98zJ6HibPg107UIci1QcETmSeWBO8SLKJQZJQYFVBSHQR+IKe/9TN"
    "anCUQ4pQPhLCkZjaynxQSoIMEEEeEs6W5TnJHVJ/TzRQ2R6pUSIc9E5RXOHo5uteTkONin3uuZre"
    "UxM2ighEg1A3y4GDeolD207ltwgBOSD7yxAC0OkQ8TU9NAp3kRYSRH8P5aOGonwbEDWcfFAyH5pC"
    "SBGSEBRRZa8fC8Sf45XLzJXzba50qP2TOJmPR7g59DLwGwYCB+Kr0JI6MmTpikaWq2c5pjTVU7OU"
    "wExYAeUC1wTqFbxtStvIH69DZU3iTE74ao0cGeuwDy4PObBkjAqEYA6l0ZIWZrJmgaM1uzw1XNni"
    "IAHB8pwVPhlDZ666nBVOKLlYpHBC5Oz79mji6UfbmqBynJhSUYfnDm6dIesgJCKKRRuYhQhTBI5n"
    "pmUg4d2mjwRESt6lKiQ4NMwZFuzdy8C6RGpRKGViCdwzQIupdYFiQUxkLjRdVpTCi52BJrAUhE1v"
    "MT4r942aO6WWZEzimkuShwXDRBNHy9hTAhDe8nqZjQiImLQogxQQNPxEZoF4DgZ2sUyA0hQZ2h7g"
    "e9wHPvijBSJH20XzWT+XYaif1CKkVFIiDyDaAJ08eIBQUjueEEk/3qzeSFgBVG5TM7Jll76O0t3O"
    "d1Oz8etehDSIy1I1KLWsjpx1gQlbaLH1EJOWcxCKgwIaAbGKYwwWGSmoNkpwiUANCjCQiULQIW4N"
    "QwQYCQgoLAOpA8pTNNQSoIlBIvdVQgDv6YuglqBqRQU0Oi6RMcwodI/kiQdWUx5ltrdNkpjFU1AR"
    "ISEibJQRToQzDmQ9aIm4fGI3Bk85RA/dC3WaDRMUSWJGKT0kD1IQFEgAc+5Ey9HJpMAnyxFkJFIr"
    "FB1OIh4RDDUy7kciEA3NbqEGopCpIQSlGjckVIoA7k5UFpEA19b0dHlXIgsT3IPGuOnbEMo6TEDX"
    "x5mAQZJdIeYBMGRGgLi77Qo9uutvgSssVEwvDNQCLuOITJkRiGKIaR6KqiR7oZu8bZ0hUhNSOk5O"
    "8b1GZMcmwTFYJw8ncgcYogOPduIUHEwCmfRi0Cxil3nMrojhBCArBQIiRht5YAhpvGRBh8nWdF34"
    "9IZjgjA7IaDHrPcUEyYj3KJcIyyUVClaJRBCHOHLFVOXJOtEWNbyqrjVcaiNhS2vH536HkujWMlG"
    "MtYxGMUZVRtCxlEZUcScrlKZl0ra+jRUtlKNQZKkJpimZi0JGmzVFjUtXOqwEkYdVrmhEBRSoKIW"
    "0RY2kqNo2kWSgUsoDVFatAJRAGdQ+GA9HAXm0lCK6aIBivToroaBx8d6A0BNBsbCb8xtCiBqUH2u"
    "nTpsADey2AMNBDNCqQT5FgAmg6NRAxy4BIBDB5B2puDgknk6Q7n8TP1ze+p2ngRZquYLBQWAHG4J"
    "Z+zdY0QaCjqlgxnjaasuo1NUKQytjGGOLhYawi2DW9IHkGSMNBUme/TlWYAoce4StHfCZmCvhPvh"
    "BEhVYANsrOSt+p95WPH9L2HRyLu9Q76YR9UiDLqDSZwjZ1c4ZiIMSw1BkE6wBF/EZD0KAR9BAG80"
    "qlAuUtCwDuFNsbhlAFk81DgJE3HRYhkAKkWFIBzSCahu7EAVzDP1hqGpokMlVUgCJBCIJBDK1h5m"
    "XydEkLP2RvRISR0LBW56Ka70Uvos5sU15AUSQgRc4OxhEAaUpUW4zKlUCgmPZaUhUGrWrGsaqk0W"
    "2Ls5zbTSa7WhI6pJQmqQsZAFAREREESEI5LdgtQQAtuzJAIWofWEQDBDIghiWAQkFaNaGcTTCv3x"
    "dab/aR/cgIecUPnIoFRPpgNT1dyU5wN3FqyJ6wjmwiRRPIB9JEFSEE4iIKvRyJQm4IIAfAygX9HI"
    "zVexCdiemA0EDxkakiMnahCqYHSQE2Bn7oIH0clvLrXp1FRWLUq1+dNZlXONcwHAB5evHBuSEUEQ"
    "YiMAoA4wgWIjyIaTVKgBIMiMOKldwDroDENHHdQawS4QWQUQkikJGQVE6AIbMR2alTEFXGKiEgSB"
    "7SI3yDPpOO3a/k72ryLok+/D9cfBCAXnRcglBUZAa6roVNviV1XTGrlcWU3OHEWLEfC7+5WD4wmz"
    "k85qBl9iCbKPZNvpjQol5J0ZCHm+ZB2gE/yYJYGJg/eTw0RLjjg01BqwmOl1phqHnLF70F0IKerK"
    "kJLhAYuIBZaan3hlkLkq4YAqbT9ryvFShN3vqzcQdHUfIAhYcUBAgqmwQwDxm91X8B5cO8ij/Aie"
    "0Xi7OHNcTtewY+QVc+bGwix6rwKDVDrRe3ER9LFe5GmAQQiC8NnhtcjINiIjUWMGBCRF4EHYwOwo"
    "r6iXEwe+rl8vow4GQXQlQIQJEgXzaOsT5DILNdhtBTBFANADIBbQ4kAaFA0YAV22+x7taxRans+z"
    "49zbsosGlQ0S0TFIo1Yk2maUtsqVNWqUKK0pNKkkkhFVjjIpFB4ByQ6wQ2CbJkOoyUjn0iCbZCPI"
    "nFNg5bNzlwcwCwkXB0GiZgGmSqBq2oOiagOzAPQQIpGAVjb27kpXK+OX0qW2UUqvy74P3gvzm2Ib"
    "iDLY7n8GoBrRSnSDb5X32eMDggd0gVhxnCglEQOpDmDhF1wCgitD0u8NHYDYwkZBl0CjJHwxPsxZ"
    "OijCyDv8ki7ol/twX3LA8Hj8g5CepBuDgQHsn7dD4uykh57TzBZXUiMUWNoWEggk80yfBCZjAtlH"
    "o0DDj55eQVoVntN15Zrwr2NCUSLlmYBQBKw02RyBAvu5RO1lWRBZcwMFFgiTVL/jPKIiIjAvRnQk"
    "3CwQlCwqVoeJdOBg96EyMiBiAI2O84A7s9EORWboFFGtwgsCC2J3fo6bwZCEM2yHKsSCYjFkijNC"
    "AUUnlKBgmdvJzIYTA1KKchwJZHcQcEYQhZAGgpCggzazbb6/watfDTUbWLUaS0qK5vY3goD0kNSb"
    "JBhIQGRgG9wAm7xxBYBAOCipyCEPpRiqKVJJ21rRcqv0Xgb2pihwi803ECQB74FQGQ3hz8xjmhi9"
    "tCDxfjEOerc37KMR4l16UKHA9JQDg8pwmT18AwJ2cH178Zlo2ZljiuZMiYFLCtRbMcESWUsxhcsc"
    "ZcsJdly43gcZCGw6R/iZIJ1BbA9AxVEPTveHv8cvJOBEkIQgoD9rnGjADe4IJu4v6QO4+Sz6H7Cg"
    "teoi5yNXiwq2WUsg1VINPlj6v4khIZh0QBkAXEqggoK7Xox8vSAO1e4TiDqvI/THh27yRhIEjPZa"
    "MPf8DGY2jVVGDGRAuz/LvNCMKPNbul72KCBAjAPK+fUebAcM6aPPDH56O4fJScvK/kt7hKlbqSjG"
    "jYiqMEYSAwCuOhalhED3AqehBgBZxB+YsYMgT1IHm05n7BC4xhCAJ6mPR86BjaEVf3QaCLiyI2rv"
    "qgqbDv9BrFEkhynEQCk+LDq/cj1F1Yld5JDJjdC4hv1J9Fj6N7H0W+tMqSxEYUsLDmNMVfLWbGM1"
    "r7w5b0fWy0kiyOLOusw6ojh6hjZVP4iz7ks6flyfSdmiSxNHKNORdgsmxTtvdr2U2Demq90XbXWz"
    "t3nWEbWjzHt4PoOOdnRHG0yJUKFR9R2hSJJzjQh+MkVz1NCG1q+OI0y5wlyTtqu8o2hRpbajWW22"
    "M41daVbLbYoINKwbS2tlGHSwuBRbussuNly4ZYmJXJbKSwttO7jtnj8Zx5Xe6dpnbHEs+lNvvxVq"
    "hTT0XlO0CTQ4481BcKwhmZuId2TuO7q9XxqEDWveHTTkppokDk0Zpwyo3yO45biM21YeUISZHDIY"
    "iEqdD406w9RF7Ae+vTB27zQJXF2VaX0cqLkmWV9pkcVg4UiTOrvUizOLOyfMC6LMKi0I0ByVe1ul"
    "rmHqsKlKDAaDSBASDgODg0hWWwNwkSQkFxtHseHHgg9jgd7OJtThJJCDIQkmuuopmwGD9CBEKANc"
    "lDmSHtUUsUIqWnjPb7+iFsWDCw9OuuqjqQN7sAI0pEkQ6ebXB5FtBingm9pxKCEkqRPXKk0QTSe8"
    "VdoCm4HgxQUM3QgMIQAhDVmIheOGwAA3QhrvPGGuZDUfgSllj2VBDxpDQgJT/V8bllVdoZDvFc+G"
    "gh9a6ujAvK69MYliX34bttUtuk6lq+f713uz9icWnSYdmjHOxpkSL/v6Xhcv3Zgn5B8MrZqHWnDj"
    "OMwyEAmsZFPB02B6hkCLCBv0QATTCAlbU7bcyHtzUbijbRNYG8+hyAv7f/9D4u/wC36mxsRIw8Tj"
    "0A3EH0gEV0oGhBvACKeZ/HB7wZCLcKVH4ALBEzbBrXlhS4IQ1puucMTyqgRAIBkREWFZlA/r9F4B"
    "DzwDdTvp0fQqGgP4mUgckt/C/z9X4rB9346PYzNxzXnFEsqgRAsHDuraQ3BK6VJrj9eC1Bj0p348"
    "oQuLGzQVESQFmtBU6gCoocEpOBMPtKCgYnsbIk88UiH+EQ7MlQHvdnkUT7/7msCeO7dmz2giVgkT"
    "sDQIqJYRFpQp+j4355eQfV4HnJrggIiqmCGwyFE2MzUoQ66Rei9CfqQ4Z2k25BoYcRymPx1lIGcY"
    "XZrCnayTDceMowm0nO+3mhK7yYq4ysLn8fGCkNUoG2UQUmEQRFkrUMlqya1ZzrDA2GcSkMk1ZPlY"
    "GTneJwxSEDMikGwpKkiJgso+zaZxxrliGhsAsG7IhDTLAmuVAJHb/JtbTdCR11oTstETq1naNgyL"
    "F/cQ6ZViMidl7RKJJkZDgYFBWCM6XMJWE3GHZ/oh8zyxonGCwmA1yGlIqpVhGUEvLByELdNpq56U"
    "MtHYVQwJBYJcSzOsa4py7cHLGUMuemRquf7YUKbY7DY+ljahcdXfS3AkXdlboJA5wdzjRFUvSqap"
    "zJgFtFLiRisuEINIQgwjN++5jWBKrhrrxlDRxJySUEhFJKbzAZyMBxFCMLC8YxSFkY0hdVm4yRGF"
    "FSkFgNJk2JEgILJgeUHk0ObeaDAizDMnAtlsI4SMC1g0L1oJBDMkFYq24Q3tmAf2iwwaYdhnIKfQ"
    "aUGZmu9rS3yNBiRKgCMFEiK7IiaCbaQGhBKvrq7Yt0gUODo4XDoKqb6rFA7t/tBfZCQAkRZ9xYHJ"
    "gQCCbrFnEWq4G1vAGIu/aHVlaD4ucaMywsRodfvJ0Xa5KoGaqvRAw8ofjivFQH89HHJFtmAD9lky"
    "yHbyMgj6CiiDAZRCh+2w+owUP4B+2OFKbiHrkpUjmdWJvhuQADcgYa4wjGSZwo3YrrNIwUXhoMS0"
    "LI9wh0AH5BGRPfnfOJM7EsOksklEFBCAiPDQTrZFZGDIyIvdjz3CmYLVFC0xaaUAkCB6qKIMCKJ4"
    "I1ovkIcqJxeqDpk0hgrLZNZWYiCwYmtTIaYkZHqMlApA0oMR+RATCalkcobGhuHRLnK4lTLJAykt"
    "yc03GUsBKykFmA2hgyCQEgfL3w6chIMhSdkYCbfEa5HbH2wBJBFM8VNfsOA8lChYAwhk9WvXDunZ"
    "kbeiBsCJRJplCWmZSMQVmsppbLRoVWlGm0WFZbFtgwkAk3wGhU/p/ZIe19xm3giJuiCIyG4IIJod"
    "vP1lVBDxIJZA64lwUqNYoQqDEiBD8RxBzJ7yC2Oac95QZgo5BO1dQJv+VZCagU0kaSeoCMWslhmA"
    "J/bUVRVMMhDsn7G4UUWflXL3G+F0UplhhYNUCTEuvK4yWIZcubXJUGLi1yVRkRqVFKMYMrWc+Lp2"
    "k+n1h+KP4z7nYfSoGh+g9f0AhwhIEgd6A9qgUjLjUSACITplJQisDe/0bWEE/SifWSMRISAEEXUg"
    "hOAR4X9c4u5UkngPcq4WR4fam2B1vLkB8PQf5szRPlgSKsIGcGRQSJROuw/kOOwXd4pc+q7TrRO5"
    "fSbsk937563oAMBxHReqK4yC4Cjg9kFoz3kKPNiqxPEMFPQAHaz7pVGwIF8S0mZYHnCT3ewBfgWt"
    "rSMJCIRiUE8Qg2Th47zeJfBBftNA0Oz5y0JoDNUSPYh+CZoflSy0KP2vsQw0Pjh/+pngC0GRIPdC"
    "4w3JwIsKNStlgWFEFqwY9qtfiOifoILv2rLG6CX+da3EG70UnAg49fcGCuNPNcAfAhgi4wQiaUhz"
    "CKJxjvNSq9q7L17aUpN2ONBtGqYs2bTQomqbKzSpaVkkGAQJERg4DUDWtygqWpSkXICegiJY5qM7"
    "UARkgyCQTrZhnYTz4UtdmgLBsjIS3iYwSQUCCImWGkdZaCvFRP2CagQ9z1ywqyBISzSU2ssRk8Aa"
    "Yt3Ax1rCUpogiB9Hf+n+b6Q/VFHM4IR0qEi6xzKNYwR2IlghKR/bZcggqhx+Pl7mvSd4tUtV7El5"
    "TgGRYoDstx3dlmbN3T8mXVpqBeRwts6EL79vGsaSwpUvC2MTyBgVcUL/lWxYuMXf+XqBVXvNt21b"
    "byd9+3pGwWtFsoQMQIqQigjJC3C4Q19T5eup0PcCIWU0P84gAQQALVBPqgCB5xBOciHIdxETe3YI"
    "XyxKOPx3ERLof8nD15Dl0f/auavX0FBY0bWfG8m3w77N+Vu3s+taMTMaNbGcbQq7bbXbqxX5ky9Z"
    "iC5EGQ01awCxUSKassjgQx4NQImsaRE/0Ol9WO0IIQIlFAdHDn+2+ExqqNZkhrRE0P/4u5IpwoSC"
    "PU4GqA=="
)

# ── Extract + compile ────────────────────────────────────────────────────
_BUILD = Path(__file__).resolve().parent.parent / "build" / "inline_k15"
_BUILD.mkdir(parents=True, exist_ok=True)
_CU = _BUILD / "flash_attention.cu"
if not _CU.exists():
    _CU.write_bytes(bz2.decompress(base64.b64decode(
        "".join(_CUDA_B64.replace("\n", "").split()))))

_ext = load(
    name="fp16_k15_sm86",
    sources=[str(_CU)],
    extra_cuda_cflags=['-std=c++20', '--use_fast_math', '--expt-relaxed-constexpr', '-gencode', 'arch=compute_86,code=sm_86', '-O3', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__'],
    extra_cflags=["-O3"],
    build_directory=str(_BUILD),
    verbose=False,
)

# ── Config ───────────────────────────────────────────────────────────────
def _find_best_cfg():
    cfgs = [c for c in get_kernel_configs("all") if c.dtype == DType.FP16][:40]
    B, N, H, D = 4, 2048, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v, o = torch.randn_like(q), torch.randn_like(q), torch.empty_like(q)
    best, best_ms = None, float("inf")
    for c in cfgs:
        try:
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            torch.cuda.synchronize()
            e0, e1 = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
            e0.record()
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            e1.record(); torch.cuda.synchronize()
            ms = e0.elapsed_time(e1) / 3
            if ms < best_ms: best_ms, best = ms, c
        except Exception: pass
    return best

_CFG = _find_best_cfg()

# ── Public API ───────────────────────────────────────────────────────────
def forward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """FP16 flash attention. q/k/v: (B, N, H, D) float16."""
    out = torch.empty_like(q)
    _ext.forward(_CFG, q.contiguous(), k.contiguous(), v.contiguous(), out, False)
    return out

# ── Self-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    torch.manual_seed(0)
    B, N, H, D = 8, 1024, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v = torch.randn_like(q), torch.randn_like(q)

    ref = F.scaled_dot_product_attention(
        q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)
    ).transpose(1,2)
    out = forward(q, k, v)
    err = (out - ref).abs().max().item()
    status = "OK" if err < 0.05 else "FAIL"
    print(f"K15 [Tiling along d_head]  max|out-ref|={err:.4e}  {status}")

    # Latency
    for _ in range(10): forward(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200): forward(q, k, v)
    torch.cuda.synchronize()
    ms = (time.perf_counter()-t0)/200*1e3

    for _ in range(10):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    ref_ms = (time.perf_counter()-t0)/200*1e3

    print(f"  latency: {ms:.3f} ms  SDPA: {ref_ms:.3f} ms  rel: {ref_ms/ms*100:.1f}%")
