#!/usr/bin/env python3
"""
FP16 Flash Attention K12: Misc Code Changes  — RTX 3060 SM86
Auto-generated by gen_inline.py from kernels/src_12

Run (WSL):
  cd /mnt/d/GITHUB/Mini-Attention
  LD_LIBRARY_PATH=/root/fa_env/lib/python3.12/site-packages/torch/lib \
    /root/fa_env/bin/python kernels/flash_attn/cuda/inline/fp16_k12_sm86.py
"""

import base64, bz2, os, sys, time
from pathlib import Path

os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")

import torch
import torch.nn.functional as F
from torch.utils.cpp_extension import load

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "py"))
from flash_helpers.kernel_configs import (
    DType, FlashForwardKernelConfig, get_kernel_progression_configs,
)
from flash_helpers.kernel_configs import get_kernel_configs

# ── Embedded CUDA source (bzip2 + base64) ────────────────────────────────
_CUDA_B64 = (
    "QlpoOTFBWSZTWZXSh4gALFP/gG/f/////////+///7////5gZb7zw9sCEAZ9772n2z7ffeqOiST0"
    "RVFOgUDKVyFsVy0JPoYo9tt9G8sXz3jufFH1O2UU3Ochd3px9udADsGR9nuday9ebx2+33z76+1f"
    "WrdZ0yfby9zXnPUvr6+z7q3zXfZ3DgHvu833K1rdzveb33xq++a7bb6p2177fY9z173uku93rva1"
    "0+99j5XxffanMOpDW6W3ZuVpawNTBg8EHhvd1LXrffd731ihzNxjPo9dt7bblUu3bVcbOtOzszlj"
    "akx7h4OZ7Gyi7m4XdySdln3eR4njru13Zy21qZ4cQb3euRY+3dtokZDDVVrbe3Yt1x3UnUruO5rO"
    "utBKaQQCYQNExNTaJkNNTE00hp6U9R5NT1AnqegNGp6DUbTSMjI0zIJTRNBAQTRDIaKnqe1TyT9U"
    "/VPNU/QJ6KbSaADQ0AAA9QBtNIGEmkiQmgU9Amk2hGTRiaCn6p6an6hqaNMZT1PUeU0eo02k9IHq"
    "PSBoGmmgk9VKIINVP02pPRqnpNGT1MaaQ02kNqeo000ZA0DQAAAAAaBhEkQICZJhGmCJoxU/JoJi"
    "bUnqR+hPSjxpTT9U9ok9T9U9R5QAeU9QDyCJEhGhBNoCaJgQ1PU2lT0fqaaofqnnqp+ij2VP9JT9"
    "Kb1BijJ6mh6j1APUxNDsVVB/fBBRPX7Q/pGQT+cCrUMjUEUmsWFAXRcTN8TXGNjFDKkiQTX/DcUF"
    "dXFWmIqkqSsGo2iIideen9o/b/Ff/PLn+/9D+wnqZ4dtNLEby5XVyKOKPJMhjXGYIaIbfBnGxd20"
    "+lM1zu9BWCqgnO2Lm8wiIJ4/8X+nDtixVCckOjDGKFRQREQ4qV/F9u70n8P+p/7XFWibVK/X9c9W"
    "X1Ge6g6Li7ujqvM6ILzTiiLdcxTTduez48ExtUqVDoZcs3wW5qT+thVjrnkyC4JuzMET+itqGolH"
    "HWawKZZWqzKWVMXG28v5ZCxO02HXzU5dpzhi84dFWi2rZbb3FzCgBRIQp4b1/Tvv44ZRFmx1YxKc"
    "81rWIr/J2UDEo1iy2xFiiWhTVKqGUzLWZlIjgMYrl+vOl0ZFcYlm3OcAIghrq5ommTdGwmuDnHFz"
    "miMdFDpy6O5ryzUEhJWNRpHOcwmUSRV3tvtXrq27lbd3NxUfDl6czlefFl5N0CMx/i1Ql0ZvQZtk"
    "w63eUo8Wx3aarwdjo8wbSPaOg5GSY8rLE46ZmK1hpMlpYVqiIxRfB5MkwNQ3ZwPQI7Q3vHCoWyxF"
    "GScVNUczCojDn3ej0ta1rWta1rWta1rWta1rWta1rWtjWta1rW26ObCMQFIC9XqknWT3WAf2Yd09"
    "J3E75lKf4d4GR146omePiUxNUl4QEv5XAPK2ByHjKCwTgO87MNQV8QRT+CHhIwShgMruDocU4Lhe"
    "HrVOw9qEiZr9eBhxA3BDXSQhCDIsPYKjN0YrDWfTMzokYV1J79DULNx0BQDZhozKD7P7Mc0DcwJA"
    "cgtRNlJ9cFPzsA1kU1vvThJ5/+Hpv/Hv8tjPgjgeqztnXB4zcOvdKDdwkkhITAkhAkI5n/7t+17G"
    "AKQm48VSpVpKkk+xeYzmCsHnjUKmEse96vT5+b+Uyt79s5hqrHsg7hhASMAQ8G9ZXvbFAFw6WyKp"
    "KhYFQGJ4s5/1U7spUiz7nHTCcnonZ52KQRiLGJpQ5aK5rgBISj6KiKilkBU7oIgtyqURFqIMWAck"
    "JPiZWAplooynGuAkPFgDyvzDAiMIcMCwUBYdyElGReg2U5gJz2D7OuG4bzDeqIM2NjuHG3P5drlN"
    "zwZJkWx9hQwi4RDkjYgkdnxaVcxRhE36YBxrzzU7/gt2PWd24KIrCHNkUFWUZPKHIRAXNmDW+KvY"
    "iWSaFl6fWoeth6AQTSAHZe1MB8aHf4EhC/J8DSpQYbym5v7RgZQZ8pk8isa8Fa5hTy7ToJ1zAY/8"
    "0XVyIbHLgspYZj5KGXknM1NNzS/ptHoawLlF9XfZgEEZGDOB3u3u6PH2OPNzAQQNSMYEmYU7ITDj"
    "64LwNrHQ2GW0iSoEhJOPEekjHSRm3TOcTtFYIccroBT7PJJaKSKtJ/s8PCVK85gQPyxPgiGg/TCK"
    "1seH7CodIcAsl2DJOC3abKSeHfnzQeUzrHwkHhN3aWRkfoMozlS9A958jAD4hgT+VasXP9pd+ynR"
    "A7BpC5+ohJVFgt3Pg5/hHsEiY/EcduqnaKB3SjVbCv9WmkIltZT285w7rfvwNOgA6zzcm2L4AD+O"
    "9hilWMfjpqIRREiQRfjpRKMOit//j58T3P4a0+i+XCuWtXx/KZeWZT4jEXGXWDUV8xAqxTPf/ZJ4"
    "RGAZjLt6RJyEvfClQ0J87zQ97N6sJ3pplI2Z3YeG5949Nmt9xu1n4d/p2NsNNWQjVCEBVEEM4AEI"
    "AKQkqEKAUy24WHjq0tfqh06quIDLOuubYX0xVVdMcjr3aZ0Z5oAJfLwejb4NM/mqqm8vEOktBvkU"
    "q7s6aU7Pi/I8/jDz+j6PO56Sr1N6m+X2RZf//NYf8MlMRYFBB8HyvttybpZXBvbB9X0We40LW90u"
    "AMNYgvy0ZhmPq/zv8P/H/X175LAu969or3vzkmnTK4JGQg2OxyHIH4URzrtuLbYZ269/0OuvmS07"
    "wyxE2uZBUDpCVmQ7UnO27k1jUmk4cxrAuLi5nwbOu0lQrC9QhKjQIjWJnlB20G+jfGsRuLJerbvW"
    "/Qzbbz6ThpCRrzpZqdmf4e7WeefVjPPSzNXm7FxB4aTDZa8dtnihJYTFIpNDsRe2x+muh3Crzp2F"
    "6dVcFPE3zeHXJsC70RGpeVLBfGUdmjszx35xZSX8LaBMv0+AJNVLPNnlbyLDRvebUFhcxqiQeium"
    "LSDPN9YgIsjZBfTp2nk6on6E7HPshqX+5iyQH01djVMzoc6kwvQ5WCLnYl4Awzk2VDvF0efd6aPL"
    "uLPWuv1lDFDdnxLs1zjHgx8NzHAKXtS8Rn6/fk9f5uK0kRMzNLRyH5ZJ+Uz8/r2xh9y0YRyw7FGE"
    "kIBfoLgrioE2ClRI7ThStXsjagXIDUbDNVDQU1z+Tvjgr7tXu9fKx+b2hVqTtVsFY46Pr1Y5TTqt"
    "ikOpbIBVCw5p1yrDEBkizGBQLMXW4h5fD0paKlKiQkIj46BXVHSoVuwtnSBdnLS9d6RGNWH3nwue"
    "qk8qK9GjnedlmnwYYggQQowqhTPwkcG2KWa+sRix08U8zWpWKrM5Wno8wDLfT7a1KormQIBrmlJK"
    "OJnBAml2zsb6vyUeLnZtzHcQZmjsjZh3mtaVNQ5d9uHJ+x8r4EySWcVta0UitmSZZF5iCI5LTx46"
    "7O6w9WvuPN65CrjDMPx5D74g6ucbXd1kO6QtO3YMqSLYsaOOujEZHOj2w3nVS9Rnh5cHCiajNoUJ"
    "z5xZqt4K9M3pyjMLJVmjW+eu/n59zmPgXllOwTMsUG1RLzMMm6Bu6tLRsxxYtPe7u42fPTvN5CIc"
    "eFKhCSYyEydLb4fBnFNVsrJzA0EEGFShYLG0smK1Tap0yQkkxYvawdGg6igQElDOwQMrj5xN4BwL"
    "phkhi5LlWdJYUVr2wWdVOY1iweRMCSSQkJJJFzKz49MQbjxtNbdl9jOYhqcfFnpUVdxNh+FXd44n"
    "Xq2NnZjC+N2cM5vVIsd/w6jROI4jsvhfEx7K6dDEx0Jh2FuYo+z4yY108g08iMH6yRuvNBCaIpn5"
    "cXIylB8B+ZTBsyY1o2Yj6EexYWXlt46SIVFRH3vnYr6PkJOQ57C92ns32q+OmEa3v8oRzKNmu2Dd"
    "xX2cY8CDX456MKnhoQuMmOTDDEd/aIfRWZHYOw7LShOiDY5ZZUNaSLq4t4COByc3TMQhuyG53r4M"
    "oOFrctYCg3BjPZfdVMZeGIj8/C9zgSlhThpPwVZX+2TpVcp3sgUB/CDqHhEgJEL0QqiFii03dFmu"
    "d2OzP4r482XqiW3MI+9mvLt9NBaadXHVoTENTLUNEJOqqHb2djFIhxNfh8G6mp6qJxjFc7nPfIG3"
    "dlbMkdmoCuXyMwFgMBS1t7ma0QpvIbjo1tZEmNP2NSQaIqqYH6cG15zbbByfM7iBQ3Tuv4TZ5hdV"
    "sqA2LdMUj6OuowwQIKMUmG+R+z0dmcW0GfQxc5Yk4udmvRjFTfpa7+9zD9yUy+mzaujxajdnaT8S"
    "pcbR5OQ2bGoCpspoBTDjfD1Wosy5NAAqC8LHhGUYbNN115zqwSw+JJOGuuudlL5+z3WZ1nxLu6zg"
    "lO2ktH06suWqvTZd+1txvDvNuOPsH5zlRMkn52MaNLaWfFUS3+Fbsa9WSDyrr5qYOmV0Hb2WVWVF"
    "J1tALlZvkBcZcv8/fgaQQHr0PRS/v4Pfs9MNmNxzIo7JxOydnpwKNDHEPRv1bucNo0a8h3opqKuE"
    "KyjkTYc0IxTDkB0xmj3vZVefE30jVVuKWWVqqCBWSixrURnxW3LL1lxmmWAkQUtHVERMlLbatgo8"
    "E6d4I1M0Gy0rF9hoMaDjsaxpUouRlTVCciPTvj7tcWoQl03SQHq4tx4lgoCagy3vyyjLHFrM5djL"
    "jX1euFlPAzqlKuDMpuTwCACEkr5T6dqBBnW2rSUUitvwoa6k8bWtaMzZaWa2sOvKNOLeGMO/Mc0s"
    "wvRslEHUeBsM4al02P1mHyYZsst6valLBbUeacGr2bCo4QlwoeU6tO8vb6/D0ei+NMyocMJ0kiUG"
    "6cqDiAmO3udufLqeLtYYoAdKXXTozpmWziM9kUr2APVicjVB0o1MeWFvBbzVIRPwdla4cthr1fae"
    "FXNSWFPjIylAr8JRS9/zeJCtq1pbUmHFB3G6Ow7RTC2wIIQy8IGDGN1WxNRNRnDcjNV1Y8fAaPxy"
    "hbs07dPAAAADx69Fx2zzePOnrvu92+x31z0gsTUETAqMiW/Xntn52ybwKwtL+sZxqkUyEYZWaFXl"
    "OLmjFvknVH2jMU3qGvXXW15QjXFomK1+q6ukO8uei9jUa2i1Nr/7yLypxe+UdfDVHyuYqgdgkIcT"
    "odO9agQdsSIGxM0tKySNVGLmyUHffssaE62PpX0o9mw+eHLto3fWvRB1FiYjzaiVijPduKy706Eh"
    "l2orA6w5n5rddSekOFX6nDXKSy8+tfKUn5QY6ll8vzBp13M2EceKW/LepSGvYnTylHiKPavT06Z2"
    "aOPwNunDYUxqu5cnbqTFhniY7ysmYaNnbXU1zh7V85RQklg3ln4dxEeLyVPcF71otfrpTjKJnKsj"
    "vNZ5d1ulYxXO+JxFrCjU100SWiASF2mmRrq9S1cPm9YCaRo9hD0tBhR0LnYL58+wkoadr3ernE9N"
    "24srbodeJkW2aZGd1ldcNrdfe29Hv33JIIfi9lE8NDXIsUN+/27/gcKKBGj51CzS7G80HHP43bzd"
    "RVFlfhGqtlWBZEPZol7xDQqut6u4ahXMpq1ZdgYY4IVJBRUztQImrLTs6Su/ZzZoaMkhGKpgSYZJ"
    "gEmCe1xtFvnprI45OfejLKE4Ms37DpCNm8IQN+0+XjuzPVlNA16F6scchyRgQpk8p1GysnceMCwP"
    "Hxc3oBwQkx4jskhVQbgzbL6l/r46Di4OJD44z6KEsrrOEGthsFDN76CqY1VQdg6sgjqstqoo1vup"
    "9KxI82NQA7iz9hAC5NxTEpIDVUnthwjqyrhOS+ZbGjm33wgmqMkgtTbJqik2ri2MmIxktoksWioj"
    "4qm26NXyZ5Z4uT6Hy/f+n60H+J9B/Eh95B/R9ZP9dIWTKCaiFFlU3xGhBN+cCDDZgxiAd3AgG+Hs"
    "pzjvTT5ul1/T29fzfsts4l7ui5HDZL5yP1+bCUcUVLV7u+uj4fiUPKK+/KD1Tg4PGEY4wWh07wTG"
    "h91uPqiRF9ER6qWdMX6nDgIsR3QE+XnoQIQz+iixB7yGa0dONhD7gLjL+nAylEQY0YP6rMrYGGrJ"
    "9hrFkJ/NBhWfzlJVFHdnyZQQBFDIfIUsD6iP8yIQgj74BS/SQR+sn98BkUS+nCTRs9q3LfDWjRo0"
    "bY0aaWltTS9TrZXxLSyapVXy1veW+ZNtrehrGxoUjRQJ0+EninznZHvt3ea+anxooe6SzUoiyVAS"
    "ltAl+7ylmYYGFXCn72YfLvq8gZz69/aF55ozt+fofcT93wjZvaXqyqBmZFmMIWIpt1KvRVcv81cU"
    "LLgL2kcj1UUOmUZip7IWkrYcs+2unLLnvRi6fDtQhnZ0x1UmhtoJF/ipEo0Q7Fq2oprXVCQItWAg"
    "iICCIgh3YoPDhmlFzscOHSEwl4DZoc1kbyLT6L4b8fVfK1Yla4edTTgOXvLlkrOiB6RpbFqXIIrp"
    "irUQ6wZXaDBSkECV5zoDFkYyjkYJQko6XHLn4ipORI/fdyBCTX3q1KyMDRDguasqcpcd2GGpiz5r"
    "3oIAmm/Msokjg/UsMCo0V/eDjfGxnE84awO/a3sx+7tVfeiPHRoWRg7HPDah7gBsM5EA+5sw/VOZ"
    "rSUwN87Tr+7VRa1Xb2RawBbumggUoc1LjM6umEhfg7+y6RZWdm/zxbiJhbmdgmJkGLjrfBygHX3+"
    "KeS7pBsQgQBzGdEwO07zUdkwbhkBSCPmRyM6StebjHdUGqMQPxLg2ZmS2ZsHr/kOsrCDaZei3cRu"
    "le7sJkJBKNzwxrHzFlNKkjlsnORUc92uVkj985/YZlEdnn812m7vCe4oF1nq80re01hGQT5/upyA"
    "9KD9pMeP0O2EeUReXPT7khDNx/G7Qry7YmhM29MeqTnQ9BzNG6WXETOwx3ap3f0HXz0mbJsOLVcO"
    "q7KI5ginPnZZqr4WVZSO0X16pIg6EIzTP4JmdqroKX5IXbPKH4rtp16J8FM0ejLfb+DdoMZn45xR"
    "jmZrjJqLIivgi1dbtx4trsXNCvCqIGyjnDgg9/79VRXj/PXHPdr21ap1aVZDI/fxIKjbt5rYLpRl"
    "BroWPOuEydt05l5CyglLaIsIFW1ujIYur4Qahd1D9ndp4JowTZw96OnYcZYGoOIkkU4xb5+Oxtta"
    "wHPz4ll+Sc/Fw7M9ASmQA+FOXRDjADuE1psZVomHylKUpSnd7NGjR3mHAcqwshPFMrm05Sx8PQdp"
    "QYYYY7r+PwGhXx3c7+ZfqlstrQtuTtVUz8lK0YxfMulRdTpMOcpNYLOPOZ+ZrEsPakoijQ/3pKLe"
    "VN/zeuTqLUqKg3vQ4t++CuMs5jQ4p70JYopACheBI7DU6WKE7u7tJlDWWw1x6TnKkOs4aDu8EsxJ"
    "0rEIQje0HmWPEP4OXO9DM4ps6u/m8bxsmteIoiZbs45WvJ1eTnemls2NGObHJ6zCIljhJQ3jgVrY"
    "Rh+8rjD1TkEiISZbT6VgRZ83VSBNHXO4TKUSoji4++6vDA2iabDn5yG+WoxR2c+e6eIjDtr0XS/i"
    "TMMCQw37S7A6gqG0qIhiBEgQNIpQRRo/JQKes6/DY/cRU/UMJv3CEEnskCCQ96sgQsz2KqqgAAAA"
    "uanVatcq58EQh5oTf0/N3dNnxaH6X33Of1g4H2jLgrYtlQWytlQWytlQW1tRfc9Mvw4UDT2ooRYv"
    "aIUWThaqkk6m/jdEKNzeVCpCXm7e2IKqw8A89I3so1W+e/hKId+hKsrZo0913lWWTlKzqm7PTCjd"
    "rk5Z66qDT10FkXpsiOPw8erXZ8z7aitjzDWGANHIha6RTmIWODiQOqg7z+BznsPLwRE03Hi+bdvi"
    "qgn1Ml8YaPIoQRAKEFEKCBXKp6NxTKKQxRRR7W8ey5uSzpuqiiiiiijt30lum3nu8HNQ7OkqJUG+"
    "Ya+vM1gA2sAZADIAZbbW9vLvPJd8cvCbwYxjGMYxjGMYxnhbVubjFGKMYxjFGKMRo8/Z23n67sUa"
    "KNFFFHw+jm6KNFGijYiuxPd894AAAAAAAAAAAAAAAA1V1IiIiIiAgICFtUIiIiIiIiIiIgICIiIC"
    "AhAjlVuVUtERBQIISEgyEhISKo/shXJqbvbxJfm4yYw57nHNPbt7u6uwJcTsQSooYuUW5sBWJ9a3"
    "kGwFYgHFQq1gqClVDd82pUW7fdMYu5yc9hhL/p+Dpt06dHNt2tzVfpd7joVwMWluSYW16Knimg1T"
    "wENKLkEfPg1UCZWck0Wpt7yxmakqNE3r0dqn3znS/Dx9T3xvFxprhY3EsGoaLjaKLNUyZXZOvlso"
    "PQZ6pj9UYy1aG8K9XoAAGEAACE5OAAAAAAHKtrzc95CoYwvw6+PHbsyxK2bhXkYPTRNs9ndDHVqS"
    "VefVSfOVx/NQ9fNriFY3U2BuNY4biXxrjB5wJtqKB8AOQx8/GoMiY1iGRN2Hd2I7sCyKHJFpM4+k"
    "zmrfUW3HW4ZW4NGdOiEbOU2aJI8b27hctPGeq5sMGp1DdPTct475XWrWvjV3doAAEAAAXS2rXS2r"
    "XToAABSqqqrFTx1IEO4oeEz7Xt4fF8FsT5Pdlg8CgUGkkhxcHH3UeSoZ3eGPRJdQIIBb29fdEr9P"
    "fuolaus2HysB9o147NNeapn7+yrsF0pnCq2dEO3TGTbPv8/5Vl2bPr70Z6cZeMdvCe7z8LNs+vF7"
    "ZvOmagnIdYpgVJqy6xe63DOiR4vlhhc8dvdGUcam2/SG4z5/KfFC/MenxoLVZW9tuWN9vRmnVluZ"
    "WZenwB655prqKGHVDDSyKtXXZZp4iacFv6LqpPf6UpRlpvr6q+rVo1enz0xatopbKtpCQwWDIqUv"
    "Yi1GFYVhJ1S2TvVPW7nWDwOMzqhrtt36RmsXta04P0WFVdfU3FtO3PExEmQMmQxjH6tM6gOybpNP"
    "f6a+H1ZvWeUus1apO5w3V0TkZUxYchGj/AZ9/avh7zByYdeveNdJiYac8eXXD2Rc3pl5vMYWBIQy"
    "RuEDiBGf8o3A9/SVbRmtmtrEpbRaZs02mZE0a2LajFrFQUe6kCwxb/SfciJk0WPmihIsiyEhEhJR"
    "XVlH/cWG8urZUKVLEKyViyMV0NZjCqqJqzTNKqfz6W71aINy4sEoBasZg12MKCfn6Ae2ezj9vNvP"
    "z8tFOWvPTHuH4kqBvSSPJyHevdNDgB9oe13IMmUA0J9YUUoi4orbEExPqY/Y3D4xVNLpsjAyKWtG"
    "Nj6S/3RPKm+UPzsQLGk1CPcRLBFiYlQzmJgDsBiIGrRoE1hZsEBYydz6UOADMd/o3hvf+SpDH0ex"
    "kpDQQLr3I6X5/1AADlVc4AAcqrnAADlVc4AAAAqqSkIGjy3xo544MDmT3TDcdyxe2+w8LmZh2hk9"
    "MBN0Xl66Q/IwhO4mcCmjecM9Rd8P2+KI6tMqCMcMmmTtPcPcPcE1x6LIag10GBE02m4LCAWMigBS"
    "kAcykKgia7t3Ty5KpmaHm3Kgp4uYydNJK4Ysfhy+U/GvogsESdZCRkH9ghzHUKLsSHqe0A4KG/ov"
    "MXNRJ9FAHpHyF9rxAP8KOzs1j/Bk0K2YFddTglzMzMsuORwEco85ShIVgmZgfjlECJyK8CzcVYW8"
    "nWQqVqbS9a40UZoiYVoYgiO2Ko7IYiImhAjVYHzJaF2OdUHKKwiAIUmhPtIKqEJtQupUAMCobaD2"
    "/noS5dVRNONz4DnoCQyUA1kCgW0/h/IAtv1KPU6UExv38D6fGUIQh9RyKey34Dtqi0pRO08PB/C/"
    "0MPdTiH96EIU/fEH0whEYjWfZ8HUOrxM2EIO92+v6Xd3d4sN9oCNp4voCy+wCEAhEwaIgRQsbw4q"
    "kIobCIZkQLRzzSFIkoxC2vXrrWazQ7IAHcN60jYAc8VjHGJMk1Cw0Zuwb+/81kS6KJYMld+mBoaV"
    "sNaC5XC9YsMqwEZhQGyIEYJY02YXRyiPtg42oN2FiMTUzAAVWobtyyhApvKXie+1GosBgYBB9yY+"
    "5M2xCpd6pH73zWTOFMDvp2fHC6NQG6D1Ju6Q86/NY/NnKfFpSaRSZVxqeq2F+X8NzEqq2lUJqzpX"
    "KBf8Fd1tRrpdlqANFrvtZST6IFPb5K8E3kS8RDFV6UFU3xqUwdfEjvWIMR/Xai08jt8QmbSbeKM+"
    "9nDrXlr1WTkDMG1Bbwkabjqv+L6dWmRZWk9JshnZ6t5q9vICs9iHm9c17vx5Qd+LhkyqlKEbC4bE"
    "xNafsaNZH4J/FaeWcdNzzL4KVOVi07XSLUzYbsYPQ6RyBDVoSO7W8kkRZBUJrPF8/Thd1E3pnjHJ"
    "WsROidLoaXrAxJGR58q4RZJjVGFCMbWSK+F/Aiq87lxMdVIgHQZ7OHdR9hP2vCY9y+pAN5ToOzUM"
    "6QFR3KZZXoFFgxcg0fdCnGmvtrhlZToRv1aCiIeZDHpd2bd1HmJxNOuKPzBIhJAOgYkhejxu0/cK"
    "xCmS/DxrXt2oZe78y+xEISEIKEAIyA8+TqZC4H68BagDIMgEBHXVL04AYns5cDVZETM589weLanb"
    "HAVkaGZJAKycRbHRES8ww/SVU1yiUkxRCBubCor4+40xly25gYXz+UTNfL3vGjSXs7MhpetiJ4GE"
    "ksJiBYxcwJE7EwDuyWdG4t0BX7iCsfKT/zLLFMtMhLFARCArMLZUsIo/5faMAw3YVAFigTStBgIg"
    "aGVkZFWEFsglQcqKRT3xogZQmApWs0m11lbqqmVV7Na8NNNNbUicUisTAi+35gDHxEzrw8/QfFrk"
    "6YoXTvcjsnIefpknDyTNJNsVEKIByd/X8vtrInKl0oPJdPj9mZr4zsIy6KgLUVkAj7Xn9GvXl77y"
    "9uG0g561X4/Y9ph3d62Zed26Q3NRDsLxfn9ByjPmOYzThjYDiV4nJjs29ISNsW8021TW3AgQQQHc"
    "sxeXluMtmUv4A/wSl4whZnY1myxyNGxU0NZYK/34xI13yvZUPXx1QwhMKLZzsF3ChIrVAj4vkREv"
    "YuSImX+OK+X7yeK69+ISQ+n+Y+39mmR6UNNv2CFHtuH6RPfS8B+XylBYh86IkQxKEd/08HFvztl4"
    "r6iGXw+skhJJLA/Ckx7ApP3dP5rX4nJu3d4HGaQeXaSbriuu2FPncmyMAGPmGBj/fP7Ea377hl9z"
    "75+Yyqzyy63mxCldZHM0OnRN5dWayxMQ4dPsiZq+x379oJf4S/IHjT4/mYRMKl8IdZDnT60P2qlv"
    "2pSK0HH2kolL/K+XtZaW0wijuFIKYgfmzz40QD4bECcFdoDdbLFVhDP5tJ5cDcGJhZr8lHF65JV3"
    "sb2Z9Sbb3H10Jeu5cfX+ldCfMQ8AfLkxRjLCEMgFcLQbW2hbS0KFtLdENSEIeuh8h7Nnndfl/jn3"
    "/6iHoRE9KEcDn/EFMzLfsTb6vokcSd4QIxjA8cH7YH1f/z39dHeqbqfVMI/P7U//APjUzdfuafUI"
    "mso7or0JGn/II/RExsaJHaCJkUissiutNOT+/anT2nSWt4gM0PjASLf1TNEoKgAUBEkjGRXuE+/c"
    "5e/eKBydCdGtrlq7fNT5834cvBx9DgAAAAAAAAAAAAAAAAAAAAAAAAAAAHPf9304AAAAAAAAAAAA"
    "AAAGgAAAAAAAAAA26W9K/U1e8a1pta1y/G2/BrYatSAA8BMTtQ2kEB4BBOX/K7EA0qPj3hPYwm/G"
    "ppIwI9bFWkGvd2f4YiIj4GKAY1c/H66LySSTvDWPYfKdJ0GPA7wH6U9A0r6UME98ETB3b3zevsDX"
    "NP7y3V5hyU3feD0wkJINJ4WUTtBmzOfaQ+yulrJJKZ4eIlQJy6fRnpslFWParWyCtpPe7SzQ0jLD"
    "PUcQh2LjeWxV03+oy4jHXcRQSQO/O+RH2rwPSEcTuQ4wMm3mxNdpD+AQEconfAOZAQPSeJB87L74"
    "D6Ow8u/IRhFKe5Mfqn2EOEkqE5SjicMVE891NwZxBWfRPnkA98wPvvgP4Bz4MtFXYERKBsDxwvYh"
    "eVinuDBpXA8+DiIWGCg10JCQ4DWRJ0CKFwGklrIWoOzu3eZMYkIMSEYQUgro9RetobChoVPl/4WE"
    "oKMRCpXzDN+vyPNYeYhPL3IKxWEA6c8707IGuAxie48cfIUea0wf7Jcleje3fJOHemKXYcszvWrS"
    "kmSgO3zHut4RhkMIcclfWnSZIfMb+ZgeqPEhP4Uej00p3k0+muoeBnoCHKmci5GEUqUoFrWtUBIV"
    "layoiCqp78BPtanpPU69ymfZhIUa1X1or7QoygnGtkZCQ+/zCU8fBR2yoNlg/9UnqF4otTN+fAcy"
    "Hi7jwGdrH4RXYpykYvfSXrvW4zXlVaqg/jQx9pi1dkyQJWsIRAQmR7pLwwrMI0QJagIXJ5FSHNeL"
    "tSSW9DfH9CK4/+vhArHKiv5W6xD4B9asQMU5B9CbAP77CUPyncOgtjBXyiOabAzEyBDnX3Etk2vr"
    "Xx+0/Ibe4L1gAxckdHn15szMzMzMy45mZmZmZno8PhVZQLacB64zkJRMR96X8Mj/oTfFDhTvrap7"
    "P0cdfpE8jg+8X6+teT8Cr1Je58m2ltwjnwazMzMzOs1z9PoZL5A7+9TvTvQ25mCHdQtmDFEKShhA"
    "DsVirJDelLD6gU/WJNIFZjUOA4pAogGz8TuRX5g1Z9zJE8rb8+pJRqc3wc3iOKiIfN/rQ2lGYqNV"
    "LNAUR/s+I/a58OkpFvLufWl8gcYQL2uDsgQmdA6xOKGZnVg+5QLQzJ2LkA4ar6k4iA+z+FQxDaZ5"
    "xpLtmqtnS3FwFZGuMQIEcQOZQsrmo5WbkUgmDNx3f3ZcX7GfnKUAr7fkghEIoelB9nL1BgEBo+ZL"
    "BnjkSxrkNAgZqKbInrfOKRbREvS5dercldD0G2FwP45WT0wvEDWDi7ODsizMgyBP2ofJJ6N4HdBq"
    "hwX4D04uc02hl4mGtc80mtzIxx7yTvjrv3DdKQLmcahVdpoHV9WeQe3LeYH9GSbjLNtPQRMyB+ed"
    "vzc46+ZwkZ60+84zG3x7crlwvG8Lj9XYH06P2JaK5B7TRd/38VPvleiWnExCQC3LoqZJTHyjm0GR"
    "CSR+yeyK1RWOdVDIf6T0dQdtHUGafDLQmU5vDQhqQQPLNtLUjtX7iCfHYTa0SWjMj3+QLJh+Tyem"
    "FW7bSgLyDLU0+AT9w+Vw8Yw3sPePpC3ukkf0wvQ0Sfro8kPAqEr0QjHP1/jmRqmeblWWFz3vNmGw"
    "bw0zaMqzX2giYCvj03jCd1eImoMuHCBnkdYFjR4E3JaUEQNYAHAdXOlKXD6UgQ3fl+FsbDr5/011"
    "mK/Fj8tA4nQzpO7pffix/l+n+n+v/P9fHDX/F+L8v6Pp/X9vV2/m6OmN8HLmlf0zr8G3YiIitXZU"
    "uu2a/mf+69UA539f6i3f9hR9dg+2rDlpq/F8WYar559RoUW/cef7vQT6LvIT+P5iUNzaIkRZ1IHY"
    "QQBq9OKZRRRRRR9nNxjGMYxnTatzcYoxRijP5bm4o0UaKNFHZVd+VXkd+eXlVAg70/SH4D/MHKcf"
    "UWWH6haM1+ZFdAsyIiJ9oH+My5t7oSIa9LfCn1NgwdR8QeUZXSgmrQsfOn6B77O2Zh5T6wHYRNAe"
    "XBKBm0PZ9dST5G4rY+owQIIhHJwTuErCkYawMiLHSnVDMNLBUOG84HA+4h6Y/dPwxK/D9oWaIXD+"
    "C/oM/MfoL9mdvrH8RaFtosVVXD1UDWigkhJOcnI4c5yEGxF1nH6AwUnvh7xA7z7CQX5Qc9YSSST8"
    "4/nQzfW7PSdnx/LVUZWCqPM2EOUTyd8/b+Wi0q1SqJCnJEMkPUntIJ9ZETJch5jrQiRYnxbwCl1O"
    "vaUU0Ty3QtpAqik3xJECRPdSOCQTsNS6zPTWVAm7BQ+YrXILzmt8kLoWDwgHK+PY0HAdghbscTqJ"
    "ojocHkOct6zgKJoO0zCMIMjCdCH4HYcOLLbvLhH3UpNNNXLVkLhmVFmpy8PeBRRL4GwpHGtL5bxC"
    "2fyRqKgurYAE2QIBoByNaG3cIcjmCpwKCjSPKzmdZ0Bcugc8gAABIC6bxryTSvOrf1/JE7NuCoZC"
    "ZhFdzY8KGPKQeVxvIb6wc0PX9TwtqW2to2tG20aNWluTmB7hzjcm8wXIVHaFYswFhS4HzB3HwL+N"
    "KKWJc5lDuToR5XQcOkhEXwwMR2rtgmQQCoPlDIgBocXaQycJ3B3ih4g3CGb6PT6sBuDbaVVVVVVB"
    "j7R2npOylsoN5ZZ0RHvyXIGzKFkTlY4fCyiQs30Vr2gSVeTTX33UZI9W5do3dXxkTuEPEWhvyqqV"
    "6DinW95NTMNL7reQyISShhC4FEDKbh18vN688IJxDyQGSFvAZvtFjPwc2cuNXZECwk8c5VN89L3I"
    "epFrxSiThDOOIS2JKmOSmJcORz1A2XRdQHEA6/YI9xwm165IflkHTPQGgobhVTXVNhmr01Eqaaau"
    "9X775acSoD7syLWfSdMtI01sxbKb3vSl7QIW420EB8rmbotDFHcBx0PUjeCi+fOSOO2KGjkhqyYi"
    "xLPUhUZm1QSI4cMYvUMVrBbks93H36ta1rWta9vTpvW3yOyGs01rvjWa5cGcik441xyvBq6VKNa1"
    "rXe3u7+7WkexvLqe1oppij74tyzvn1hIYh2HDA/NkWi+WcZ1GH4OOlOdtwoiE8AKe9NgwnxE0Hkk"
    "9vjMCirk6du1uZW5tX5PqAAGF0vRvGua69QAAIAAAgAAD7/XS+Rru2td+6TV66vdvNvRRiHgzYxH"
    "v9YFMMkZUF7fX6+oUKUGVSu0j5zRE0NxA1ru9RpQGVmMbzFgbbEz91fdsgcg6wC50K6PdGJ4Q6Q5"
    "xfKRTwQnES0O9hhnZqiLsPyiCIIijXFghBgl1YNFISApApOkZk+SQJBiICH3qtJIifnssAQ3ADqn"
    "3zzsYoej4+J4+m7JD2CqowRkhEZBK1Sy1NlmpZSnOblqUMsoZsRSTXjdPb226620tar2EP2cwSIW"
    "eVfWDEPYdL+kf+X4qbjaXriUMB7YqchygnTkPScT84bTalnSGqGKWKOWcwIDoirYdoonMRVZAgQY"
    "SQiQEkViJFA40OORBQzdx4RQzyAPH19UMcwajsAATU9Lnr4sl5pZr1xkVRSZjdDMa7Uj/OOwMkV6"
    "iAD3XTGdTuXp5uTqHk0DWUw0x1NWFB2uWvpkAgB0KAJ1c4v4ts8waiB5sPaKPbRh40iJyNoXZ7cH"
    "bEswkwXk7kIXpoYCA9229gDnQd5xGHFReM7KO0xTxOGD0IotLWUIwfAEH/oxSsKxjQuCYhYCvJBT"
    "gD0couQb+h1jw4rIRZ+/w2GWaaqSiwQoj4Z0K79wqXolbc+8lV9jbxJhaW0VSqhRKyHyaHdxPApY"
    "tgcWOshdgRIzGgQ8UswNDg0GmRj64n3hsaPsgUR2uNyoZ+B7OG1EOTCzt/ZvAzUNqkyJphwmSL5q"
    "oZAD+ev/kSEF9AQCuyg7YOIxIb0TSIkBDzqlh5Ai2J/XLbpaZGBfVcBZCB9gQDLYDjDClyXEpkIJ"
    "SkWbzhqoqEIWS5I4CiTFKjBBoR7VttKYUlrs6T8hot/AepUpLQ4oqVNVzwzLd2vRb2/XXwUS1Imm"
    "EBU2bqQDXGkLRG258mjpTWw4Q/PuDd/LCjBG5b+DTzZV2m55D3qoGt4CpBwAtTwC5Fy5jlEkRVzw"
    "WgZIBwW6hR++VCHvoXrfSZSWLILEhYYWrbUYMH/lE91MFU5s3E4mklQVrJQFhGRqGIlJAfMAVS5Z"
    "FgMi/tnHIxf0hOFhdQQEEk36X6uX+Sr+P8m9oBoLP0f59QM1r89FxP5+eZ2fNBtarQhmV9eSm6CJ"
    "b9AUMIxZKIQqWyicUmIkRZWVmd3GbQPO8nZyKTIgMk0FFYp67Y8HNdLm+UpOX2NZTQKoKaxLYE6f"
    "G0dgvRqPOo4XDPGaLkwZBzzjZ8aXls+Qmp7NTg44DV8tUYHFNIQ4IIer0iIGsW5zkkHvIPAucUOQ"
    "fMBdfJ/Ma0hRPs5KCiM3QVYIqhSJOJMSpOCJTLe1zJZulLIcaNYamI5Vm8MM0iOY2zIiQwzMtEyV"
    "KBYmTKb4DjADETYbgJExRbKbGmFsaUQJClyFIYRBWyRQmUlJDSE1JkMQ+zk7T5UdylR3p3ACJUJJ"
    "AjokUzQEC3QRbAAKYAajITl4dyJD1qlSeEvpzduSRRbPNlVK0DcKpqIGoQG0IgQSAkCh5XtVS+29"
    "H0G4qt7OJZAwHzJs1A1QCIh6YKi/tzUzJFi9Uh2UcYGju+bhu5MTyCBiJkIbQuGLH/bDaMhiq4Bp"
    "RcO0mb4mvbgFR60+WBCBZN01g4eA0UxiFiC+GKY+4Z6Ihkp24b8K18JJROyrBZkCqnDdUhkvSIQK"
    "3fOfHPLylt/gw68b18wSjPCiyZtqZ7bg6r0ute+aRYjD9z93GdODnzJ0vaLBUgICQSEE7IsdGqC2"
    "HNk1iZmS2zHRjZS5kokS3MHqGe4YGsTBmzQbmi0pOKBghkGAs5iSQbQQishRrNAkwygRQK1lzfYF"
    "enXgnEXfXMj6Gk0ktm5pR/bgLZLTDtEjkmRnWHvZXVhnEluwA+8530dDksUC+dGPv5Z4WK0fZlJN"
    "C6Y34PPDChmqIM9K2yyark1yMh53l5RoLKbRsrtLjHASQQxtppQy1gvSwha7MrUEm4Rvjhe0amEy"
    "TQWjPJInh5jTSfpry5NlswHGzohNyLTy2R8JAwxBYILhQ8LxO6yPYz2sOJWHLLkr4WFVXo9BzbNp"
    "p4EXQxAqb8qYzTFhqYnHFTpLp5pXhJyE3ScS5tFIXVk3NKHHJLNzdDLDVYKElggAwxCkgTWroNAr"
    "Gb2caiaM1m97eLpQAAAAAwAgAAAAEAR07ey3Xp2IV16ubr2I1atdvOAAAAAAFAAAACIkkkPSHaa/"
    "gWuPDCaqyHNxuRhqAUIq7A2iTkL4LaZpFOEVcNqFKsUisUgQSEZAGQYEspyTEMS8+A4d6ls537nV"
    "2465psUaZKY00xaRBSFkamaS4RHMNTF1s3RZh0DdtvNdbqiIryrggtya6S6II1eW7NJk1eVDK7br"
    "XYgjo41tGFGiVOPOKnMCbhA4JhsyEq5AMKIO6JIRchyIkLE1YoYXW0EZAVQOo2lghbYJJKxEIohI"
    "yDi5ianfguxE2cwGVbz9UJBkZGlcoUCYkWDZcoWGFgUSJBIhOAhCojISM9agnj0PH0euyjo2DtMU"
    "2sxmNjiWxYDV/KfsKd4/7sra1pm8Rx3dh/MVzk5MdMl5VNa6Zz29t74C6rDmIzdCEMYKOQDoIQWQ"
    "O3U5Bk2Jvi6DZqOAGwBNhNECgTf045pw6+rgGERC5gZ3GcjS+Auqgtc9nYQO4MgPVapzacmsQUhB"
    "E/MslNlaNNspqymtIRTLTJIqEFYAIUQRS/ENYIEbO2IkIAYqL1ZJ4YeHos1gU3e2a50ACnbzBv8F"
    "04G3N4GodgSLEgRRIgb7K89FQikOQaAlKUcrgLsT3EGZBi4og8cbp0Zdh4UHYS/Mibth1QLiEK+2"
    "zp4hjPErvyS7wjfcISjRgRE5VBOcsQlxG6BryKIOIlA6xipBA1wyWAZNwrLjiYryH1khAIIhBRIi"
    "IEUOwbL1kUNgcRWMCavE6cpjfh1KlGFXjJbDjRjfDKjb8aa8uuD2ZrjpwFyw7okRFhWKCIoSB1t4"
    "ZjDg6jQWBNGeMANzXvwqHU0G9B/NEZ/uOuFgYWA2EGO39eutFm7BmHabEQZDMjmhQRCuYQf1AMVq"
    "0XqId1Ha/F8RzKIHQhJ8PWcDUHJ1SSSSSQAAAAAAAAMAAEpJJJJJJJJJJJJJEmJJJJCTycp3/lHn"
    "LRH9OAL3yj0EHJQIdixSiT5cXl8gH7wPAojlA3Ecl1gancHskg00HWmCwM6mz7x+Y7l+iCqQgimH"
    "n+Y4qI84oNgr4PAiB7o/oCKsRY4GGnKgKkOJDrmwQI35agM8YRVO35JERKfVE/UioTbgD93XWRGH"
    "QJDtQCL4NQTPoO0IIkjVBQk9pGjBVyTkPGcAv3YNERE/rrKbYN0WRAIkBYQQLUrQcwIG5er6DxIC"
    "YriOGuEWEERkIQHwyoCJOfcShmRGtEKUKSHu1gNk2nMEFwEkQRkBbkErAN5cUKQrWq6jy+7eYRU9"
    "XgcyTcGwe+90rZstDwHQFJ3VcVXelQcMv5L1da4eBA/Gzu6SQA7gD4vN1YhmQm8y5zOBUEwTAKmG"
    "CDzQRE4cyb5zmZAJtc4bJYpJwuTSjIsAWfXMH24oFEbSUAy44RIEBFJ7MBSlRS5AbxBSlaHWN1+b"
    "za7K+jGppNJZa1otizaMJA2BSUcDfECyRk+mJBQBRQgQCJBEz4GIDIiEiBPdM7D4tnt2EDfSroXt"
    "dcfkhoGQb6JHQvPJgEjEik5AmN2WQkKzbZKfvMD3feKQN3dh96B1Bkh3BaiHVFZPwwdXUoUS4KOk"
    "+mSHzhy0SaD2AegxWwSqxSkAoUIQkkSFpqSBQ0KHNspRVrI7HgUcx85u0fBLdfu3LIiSCxGL4D1B"
    "6fXAohJ/CUKAmHz/OXFNLopESqiqxF8Y3/IWLmFVH72gdRXSvFVEhwOhOWCX4kQAapU74JIGdFOI"
    "ANLBGMGIjas+ZzW41tiTFqiTa1JUIJEYSMIKHwDPEBgGFhPaO09/O4N41bQK5UDx3R5zV3j5udAM"
    "h9MB49dBUZ6SiQzADawmwjJO4/qwDnwIisig7/so/DiVUkHZHtgku4cSSCJjTcfsmpPmexs2x3IQ"
    "8K1SnrScIP90N5BkCxBYRagqk+qKvylH0ekMMalGbpZPiLCkQcZeAVRJQYIII7Szi3Kcsk/Jbtk/"
    "VzsUOCPLmWYDONCit28nE1wtc+Li70uGUMNFBCBCo++XA4ZEESl7KdVs3UWcV9ZZQWyHAQ6DM66A"
    "TwkkRZAfRHky4VQHvtxAzm7xC4B70hJAjJAWkakVebhelP8crl4pXyta50qk/ujRHCL6PkDt847h"
    "fOd7oyomA+a97pemqp2dpkJqkAKtE8JWu5K7elPu1N1TeSZnwhnGjfq0sA8+D6NkgyEgVCMVM4to"
    "EWDIQJCI4akCh3KKm12IO/1YaU9l2jQ01a45qyaExnT9yzRxrEfdmrJyTkYUaIn7A0xeIHaIJCKK"
    "RFwZhQhTBIw1Pnmi5fBTR6YiJXClKiQ0HWIRV0zx9fu28rW4uDk3BNN5putI6zVDIkFMy4wGtimq"
    "0phRc6awFhIm7U+rf2zkaOsspkTOLpuSnBcNJo+GFCIYoxE7YYzIiJi1KIkUEDP0EZoF8DOkMxJQ"
    "UMDUO4PbmGnwEhEkGDOaEnLUn6tDMT3yKMVFIiDoou/btWg1OyCRAn/NWayQsIFUalMG9/TRxLec"
    "8G7JTy/V1ryzfBl0DUKLuyyLI7+q70VM8aYe+whtnKIRUEhFA0A0VMRysFMlKwwbNQhYQpApJQgZ"
    "NGoYJEgigsh0IHrKZpKxlgIlMGQg9NFRgobOEXISwAZkQENDmukTUIh7okHPKbPCt7HXdKYxVMwI"
    "kkIRNsoIBvQmIcpDtRE1j1RG4K9RRAPyBVYvAYG5CDTBjIPagd0CAokVetx3xOIJ8MEZCRSIEQXJ"
    "23yZZ4nQEA4jU4xBaiMKkhAKFaghMkipFVTivSINAq393n58quRIpjT1weN8c+sQyjp0gfDu4AkR"
    "RcpD60jo2MoGJO3CFnLlZ6i65bzeOasE+rSogxM5ZiHpNQw2b3o2XkyTuG19cKkJqR0nLxvUaiQ5"
    "IaQrBOHi7iDQlUAxFUvkNTzOScszUzlXLS1zMZywAMQAiAEFAisYcndAEN3A92pSw8fSc138nOGY"
    "4IwOqGgR4noKCZMR7FEuEZfqldJWMTCtkoghDphxxVTjxTqAWiorRavS0RsNTWvD1Ps+xdGui40l"
    "NzgZJjK4HOVzNyTcTgjlcUzLpb58tsqSQkGoiTSZRkRTJktDE1RY1LVzqsBJGGkhQiMFbYFbFZUl"
    "W0bYkjKIIFLKRqitWgEogDOhORoj36ykFddUAzYb9odh2ZUBqCajZ6CcszuFEDYoPt4079/iEStN"
    "4gQ3Aj5Fii4jiVEC+PDaEgEMDvDnTAMVXkzHXP7Y/1730Op5iLNVzBThrBQJuYpY5WwY0FFDEsYz"
    "uaasuo1EEha1jDTmSk1kFsGxr5jnIBKb0c/rdO/fTANlFaBiGtVsiiZew/WFt4TbuUNvUSeOt/5a"
    "7SdesrD+dbDy0Xqq1FVy2v68CzOLpCBTl6g0FRI2CoMgnYARfaZDuoBHxQkQC2KVSAXkVa2DEOsU"
    "1jcM4MgFcbTMEIYBMCmBYAKgxiUIHdpaCaDs51RFycsjNtmZJ2kJRZAVIKgSKrnel6mXzdiSFn7o"
    "3qQJI7C9y2iZlqKWnYxTKzILJIQIuyJqgpSlCC3Ha5tapuqzbNtaLVsVrJoAimmSFgjDhsJFJEJl"
    "ksQAUBEREQRERmpMwhWQJMmYaACNqH8QRAMkMyCGdog0aIbInHCv+MXRN0O4eSAf4ogHkgJ52KB6"
    "4padWKU4wNe5psR+sImtIonsA/SRBUhBPOQEF4HJS6wioBf1lvRwxQDwJ1QAoIHlI1JFe+qaqmqD"
    "wICaw0/Aqn+fo3K/XE7QSQBkWCJUFhBKGAGS83d2britUkpFWubUq5pqpITs9UD2rebXIwlYKBUK"
    "egpgkiA5yhMU1OLxpq2gsCKyAoEkUgyCom3Xcd2YhiKAGMSQND7yC4Zhr4Hf16z7fqlzZlF/Dqb3"
    "fUpBCf9MuAshYViqqsHVwWAwP2mG93RFkLCsjCyEoRixHw2t+BWL4oTVxeWX+JBM6O6aeONBRCsR"
    "yjIsgCTweeOFKJ9r7aW1yrQwnnLjmFKag1YbQNOze8LDUPQWL3oPIsh7N2AuIhGGkDDIcD/dDQG4"
    "Lkq5MAVNx8/feKlCbvXVm4gaOwfgAJYNyAgQVTQS4O6bEzX3O3b0QR/tRPILu7pty5ta5nk9Tl76"
    "AGzx42BQj2vKIlUO0X54ryRQCoAemJRBIiQBeNtODESUQJKwFBBCB2iTnEPRRv3BqTR81xz58mAK"
    "ScDUEQWCDnjMOoY8hIQWuYAaggALAEgwEMGghkoVDJgAGI9SgcOGpKvBjIkjICoaETFIxWiTaZpS"
    "2y0qba1KGK0pNNpKCSSRECNyICmxN4cFQzUzmAZJJSY70V8Gqoxom1NBw01uxwAKCRbG41pqANeS"
    "iBq3LrTMDuinyCxiki8xRAgflLPjSKkSRIge4/WE9ZiEcMSRqz6sK4wUUaJKrm76eCHPA9ECsuo6"
    "EEqIHdDuDoR2wCgilDxh5w3MJGQZaBRiL54p9WLJyIwsI7+eReMS/7sF+eFgeHq9Y5CfmUbg4EB7"
    "T79B36UKeCqPAFN5FiixxAhQg/Wh7OK+uTlWCGRs5Bkz43NSvW5A5q9G0QEawuIZgFAEqG2wVwkA"
    "v1MonRlWRBZcsxjSa685H2r0ySSaud7d9t2a5pEoWFStnUXWBqaMEMQITJzQ1K0WFFFYILAgtidX"
    "277wZLm2ThVyI4kVkI3ILRNpBNAcjJTAbBdoU2k0QwZ5CTQxETBAjQYBYJBkGKvy+dBPYEQkEGSR"
    "CBADW/BtCqvhl3685ZErGVeHu2r2/zWVKvBRU5whD1sVRSpCaHSXKr67hhLq6GIvFNRAkVOiBUBk"
    "No6ewx0QxA5u7w2kcMq5RQ3PCQAsbjGFnpxCLnieetRaqJcwsXJQwpkxqLZjgjFJZSzGFyuMyhly"
    "mOIZomtyB0O0n44qE8AyQOgYgCHTsdvo6cOpdoop8jjGi4DbWEA3cj/pA6Tus+F+UoLXoI5hZmDM"
    "rCsmWVIpLbAlD+z9Qoop0DxJAUhJsthEVF3PJD1eBQ673CcweNOh/VHdsSeuUAdbVmX2pFg5aqqM"
    "EGCBghPMaokjZ9+/KYxLYkAgHrfwaH38hy2ymBl9tHmPPQ44qKfkai9T1Uxxl2SxjbRVURjAkkBg"
    "lclOUEtIIeQVTtWIHoIMGQnhQPK04PYQuRIAd7Hk+EXO4RB/fEoIuLIjavMCIpsPNtaxBFTKOLVE"
    "iQac57WbyTSYWVLBDdT+vHyefHA+Sw5QpFUUYqjGLzRq1vfJE9/sxiZeHwIWIpR49wo9Z1esMZqa"
    "TLwyWeur4pp77UxW5W2kZ7FwKoMS7aWtBWpEay1bEtrczo92YTunFVs7k1myNnoocyl4TODs6oJJ"
    "zXIh9cESYyMEN8s2v1zs6U7lHs7ho2KxWKo21lLbStmzV1pbVJYW0tpbWyjDlZLgUW7Ktcy5My4J"
    "gFjGSlnXju14OI87063ntqZZzvMKkupK2lQSJNDu81gerE3QzM2iTKHHdx3dWrW+QQNW1odNTBMk"
    "AbNXEuGFG+B3HK6xiubERRCEmQxDplD2xxAOQN0fzIbGVR9GvQ13oQkqfzlNQNqgkqF8XvV2fDi4"
    "LKFV0WByFWbcK2LvJN5pBcIGHYhhxikpWwXzb2kiQg30Hldu7Yg8rvcNxq0JrwBNhDyeTya13ZW+"
    "bXc1Ns6augB04IHlCHlRTtyVCK/i1h4Ho69iFsUI/9oWnZlvmHChnlSAMooYAa9WMjfJVAxT0Jvq"
    "eJQRWqT4GnIgHJ+YIB1AU1g7WKihiGUBhCIEhmy8QsX26Cq64hfgbi+SNyd8KJUkdUgQN0E0gJT9"
    "f5McLc2TthDju4kD7snKc4hm8vsYmCX34bttUtuk6Fqzr6b+Di/LxZQp1w7M6y6V575PT/NrDX2y"
    "8o8c95Xp3WFJCIgMrFkLTiPSRUJBE50AsEaU5rPnxphNIG89Tq9brCL1KBGOu4GoqdghFYJABuDU"
    "QoDzhgBKCkQ+kCwiZtqWhDJ37zhB9YIEFIpxhUVkbcD/7i8wQXjNJ0fFylGSUWb7k0BBpUP8o9uf"
    "7nnzODj3+CJZRAgvJfYQ5AlctDnG6yDHg/VZ6Q0AUjkQqEFiwI8qF8IRYO5q3wtVAgMH20tPGjhI"
    "Q92Ch21nr0T8IIkG4SJxDIIqJYInxkQCwB5fZXdrx8ie1sgIiqmCGgyGYU9QzWpQRFeWs2eXhSdm"
    "uTowwmUr1ViQMmNxxZQboAYbjUGE0hy114shd5Kq4kz/BxoUmowaWREFlERFhUqblCw1qzlq4Mmw"
    "ziUhgGqQLONXJFkTQqRHeFJTATBZR68trvw6OBKoiMMrE0goYdf0bGw1hI42UDuqiENZUCJFkC2w"
    "4tUEQE53oJRJMiTqJCgqQRjbUNRyy/XDyuoc2kDiMh2cw6bS73XgToM1dAWca6HKcZSOAHMSUFJJ"
    "aBYxr1YZ4U81jha8OGWY3+AKFNcczJ8RGyvnnEgYR0YNRJAN1yscxLbC29FUyxqy2cDqEmSEmIDE"
    "IOIiSwERYxnd3V1rAlVzm76VDU4A5khUkpzzAZzBRkmmQGJgZrWrAwYlWTLZxNbkASipSCwPQXAN"
    "TgQSAIo2HQE2GB0bzWBFmGWFBTaRgWsGkDpQSA5EgrFW3CHBswD4CwwaYTcie81oNptXRr3NBkQa"
    "gikFEgo6QQzE2UiFCrV9NU2EQIBh5d1w21U11eA6+HaA+SCyIE+IsBxYEAiFC7uABVcDVvAGIu7U"
    "OOVr3GdEChNntJv0suCiBiALvgXeE/qiBuBBhtuC2D2MmMG3mMgj4SihIhGiBQfdBO6B/EnmJYoo"
    "wYHiWipHV44m8OKKLxFw0jAjJJr9lXOjRdQsZIECEYvAoNq+gxlqBT354zROmlLBkkYQER2NBOdY"
    "JWqsxZiEAT4sBTMJVUpTAppQCRIEIRIkUToUwB7BDkpmx4wbsNIYKy2GsrMRBYIJrQZJoiHgclAo"
    "XOgxHvQEwm0sgZQ2tDcLJLnLc0zYgZpK5OWbjFzSssgpgNoYMgkBIHx+eHAc0ilh3DATd5zSR7o+"
    "sASQRTVipp3bR4CFWzbS7N73f6l63q7Ly+hXfSuaYSGUzLJNItKymTNptGjNq0o0tTaWkrZYbexV"
    "ubL+D/VIer7jU3iiJywBEZAROHedFQQ8QkMEPOwxhCsuqAVIwSAnyncEzJ9EFscx59upoiDmE6h2"
    "gTL4VkJGAzlB9kBjWSwzAE95RVFUwyEOk+d2ciN+ly5L3G+q6JmYYWCqBJiXXluCoUuXNuTFFxzX"
    "BscnEXIZQ447vDv+x7mvq59a+D1fhKBxPwnb6VHbAnSqnOgFkZaFICITuKSlReH7mrEE/QifqJGI"
    "kJACCLmghxEfA/bOfy1JJ6CFgojs+VM4HK8nIB8nc/tzdEPjiAQgZwZBBIlMnRLD9BybQdx2rfy3"
    "SdCvUv6U73hmnn/GaHkDlAMg5RDNfBFZgiDY74LRgbSFHNaQjCaFJIdKjrj8hUgShEK2yUNrFLzg"
    "v2desBfrLW1pEAAQjBKCd4hMHv93uO4C25EfrMgyOj0mQOaJSc6H0Nrk9EKaoK/RTB7of+KZ5gWg"
    "yWgV7IOMNyfQIsLGpZYkLCiSxSMef2zxPzCEvjeOLIJf61riQbvIk4CmOoLHdtp4LcD2ELjJrQjD"
    "lYHtAwIegzqEEEBE8GsRVFaamm00KRWLZs0xIJBIDBYhEIAsHAaAaVqoKlqUjDSJAJ85EbgEPDR0"
    "XQBJIMIJBfHqFA/ixQFeagsjA3RkJfsSJAEgosgyCYmGqO2WVV3KJ8hMwH4V8+A4IKPJCjNMS+YL"
    "hi271rCUpogiB+z9P4w/WyE5nijOlRZOQcynkMEdwLYQn9dOgRVQ9nYefZrPSXUusWR02blEDsuZ"
    "OS03pLrZq4/E46tHg5GEjnfslRxgXzsllSpeNsYnsTAq4oX+lbFi4xd/5fEogdUAMUUDfofpSEiy"
    "SVsWyhVmqbaTWtoXTpq7/jvX2VLG95wRcMCzYf2qKkUVLIqHsiivniAeo6w6/OiJOfj/DbsO32WI"
    "iXh6fHIUWh/RSlNwSSDIMiSCM/FtH4X8x+Mxx/F2MTMaLaM40LXbW1227bfwB+8wQcZIkhryzALF"
    "RIpnnkYe7kCJmPMiJ/A5vt82apRXIhxx9P774zKqKNRqRE6j/AXckU4UJCV0oeIA"
)

# ── Extract + compile ────────────────────────────────────────────────────
_BUILD = Path(__file__).resolve().parent.parent / "build" / "inline_k12"
_BUILD.mkdir(parents=True, exist_ok=True)
_CU = _BUILD / "flash_attention.cu"
if not _CU.exists():
    _CU.write_bytes(bz2.decompress(base64.b64decode(
        "".join(_CUDA_B64.replace("\n", "").split()))))

_ext = load(
    name="fp16_k12_sm86",
    sources=[str(_CU)],
    extra_cuda_cflags=['-std=c++20', '--use_fast_math', '--expt-relaxed-constexpr', '-gencode', 'arch=compute_86,code=sm_86', '-O3', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__'],
    extra_cflags=["-O3"],
    build_directory=str(_BUILD),
    verbose=False,
)

# ── Config ───────────────────────────────────────────────────────────────
def _find_best_cfg():
    cfgs = [c for c in get_kernel_configs("all") if c.dtype == DType.FP16][:40]
    B, N, H, D = 4, 2048, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v, o = torch.randn_like(q), torch.randn_like(q), torch.empty_like(q)
    best, best_ms = None, float("inf")
    for c in cfgs:
        try:
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            torch.cuda.synchronize()
            e0, e1 = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
            e0.record()
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            e1.record(); torch.cuda.synchronize()
            ms = e0.elapsed_time(e1) / 3
            if ms < best_ms: best_ms, best = ms, c
        except Exception: pass
    return best

_CFG = _find_best_cfg()

# ── Public API ───────────────────────────────────────────────────────────
def forward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """FP16 flash attention. q/k/v: (B, N, H, D) float16."""
    out = torch.empty_like(q)
    _ext.forward(_CFG, q.contiguous(), k.contiguous(), v.contiguous(), out, False)
    return out

# ── Self-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    torch.manual_seed(0)
    B, N, H, D = 8, 1024, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v = torch.randn_like(q), torch.randn_like(q)

    ref = F.scaled_dot_product_attention(
        q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)
    ).transpose(1,2)
    out = forward(q, k, v)
    err = (out - ref).abs().max().item()
    status = "OK" if err < 0.05 else "FAIL"
    print(f"K12 [Misc Code Changes]  max|out-ref|={err:.4e}  {status}")

    # Latency
    for _ in range(10): forward(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200): forward(q, k, v)
    torch.cuda.synchronize()
    ms = (time.perf_counter()-t0)/200*1e3

    for _ in range(10):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    ref_ms = (time.perf_counter()-t0)/200*1e3

    print(f"  latency: {ms:.3f} ms  SDPA: {ref_ms:.3f} ms  rel: {ref_ms/ms*100:.1f}%")
