#!/usr/bin/env python3
"""
FP16 Flash Attention K7: Auto-Tuning  — RTX 3060 SM86
Auto-generated by gen_inline.py from kernels/src_1-7

Run (WSL):
  cd /mnt/d/GITHUB/Mini-Attention
  LD_LIBRARY_PATH=/root/fa_env/lib/python3.12/site-packages/torch/lib \
    /root/fa_env/bin/python kernels/flash_attn/cuda/inline/fp16_k7_sm86.py
"""

import base64, bz2, os, sys, time
from pathlib import Path

os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")

import torch
import torch.nn.functional as F
from torch.utils.cpp_extension import load

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "py"))
from flash_helpers.kernel_configs import (
    DType, FlashForwardKernelConfig, get_kernel_progression_configs,
)

# ── Embedded CUDA source (bzip2 + base64) ────────────────────────────────
_CUDA_B64 = (
    "QlpoOTFBWSZTWQAYWz0AHA3/gG93/pV/////v+///7////5gQL73eoEj63vve+9yXvo66HRrbbWq"
    "+3p0ObACpevT22xe7oAMu+Y+1ADJEvXrT3vvnZx7uqezvvZtu3tOO47agvgJp2baxqiqG993x83r"
    "5297Pn2+zerePn3Vn3UujGzWURDatng8OePtg+X0+Ht6nZ1pe84fe+7dnSXoUatvE55jVejRTbGW"
    "DNm22vgO46zN6OTtqbZprVSqtZXdugSmkI0CYQ0ATQRiNMkanomp4mpjQmgAaAaAGINNMMQIImgR"
    "AyFPU9CNNlPU8mJGgZBiAAAAANA0BJpJEIaU8JM0VP1J+pqenlRtT1DT1PTTTQ1HlD1PUeiANPUe"
    "U9IAZNDQJPVSpPRTTU08IamTJiNGgGmgA000AAAAAAAABEkgIU2jQ01U8wU2kyp+noTTKj9MlP0U"
    "8RP0DSm1PTKeo9J6jRpkHqPTSCJIQgCNNAU9I2pgEE0aanlT9U9T/VTyT0YUH5UPUeo9QMhpkAOR"
    "VUfvggAHd8r/OKVBKkAiSEj5JtxbEEBRamalf95rxezq/X6/qfE+G39/F8+wHZW/MOUEttohw4sg"
    "zKEBAEomYChKsPcZRimTe5lu1DFZ+X6ui/8WcHdVRYyDAIDR0wScKP32j0RP9q+LMt/mpkfsGNVJ"
    "AYoVTqwFyGPramCmIbDn3OZhibKlnHJkFwrTi2ZRE+qtqTeWxHNq7ayCLczGpRWJZRtlSqGP80k8"
    "WpndbvGnG3KKvC5MrDExfwsmDjKNEKzRjUVplTpDfaGiTYZY92YZWC9SHAZjzZ0IBbKrERURWbM+"
    "SHICTihI4sbqyEtvvz+H4cza6zA0CQTAOBnRg6ksg7h62g/FIO2MWgCysgLpMmQhlgPbkAyAEtNX"
    "k0hrlc2dOYVw2c4Urxu7nZo4G4TbEXDehhvpqdnV5mta1rWta1rWta1rWta1rWta1rWxrWta1rbe"
    "POQxqIJJJISKG2B33B2B2ct+4uZxIcCqgoxbewuYHYbUvNsA6jW3NinUshwHuWhGGYZsA1ms9MKP"
    "th0eY+ByP/OxsFY3dyBbES8w06pWDTBGQT44G1guvpmUnV+3uW/4vcJo/IeNH6aJwcjQ+aOxkJCG"
    "QgR6u8khtyAImIkqoIR8AkCNUef+w+XHrtXuy9WPRju2KlM+z7dwcr3tihEeToFhaCCSH5+iw2e/"
    "d+zGMjNOVFzcoRHbttbCNkBA5YIiXFUAKhUUJBTtw2RtVQlZXyRPZEJnSpiAeULevx/u7Ke/fzs+"
    "62rwNY7T8N2Zct7ShhBzi742IJHHfteOZkQd7sZm9j+ei92HJoCiKwgwhoDPUfS8nK8b4aFMhRJ1"
    "c1HgJA04rYBy0b3Tww6CVLtoCf7V168FumjVmimHESn3Sv/V6kz0pswnCGVgAch5P/EiLKqRNFkS"
    "QliGD+FIdkXMULiGpinGzSB1Nd+XPEMm/5UtXjEezZR+313OwPoA1AblksCkmEMJTLVvVmjFtGPg"
    "yd0XjQPSQou9hVKzsjWTl/s57BmJV2bNTTClssNFCHh1Ute/a0eUaO//J9t1wobLoqSbb8J/58ed"
    "nsqrRMx4YMHI5cDX5g23wbazHkmsAYYwFIQBOumxBAx4/4+fvvVs+3KGkrR5fs7dXSGAZi3pygeW"
    "2ywU9J3RjgMHXlbpHe8NJ/c2Xuvlf0FQEBKccLpzwAD169XXdETVBETlr7LapMADCO2yuXv+eksr"
    "DQ7wpr7PaWdYcOcvj6xxKk8g8j03CZv1lc6PFv11xXub0lug3uhXD0+nHF9rDNLGtgZvz/4xA+Vp"
    "6Ib/E2kmMvg7EP0+8/4/RCv7NYW1BiJVoW4Nrb9xwYp5m05gagvRaIQ7WbI7I3Llsdpd/wKtBOik"
    "6ON19HMmijyDst/CnrNXEoTddFiB02Yi8EUzyk9RvZBum7bqqrXKIYwvmSltkGpMQDBY3+cGzk6L"
    "kDuyYx2c2GaTTPnnhGBoK7vlBd6/9Xj9Yvq87xeZOuK91nXYfJonAkKQiUpQNCu0C0W2wOuQU6Mj"
    "/MfAZa0dHQr6ggZmoLlz6TdfGDgQO9XFS+9TXi1DOINai2pzISsdhwrUmPmhpIOKOXU3BedbqyXR"
    "GeN5nWHfp0Lc56GHlg8CtEBvV0I0ZuX37UONFPsJxeOklSFgMoSE2XNhivrwuwsAoTDQlMsZ5Cws"
    "lseGHTG0naOnT6DUuu+iiiRuxq3Oz66uDvJRxu7e4DEmRlnZjB4utzpgnWqYrGM+vjRfiVNBtQaD"
    "M9IBUKG+vJ7YsJIUg9I8kzXdw/LjpiiwrQ37e/QgSvKxYDuUPjI3SS+fM0QZCN3zwwictNWUTjma"
    "9ewMt5GD0VFNYnkdrcy1ZdI1FE2iD6seurXz3u3MhBB1CHp8Q8i84192K0a5a1W9EC3lGM/LTZBu"
    "hzN8Ka7H1QvR2MMMamoGk7K9Ai+Gs4v1DE4RRblO0Pbk0vyeov6Om9nHSKvafydXZNHj6ppwotvo"
    "tFxltviyczxHtcvwScQzf4Vf8EPSyE3QtwXa4VrMx/PG6tzf5vG3lAGcPZthzU2+miLB3c52MKMM"
    "fYtaVto+LATlyQ43K3iQc1YK6b1t2Ed2ivkPwOxtFpGgD5GTOLhi2vDBs4OFPX237+tnoDDO0bVE"
    "LGXsFafB2oMf0bKJVPtS46IKTxU/6+l+vX3bXLrGRboUN3+47/UAEgvjqOWTIAkjKADMXvGiGzGD"
    "A3ANjCpmzVMEirHOuHzd9X7ud59ONCUbSm/DDxxqq/Tputbmu41cvPFRlKOufLTpNJg22PgNr3GS"
    "108FISB3R5+umugbReE28Pa8bX1z9cKmFXSVUvga3KLQ4I7aqHqN5tJlqAcxXo9c9B9p6GRUVu4n"
    "BCiKNFllYpSxbEtJU6JQrks94yS42FtBZWkVAxAwTwDv73tvlGwqG9TThIjwef1G9GKFLo4r08Tv"
    "kVWvUICBREhUPGRhTx9fPKXN91coWQZUObQO+BBCFjeUF3OiaXYhzKxUwwuCy2bt3dyVxnbO+3k1"
    "p2aqTvx2NiZAsvWoEIDkOebtx3U9DG30nm0HvNysCpaHNS4uWKhT0vVSz7L8z8JK8z+rY0WDhU46"
    "rtdA1z3aGfJ2Htt9jlm6LjtKgIwHsR7o8D6ajnEdEpQfOWuolUElZFx4cJGUjxg/W4/onpuTaoWO"
    "GurL4XfX9HOF27ekkkkkkkkkkkk7rQtyt1YQ2vj6aZUetrWyCBXyAcCa0OQGgEievdZfG4wgPObO"
    "7liB9sYtysh+IK3y4WT1d9VrLsrhpRShGg1GMdvlsg14fdJ1a5CMi5mIYKQlAllkdlEHfbQx5XGq"
    "RXCbGZSdVEY8rVTciRrUGrV+aZEIewxYpLLa9Pet02NNWG6ZMptZi99dBmhELqR+Fnpvjm2n6b9F"
    "bct9ODZbLKERdtHnq0yj9yMYlcm0WA0duW7zSWmuERy2inFMKeNqlRztjDqymQnfTQTdiEeQkZ7G"
    "5jWXuwVqcW1ar9VY7WmRR76gIBvNvKeP3+8ynWeM9PmU+300lZ76bNMoNY+dI5HApUWSNSkqxYwH"
    "UEmXC8OLlEETsgqZVQoqaQQYnmSgmZM3W7jQQx1yNFmh39+gI8X5c0Ixx54bwUGIlIb9a5xYnPMn"
    "3vfp2xCiSQgXx5Fx15KvuLTY7DoQ8LpN6+weNHv4b1ZrKYbNFUmKph7gdT40Rjre86ZAy+PB/D8A"
    "7GKuk4zbk16ChEYekOfCkOaCklSDfjMIFEkFBGT7YCO/7Fdfn8qfwPeP4EP6lfX9BPvpLZGTQnuy"
    "o/eB/j+gGMADu4EA3Q7J5x7k1HW6XVy9XV8f2W2cSp7UfkzjdEl6fHm32t/v8O8geYT55WH0W1sD"
    "6TRKoo/pWfWygisC37Tu3D9aA/LEpU+Mn5QGRSEV+QYObH10/pjZ+IipQQUSCRkIus1VYkjAk2ns"
    "yeT6D09Xpj5DEg5L3xuuaeuxYMKqb33fleAC+pA4fqUl+R3yjv2PTczhtEPu+GD5I18fM+xxfDHP"
    "DlyHy9DThkWKBodF8aYa4r1mm1BmmhOm6NJQOFDKLId1VRkgR4IcQkFFsywg1R5GwqdqPZhhA/fu"
    "+SyX3yVJzw8gW4ZtfibW540/TXBfghDfFoK05Wj+IBdBcu3BihiykIQHA5arJdH+3TOJw6+ycrAE"
    "4myfDRbAk/y+vhVQcKWbZpZ/qQxajNA2XR2xM+Vu6RFU/CRXGV8MlKTGbgzstY7o1moecW+67Xx1"
    "ktrRvlY45ZFxcY+rfqPxj/WYlhnLl08dvDtNCM2oPCVbfv/zWV1+VnXqp4fRTp7eh4GnRRoGob/7"
    "M44LtZNLXptR41m5FP21rLP0XYy6980KNTIz564q10R/Vps6fl+wmvyzp4RNh4bg7qmnLWQl/Tr7"
    "7bGqM4B+a96Ilj1hDVHtlGHrywnU3pTvg1MEY8X1yvuLodtF+sjz7t8XTS9d+iPbQMOkFWZlqN5R"
    "sBkdJk1UVp4VPEifaOOOOOOV8IkSJaQKGpTFyCxlAVfnkZ0Saphhh3LH9SwjODHcso0qPdL1ZVUE"
    "upK+Oq32P8ns9dUK7jhU+oXa7UrkNN7VvSXZKEu6+BbaYntj5LY4Uy6I41vp6vD5kmWveOxioaDT"
    "HDiE8M6AG9QZTCROa2jfo6oeZVaEm2a+l3szc+g3cC9KJYzcduRPCa1dNNEeDJAWRQPvvp8olaNI"
    "GoO7ISgyQ14bWvr7x9q027ONq1y6vAAAAAAAXLTtLVp5V4MvmVrXdrC1PoBotJqyAg1wONDS9IDn"
    "KRTCPT2SnJxhEe7rW+JI6K/sMCtF1K8IvZGHzfLuo1+FWcq/5az0W6vfSd15PhB6LajEbeTBoJmk"
    "mGgNuNAgzcNx+ouPI5bURPM9+8ENoJAAgBrZAjAkCEMUUUUUUUUUUUdw1AA6gBgAwAYqjsYXLkcR"
    "kYxjGMYxjGMYzrtq3NxijFGMYxijFGI0UUaKNFFFFFGijRRsRdfWAAAAAAAAAAAAAAAGquERERER"
    "AQEBC2qEREREREREREQEBEREBAQgXOc5VblVLRES2qWoixERqtnjXdvMvYd7ePz5t4Z8lkbSeEdR"
    "KEVGDHV6oYHjnDy5NIuo3KjdPUJvifNGvBLAOau7ZS+tXL1fRKntsoZ+x9+Tx5Httrlt48ID8YVx"
    "8HldO7XkeiAAMIAAEJycAAAAAAOVbWb+9C7cL5mHn19fZiHSeJe9eHdpaYvedN2+IV0PN6jfI08i"
    "7UUNVPeT+eDqZSdODcJbKMUWnawb+8twQKRQ0IO6qL1hsPHMuKDq8KwGGOoN2lJJJJJJJCAAALqt"
    "q11W1a6uoAACgAGF1WrXtnjXjS/MbHEzOwSUs2i7d7E9sa1rI+Ywdmtn9ku0Rs2198ocn1tDa46r"
    "Ym3x+63hnTs8O/W2NrBLRghduufBm2+hOvh7VaUUJsCm3syu22UG+dWrQ9+yc4rZw1csa3EnSTOn"
    "m7E2Zot7tGaV1bWbMUmmZq3sOwf1Q5zXhvWlhsdhX05XcreBuZnjT34GIqiDw6zyNW3lVr71nrio"
    "UUw5tDlwHDWUKyHYZXCbYW8yJ11wd2/f37Pst261qZXHzsKhbL2yNuk0iQmZCZsJe3XRBjpJzynx"
    "1KczwlzMGwM2pJDwiIShYe45M0PWU5s23cQKwLL6Hbecw6jpOjTl5qunUR8Dr/ynvUU8oxCArIps"
    "zWSzNSasVoti2UQK8tlKQ+9+FESzdYiPNFhFAuC0orDVLlstrX8mTMFhggVJiiFcT6dlu21oom2Z"
    "ig6CWmW6zIZLma7T1/h73n7cdPVvtbxLeotsfdwp+OAfafuq0cH8AhSiP6kgClEL4CF09TUOcVSy"
    "/5QdJrN8h8J2C8u0mgNWX2ObnkGBlVH/kKQENEVQfX27W3r9Lm9P5r0u5F2dLqvf/lAAOVVzgABy"
    "qucAAOVVzgAAAAFuWtXaunOnZ1U3YpvVum7nXvM2keIRALkDZob7yQgaoTFoszWaxGBGnQ1BYAC5"
    "AUTUgDBEz0043BTBrOjQqCn6L00+S7xeQE5JCDIOCcIoulD3NN1lfoiEJhRPr7idZvN51HWdRDrt"
    "azw3EAB6aNgRNqDdoJQdkqGJmW2Gi43qKLkRMVoZCCO2Ko7clETURwfajgLl7mVb0CxAFAozIqqG"
    "0LNRS5W2H1RDDAAkOBk/WO+miOB3F3H5v6REZZPyx6veREr98658HeK7HQe8w3QPlUtREoAj7Y6r"
    "i5u7XwjURvskLNywcLjH1UlkUTBSiAqSgHhQpxsYAGPtwEj8M7ICURH37Pi3fM+x0fjewHk8NB9b"
    "X9dhrxYfY9u49/cuPlj5G/Z2k1mvVVaqj3HD7I8oco8oGwO+qA50m7D3WDVBynvlonzxOnad9SVc"
    "CKqj//5zkrpTb29cs9S48DjQUey2znFupdejpBrjVUZUZYRZtr8zD6bG1NF3dJ0J0Jhb2+t3OkPt"
    "+9IzR3oaI84YdaIbRtEkC9th78ECAp6Hw8dCHNQg5wMjJpqa9M5C/OucMj0xqBvim6O2cJO/KuNI"
    "mtVBL6Lb4bFonPcjCsoGDgmuQXjCQyQoJCBh6K1cO2FsvgOsBhEgkYJFYwgG/kNn/JcCoASJEXjV"
    "PRj7uF3VZET1+Grp9jDSiahCHALtyxk1QsHlLO9MikG2qyFl7xnVowkcYjQEg/aHNOU0G/kYgE+c"
    "EjIkgL+ZJTz/VikD+VjEB0FgoCMhRIVCg7MgfMyYkOxi6hECAj+AQkzUMhmD2/EA95rW/H3waKAy"
    "9T7tm/MRR6pySAkti38qvv/csKKvOEqNQ3Fhm9t+2swZTswQgaDYC6q5hBTfuUBEkTTGSQkShI3Q"
    "uPspdG71U7YGrFPf0YFbUi9/uREuiJYXq5/rqEm5/X733fFcgX4+ZBo5rj9wPKl0B71yUFiHWqEB"
    "sUq7wGrSUSemF/f9cLFrqegI+E5Hq4/Qe90ltDu17tOXRRjwAJ6RBP5aG1/JYqNq2euk/Zt1Yxlh"
    "7+bDp0TbKmIU68KLsnDx+RMLXrd7wOnG34I/igf8gNH9qNKtDvIhxp4Wr/q1g+djG4tYPxnFFfvh"
    "RvAH12IE7yusBu2SIBCGn38558HQGQmLUQ9ru70sei4QiRhJEFJBETjsH6ND3/yE0CJ9Q4RRP7Lz"
    "50x7fomNTfhJJ6PzTKHd4gNVg8UPmR/kA9oTB0CehEyE5MwDhSIUJ+xQPJEawmSMfKqGJSrLKuhM"
    "9f+GpOOTaBgi/OAkDMI9vDEZGmDEixkQPZB8R+F+zm1oga+abD0IpZBozfcT1sN8qeypJJJJIAAA"
    "AAAAAAAAAAAAAAAAAAAAAAA9Dv4AAAAAAAAAAAAAAAGgAAAAAAAAAA27Vu+vn1fGNa02tao6joQA"
    "+WBvLjwYBR6fOFrLH8ZvvhBhjhg9ksQPeJ9B9RvL6jtAf0pFbepUPI6Nb2eW4M8E/MsJ3HmG9Hre"
    "V7Ac5PAzLCNJ9UO1sEqBN2OywWtmFj0+n01VTJuH0PBofqdSUaE+kJctViQvtGG8oL/JdBOFtISy"
    "UWhwTSVC9uVPS7ZvNjgbAcWbo/bYrhhzAIB4Ej3GW1QdCTxtLFp2o2D2uYTqtmqyJT0J1Jlskh4c"
    "T2yuaoVAJOGSClC2RohCpTdPkGDQh6MIO5E0HSMjI5WE0N7YaGmIeMDhg8zRDn2eIeRqdI+pET+x"
    "KSGlhdD8o3RNkMeHgOGk4FXZxKsAIQXVx4mqGCCTPrrh7qfc1Xyu2RFvh5vRPVJIkQ35K7y6Bp4k"
    "6YbScz5PQWxCxPIVJaeTPVVcp8aKcgB9ar+UL2PycQeFzhDbx/Z+tuav5ekosmk67Twl7y/P3YFx"
    "efvopHzCzepKMqsXrfQUZwJDQN8qFbbVDTjhde9Ke6qxORB9hXYJ5k2flE+6neLgKuThDpHvVcNh"
    "IHpB1ID5y7whYlEnUWty3UyTiDPNHNNSnhTIuQ66Bs3LlBSa0fYqYgBoqwNZnoaL+p9kZCQhOLIw"
    "s+02EGQz79pRxeKcp7J+UwZyE+3zn1V6bj0oidn5Ps8PN3m90hGUdyQjyt9VFsJFvHxUgdeAnvpZ"
    "VwXLblU2le5LesvCQCzj6qmEpj0DoNsXqFnUGF7E/89TgkgDpgeY+wfNbE5DiE8/doOlV6j2jwBY"
    "zPrhzvVjvqF/Zl76xaPqSwVZH2KhqLc+SAd9jUnKqK+i1Q8Zi30HQ7UwtCwTaIHEd3NKRuHwSB+5"
    "pjCHD7bAeH7PX9ma4QPHFi5GHdKbJBogvnPEIQND3l9UB4GemwNhNKjiC4rjcgbmwjOFb/t9Hyf1"
    "bdPh/D9P6Pg8nyz4v8j9e2JD6cSMV/QJxr2ifZBw/ccl/X7VAUzTTpo5QY+WDnA3Q9xkpZskbUe7"
    "C7wp1eTz5t5/xzp+EMem24RL6t9L7xsEN/Akpwx/X6MdlVWA/qhlcwSSJNclviT6Nt9B4N3bV37S"
    "qVeHFMoooooo/dm4xjGMYzq2rc3GKMUYoxijRRoo0Udd5k8CNweAsnaNJTu7pTcXFfrFsfM+4q5B"
    "eBcYEVD5QPfMsg2R1wIQdWi0lWqfTdJ8i+poLibDtDwSUdaD7IhIj+b7NNnqtJe177gvVR8zH4hu"
    "qAZI0GhCqAGuM4sQFgHs+M6gd4ebrJzfePEIEbl+ugJWPnNFXaFkfFLwwG+BXt6+ye+h8yR+D8YZ"
    "KJ++fFfhz1HgL5RBPXSqC4UzCejtiMYiL7V20q+jvNiHoPtEgh9QmOghJ84fsDrdHtnZ5hgHQwAo"
    "Df4JPXSEJIU3Fuh5PzEX8pEcIYHkdSxKeh3Krsu3rxZpgY7fo0CcteJqqKgoqHHcVnW1AN7yE0hp"
    "4DaQDBs7XBF7BtAP5GR1E3Go8OJTxNoomQXTXCOuUFVQSDRVAdyzZCRaLmv3t/blfFrXL4GYs2SP"
    "EiKXIC1rRYu7OV3esqmNhIDoBIy4M3ompCiHfBZ0AhJVMEQi5cSXNOiWNgZkMRCtLQ7jQIgcuh2Z"
    "ae6dBoKTrnb646eBCeRfYaky1CLHqCKH2Fjf0gHUC9HGS8FTiNhRojxs0gb4YBHZzic+dkU1C9gO"
    "QYAZCJzOjJ2zr83VbbaWi1LW2lraWjW22lo229xA8Zw6Dp7jlNOb3Tou1hwHYEHCHgCPVFtohwCD"
    "UQ8wXIrXiDURNgcgDiUMaGQgQCVpaay8OCTI4G9OlXe9pwAN7wTot3FNcLaMjsHwPVlZBMmAzIMa"
    "+oQkkhJCiAcKmLIAr7RQTMrYVFKnYb7B6wHHl7fgB4c5EtAYLQCut362br7OMYogcQLTLYxhy9Wc"
    "S7ywyCgHAlmYMyDljziIZIVJq0EDKGcsWZJWmohBJSfNDiKiai3QBEopAYR3oAaJwiOsezCSSQAw"
    "vF3OAAAQAABAAAHS7u8+87eJbzXculxde5iyWDi5+5IZocu+A6h3wcuQNgc6vfiayE2iNZyZJz1q"
    "6oi7B8UQYgxERsFsrAwClVgUHMOPKAs7/y5hX4W+28/LDDE1ASn7BinDX8a4HRAnuQ8oKTyalAPP"
    "BTJVjZmlaqWlssrTaUlNpWlc5uLJplKUoa5+1OorpAO5JBIOSAMAKABCD6g/GKW2idk/n8Ff6TJK"
    "od5HuwB8u+eEDisPHwcIZ73cF3XEyqv5Cqk0AE5D1ahAiQIEBgxB2EKG8xMBpBy6VDLIE4uF7DmO"
    "+hjIchhxxkFRSaRvE841ypBzDAVDsdi8tMjEbltu0QUPi+IhCugThpkq86bzrCwhDxzCzyDEVEsD"
    "WH4tjuyi7QOfchEvVBEFTTfewnnEerqGHEEOudhg6y13miIUtLyIn/EI1fE0HIwlD9cCKRDiJ0C5"
    "Bo7xOzjztyA1KgayIP6U1YMD2dJqWxa7iIFr6F5JYzCm4xXwTrH5aDMOcUxswLotIwKkjUSKONfJ"
    "LDIgR7UkU4YcMsRCJ+CJfESI2DcECgfkCn2WZEFB9LNoELEawRBwfNkIJQxZyOeuioQhYLqGYokm"
    "RqTwsoXRLlgLMI2Q1foM0N/w9YDgLjJ8qQiyQXa9t5NyoOqIOVCaohBjW89JlmcEOjcHL/rijCNy"
    "3+xoMp3m13nx1QvHeAqXNWdB2s7AxZOHWHakAmF0SFedHpLYAxESKpOVh1xmolKFkK6CKPPuS2Qx"
    "QJ/GZ3L/oS/jDQMCUBCA5eNVT2SoQMSHgh+1lRjyeeGwPxv0MJxN7NA7asC0v6NodKQDEDptFBSD"
    "AaMoqixKnzpPWdnW3HPrCGxGRAdyKoCaJJrkv1Fnj6mspqozeVws2dDue3WeAsaC+c7UwEkHCVbq"
    "/1E3np0N7fcNW3VRcL00MOKIeXnFB2D8SYDt/O1Ub8Y9DyOQEvSfJYpFiGJENVgtLmYjFGhNazNG"
    "LlFhSmGC3LcjmXLUyUSkojkzDVbEzCJlFFLLISFjRymQyYh9fDifYRRRyAaN02VWFKTcAgGSwECM"
    "RZJZpQMM96CboPdbbbUk1liUMY8pZdB2CqawpTYgQB39oiZvDYJvRqL4zHMxFIK8tnPRj+KrYS7A"
    "z5TTWLqfNDmkhqENhau82Bb6bpjvE/TvyXdNYOZqA4MlEIWQDffffqVo+FwMULadHq0s5Dl9wy20"
    "8Zq591ht7mwq3c7JGR8mfjzy9hZAkgMQiQWHqTThpKwl6WCwTkByWailJSnRgGQTgs0DAgxfS0Ew"
    "my2B82RpOiPp0nPtMNFoM6S7YE2RPAgHhi28oLNbi7DCSErgtrJgRe2oDvRoWjSZDxLBkTuKIYoa"
    "cH1MZW582s9yo1f2hbXGu843EjaWTo7xnUAbwA5bO4lXRk65DM23EIJXv71gIc0XfkA5uxkDM3Vg"
    "MBkR1dhotVrp186pQAAAAAwAgAAAAEARznZOXSuvr7XWjVq0AAAAAAFAAAAqooqqmbHPl3eaHYHT"
    "OgeUc6QOrp3y9MqGuHV14aFA6hhlKdCXqFemBMJNiYWLG6hDeNim6mrMipISARisYg0UOmW1OoTG"
    "vgLKjRIrGVVMYrBikIwCBqlASST1qCeOR4+keVoZjpDrarT+U/kYl+Q3GyoQl0JtDEIqluT0brZR"
    "3b6aZsJFW/CXFUEIQVs5BcFkwsacIB4d3k476J4E3iByouKm9iGhZBQa32G3GLQF9aApuIJO8KT7"
    "zcCHZgeUIcjZi13981TpEHx6A32T27cw4cNYbRgsGgHlfbYSohN40oSHQZA7U9CDNAzchVHrMrpf"
    "4ztRCs/Oia+rQLRYVROd7S3dzC5whtxS6ImxQTcWkuEYDcvxhoMkLh5BXIXAGlW+FwRMTCsdmDgc"
    "D6iAQFgokQECIHJLIeciOoeoYwJrO95mLcexU14iUAk6FTflJSf1mFuWu+Czw9Vq5eN4KIfUwVdu"
    "LX0xi9TGdmoY6EHJt4u5LBptB++CT+JaFhLoWHQ1XuIHYfgbNaFBALwQ83m/C865ep8HyNtteXaN"
    "b0/Lu75gAAAAAAAAAAwAASkkkkkkkkkkkkkkSYkkkiPP8rzLvVqEELxZT2GGoEQ72Qvt6zb2gPpA"
    "1+8egyMgO4+aSBsKDrS5uunV/A7IRBU/IdKAHEABPV2BA6gEthoBRCO7Yq0W6ApAPD65ERKfXGT+"
    "2GnIrmn23uXQtT8Vi/UBPRTXnhRagbgTB17i3Nc0RET4Kwm9AuBCQECDBQhAUCKQeFAN3nOQFrpd"
    "LeHvKWRRRiNMpK9k4kjpA3DG0LBJRBSEW8M7iiUbzWvqirrDh9+1ugL68dQTYOw3bAL17h+TXrwh"
    "0nii0PNcVV2CazzX82beUS6x3ZB4wkgG4fP4YwQm84GfaaQLNqQpAMJUuL2QTWu96Gr0nMZTbnMB"
    "K5cTSGpD2WPASQkQgNrWLMFFJdWCqlRBSAbT0xLL85elolsZCUBE/NCRQrGmWUKxrdfc7TaNUVU9"
    "VU4HvX9FwupgSbPg5+hYCAJqUAigUVQEMyBCAXHpiW9+6g7keIIgnliokiJQeZU8Acl1wdQGwIkC"
    "AMUo5iQIu9EHTXbdu+k2ZuyzI5/GvuI+8jUD1kCiSMkYWqTX92tEXo2cBttIKKVSFRTmsEZFJFVg"
    "fONcRIB+d4FYg2zaQK2AGuHNvXfs/jDeKXTxiH6eih4ZKu5dU7T5/EU6YaHc1Khd6xUUMpEiHfZk"
    "tAvkbwaBoLHCliDjY73Ncbi2vdxNXvVKbcRquZspBgedsPjpdrYzagOXAFBiyGOMMqovFLQ9yrAj"
    "ha2IfLQGsAnMTogqW0avRaq8h2+l7RKGUiimuLrcxwN7cAJ6ykZdEGxfCLjQZkos7vPkYsFEUIEC"
    "rciVsCcU0NULeKYj0bt+FW4cgjAyge6N9ECgNgiPbwD1nq6Q7eJ6y45KXmgUSsOr3KSzkFgaGCM/"
    "GDfAgQoiikDRY9gQA3a2h9n/2wWH6d62HPKmjzxESuFIVExRmO2KSL1+HTMqZsKG4KJqasyOqWaa"
    "wdK0NVSwvLDbzbcj9yW6F0PFNCEj57phCGrdQSSAGRMeXojTa5vJS5KISBQ+oOWQntIP7sGEO+QA"
    "gIpFAdnhUDemnStjEHP9XCUb8kzh7Q/sov00vSgendsoqn4WO13zHClrJaJVGCyWy8gMLcoW12xd"
    "06MF4EiokgHAbiWwC5EUQo2ERL1OjvW3fqMwzjAIMkIxN0d65ByI+dETYqFEBPkKIh8le1cHKeYo"
    "EuUhBiSJ2Ue1ICiQQ7C72K/jBWRUcrY5L0IdnRA5SQg2agcloCAKlw7VSgBLnv7NJnLMWQh8kwaY"
    "9I7U1WX15DSwkqlPaueCJW6i5nw8uS8Eu2W7UPsYSyY8GFa7iQ9oNgPUnedRmUZFz59mu4zymEOI"
    "lwQK3HxGWVxDDNjDZ2ns35RmncO9newSyltvIpAWCCkTgOWCCa8U0nTWbK7vAFhvJugRJx7CrB2q"
    "JUYw66JKFhBeVHVDliukOYIFXhaps13vH8mKyZXOJXAUyuXOJC5yrgCSMNstGwWybFFNqWuvXTqq"
    "3ktaquzsRdHnzgmbwiBoGp8ibpWYVA0AHrI2KKbFvL6vdv8EQmN6jtUTgMwoYroCGXNNDYHZuFux"
    "2d88YG2YUqawdy1Xdji1mDRRxmJ0Ia1NXHVLNRLQvSzTM/dk7URUHTo0mp5CUivlZ1yoqaLhBBYm"
    "AI+4/MEIU3jZ1C4vb9D8EUVDy/Y9YmgVO+UPbF2WDTQmMxBsh3gwPwFV7iCt+QwKzFL0kWNxaheC"
    "dFJhUmgSqYqyBCN1DgmiWhzQBHBj0hmGWSeYQoyBRCCE09m1J5R249UFMn9DNVRBShuPIoFMyGWK"
    "jAi5w1KtIFCK2kxKVUgaAiQkWAALAdULIo7WwASEEiloIXGykotRdGwg3AY3iijg5sygdM/+hmOU"
    "50A6KrnYie3Lt2xLCvt/GARiAjCKe8iqDuNpTlBQZ8uwuK9BOIkidECoJNwKGm0ftRD92zd0IsgR"
    "IkVQuvvvZAtSBQnwSAEGSB0eKdheOVhFizEUp5i1xIIByYUBkHNx0lGpEuhJERIpAUTXgDIG6ALe"
    "MgZ7vpFDjxNvQcNvzaO62C1EmwuvzWLO6Bf3IJzo7O63yy0u2LFTIc4yChxdexIB+L3KYx1THrtu"
    "ppyQ0XWmPb1nDDy7VIrevvCqV1MAVNZGoDq9FWNHDoPeFw2gCBBVO5bCG7Y6L8HWc9wj8APEXTsz"
    "W/m7hwd5NG7A7QwiEyUDTAA4IHPFHoSdwqSnpuZZKgxFgIM9nnMOwnlKYyzKDIEiGoiGRce1B2nH"
    "QimrBKSiSDCCrsTeCtwMoXwaFgOwUOnVUjRq1uRtCgkR17jQNWSqm5DD0xKAwRdWgxEXvQ1iHAMB"
    "yHXuOQhShDBHmh8GDJ5UYWUde6Re3Eu/dePgm+XAEOruAeIELA3ICd330+EFOrU2WQkSRJaABRHf"
    "SvAL1eKaMDhmBloXIsmBW1m5wZEiDmZkDyXGLhJClRtqRDytRYiGPynWIiIjAvDiSb5KCLTrVhrU"
    "F1xNAQmTQMoyiXSSIwCsHLLW3FCrIsYTB5DsHVDpN4EDpDqLxtGQIGCQBivX0qqBo0GkoQwDGRIx"
    "Im+mSipgEIgKkZboLSp+FzhCrYSIPud5AkRdQ+gvhzEyQ2Ha0H2fvp8CL3baBRcFVTzvntVTp7fZ"
    "JhzNJk6g8cDhv73LEqVg2lbmWtXMzW0JjOR6w/MyRTYFggeFgAaXVtLfG2hSrWIQ3JHTZyI6A2gp"
    "tKFBHv3no8EDvvdJwD2ztn4Wbc+kObCMVLSjPUUKWMSJKCyEJJ0PuUJZeFVd9CK8A7Gmx3CFoRIL"
    "leoQP4woIt2SHWgqJg82orAgqYTBgx8Xio3X0qZhqj9OOy3awobS3hCsLynAReqnwI9uj2S9g4SN"
    "g96bGWiicoBxCsUs63fx94Uq2U6znYSdyNK6VMbC25ix1sM2ZWAQSYUHiDtmweTimDoMwGFIhmTD"
    "bIfVaITptkOYq+j4uw21DEQzGnDBatKiC17bkRcqcVtLw02dUbsWBJMkCNzVLAzaXBy5YAQUUK02"
    "MBBDDa1khqQQSKADMglORaXF3KzdswEjSDKomoZ2LNZzZEDKuiyApEC5RacobsDCiQFUA4RjrWCC"
    "KiwO3u4Ni7kwSEhAjHjuKtJIwCETPPNPDPaYR6k8qJCvIiFMK+4vZ3mDgPVsjXZi+zGAMEVU52tO"
    "uqCMgHOGt1w4lBCSqjIvNGoTETGewgGgBTSpqIqCGAGLoy8DQV1xMdDuwWmYbabQnwuOtb9iYEPi"
    "mcChhmWFnnDWW1S24nAtX5t/+f/tBtDcCvjpxdRjwmsmsbXXKncmQkFARjC0P9fxod9TbFDcCxA4"
    "cdDM043hxYpJiodEE2sUjEBLrK3KsKIgQ0uI6mB6YKZuvBj3KhUGRqv2fnrAQzxUJ+eBr6Ootx3x"
    "6ePpe0empM0GZmYWiNYveJpq9ZPcmwi4wanmjzC62YiW4C7gsd96iG2H11n9YIkuSQIHQmQQRSwR"
    "QaA+X1ie7djx+vNNxAkItwr2kAa4JQDHOJnaxIWRg2QWEZRpBJNzdVDae/tsRQNtrFmAyKGxkxND"
    "rbVi6ikG2ZtoyQgDccwoUuUFHu7jysVMnNqoYsAhqwmowhrzoCGlVEkQkaqnGvXqLo4IjYlBDCLT"
    "CMYS8M+oPLiYzAHIJm3FOd9ct5qcTgDt0NMS5opROF0mGb3pNO4GMCiZMDGUc9mdkzg4FFLCBMoQ"
    "QrSoGK3JwJm1kYZBgZEAdoIIgYlikKtAcNmEkcsEBsJqcGA0CaGEMxpgQsrS2HagltbC5QY1in+B"
    "0oMKhgOpKfoYF5RQCQUSImqDghlRAsIGY22UYAhk5VFXt8JAPXqeskg0Dl+rUhJxtr+huYiXgNxg"
    "cOmIUZ4tBsY+o32pbqqYt7dqqFGnSo1YSZ0fhyp5Yh4+9S8MbwqvFmHYdaIhr2lgNRjesXJU89LS"
    "AE6UMl7xDXnthaBeNiNXq0C0Ihe4XuxZtcKtZUF49YKFx0LSTZltLSxYIwUo0ZUUog8hthYAj54N"
    "t6ZGkCEpXb5GJH5Y+4ASQRTLBXK40msTtCwRhh1X0TZP4+MPmthMDT7EDUEBCuhVoQwqCJyVDxib"
    "4KSIHJv0glMUBh1GQDB08WQgXBDYOCE+NdkOUaIHdBNPLzYeqXhO1qQqQY/okCNSBCRPN5zv9wU3"
    "e72xd6BNwib4pYJaFACIRkEQz/BsIJ+pE+gipBgOaIdxvD9vlR+bqTl7bySWZZdxxTXDj8Y+y38I"
    "3nVJEAvgJICkCpOKWPUacl5PhXrq4fu7R8C6fd5/abgu7lDIemBejAgXP540ZbIUUf0PKUEhuEdM"
    "XjHmyZDu1JAoI06JStlnfqNQ5axf155nVmntO8Pbr9mAqfNW7jVJ/DK4LoEm5QTozRmtwYifdElB"
    "Uj6WnkH+bpXdMY4X/nXpUudEInlRkiXlIcAirjm3qAWDWJw1ziCpLDBb3ylkbRCHRRh4rlsEIEgR"
    "DmM6A9u6lKOmiCI50GFXkon4E1kJHkEkhOiJ3BE7KoIXLMI/5/VibxCExcIwSYQ1jFSyZoED870g"
    "gADZrOqYkkm61BokYDgJSQKMoqNylR2iUwskOlmsKSBUDp+bxEJA9xA3k0YieuIkiI2shkaNYKcZ"
    "TQ/WIjBEbAg+2Cr5oj6D4/MiJiJ6TvK48sd6CIn5joHTIIYr3wtGQUkLWQD0j+lsA3w/7vwBs04F"
    "rgRNK4DyoiV8xH5/ixBotVQwMERP/xdyRThQkAAYWz0="
)

# ── Extract + compile ────────────────────────────────────────────────────
_BUILD = Path(__file__).resolve().parent.parent / "build" / "inline_k7"
_BUILD.mkdir(parents=True, exist_ok=True)
_CU = _BUILD / "flash_attention.cu"
if not _CU.exists():
    _CU.write_bytes(bz2.decompress(base64.b64decode(
        "".join(_CUDA_B64.replace("\n", "").split()))))

_ext = load(
    name="fp16_k7_sm86",
    sources=[str(_CU)],
    extra_cuda_cflags=['-std=c++20', '--use_fast_math', '--expt-relaxed-constexpr', '-gencode', 'arch=compute_86,code=sm_86', '-O3', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__'],
    extra_cflags=["-O3"],
    build_directory=str(_BUILD),
    verbose=False,
)

# ── Config ───────────────────────────────────────────────────────────────
# Canonical config for K7 from the progression series
_CFG = get_kernel_progression_configs()[6]

# ── Public API ───────────────────────────────────────────────────────────
def forward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """FP16 flash attention. q/k/v: (B, N, H, D) float16."""
    out = torch.empty_like(q)
    _ext.forward(_CFG, q.contiguous(), k.contiguous(), v.contiguous(), out, False)
    return out

# ── Self-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    torch.manual_seed(0)
    B, N, H, D = 8, 1024, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v = torch.randn_like(q), torch.randn_like(q)

    ref = F.scaled_dot_product_attention(
        q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)
    ).transpose(1,2)
    out = forward(q, k, v)
    err = (out - ref).abs().max().item()
    status = "OK" if err < 0.05 else "FAIL"
    print(f"K7 [Auto-Tuning]  max|out-ref|={err:.4e}  {status}")

    # Latency
    for _ in range(10): forward(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200): forward(q, k, v)
    torch.cuda.synchronize()
    ms = (time.perf_counter()-t0)/200*1e3

    for _ in range(10):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    ref_ms = (time.perf_counter()-t0)/200*1e3

    print(f"  latency: {ms:.3f} ms  SDPA: {ref_ms:.3f} ms  rel: {ref_ms/ms*100:.1f}%")
