#!/usr/bin/env python3
"""
FP16 Flash Attention K17: Auto-Tuning (Simplified Headers)  — RTX 3060 SM86
Auto-generated by gen_inline.py from kernels/src_1-7_simplified

Run (WSL):
  cd /mnt/d/GITHUB/Mini-Attention
  LD_LIBRARY_PATH=/root/fa_env/lib/python3.12/site-packages/torch/lib \
    /root/fa_env/bin/python kernels/flash_attn/cuda/inline/fp16_k17_sm86.py
"""

import base64, bz2, os, sys, time
from pathlib import Path

os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")

import torch
import torch.nn.functional as F
from torch.utils.cpp_extension import load

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "py"))
from flash_helpers.kernel_configs import (
    DType, FlashForwardKernelConfig, get_kernel_progression_configs,
)

# ── Embedded CUDA source (bzip2 + base64) ────────────────────────────────
_CUDA_B64 = (
    "QlpoOTFBWSZTWY78ckMAIkn/9X///tz7////v+///7////5BABSAEAAIABAAYFM+956h7773om9j"
    "lc689XvN0ZRvOO6BnbVQQAA0NPQDIACT1Trpvlz72+2gKVz649wAPFEtdIveD47733vl3R7bXzLk"
    "Nzry71qOrbbCT4bFu3Sir3c726dvMOjvqN87NvH3e5Xpqa+eevas9qi7altezXWq20FiXABvDT3P"
    "vPnS8zczfPe97mnrVm7YztH2O883SfbnYVtpB4O1x7u7bb2Op1tprFswPd66te73dd7t4Aed12Nd"
    "92He61c7N3b73WFzqKVa3XDjucGmiEAARoABGgCMU9JjU0ZU8p5J+U2qaAeUDQ00B6nqBoGgJTQQ"
    "QQTSZAyIZJptAQE/VM1PSMmmEAM1A0BoNBoGgAEmkiRAQmCA0NEj1G0mm00maajaI2jU9IyNHlPU"
    "aADTIaAPUeoAk9VJJpFT/VT09Tap+qfko8U00bUxqADRoNBoNGgAAAAaAGmgAESU0BAI0noTTSMT"
    "TCmZU81MSaeU8kzRpPQ0QGQwQNGgBoaNAiRIJMIaTAmTQIxGjTVT/VPU8p6UyH+lQ8o9NQDQAAGm"
    "IAADyHeQEQ/HEUQPN75+qBJIEILH5P+LgubdS3EDZr+NcbfvNx/g+Yrx0q7ZUSi21BtKMnTn0fs/"
    "1B5zxz+H6+urq6XxczMfzJ0Zp95Dn1sigy8O37Gr8KbVHn387qHR3IsFpiTBMwJCQLr+8sN+D5o6"
    "uxV/r/pRPbumGct+R/6lHA3szgDzGM50oOkoMlTqYVhrVihDpxK6ayZeT+Yq6sVYULTTmWQkJE2E"
    "mtFwlKRq/u1iC46Eg0F9j7L/l7nP1rvTN1vpxpoYXLaB34TJDudTp5TWTNIpTsYXJXk73chc8RGj"
    "s/ekmwiEbCc2j8IB5pKl8xdoWvHkmJU/NT1vWcxo0q/pKanYmCCEn4RuSBtz52f8FtliYKCY1mjW"
    "PbXPy6prhy7JtzqX15OmyTW0kxBqaeWkSd60BISB81jWgucBcUMNu7CF5fH8mdF5Q5LumAzFyyh2"
    "/PwnX1Un5k4fjLWL8XUWdlO/w72Gq4mZJjVX4M6CXIT8cncSSlZPXo9NXCcdX+eXoO0309TZ1amD"
    "nIM1e3/b5zWta1rWta1rWta1rWta1rWta1rY1rWta1tvfOIKQ7rwHyPJOaTqZnjs2k/aA9w7uDQZ"
    "H0Q7dIb8UjpkIQJdbu3bkvF6aIFwRQminAmuJTbMwXaYVrU8w8xW1gc6X3YyPw4AVAkcI6fqoE9Q"
    "ejfuyk8Hd8N36cX3LoeM9BZ3azaFg2mcdqEEghCpUDiSMQJ5VHTOJsoZ7B28+G82ei8usvn+Kz2t"
    "8ViTuiKl/f9jDTI3zWdnXzvL21Ns6Pg76N0Ro7RmXWZ1LaTbq9rW6Mj5pTbn1Xv8ei5ZzlxWfhB2"
    "Mw0Spdt4dt5cjx/GwdaAJbkmMhKhxqsk8+7Hu+rrMaULrC44tBwOzWYJQ5O8Pq0nN43bui0t8V+p"
    "p2lFWxPB+V6gdq7EX/s9HJmYxpyUeiOZENKOaqGTsOwbIou85WFNGEsiNrfc5WGcuV7/lESCRIQJ"
    "KBlBJCwKIK9dlANsEGRJA/P3+WfPvwUHuRXtGCqGcFBuiqWPzd/bWBCIAoKSQQhJP6Iov0kdXl/V"
    "CIDOkswP+XC6SkPm3+toar3u/Tf09AKloSBISGUQRDhz/33nNv06NQAocjq5rwjhmkDaxUDljlAy"
    "iZUdWmAE5HMpOYgBIJpEoiVJ7Puv8M8vGmvPjBr0c3yfQeMMbP2OvjzDS3hPJ8J64sdn5awBhDCQ"
    "I7iLDjKdA7csCzVxXUSz0e7ZjG6jnxlYFwym8vl8sBtESO5J3JvWm2Nn71xX01c1Z7Ig+xiDx3w5"
    "0fOxyT1kkX2UKkFIKKsUhWFI7/kW8ylFIehTAhGIHs9C5R51G3/FbxZ13ddSp2vgycG0D1S8wtCb"
    "h7MJA4NkChCCgAatfRQrwQAUppdxo5TgRX6Tmnvnm5mSBDOJkIccZCMeT6J+Nu+PN8O5/5egU3Ci"
    "d9fl6aLZA4aLfhAGTdw6M36Oj2/J4TxrrXZ6te+INa7hNzyAx1VnvFnqhsLHOcsMwp92xZm0M/0w"
    "LFcd36bvkzlrd8k+c6YMGctZrfJ1GtNXiwawbWv2/EOLZ/q0s8PBG4zB+n12Nzh7mkfjW0HS5joU"
    "VaI6EkXLjslhbdNA8R665nSrIPoKyB4O+2Odyv5lr3+M1cgHNjhfM8DYlk/IBECn+Y5Bmmp/AT0W"
    "KoO14m4jOgh9Ivx3xh3uX5UnoLQ3k/REwiQ1aATAgQcsFxSWvoUoqjMEUeLdl9I8JPIkma42zJsj"
    "To2bohUKpEHJn8AETaMxhSBYMW38IoAjLe8hSyXXdqBAg86QEc9k6CWvqjkk5tOvRvyiFVLEEFNn"
    "pJj9sns0245BR06KBOJ8mv4/Xg9W7ovuF/mAw9Po8/yfHLzUAffHzgIyIpAgCQKhIqFjXH9p/Xhf"
    "87W6XaX45+9+jXWbmACl/Ns+Cz26ZwhsMnabS4uPLbeIWxA2h9tz1f+bcUbLOBKzphgGMvsiRozT"
    "ADTEWvxZ+dwAAjx35d2YswAMJ9A6IWPqcvyXtfHDFMvZ+A9j1BR1eLyTjzW+WD4fzahZafEUes8p"
    "dmg7UkgX5jj4miZE7nUMnOyzp3fCyxcoQJXKiAJNiC6xE2HR8tr/j3jp9LXAO/caJcN8LrfJIcgH"
    "S9venWdB5QO4e839J8NaO+ww8Rm9XhfHiEjNGjJ4eIc52bxEYYBSXjAsHAEUgjJNq1UY0ziebNL1"
    "JNE1dRX6+iVuaacHFu5bsSJXKUErI07JSASB6kM9ZQOOEVbvJHjkUUeUfViqod8998kEFBjdeQmF"
    "tvVDCIJwUbQgEiZoCzoeECRpN+SZkrBl+zzp6PWxPXDF7jujKnYwyf7zMGNgU4RuDIpA9qesRTVN"
    "MppIpOWRYpfmnpMHKQWMUzoSw8o78J3wMHuldK1tdAeZluGOvjPH11vptxn1+R5ZcCw7QLXgcg3C"
    "4c5Sep/UVzorPEbW24T6sMxW2r7jaRHgbriM4YeZtiy46rDQLKBe1ScsTp6KtxhTHGb62bK1F6aq"
    "JUYufxa7oTGS7lSDfRT4GnEtJpl+p+bBIb+Xh3AWvSuYXjy+pckQQTobQc/NRYNWhlRRxTRjpDPE"
    "Q6hy3hfHnp9JfHnidMkIJrjVj83m43uKEvQa6KwwohY8ORGM7KxUqVcK17vLvY7E0b+3zr2PtrW+"
    "3gc2U6lQbD9oQQysnejEDAGzPhOHOTNVHR0z3JHmVpfcrB71WMH8yyD5nSXRQ7LXgGlYjaHmw12i"
    "x6ZJ8Ggud56fmjjg6RbjMNv1DeBmWNlr2+jmFWwZsSg6J+tbXXv7aTL5+1LcGosdjRaaaGdqH59e"
    "+h4yyuCBYE3qFMGRFixQHX1vqkebdJ/vB3xW2WNGOUbMOxOvKu4ahh3cL3cx2vGjyzG6FiAdgTNe"
    "rM4FWMRZEBKAkgkDRDFjgBCIxAAmkR2Uz6OeNs7WNMk2iIXVWRwiNYcLlAyWvlIdPe5ylxCXA65F"
    "Yw8p0v5jXYlAilTcQpokVVVdAvVCCPmWVhnnQcLJPT24oZHhQQD9AOoO1Mu7Ko1AebRK5d64zhsg"
    "EOdzjBCHx+Ol45fTfFYki+dBbcmD1AzlYYGM10fT2CezsskGDxJY2tn74GjB2eBj9WbW0IySO+Sl"
    "uYahlayCV4TZLhdlaEKogRqempAgQTJjMxa/zwnvriAxvqNoyZQwQRV6sbqiLM2wR3WQlhKI3IkI"
    "TYfLtW0PmuWgFsy072hjOOLB0WtwcRgv435UbQW5yKMFUAleZUUmdzMypNb0qlrZb4EnVGKho8AE"
    "nAGDCllezAMPKeijphQKZUFK6dD+aRhzkpkvtE9vMOvDD9l9EQUeulkhk6LnU27onOcuRvk50KIU"
    "EM8Nd/MWjM4X9S2u1ZEHVe4IN0BpTqmvf2hAnOiIGKAB0e87A1oqDQlqOVJXRjKex7wEw7O3hUiY"
    "Gv6VfMBolQnBNOKJNTcY+rr6UiQbpPOCJncKdW26XTIBGBWlQ3bICB8H5/1q4j6hKlgyUzSaHJvk"
    "yNuX3lw5pxCQ4nyW1x878nJl3RJLA0LN28J3KsURqD49PLRNIH+D5QRVl96Vzm/9bCaoLEqoXmcW"
    "OurlxAO723VY9eUipOEKQU+Xx5ht7+p7/Cvf5qxII+QOQCuRWq9eNa09RE2ALwveb0RRPH9aJFdb"
    "ao8zCB1ucXO80Sjpfi5g5gDgPF83e9Py8JpqBlzXZJ8MJLI6rPdkymWAbRMoco03jrB5w1wneq9X"
    "rKOEBl6Gc6xmnmtL17+Z+sYWNlLz9GaQXTQzLkcc4lZ86BZpMvTFVesQimIyXPkgQJba/CbnMSD4"
    "Gccd9S/N/k1O4jA3plXbAabY4PjhaoUPn1iPJtj+bqhVMgmQzA49i64NF+xE6MGdndeOWE1OMtGL"
    "6Y3iQFAKbItUnLRDHoj5/RxBGZKhYFLVAMiMCQjbKCFsi0pGNO5GXJfoZKBkGwVVUoQgUqCEZQsA"
    "5BsEPYhlx15ExLf4HfxhTLCpR3SQ67MkS9Blmqmw0x64ls7m8sGHpBQOCZQSCkNU9RvJetJ0x6ur"
    "jss13yT80VAuAuuWkOU6ow5Pke+9wicEFz0chBF+Syoh+Rp3OVRVwyQZ4gHaYr/XUj7BXMQYttSZ"
    "sxNUgsNQoyziwhq6Upzob6nY0mFlH5cEdia17PBezw4Bx4uEhgvdRezJtm11B8mKJhNNPQAppUWG"
    "SA6cxEk87gQ1dU8tj172oc4wd2LuYLCdbk+TGeeKqOevLYJB5YoliEbhJ9WdHik6igoIlNZpUBGq"
    "hfOmmPB0x3msF+gYJcL+PweHdu7DZ9Pa0N1b8JMECPFiIJx1l4+e9XoziRCW02t2KlsV4Ns4sxsz"
    "7vf206zrXXg8rbngWufr9eeNhBfMQqYWVYYbwxu6OHbHFgjWxdV408xJJJJJJJJJJJNGxnWGPXL5"
    "2Uu11UZXBsiqDqyKBgQKCOImiWgKBrQgkHMoeSRMR9k07UjoO2jKYq/CzJRsIsoG6Wirl3enFdxa"
    "WbPd0caa+vcQRuxASjZaAFAGsiY7iRBVoqvxRCQARBJDGhAcMvoE1nK6fLS9NpfFj91jnZXxx3rj"
    "F9TlseCBrU3KRUJNTtn2xFL4xkEolOdVCPSRheNOqqDxo0ZszLOFD9hjoHPyB7O1xDqjHSRsioD3"
    "m0LriMHSnZjcIIgeowJBmwR9y6VGaDKujS+IBw9YzVcHrThUuuQQO8Is1a0KNoskTc5oIS0E1eMQ"
    "aEBDlxwFsMhilvkD0tPhaOJbYgUAPLAaKWt6cUJ7dt9kpFNd/qpQzJpWzXa9LRisAotnnZGIXrk8"
    "TK7LRj4jNU69dfNUcCrTPtoDxTknt1QFp59FO3Cm8Vj8pz0RXVA3an0X8ROGLk9KaSuQVhVqbLsu"
    "yjXd6ZbzMhN0+E888W2CR0yJKYyxQ3u4HKK63Nb6cgzEJ7dT8L6XRmDHetZp9bduvsVJZWWG2KmF"
    "LoEux4IzW1q1txsSu4tGl8LFSXB+J0ayfZTNzpij3rT1cXUiAZo3tzusY+nokk0vG6hXE38zEHtp"
    "n4JwliBitaAmNfs1RRrmLELiltc4PqPhke2ffKBnmOSQ23zupjHpvMwTzqoISCCd3n04/byUbtXW"
    "QlAJWcqIwSYFJ5NFu1dNYEiP4yai7rqqcbA9zlx7d/GBhyHu6OnWsrwfLy5+jkH5wPGB5dxTugOC"
    "RjrRI/aBTYdA2EnUUDc+hQ5y5crP0resBODbEG3mbMYbzJLyZ1Cnk290U2gUiXAKS7o0b46aBBKQ"
    "gyAJtXUQlYHLLKzOL6DIaRSTrGD96Ukxge6AgEEIo58zcOesD9Q+UfqBFPZmXouIv+0s/E18VsZe"
    "qk9Ve/4cWWXxB0UZTOvIoc1eGA/eEkgTMeA62r2XMaUI/OAP0D+u4BBmAAt2hgJm3yVOxFIbFJ8O"
    "T/rw9OaebNetBGGelg7P9eV1mjwj/cd0S4BANY/p/SwZQupU/tc5SsD8RSVEUTyl9bKCBoQKHK/P"
    "1JCWbflz9lWNpNr6Jpbxwmy1mltaGpiaeWXDKPV6NfBcvlafC5vDb84nq6lnsYYYVU9y7D42Q5IH"
    "Hm2XGiPl7OlR98a9mTL1a8cke37jYHXFzHzsnu62hxJDsgpGXPa0288c5yW3dfLQ+Kg4K1hx0WZS"
    "yHdVyZkHioKYJ2xcCbcykBqigVugflknVOj4KF7ioJQPPqIHaA63Gq5RbnyaLZPjOx9rNmcjGlKi"
    "Ez8h/QAcoW/16bqYQbXCIZwOes+agj7Xnjr958gR1jCHPVBw3UvJCfH8+7ZkngeB32p2dD+iwN8M"
    "ZAAxCRZCiWh+rVlvMEcZO73wE74GwgC/WFRBliA3WQDskyPSjwnaOZSbxdIL4HeOqNOY5ek7CnVX"
    "Ec7gjGAIHgHeQqGPV8KwQaTTq5qCy69Csv2uEbn2uWJl35ZEg4CLlBEc60NVnSuRAyfw5pRkGdNk"
    "VNq6j7/msg7Vi37cM1xkMiPGlWb52zkXkWtR9Lu2OavkCK/PWK02Ybx8fs1zc1/Bejzxcrx7Oa/f"
    "POE1p/FUmzf9d3Wp5ZCBPlxUbIYoKCOCTdKcF2WEg8YuP36eo8EJoTSo243O2o6HuTsaCU1Y4Dr4"
    "j35z94kDrAvbikRp0pLyZEjNcnF/RHza6OR8VHxBF42cvMIdHJfS6SAQElKLRqyChIHMAh9DPnEQ"
    "1yCUE+LO5c+4OOOUQQQb98kkjlGomB5jYJbNSvqrMfY/s4xZtc7nGG+01QR16BAgpDeeEJnX0uwd"
    "10x2RRAbIqSz5uR2OKdg54j81Mvj542SQrnBz53HASVOhPbcBvfeds4jsHvXu7z1cuCw7yzoM3MP"
    "uT15qZYgMvBQBWnruUPkeoXlnoSV9lvA65fdNO2XG5xHsHDr03CkmB3F7e7veL7+B0c/Rfeqh4pI"
    "IXQD88UkJE+7EGQEN4wFoOs724sobBEvXoUEle/xtWuXXpAAAAABJClZaCCdX9Hu9f0eoqfB+On2"
    "sOn8IIkKdp4yerxwgZdsq0ri2jRNeWWOujQKLtAIb52Y9cHuUEkfP+rN6cY8p8CXtfPmvavvhcxU"
    "Q/tx19CchPyRpI50s5qx2TzrTyGC/QscDqP9zsPpmvdvp5BtToDQc3BLDebyHCjt1RE87w5AQ1BI"
    "AEAMwKQxTKKKKKKKKKKKKOeN2qrfEqs1WVWbbW+LvHtd68WMYxjGMYxjGMZ47atzcYoxRjGMYoxG"
    "ijFFGijRRRRRRoo2I0UXj3AAAAAgAAAAAAAAAA1VwiIiIiICAgIW1SIiIiIiIiIiIgICIiICEDEH"
    "NVuVUtERLapaiLERG2QIq2CnOOkVT4xL0hzrxVvBI0pEl5+/ZPq6fLbybn10PEGqA9QKBJgMcUef"
    "v6RpjpzATjLknE02oX5mE+SnZl8KXX8kPpqX2DWU4anyQ1cRi3K60CwcCSSSSSSSCSCCAAMLlzgA"
    "AAASSSSSSqAIguXxUzwpFHfycJx01AaaeesYbhsqTjslGhw8R7ZbxlelIzo9yjv8hAQGXENoizB4"
    "dzjzWCICAk5I/Xu2po3S2iReydiAxV+6ycAnkFMIoyWD1S19Mb9WteVev6sAACAAALrbVrrbVrl0"
    "ABhAAEkkkhggCDPzLrZpAOmQXDlBJr2whm7mKWjD7h4qQIKJAESPvdoFH5wZJDhV5AiWoH6AvHvS"
    "tkCLMQogqaNfsU8hYKNPcNaCEgghFhB77UzepYEa+cd4viWf5SGbbLFAvf9Xj+JfZe0eb2XCg2KL"
    "t0jUQvXk4M7ZCYxEczui19EF1LFIjreD3JE+VsThWwgL4g6WqSAL1Ui5yjbx46ZuAoI2r9qCMg5V"
    "QZ+tCVI63HEie8+MXjDtAoww3PsM9Xo458Aq+hsbiuREdx5jn4/FnvPK/TpJaoJqrveBhXhoGgRZ"
    "QSqkvexa91Z5o3Pj4gbbcOPH3944rhNrTsHTduYyDFZabofRrgyDueo8I81xhgQIwr9mgWBhjUBZ"
    "h8q85f0Ly5S422czabiGw37rJvkjR3z66CL60VtDFKtRUCmqZqlNUTNZNrFTUqsFUKajaKxa0b1f"
    "n2q/NmrGrGRNiCqMai3bn0La0tt1bWXX0urW4ra6QUvovDrcuc4EpEkAiiLNUlMpkyURZiFZPuZf"
    "9UNH4/7byvBm0GvQ4KMXnb+TMkxVQFzD4OC625Sr+To/31rE3yzWpWW3i0xJQl6c5u3Q9UilVGZw"
    "YlC+MPdx26zjeMo6tCbAkAg8jyDfx5pu8+f3e9PHlyx+0c4fH9b0y5KrpsAuyrj/qMiEKQR9SRBT"
    "CNxAUtPwNR8oqnkLIfLE2G090R9Yk4CPZ1NhHCc5+w2jabgWIQYLO59xDtIEh++IUTyPpfAOZ0mf"
    "qZo3lYu7d6xQxddou3b2/5t4Xz/zAADlVc4AAcqrnAADmqucAAAVVVVJSEDDlTjocBnQgzoNFDEb"
    "y++v3DeNx2qa3MHlENsE7kX4/aoo1FBUD7q7YCEw5DZRAuLoc/PQcjxHiPEIkwLS1Xu02kMBUXUo"
    "DBEz43XIpH7wbjx5AopzGAZ+X+34hewjCDphCJDqFF1iccttwHswJEkUvUTxcjzld0M3Io4byHE6"
    "DuEO27t5/LsK7FojSAP0a3gx1JSWC7TGth+X1OLsM2ZoNy5ad4ObjkMMMU+hkYAY3VDKJmxsegWy"
    "Fi4tvBGiIIhrMSyACbkMNQRyPEDhj5Ufj68XP0EuHFm662GAQUq0CekruwsSNynSXF+BX83d9PLv"
    "nXbj6fh+L3W8f6RMCCk6fJ8/o7nAV+7wZJufv63DL7b2WxcaSXoECDndnw90jxM6DvGXF2YvG6v5"
    "e3qu2C8VSuHvDWHbj7BB31Rp+RG4jWB8WfyqE6PSMo554jFIjTZYZsHLBn+qksQTOCqZp6bQwwq7"
    "1NQqJrityCnaQAABLAURBJ3fmowHxK5Bw2Rv5TugF+GaWW56gc/k6eELLz/18JmkH7Gwt4SDGX3t"
    "c9M/smjh17P7Tuxotk3JOsB3u4Kl3bjtYTFL1KEwcS/qXtwfTy2a/6xZTV/GMnkLxsiuxOGPUoEo"
    "/Nv6ZqHisOdt2P908m97/roTiOfbtCyP1ISOnv8878h4RYsw0ZGgkUSoGiVShKlSDzDEiuciJx3w"
    "mJENi8hiOyEJpYTnLxWBCPJBABKRDBQgHAopC756nPjGV+Zq4q71xadk+buUNLliYW2iqdCiO+Us"
    "29Nh1qaemuGlJ5eq7JD3wDUiHt2a8f5+W7r5oXb/Qcg+UoQIQIJGKRGMgVTv9Td3hs/5YAVACQgj"
    "tqsJ2YXcdKKlw5+fMUSCTXyex3FNGH2WHB2EkJDC03gAhmWmGiCXCiUYEQuAmlD+NKwLCv5UiEGI"
    "EflKe6M+wgOvX+DT9tKflT3/v6yppMB954Ogs0jOmhROkEKMOeU4EPtYUIbGV+jVSGyOjFMSClT7"
    "JATohejG0E+4RkDYRS4IlCj8wD6v3umd08e/3W4gHb8v2eF/dk23gCHxuLBQR6fBgxh9tHm+L4ep"
    "qfXB8UeCJ8E4oiFCJdDSxrb9daHPO+GVHSc0JF+vD+on6NugXPjOa74vtyEh8b1Qwx3n2p2ZYwkT"
    "1W7/c2qMEfW6EROswiJs/DNHrP11+qymXXUF1T0QojKqYhdVfh8nms3TC/D8mNWB89VhpVKEHH6z"
    "qH5FVLigfHgWH6yJin2NPgCH4NtBq8gYi80eAX67gwIfvCDEbiJQoWNMynmIVFfAE4QP3D057GdX"
    "itfuILKebS19rO8h2OuSWdonaBD7cQT8V62S0vIc42atx0Lizah+n7dFxRVEBzMxoznhZ1iVnWyn"
    "0bMMPWIeT2t7tj3r1vEgazIxWiXR5xdFUxjK/4w/aUIJo+YWgEovAPhogTwq/ImoWEEgXiBaBGIQ"
    "T8NsUBFpVkhKQTsvu918mHXB9Z2kIVxHYUejKn0icSOJI1GEVEkAUuqBy0d5dIw81NRh1sSVSatt"
    "XRP1o0OxEfZEK786Mj6C6Ovw/NJYPe3PzxRn0TpnZA9UbWd11DVXe1hcZv3Bf1gOJ9VIpImCmbgv"
    "rRPiUvR0Ee2CPJIlDaIEgMgGxFD4wAqyR2Cyn7BB0KATrr2ByLoAkTeky3J1ydgHpzO+CMZIe0BI"
    "G1JcMfZf3RqqIwWKyKHgR+1al447jzBp1J0opSqnruxDSIpE9Ek8JDdHG6p+cBJG2vb+RAAAAAAA"
    "AAAAQAAAABoAAAAAAAAAANnbelfP198syra831vbdR6xR5ekxzkYSH1Id30BaFqsGChgHgSkfIBE"
    "Y8j0mssdQD7Ce8DSu/MJ9cQ3B5BB8AeIu2ugdV9cFMAqJ+AuRDxvrLeruEPpPa731yB9GbjOexTR"
    "BJRaPegFF1KWT+CxOmBfLp+ExDUyDK9gWh7Pb/gqqmbhc88fNy+/l7SxHxpJk4lfNjq6u2VmcoWl"
    "pwSzlKGcolBCakjjtilexnN+FszasnQDJIxjOQBeeItiKdgr2zxNFLDA0lb/tlyeqe8bF9z0/TEP"
    "AjsB8nqDG4UPWpVArwHJ+hLVfdv8/36kSg4EkAndclq2hSIYT6Vi+RsB3ZiOaryqbOsgBoxTqip2"
    "at4Yo5kEeKWLlwiwwGMI8vTR3ErMriE3EAv8kd3MYokDcKG/A2uoCWIwiZaykibo8CHIZ0hiESSE"
    "iFzjUofwhcqV5Zhxir71Onoa8X7wfcKFKKbwgiSPmAzQO8Op9FwOI9BEQcB5CfKHrh+RPaQwT2Cs"
    "coPi++q8vNCxqSjwopdXa9KKnSHSPQAnMPEMlNnY+90IQXvTnxqIjr+xaiB+fkU50UJG8KgRZHOO"
    "0ueXZ+x4k3tm0Kg9dhPWJFNU1EoJUF5r6HFnCrb7fdEkJA84dKwEKGyS6RqB3qqbxwgblPQmtSRP"
    "veDR94l4sgwTogHBgEKoCmJvZRovWKHmHFUwIuA0SZJGjZjvXJctyvla16LUP7hh64nt+XJKIZ+k"
    "8SsYMr6ysYoI52mlUlmGpNWGnQujXqnLecOcZxWylsrWliypHQqnJyurKjlqZYzMVMqz6h16Qic/"
    "KrypfSjswLZ5Ig2Lq6DvA1g0v2ajGDQCQpcsgHBHJ1usodjDSCWuWRYQIFksolKIhRYoVpQ9eaVk"
    "U5TtQalGkpQNyP5z3B4ghHykbwU87LylLibl7fRq+I4P2JnC5lIJKW2o4jo/H7nI5+SIDr2LwSjO"
    "tCOCIyyoidoaHEGqcoOSIehKATI6AibO9pU1+d2lv1S/iWkiF2hvG98z5281fDUvSmD9SG5dzbC1"
    "Q8rZNS4LYJ4Uw1WB+WcKkhJCSlPjPqUHrknUj7i7aTnFDznYB6Atl/zP96ocSH1UmAcKqL4+2H72"
    "HE07/xmG/WlhfJMC/EQdG9rD5i1Wcn1LPdsydb28WBqTho4CEidohgKsWAhQ9rtKH6koROK76COK"
    "PM9ae8uCvxCEEMh+V+zCg+4HR8fu+L2L3EhlQEpaQJBB5lxd+vxwGhIn57QFkngPWBEF6T6hLDc2"
    "2zqGorughAlCSiIHiGCSxoIQsyS0Py/1/g+Tu9fqfL6PzfN2/ffis7TzPfPT+7f2fye23LKmedzO"
    "k+NvmLkM0laGkwFO34hXH9JQXQl2R5ppaq34ZTCH4scrKTVjhYd/uDmOdaHT8PD4XLt0xhZbhsZ+"
    "7/KXNwQMgOPIEjjo3CzfLbwJ3OlhrUUCJ8QVuJlx608p7ivzzyPcEO4JACAa2QIwiiiiijyq+lbm"
    "6YxjGMZ22rc3GKMUYoxijRCwUFgoLy6v549SniJNw6zXojwPEt9qPe8hdgYP4BaPvus8skEkSMAi"
    "/fYMY5joAms9AwyBHAD6xponchqikiQgyHzO9JkEaWTMsq8vP4Jzq37HYP7sDglDkBDYX6nHWekZ"
    "p1WrczMzMz1Ya29ohuXfLPxT99fPYc0NT7IT2Iqf67HcH2demqVV9j1BDpePN2znu7qNl3dNwfrW"
    "UQIQdoW2kCOovJrA1Gj6D7CxwKHKGQu5IEcoGDAKb7dSewgftlMZC+z+QBkUfAfU3W3tGkEkEwAS"
    "V8M3L3HWXOrfZ+kKZJJ+KTw8T0B6VD8KmZoQjDrf4gzH2x090vE7ou/hJ9VEJJTaGBPYAUPKcwxk"
    "CeHqAM0DWJOH3QhJGSWGiGpouf3YEPkVnIBuHMTa8djQRzF/Qc2BJqMjp2FPgNSomAY1gv0s912P"
    "Ax2v1xsMDBvPC5VIUzFEkBKM0RnuXPP7osVqan1rpcDVq5TW9GCssru5sA6cSRXYZhqPU73moCeQ"
    "rJFjzhE8CJID+B0nHnF5TXlvwqiSU2IpsNKNIHQE1G3FDu4/AthCDAIsORhc7OvtqqqqJUlFVyp0"
    "gnSab+M7aDZG4NWTbZCd+qbwg9qsDpDqF1HYQ5i7pkIZFjNNyvQaDg6J/VdyJ7W3lbPiEKj2DjBE"
    "sSDIEOYyyior27h4u3vYZc8GTUMek6zK5mBkMEzD0DDaG8en1+vq4HUBv1UwYEAgUjfjd1GXTnfn"
    "jlm7DR11+Bydbu+X2GX5zLIXd5hRCHZ27apYwa524XZs4Nt2WL4gmr6O+IZ0knRyTAjUQhUkvfu2"
    "9/X4PxQABhe1ucAAAgAACAAATBzDkaO7fITv7nfyk1Nj4Fp5g6ptA77XOCJM29u15vZXqrw+Tb5b"
    "cR+7nNGY0acTLmB0MJlyAzYe/NULEGfDSiOoDh/hgUGaEDQKBYFB5x37d/ig6jBFPsFJC/Q/v7Qv"
    "y5/N+Lh4oHB9IqnHxfVfumiTt91O8IyV3n5EjDvy+97NVy9LAGDIQIsjAJSpZFizbVmpqzKpXNc2"
    "5mkqRoopcr3tdc+Xe7tiRuABiBSKBlEUkkED00nu2+Q9MiGe11mQeCb5I1ySyqsuFjCPAAOHxU8n"
    "L6P9e/zhsD2NMQkO9ITDhY22w5AgNbkR5lPBgKED8YlJBuoRR2CQpqxgZ7CaCR/JFtAJBZq6Oc+w"
    "S3WKVyNbYkV3uI1zDsHFdRfn2S0aV6vHyoJBUGXmIyMAL++N3JIvO56w3GgPZFAMHYpAagVq4Po3"
    "08a2igu30nqhDnDqCO4z0Fe+yOXFtETAyh5LAun8O6+GQ2BnqSdFjQ72SUpQhSCDNeksWA6QHcbe"
    "A1mIFuHeu62KdJkZGMXTqdQi4W5Gv4aYRlbLdLbRyRwUvgisgay/Y8FNOcXYXhpgJy4dy44jNYKG"
    "8iDI8DUf0yuJmeBsPfzvMQCy8sxg/TDoSOchdZ6UCd0s3pSf2pCRkHI0Q++fEc2lwNA6S8m0UqWv"
    "jCCQCEiQXCqRYsng/RTBsLZ6VWSVok62Ng0N/jgmhUW4WiVa2UcgQeWWYaIvonmlfAMSeVA146A0"
    "Ls6AIcisozTDg6ZmS8ZpK8CKYYYkuUSd1DQAmRqeHg46EImTVpdoSam4CAUjajRtLO00GwLcgK9v"
    "ufH52FxEwO0YT6EhAIL2CP7c7YiWRAgKSdJ1VNZkJMKJUGhZIgR1+RyuZhz4J5YTkOMOPApG6bng"
    "ab+qnkhUhGa1FSGWNBC0KMFoDXY1IeKVBkB2QEuEiBM0HMNyEid1LKKNxvssYTrp5uElBy2MhzsD"
    "jRoCcklT+huzwGFDAkBvwquu6igfOEIj2pCkqy//OackkmMARGAPIQlSFZ8ydbvrobeOjttMyMgw"
    "kRjoMZGAQM8pOBm4B7OFAeJhvmrLe2qzC4k1mY9wDuPLYQWEqQNnimaLUrUlhRFJpouvD6o9w7/Y"
    "dya7SVfCqMBimhh0KAcVUeQCzqhvC3leaRe6AOlgmNuE89NCAwUQ1xMtlqA4mt0Q0N1MhS2pli4w"
    "QDWgzLLIoIJDTBFiYOIZSVfJk3hYOhlCijVi1oy7jTQxMpi+rErkZLLEkIaZQ3YYhp9G9J6iKKOp"
    "oAmmTREojmijb3lkioNRDbdDZlQtly7vRzFrwl8XrjzYVUog6OGpAGLqBgBt6REmAZI7mBt8rbVC"
    "STJO28kcxSMiUwYEBoiHetqiQl2Gq2n/SrvvMDF4NFjw8xnWrh/yw7EkNyhQeUiO1lyTWNEi9ohS"
    "FwJMxx7U5a0A0gcYFYpxdI/ZzNzNNNkKJyq5uJJEqqNNUjIW8WiGf8op56ceB3kP2+0vtlRKY8zt"
    "CdCXwCbCs9zu7KMxNRihsrKKZEU8h72Ym5nA4JhkAJhMCJ0Lr4YFZUQQ2GzhbQw4kpTNEPkGd6hm"
    "cGhCJTQ7zLsr0MP8eG0Jb48IycFIy4XWt44G/0YpK12dD3mWS2zbWitAVFJpdaTL5vLaYvhZemVw"
    "ZnNK4RwJ2sRJFFi+Ks1i+16llSdyC0s6wsGmmsl1CLtqsFzGbArhZDDzsr2DOH1y7ZTguCG2ZTrZ"
    "otGjtAQcYcPl0urtc4tyhkmU41aW5TdqsLtdxLhNKBtjkc53Y5O62VrwbTEIyyZkcAOcEZdhZTUG"
    "6yJ357iEsY53ImqMO+ERyeyykYRvEJJobOeQgRDSG7LbsDU1otospuSCrrFQcVZYSSQAAAAIAiAA"
    "AAAMAPHtdpcV38fDujW1aAAAAEQCAAAAAAC68NeTW+JlAOA9ccFnprMSZLNFrml7Mk0aX0mmlFLr"
    "rOa6nTnhupJJJJJJJJJJJJIkxJJJEdWuoedKc4l6hXpJMgbJhYwGaJBKaMFmNBEs14bk4prwJGJA"
    "iEHMKCgISEgQE2SgZIT2KCZesfCvDwqdOiBtA4KPR8JkxZPePxSIAZPWmhBc/uR7FJKW0lxIxgo/"
    "XnEUbYUAJXOnfgxVZIgiDMFsMqep0VCOeMw2ummjadymrM7DDDw8KmwGKopqHTmgNq3lRzF7q0Sb"
    "U0+xqpwYIHEDE3VYTOBIimbAOWDx3UhQRZBUQ36r39ohIJvHnMFPZ9p8XMNz1COkABN5AGIHqWv3"
    "IkOgUPuSM8FnAMZCx1USQkhRc4TLTconscgu9GvANaOYaLGDT1bmhYQBkAnJeJegcg/WLHTN0FR8"
    "Mxb8s6LnaqW+kB25dO/HgUpaFj4d+RN7oU3DjKiPKhrwhlzn3M4XQnv9AWGb3ls6GEPBIEHW3qiQ"
    "oZsRwoftaskbhwTFtVMjEy+JzwC86+OT16zDB8y+AgSCqRBBipXL8USgPMR8O/hcVE6JDqpCkOwI"
    "OCuN8rAhCY1hr1ql3pESExflJw9Gt0SyRg8Rpmr6YVPjbXTjQOjK+FDhopyuvwSeSS4WnIyYgW7j"
    "Mzbtxl9cJ0rR2Y7R3uexRmciRkhfem1sGSH7cGfkNcLAUOff62hNJDLAV2STkn8BeN2S3bEIEA3w"
    "QsPVHuIekh+Hso6kAdVZBfb4dcDn80AAAAAAAAAAMAAE9Xu+/16brpWu1xedDQsyekgbIRWeCJRA"
    "MuvogfjA19k9M5Wwhvv6kNr4wD6CSDwwXJPAI8LF8EZXO+GKEoMj/SdLIRRUsKhvZoqcREOLLvTR"
    "gX1KOQaTcAo0n3QO/v2iBeUDvCDA39e2whCzwp2nF3qg/NV6DDxHjk97WGwDEqJ26zvgqysYn07I"
    "ZEYc0IoKMgkiGDuA13HbYKYiJ9WsYYxJBsCQTzLIKjxhiGVoDBBBggUsArIAKBUFICkAsBJ3ST3f"
    "r+KBa8N5mt3t5ehaTWPXziaI2KlujzyephodFaq2yRKKU2nQcpvcnCQiaYTeQU0XbtzbAA3wHXA0"
    "niyHWuocVk4/QBUTc9Pp6MIflQ+VPCMnol8CqucgMoy7pOkusB9iAaAoG4a8HCjuzUSTgYnNAjRt"
    "eqaIXNy1c1OSm2ltueC8+r2La19jr5KtFGYJM1Xwe9eztLgixxoMwRtVKE0QxUystsiKXhWCo1FF"
    "IBufJO+AXh+0KpaVk7+NvCy+a1tFRk1sa79e1FgIpIPvcWYHx7Oejl9aMZ5KEldbvSOBrhMDbDaS"
    "UHRqFDVwyQmMjqcHBQO8Bv2waHm0NzAoEM9qgpJgYbYMIR914Yl9wBwSQgEGIlxKBpuLrCRF0rdd"
    "72/njrH7Q2nx9C+4j6SNQPmQLlyRiQoo0C92p8OiivNdrCb4GsvRUo7+GIxJPGkOSZlgXuUxmmiC"
    "ICMlyyhCJRAAfpDL5zVTr9TCgcYNI6FC6nvT0hjvTbFInrddytTeSRkLgz7H49xIauIp9cyD1orz"
    "4KvAWPePa3bunebPWgvcjOahB68XGBDOiHz8rkDO9C1JM8DFWPBOhLbzkna4jKUeSepFggaC0AUn"
    "siCwPZFGyyiJYIU10+vqOAUDQyWMjFQZH10JR5UNZI5cAYJGCMEUTExhu6wPIVRSIQuXAtyWvbE4"
    "AU0AbRZ28YmEo0mpANo2gtev4N+Mute5by5WvZVzmeu9j3ryiTFAtPjJ2p3+00v7BXU+M7Z3grX2"
    "3eKDSyXjVVwHPrInIuNq9UCt24yMc9JgG2bQygXTKwLQdLIGUPohg0JAaA2iI8Np894b2/U6baC5"
    "7hokz0jVVBYcOOdft9/QGh6jcb4x/hkHqONKCWQVSBY6A0LtfTXLYXMyQ+44aYRnvj64iJfLRQQZ"
    "JBypOTniO+De+Adfv2FPV9A6PO8MlZiBgluLgS5w5DAUdGQwyXCwMMbWWmY5YY0rMDeppVLS4QVL"
    "xvFkpVrWeIIb6LRFCmnUNBLR5EYFEuoYS0EHI2eyNBfMaUJmoSIFI98OPiSmJyyBPzfPiGzEHxsF"
    "igMFBwhdlIIkmi0Lb4IOJrpecib5Ji7e/FXpZBTm/ObRLRNNYY4zqNU2gfZmccsGCAOUSoGFvTIN"
    "9I6ZrppldOCFJplSNmaFOGyjjvzcQxCoCJn1UXCslOeLohegD0khIR2EBA1o4HONo7fKJwvMJUTP"
    "kPh3pvSM5XU3LoapXEKSEJVcfyq2V0aukwjjQ2dSHcZ4bWLLa4RPLCCUA+gtiHcfiY+HdJS5prCQ"
    "kJCoyBA4oHdhCRFEkgj3U6UA+aIBqwxE4POL4z0Cd/wGVqJlPCrHKmqRQSAD1TqH0iNIjkD2c+7k"
    "v6vLVXPYYuO6oSkmKgzZXR2IeuR7B6kMJ3LBGJ2aTIb0WE05EHVkyKNtDuyJNaGGcroODj0GZyMe"
    "rMe8ydYOUqaE0mcPcv00nvQ6yg1LM74EKhD7NlLtxPZC0LXMIABSXwO4zl4EMjIvEcmeMG5kpmEA"
    "kQigQXgj5oKmN3ice0MNH3cwWGIHog8D6UoIQIp3KpRAkOmiQoWEF56OMOOVBxDj5OmKRtRMllZs"
    "12puz1fXVGkTQmSokqTBk2NNNjZAJIwZaWgpNJZSy1Lbts5eGt3uRWSFNYqTUUW7scm21c9zx2t4"
    "rRPNHN67uQTMAzXBPHFNfsFFSsanPXPqUKeQW827buVaFzA5UTghWBKBTIeW4F0Lm9XEwCHQjZAy"
    "TIIJmVm5hRVqo4Wz0okmPWBz40UqczBeag0Hksc5uezrFcdimYHRONTUw0OBYO9OcrrAdu3HSUrZ"
    "QvJDJy1REYzasFKU1nHfMMWbLDPdp7ETjasaNUIpAwR7x8zMQQs4Zu3AvO+vrfyYKx+yuSWa0Vz3"
    "cmOV0IEIRpRLF7AYfedEFF7hFAvwx6CggF9gvbxT7cKbCRv2kMZCeZsgaTkXQbdOvwuCwWCKkCMZ"
    "REoZUqRsUnYQ503LuBQTM9gaBhfwh2kSClxgAoyRBdIF9+IXG547JyYOTs1YhYyXbNzlzBisZj0D"
    "OBLMyGZqZBC6O3dS4kmDcgFq2ipZMpqrJuua3fnI20Qa1uNxtDGMBIFYJSwIlsJRstIRQFiwiKMZ"
    "pJVMuMwAjUCkGSusIDmDTQGBIaJI1mmQFKwJVLoqNZOjNJ2wcgbzHs2wXfFkKCftwNmFLqgYxnko"
    "xRfHuGBv+AsD44AkiEDzv3oqA+3EQXebzMuUA6C9geawUebAEO59JruKkIQhJCTggJobFz+JQfbD"
    "seCsSRAkWJACQIsSAha8P34OBhe4RT44FlYjURIQSQCdQOE4DJewsEYV7yBp808TGmSDEQYq7oHN"
    "NTb5S1JHxs2uUZAIQIEQBiQBSa7+MkjGUZC2BAb5IkYPA5vdVGKc7pDDUqiFVszgnwssLMuQ96CX"
    "2hDlh4V9MLahiaortK7Wn1qhP2TC21EqSGkMmLQ54UxNuM3qWGmaYfTdOGzsK4FtPbKhAuv5YVRm"
    "xRU2mrV35IUssSxypzC+/osaDOTemxFGIA9SGvqvkVpYXXaHSZeGBqPek696j5Q7U+SSC7uZDjDg"
    "N208hlfnQ6dVwSBI2gkckDGAHCAfNFLgu6C8fI6hYD2dpX0SEkeWvdbUjC4t1rJ5co7u0Di6WZIp"
    "FgsvaBh5kkNpQXuGRQ4KEdDAsPdUcdSnv/2UWgdBKh8OtsoZEkQyi0RdwxRMEXy3qcCFgMzcWHmE"
    "0D5ToYNipybakaIO8xlzZEtMbC2ULLTibTY4QBwBxAj7DLusMDntoka4EqmGdAr8N9BE04g8RjQ8"
    "0872kSELFo0F+mGR8yH4owsBObxkX8olpjy/lQB5Pr94F94CYK27C0LboSgo8ffCXHMoweFdmlMf"
    "NwoUk6Z7JV9ccgMRCmMogzA7JMqsbvqF4xRbF3YeBrIamfyqaQhEQikYqB0XOm6HRI3eqGKKREEn"
    "a1bnAElkUprwcRAMIiiCxy0fhO8IiIjAzfMk2hLYc7WJd4TExsMgEbZjbtwYRxATNixlFzAxYqyj"
    "1R5Q12AMgdYOocyHqKPn77QkUGRFQ5ORT7IGoWAfZiwN0CNfZb1bV5W22vNZKrWY+PHNygzvPEq/"
    "8WC1gwhh5ThIRtM9BaPrV5ggMiyeHcgfSMANRI6ohjjhpqlkDqinQepKeow/W9xpbg4WmzyYYax7"
    "Z2zwk7moeZtuvoMaBwAzX1to/vIhpn+H8ExT/4J4LJ3XOINAPvICPOc4z82iRSZD6zjh7AzCD4hF"
    "QrPI+FnbfXuD8X8cHGNaYAtmhiYYqSKm0pEROvzRPifSr6HGAh4BwA5xxz+iHtWC/VH5RFUBY6ks"
    "F9o7hxaZDpYTbMk8wgB3Smq9u3p6voXLmxrMkg2935Fd+pKMSBBs/HRdyUAU0A9nUX4qCMkkFBjG"
    "bHsfB8PhzT7PsHpb0BObbeKXap2aLq4VWCmVMmIXVDWnw+UmDQdtcuaOiw76CaY6t5zayFp6tsnZ"
    "i8NiH4z00bF9LlkkkrHGxra2nKZk4bJ21u75KHg2hn5L6k3RpMKFwbSI5r2pfTXWYFLIzkNp311j"
    "KwcHfIPa+prpwjS76uY6ntrx2wU5KNYhFttm0FO7ue/LUL0S5Wzxs7mo78dtA3+xyQS2mhjTLJdI"
    "OCbbcfOJaIji4xgSim6i78MYy99HLCAqRxdOMdSlGvpw2aq57GuskRnnxjGaUZvJWahsjMzIQtCn"
    "bClB4bW3VIKTIXHVb1IUVJftsUrKa0j120ExWRCEhA7oSx4y+tx9L3e5uauK9EFKqpaSzoGrNzPV"
    "Q0FxDSC2VFZ56SyDI1QHS9UTFX1EZGBAejipzpPN3ymz3G+hLb/Myw5ZBB4AapK5aBC4u2yv7r8E"
    "wLSlQaiKY8rN6ddS8gSYZyzWkS+Cnh5nd7C0YiVQ9Zp0gxMM89LSHs4RZB2ApZW+boKI3oexo6lW"
    "s4bW0bicnmSldmGQWG5CYSJhZCzwv530Tr3m1etJqTLPviAfgSe7BkPRTa/ehYUFMfYhrVtUtp9i"
    "6ydZasgkZ1xdLa+chjrlQPDkhCicNiAxImmB3QnfgHFRnRYuuF46Fs8qKIsK5jpyKlDCoQGMSjX4"
    "J05rpIesh1IpDzSMLdMwIOUGo65Z1MhWg2vCRkDrh6CWRGOoxFBFJ7gEQKvj85eBlckcFIZRj2qX"
    "J8/4uG/6PuqAtR7rk5mmodIregDGjVulO7BNW6weqTtoTWGa0FtVrTUVkjokIx2pE8AhlkXdRC4y"
    "Oun2giXUTsGOYUgpYQhAUux9v19/37t3y2ahiEBhggSEWwrBFKgswX48xkL5IZN/PLGuHIbQMotG"
    "kEMipE1iiM0k1zacmjJrpaRcGAXLMZsTZWCbk3eETNXIGHCzsw7DWTBch5GgKUcZJKq2BiZ+va9y"
    "CmqiUCOedXKZwKTE6YNCSjMxCDP0ohgSZIMq7sakGFj6V6xAnX0TngGIVmLKU7EDIjHL14VoNaNU"
    "RrkLMYq2t7MWSbFCcTp5qxDRlyNbew56d4PACko1ucTDU6N1TiQAiJAUmtFJkpIOtmwbg0myolRC"
    "4rDIYtyIVS5NsJI6ZER0dQxqZgQCD7YqXaDkX6AnqcqCyH0RRx59o3LqjeyckCFBJOsQNcxGRbAO"
    "mkA0qttVYT2yymVjJQ0TrLW9XV50kiB9MIc8ZBpA0V2zOJUNlU/GFVKWzDtD6oDmOnvaSBhsiSa6"
    "HgdPBxbTiDjy7EoswA4bua8fPTUrMmwUG1gWigypHtIXaWC+cWQJlConka5dNwbRF3u8s1XSJ6Yg"
    "Jqu+zqaVssyW23o8W79u/FJCieOSa5aYdSbGhtMDJUsBiYV6Rq0Is1JeqUzGwU8UBLI2LlykKIy0"
    "KWy0SlSllvUPTQNEjPTQ2idcvP5Lz1clyYTq+P9pdzfC3PhAAAAAAAAAAAAA5OAAAAAEAAAAAAAA"
    "VVXo4IdnROkdchNENE8ZIgCZ5TdEDl8k2J3xTGgS7UScoLSpafn9AUICJ0BwgJIyB1M0jIN9pObs"
    "wNQXERM2CBhQeBpFg7+NxniIFBpSR5xyEnZcWcWmiD3SoJs8exqSOCuqkq6o+1KqNQkqRgHaHv/x"
    "Hs9RYU29ewOkGQkJF4iJvQaTGoR0hcCIhAgiQRKPxsKuQT5hT5YSIQgDBiHkMlAMuo3j93++jq66"
    "Phb1fwYkk7UsKMU87+6j54gdJ7kLGB+KycHhUJKkUqCl8FJFA+81bsKr7p1A0Y4oHzni1Cd/r6wO"
    "x4+1eJcBDcQtPJ13eY3OTwkXRMPTBAt/XCjLjGjUfEj3EhJKmRO6pIuuD0CfezPEx40VEIMNcM4W"
    "ZIOGY8Npts6xeGg/pjqdWqfUftngMF2nZKZW3MwRDsfpDn6brwaLCgUOq+LQaH3ClnxWLO4SPh8D"
    "eOeDWc4/pXyC1Z0A0uthQpi7UMDYFOcEDk4CJjEE3ocNigjhcMT7pclxk147rW5U1PynNMxLeRy6"
    "kgU64+9AvkjhHSKeARHEMj7sshjYCdyQh8Z3u64tVqd4tEZWktUnCGWXw2maGzCmoxjs7BiXeIV0"
    "nSRkhykNAzwPyaC8wZJAPUeXd8msosvGYnj3tWJPKernPVebxz0lw7EzV5ZRpk5VdTIzUJsaqBMi"
    "sWKcJlFLIolRdmWvu6UFD5QDpDNdxsXqhIqSJIiN2Lt/pu6t/kBDv5Gy1/uCIwRG0UPLEfdAWoL6"
    "9a16PT4XrW1r8DvFK/53A15qvxFSRM186BaBISLcBayn12rQE+bCr7A0VYESw91ET/Y2+xkBCS85"
    "j/5QT9in7AQP/iRDYfxh/Ip9r0tTvK/F/E1LTGs/4ZiFZ4b8ni1Di2qkeKVRmUKB6E//F3JFOFCQ"
    "jvxyQw=="
)

# ── Extract + compile ────────────────────────────────────────────────────
_BUILD = Path(__file__).resolve().parent.parent / "build" / "inline_k17"
_BUILD.mkdir(parents=True, exist_ok=True)
_CU = _BUILD / "flash_attention.cu"
if not _CU.exists():
    _CU.write_bytes(bz2.decompress(base64.b64decode(
        "".join(_CUDA_B64.replace("\n", "").split()))))

_ext = load(
    name="fp16_k17_sm86",
    sources=[str(_CU)],
    extra_cuda_cflags=['-std=c++20', '--use_fast_math', '--expt-relaxed-constexpr', '-gencode', 'arch=compute_86,code=sm_86', '-O3', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__'],
    extra_cflags=["-O3"],
    build_directory=str(_BUILD),
    verbose=False,
)

# ── Config ───────────────────────────────────────────────────────────────
# Canonical config for K17 from the progression series
_CFG = get_kernel_progression_configs()[6]

# ── Public API ───────────────────────────────────────────────────────────
def forward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """FP16 flash attention. q/k/v: (B, N, H, D) float16."""
    out = torch.empty_like(q)
    _ext.forward(_CFG, q.contiguous(), k.contiguous(), v.contiguous(), out, False)
    return out

# ── Self-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    torch.manual_seed(0)
    B, N, H, D = 8, 1024, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v = torch.randn_like(q), torch.randn_like(q)

    ref = F.scaled_dot_product_attention(
        q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)
    ).transpose(1,2)
    out = forward(q, k, v)
    err = (out - ref).abs().max().item()
    status = "OK" if err < 0.05 else "FAIL"
    print(f"K17 [Auto-Tuning (Simplified Headers)]  max|out-ref|={err:.4e}  {status}")

    # Latency
    for _ in range(10): forward(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200): forward(q, k, v)
    torch.cuda.synchronize()
    ms = (time.perf_counter()-t0)/200*1e3

    for _ in range(10):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    ref_ms = (time.perf_counter()-t0)/200*1e3

    print(f"  latency: {ms:.3f} ms  SDPA: {ref_ms:.3f} ms  rel: {ref_ms/ms*100:.1f}%")
