#!/usr/bin/env python3
"""
FP16 Flash Attention K9: Reducing IMAD.MOV/MOV  — RTX 3060 SM86
Auto-generated by gen_inline.py from kernels/src_9

Run (WSL):
  cd /mnt/d/GITHUB/Mini-Attention
  LD_LIBRARY_PATH=/root/fa_env/lib/python3.12/site-packages/torch/lib \
    /root/fa_env/bin/python kernels/flash_attn/cuda/inline/fp16_k9_sm86.py
"""

import base64, bz2, os, sys, time
from pathlib import Path

os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")

import torch
import torch.nn.functional as F
from torch.utils.cpp_extension import load

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "py"))
from flash_helpers.kernel_configs import (
    DType, FlashForwardKernelConfig, get_kernel_progression_configs,
)
from flash_helpers.kernel_configs import get_kernel_configs

# ── Embedded CUDA source (bzip2 + base64) ────────────────────────────────
_CUDA_B64 = (
    "QlpoOTFBWSZTWaHt7DwAKwp/gG/f//7//////+///7////5gYt7zvJAxZGjfW++Z99nvdb72dF7O"
    "2eipJIUAIK0FBxBu7qAxL22zvpiM7u9Six060H3e3dIvPvfea3XsAOPr3YT7D6+je+HXfN59rnvr"
    "Ge7h711r21TvDz67z3b73XZoqeq+Anr33x3ba632+8zvH13261r7ud7nbp7fLvX3GcW7euXb1z56"
    "Hny6+6+yO9q9B2VNVhSbA1Gu7R8CHyroa2z7x7e2Qu93PG1Otay7uyO23XOxw26dxC6MnV13vvvX"
    "vgs6z5m7HlqN27Ne5zmeO1Q4ZbKyWtbXhxB2Ox3c7bGEnd3EGm22t7cyNm6LlNuVudW7bNvCU0gg"
    "AQAmBAJoamTRoEzUNqm1NNRgAGgAIyDR6aQJTQQQImmiGpinoaSPU9G1NPSnkJ5Rk09QaBoDQBoA"
    "0DyIaMJNJIghMJoBE0bSp+1MlH6p+qePSnqn6m1Gp6j2qfqntKe1TyPSRvVPKeoPKDAQaegk9UqQ"
    "kp+qeRtUzSaaGjT1ANBtQGQ00NAHqAAAAAAAAiSQmgTATQmBJT9qejEhqp/pTZTamk/RT9TGqe1J"
    "nqPRqE9TT1B6RiANPKCJEgTSaEwmjTUMENGqeVPzUNTyp6n6j0pp6nsqZH6oND1NGh6jAhoMmjdQ"
    "qAP7IIKJ5fO/viP7ohaFohEhAxsKAiZvoNc1EUGpCJKkoK8nLWmRo1zphIE6HQhCEaXlfCfY+Z/n"
    "vj7fwL/MbvTcbOSkyG8OF1cijkTgmQWswQ1A2fAhvsLtbQucLrQW2fwOKoJxti63zCIgn9v7X/rZ"
    "iUDXQaIhMkDpJoiIcU2/H9rE18/4j8tZtFYsW+jtxGf8iOFB1XN3dCRKMqEJJFxOmSFk1GKDBm49"
    "3bMxKlQ5Dc23LmoCsbwyZBcE2szBE/dW1DUSjjrNZKoxcQxMXG3f+YNMjE6DYOfbToOEKvBeQLa2"
    "2iW0rbQAokIU7Na/p26t92URTYdWMSnC3FX6uqkEcYstsRYwUthTVKqGUzLWZlIjgMYr18M8nleT"
    "I3Ilm3OwIghrw7RNMl4bCa4dzkrkY8KHjrw9G9cqIkJLUaR1qsVjBREUDik/MeMCTghJhwHjXRKv"
    "xjjrb6KxqpYWieAd3B0DRBGkhLSBP5Yo3l6H+ZOCSqYgd1c4RPUKQy5CkLPc1JXLLE35ZmK00WKu"
    "S2laosRTutw4WSYGQ2s3OQS7IbbFMZbLFRIoG9Rmsy3FEYcezp8jWta1rWta5znOc5znOc5znOc5"
    "zs5zla1rbdcRJGMihBZzQnOT2EJ+/OZ0D5+868k65v15wTXz7ZF2dR27dqbU12tyyx3QS/Q4B4bQ"
    "NnhlBYJv2HPDUFe0URT7rHYzMFIYDRAkTbBEGS1BiXuyYvUlEXXu2EogPig6yQhCBwNCtAzF7Up0"
    "vtqaykSzNoL71zQINTuB2GIJZyw4ft/knmg6BJOAZXpoflQD6Eh0DIdE9T2r9v/t7+v6vT6sKd6N"
    "56bO+dcHjNw5bZQbwEkkJCYEkIEhHb+7R5dUQJBG9mFSFQqShqCvrrEjiEjAkSTll8seH/jz8b+F"
    "0r25M91+asOqDpEYwCB4G9BXwNigC4c7ZFU+BmIYBUBidiHLKe/lKkWf/eVJu8k597FgIjIuJpQ6"
    "0V1ugJCUfBW2QFLEQT4IAAuCqURFqCjIk4MkPcagKZbFFSm+twgdjIDwv3BCCMgbpCwUBYdKElGR"
    "eQ3ZpyCVlwf/NcGzYSg3shAsYvN442B/LfSRwNtaZEJ/IOMIt8Q1xsQSOjGWLxIQ5Mbw2UemZTp6"
    "7Ne07twoisIc+RQVZRk8g5EQGk7Po4+2ajXovLaNcrhLeaVmCJgpT8lK98DVrFE9fakgiEoOSaXq"
    "IEHBHkQDOVsYArXMae3kjsE69ADH4r76UR4nNw1wwzHquyV0NglpTx5Kdfz2jzNrMmWi+XrsTAIU"
    "Yklnqs+76br4aPNzIQQDJyIwpVw0hf64LxNY3aajNrIkqBCEndDxHpjHORm3bsnE7krHSccroBT6"
    "/NUEFZL9/h35MO/Vax8sK0H/O67cnw/1lQ4hrCyXMGS1a1jQZhLZfTnQ2ah560PCbuSyy/tISjQ8"
    "3vIebAEPbLJsScVnxc/+y79NN8DoNIXLyISRUWC2cepz/KPMSJj7xx23Tp0Cids4ythX/nnpCJbW"
    "U9fKcLPpfNcAdDt6nh8oBmrx50TKLD3SohBESJBF91CpRl217P6v28z1f990/PjTxV11w+n8unp0"
    "o+jNW1g5xXuEDwHb3f0yeMRgGYzdvZGche6FKjen2YF74N6cZ4TKRth3Y+O19w9Vml9pt0n2bvLU"
    "2rPVmEO7ipIIZwAEQCQRaiUCQ36cwnbyvD0Pl5XUAGW9tdhsY1maqrx11PDltpWuogCY4dfs5uvb"
    "X354V1XmIh0luxJFV/Z26E7Pmfidfqh3+j6+9zyKvS3pb3eyLL9XXYfrZKYiwKD9Y+WfG67O3dbX"
    "Bvlg+n7MPdfqV0uAMNcgx27DDMf6f649f/Pz/j5aLIvQ9vKLGMdtFT3aYYSMwg1OHIeBrqstLLIa"
    "7NH2c+ajlsDDATZ5kFQ4kIrzEGpbnbw4NY3KptBv5jWheXl7Pk1dsZqt3lciFKHjB2uN1W6OQjar"
    "JerXuW68LU2vA/JjbBIvhNod+v0eXes9q3zrrZmro7FXcPHV4bO3Pfd4kouJiYmUTUidKsP2FoN4"
    "p5o6imOWeisltb69l9jVi5ohC8pkqAxnSPFtpDESrKL+htQqn7vrhR1wz2Z6zrGPMbG/g9NkscMd"
    "ZIe+uJamOggdkboLadOp5u2K/TTmWaDRp/HVQkB+WbsXJmdDmZML0OVgi6kn4gw0ihlS7xdHfr8q"
    "PPtLfNcPWUMUNr9q13PTsp+WgpxCeLziI19fu0ev3s2mhFVVTeOg/TRP0qvl9fGcvyLxlHTLsSwk"
    "hAL4VzWBSFXCbCR5TnNrPdHEhSQC4aoCaZoEbrPp5woxd8Gnv8uVj8ntCrQnKtQrHHR9+jLNNOq2"
    "KQ6lqgFULDmnWacGIBWihjIoFqT35eJvFibCQkIj45CAXddquwt3YXi6a2txMRjYH4ryOfUmuxxJ"
    "ZTi5EwuiY1QIBhc00CCAcn5SOxuTThs8RGbnd4Vsb2LRZanS9dz1AMuW36S3LItqQIBsG00S4mcE"
    "CanJmFyfMt2ed9O+FYrC5iU5ynkGbnRjmerXCmoTJJbVa97xMWuyTLQxUQRHRbebPfd3WXtjkPWL"
    "aGcsxjs6j8swde2OMO61HdIW3scBpNC4C67mN9Dtl75b2lYxYZ4enBwlNLNsSVr2xdrN47T3a2m3"
    "SdQpJJNJNXnjHWmwLkPeHNBEQ7JAncQ+I0O4ORemnhjsYvXod3cbXt29ByoIhx4VKEJJjQTJ0uPV"
    "49YndcK6cyNECgypguFzimTFrJt06ZISSYuYvcH7hQdVBRJrcIGWB9YrEDgYTDJDGCnLM6Syotb2"
    "ILurHaNcu3nTAkkkkySRg0u+feiDkTE8Ra/ixwau5HZ4a7WFyLrnTu+ew79jPDsxlfG7OGtYskau"
    "/ydTi0RxHXhDCJ15q6S9iY6Ew7CNrFHx+2MmNWqrLiGjiSg/ImUYGEJoimfjwclF3uH5lMC4mxVC"
    "9mh9y9yqVdXKnhKYhRRJfH7WJ+HvJGYc+kswqaeuGtYxujXLDzhFbCjVptg3cdZwhvINhlstwxeF"
    "6FFpI4sMMbWoYm/aIe6gyOsdh2WZCdEGxyyyoa4kX1xPFYnNzkmYhDd8N0xbxOc66b4aRuZpuszn"
    "jxRFfZ8Kc8CVM5X5j/TLK/2SdKnfPBkwoD+EHUPCJASIRcdCLKLnLttrseLw47fRlpp8sGtGEfXo"
    "vi4+ygud3TtqKQVMoOM4hLa7jcODJmEwZGzPsnQ+ac4xiuVrnukDbOlYyR0zgVy8wYLBmAtqbU+m"
    "BrWEKsSGw62usIzZp/I1JBoiqph/lk2rbNtkHJ8j4kChuvtw4TZ5hdVrqA1LdMUj7O+oxxQIKMkm"
    "G836vF2tNXZg5wwJxc6Z7cIqb9fU7/M+F/3zoIU2alqq2ovph8QYiNx5zfdqAqb00ApjxYy+m8Th"
    "4rADMJ3JsGUKhtUs8bQJMPbIUsbbdMvfTs9vus21n2l3dq9KU7KS59GnPy016LLvhsywDxNnPNm9"
    "o8oznRRNP0sYvztnZ8lRLq9FbjadBmRVUc1IHQqIO3tqpl7Cg5tALVXukBaZuP/j58TMCA873opf"
    "5+p8NPphexg9cXE6cTkcSDRZ02QeOGjB8b4WtTIOaKaqt8KziSakvTMhx0xsT13nx8B8p5+IcvFR"
    "SyytVQQKyUWNakRnuWW5ZeiXGaSrASIKWpqiImSltt+9bgKaMWtuJ3wyeHve6+Q6zu4Gpq2jQi7N"
    "TCFPb40+E6qIkEtN6SD24tjMIAoDKeWGMaHZ2cmx10dXycr6eBtqlKuDLuc2BSzIQpSUu5Ag2Utn"
    "yKMwrMMaGupPO1rWjM1X03W6mtOeeulvRlDx2DmdjLy1TiDqL7zI2U6V20PyNGHt2M+bcrylLFa0"
    "dJwavVqKjfCW+h5Tqz7jBvj6PLywjTMqHDGdJIlBuzjQeAETzR8XT1VejmJgA68eadnY1BnLlZRx"
    "uGLeIB7MVoboO6WnP0oXKC/s2IRXr8VrZe+WxZ+KrppqXb2dju2z3tYvr+L/IZynJ7p4WFHLSemw"
    "s0wWqBBCGXjAwY2XVak1E1GcDWqMa+HiM/25Q0ZsupJVVVVVVVtTsTo7C9HZc8x5Zw4cQvYhsTUE"
    "TEqMxt0a9Uu9szeJUFhhyGcapNEpMc1mKrzTi5fk3sqh7mZijBQ06YVVNgUI0xaJktPpuspDwLHo"
    "yY0GlotTa/6/e+Onfoj52sWwOiSdM74Jsh2Zo5lkkSwzmmUHfdpraE62PuX5Ee/cPZU5S0Y6ExnJ"
    "HOEOloqHRFnxbJV806EIZdSJyiQVTlnSnVM0vJaHLrKihdds1yUZe4GNFf1/YFuqkqYRlklhmwmR"
    "g1NBK7kReEIvRPT67bKGjl79eezUUxqjx4u3UmrNmJjuKzDVq7c4bfWA+BfGYwklRypn5+Ujw89i"
    "3pHs9r90zzpFVUl3qez2Ot1UYtppOHtYUbbbapLXVwHQvA21K3e2cavUBMxs9hD5cyrdTB3ncQQa"
    "KvJs5zPrYbmyrpui51UFJD7q6iiLMn3ovaLN33+nzjewkMH3/I4trjVyLFDdu9u73m+igRf9ChZn"
    "djqLzh91u42TpiywhRhlULwIezRT3eE0Kzp+LQ4bBbQnZrU7AwxqgqSCipltQImbJl6+Yru0cMUM"
    "rJIomEmYSAEmCetxr7e+shlmf6Y25oTgy2P1nYhNBsCEG2T1ddbHu0rhp2s3fPWhqYZAh2Vuj4ZT"
    "lmYu0nlYzvl5UdEEokhIHkUyQzWeleXVUv9/UXnBwcSHyyn2KEvfnvt4QLoayqO2ONNlA1lYdY6r"
    "5Rc4W3UUa36qPUs5Ho2oAdxbfaQZrU3JM0hBLbD5E7Gc+F7Hv1xM3p4+vbaBzQVSSsItUUbaumNG"
    "k1ok2LQAovyAJMZFUD2x5j3NH4fd+58fwQJ/WfKf1ieuBPp/MP66BkOCQ5iUySQ62EzGfrAgw2wG"
    "MgDv3kA3Q7KdkdyafN0uXw7eXv//W2cDB3Rcjfql9JH7+mMo5IqWj3eFdH1fmUPOK+uUHqnBweMI"
    "xygr3TvBMXvtty9MSIvxRHqp5ogmMdLhwEWoZj6NTkARP4kok+0JvJTy88IH6gNDL/xwMpREGNGD"
    "/ysytgYasnqaxZCfqgwrP2FJVFHaz3soIAkyHvFMk+cT9MICWt8KrrfTmtfoz/1WNpL8OEmjZ8i3"
    "W+fWjRo0bY0aaWkoRInCXDD+KDBkAIK+qPhE7yAo2CASGSYSQISZIEhjZtFuW/6m6Sjy7pUkPvQk"
    "D3RyVoyLUIUtoEvw8JZmGBA6UDn24g/QrZXBNjbjZ8RJG31cnqR8nJk7VQi9DKpjBy5KysIWIseu"
    "7dvLZOFOXyb89GF2C+RovoeqlLplGop/RNjgsXfjjfpnt5yxhPl2khnZ0x1mpN9hIx8UxS2Q7F7X"
    "lVa26EgRw3wMMzAwzMMthouUM0ouc3Dd0hIGewUSKJhk9x/PAvWoaufj63qt1G94NuZVzanRA+Y2"
    "tnSXMQLETl5QowqydbTBdyBkWrJa1qqxYS6zAMYRtrHU0KQko79Rz8hROhJTt4UwRZw7N5rfYgTM"
    "oPe8HXh2pbCE4oRZbF8yCAJpucyyiSW9F5mpLqvpDhfGyx51tSDv1N89f7d81+xCHCLQVZUanLNl"
    "MjtALxnYhAPz6/+05tIDbK05fn0UWN29cGrAW3suIFCHNC2zN3XhIX1+HTTeZ+aHd0d9jqIk52hw"
    "/pKXdtJRU2QeJmoDrx3Lsi1iICECBiqtD7VM5HQsOMmqCwCECH1o0FkZK/S4xxmDTGgPgUg1hYSN"
    "xsHrpBNlD3dPITrW7uCZCQVOrxy0H8a52SwSutVBg9zx9KrkfoOfxNJRHq7+l2a7wCewoFxPLpKj"
    "8RdBFYS6Jw9KD7Imn0d9gyw6iGWHn33Nl6fzUFs+303GqLzxMPZOB3nici/bLLenYY7c87/5Tjyx"
    "2rYybLhvs33kM8TwiZkVbrbdNnCjPE7Rfl0s5JhG1M/imZ9Sqtip/vQ1L4lus5S3yNhb43/VY108"
    "5+5OQizSVq/2TbbCdcCi8pbVi15MrJYyRAamGaDgv401ren92zG0zvm/kuls26qKtJPpY+g/RnIK"
    "ezN1rWu6jKDWwsede2NBRdoooMSFtBKW0RaQKth62IcuHhbpPi0r0/F1+EcXHWHsjt2FA+KDmJIm"
    "Y6Iadc+WTeIgDusOl7zYHM56gzkMAelHDyob4AdQmtNjKtEw+gpSlKU6vZ0aMHIszOMNbiUo9EL0"
    "4uW+Se7sKcohwRE34VcNhccKqjnoKcpNZhRDB2koVxdiioxhPQ6TDwqNYL+eCLaHd7qiTWzGcaVK"
    "OH+zZfWzz+L1LMthSoPfTi6uqCuNGybNehIzLXSAE14kzrNTpZITu7u0mUNZZDTHsnOUYOrYNA6t"
    "0mYkaZvBIQjE6Q6jq/jXbbJ2S5mnHhehRqmm+8UiWYjFoOnD5m7GGOTHN7a2lTYL2CTy+LgvcwJX"
    "9BZzCpxykEpLlXvqMDjl40dQQJo7q5BVJVMNHLdXhgaxNMR8iGxMUc+PHV82Qmx667rpftoYYEgY"
    "/Gu8PSGUdsuQMAIkCBlgNBAGj81Ch5nZz2/4EAf7iC84iYD2qCRTsqKCU26YAAAAAAu1PJasUBXu"
    "BE6kcvs+Xm2yLDL4AsnIurJJTJTSC2VsqC2VsqC2tqL5PDL9rCgaVSKEfWvaIUWTh0VSSdTf1QCe"
    "xvOaoCXPs7IhX4h3UDeyWezuv6pRDvuSrK2aPnQUwuq8JOylrzoq9dPHzGrtoVRXf7dPL11+aV26"
    "nBPgHgcgcdBdrpFPaQgNEziDS4bz/cyPM6XMMMUWHCuxJJIEepYQw7ShBEAoQUQoIAUA8EUHKKQx"
    "RRR729nndulnjeSiFBQUFBQXefdSZJ0HEKeE8OGK8d8TmyBk6+U3gA7wBgAwAYqjysccpjHXuTe4"
    "xjGMYxjGMYxjPctq3bmKMUYxjGKMUYjR7fn6Xt+W81GijRRRR9D4vbwo0UaKNiK809/2/cAAAAAA"
    "AAAAAAAAABqryIiIiIiAgICFtUIiIiIiIiIiIgICIiICAhAu7uqt1VLRES2qWogZISEhJmZhv6EP"
    "UV+7QKHTRJjDjscczduvu7a7A6cAjOYXR5DAtC2kGxFagHFQqliqClXseE++PfIYu5owh+59nXqy"
    "zZr+LbNDmfKl3uOlcMWlsSYWp6MvKaGy8CGqXIR8XNswWND21ONvcNWZsHDaHxXfA7Qxo75VUb/T"
    "5VwxkcKa4TbgVjZmi42iizVMnXZOvjjwP4TzeLcvsa1tt3+CdQeLrVVVVVioqqoAhOnAAAAAEkkk"
    "4DMWP4oVLGOGPPjx16sipm4VZGD0aJts0d0MtGhJV7Oqk3lbR/TQO1fNriFY3U2JtNL7SX3Vyg+g"
    "kRxA4jH0cKAzExqkMibsO7sdW7ItihyRw9ENvkVsZomLQvjWiFbQiQ4vPgX48TzpOoYNxnGhpHN9"
    "VvmeVWtfHr1egAAEAAAXi2rXi2rXjwAABQJJJJGSHRhQTkUHO38vq88fByfqszJblIIcW9yfm82e"
    "D7ce1JbgQQDly5d0Svy2eFErVyNR7mA/AbAdmmulbP4ddXWI7KZwqlN+3PG8vs65WdlnohVXgrp9"
    "LZtW91iedL9kttlV7zJb+VaKLJk0Fxhcvlu2Y1SPVVnwkoa+6MMaW1/ANpr9x9qF+k0XuCTpJnT2"
    "O8HZXLcWul1NVa1RtWO/fOwOLucOcypUyo39Bn4dcbrNHATUQi/Xhiqj5vJKUZZ8LN1e7Rho8uka"
    "qJ0QjRXOiQUGS4aFicXIvLCuK4k6m+jvZPbDneDwOMzqJbffythYqqaKKJVHwYU1r0Nk1vZtyMgS"
    "QMmQxlH8medQHSbpNPb5V7/x7HrPOXI0aEtzRIPBxXidRgF4mc9hPftZureRLyLV67Rn0mRjn2Nx"
    "5ezRFI6Du1dxHOF5BkOcgUQIc33D0nrCEAUjLbNbWJTWi0yzTaZkDBYEUCCwIoCgfhsAwNYfrP5Y"
    "QhtKYT22QFkWRRRSEmhVwaX/rYbZdWyoVa0tiyVizQljWsxhRUTVNM0rU/Zpbts1jNszFgmgBxyD"
    "vGBCCgmHCEP3pVAbDhw/Nzbv5+uqnNp2Z49w/A24E9/b13PU/d3ShJ8KfMCLsgcB/IFKSST84QFG"
    "+xWaApfA+xqHgKpZNEY30taML+4x/wiek55SfWwAs6jrIfSYNybxMtGjnOcKQOgiknCHKO5vyC3Q"
    "4VR90KQEOZkkCfZ9WZPf+PcwP4vXF2DpEHXBFw+b5VVQDqq7gADqq7gADqq7gAAAALda1eR0tBi6"
    "gTBgbykFNTodktn8x4NYsHkCm7kEOvyWB/HEXzsE26DpzyF23fg3ojq0yoImUEEobU8DwPARNu50"
    "jQNXChMZ3OAgYAvQoAUpAHUpCoInDffrwqmRmejgAinhznTm6VK5sWP0afmP3l9kFgiQ8CBCD/aI"
    "cDoFF0JDyecA0qGjdbAXBRJ9FAHgNyIbW0Mx9QFOzSP72TQrZgV11PI2GwtOJvIdfJ6b77XkzERB"
    "8JRAiaVacxQU6eUlStjUxg2vqoowiJlWpmoI8YqjvMxETYgRqsj6ktbsc6oOSLCAAhSaE/GCqhJz"
    "LhSoAZFQ5qD7IpZYAKU4xPkNDgSGSgGchQLSfo/fAWv4KO10oJjbt3H2+mUIQh8DgOb3fiWukJOO"
    "OItMMF9a/7pjqRNj4QhCn+hD+PNEM5n+n11z0fcPLBEPds/F8tttuoP1AQ0PR9AWXzAhAIQb2mKE"
    "ULGoPEqQihxIhqRAuBrqMKRJRmF7771ubmx3QAPKNkRoQOmKxjfpkyTgFhoxN8HRn+FgmEUS3RXn"
    "58jY2riboLpgxWppRrWYjIBxiBGCVlx1wjpEfrg5Q4cVBHUYYAzshvc6dIgvyMPJ69UdTUYBgE34"
    "Jj8EzalU7p4n7NUt+MDvu0/ixutrG2QehN2yHnX6bT5l97KclNnyOMPh+114Raev3JLDu/A44xph"
    "2XJAu/i7KzE06KE03UrmWu21lJPogcbb5qJ7Y2Jdiy+ogpFkwd/YR9JYgxH4bytfM7esQa1fwm25"
    "nDij1TzVx0JmGDWg3xM9B1X/ifPozyK60npPohBvGtfHaKffADpvOg6ZafOw88lBDxCSIHBnYcNC"
    "YmtOGWPsz8dp2Z6vVt4V61Km/TgcvNZcmNeOUIXukcQQ00WoSKdDzSRFkxp4PQJjbyuBrwLgqfi1"
    "dhjvaqjjLhSSZLomsuEwbIKlBNmxoSJ7X2omLb0g1SbVKEAdMWo0Qe8T6XhAe3fcgG853js0mkwF"
    "h3nTTEkrJ2OQ0/BFOVNfZXDNZTejdovIBzQ1KD0Qdm29RsJxM+mGdmSSGZom2D9/B2n8Ch4SkU5V"
    "K7jfEr7vex5sMCEIRBQisZAeXIGYkbh++8WoAyDIBAR3ql7sgMz5+rI4WiJ27hnwrw2TyMcgrM0M"
    "ySAVk4i2OiIl5hh+6qnCJlQUkxRCBu2FRXyGd45ZAWsx7N5jBiFaUlya0whxOGBWxcQCmC5gSJ2J"
    "gHz5LO3oMnCSE/lGQjPaH+xwwUy0whYoCMkBWYWypQFH/d2GQw2oVAHVlZXNsdTUlXlNzbG2ybbx"
    "Nrkm1LAh87KIbLoLIwjBGQ/IMk0gEYI7gTkSJEiZkia0isS5Ufm94BHvFN92bQd9cmoi4zUdTkdc"
    "5Dz8tYnGIogtanGcA3u/3/N8tYo+ml1FSXX4euZXy2CUHHQMzoCEVj+V143+F+78uG0hR+SeX9v8"
    "1aZXVVWejPRTwt7nMsHz+dGGCKYU4cvX2cw2F6xpwLJ51EjXFuk2zzWrCBBBAdy7F5eew9uvdLxD"
    "/RKXqhCzbY2vi1cm/esXNdRcvh7JJ05J/U6PDpoikKnIwvOzHIKEitUCPV8qImK3oiXfhivd7E6r"
    "V9ekVPxfpP9v18Nj3IHDl9BAp8mg/kIfBDSE+L0lCxD5wRIhgUI6vp0t1n5mxa6vuIX9/iSQkSUA"
    "PnZlHzBw+8+P+euEWb7jo3du9BxmkHydxJucVz6c4+qm8TtAh8RAh/f5vxprb7Lhl9H8B+Yyqzuy"
    "62zYQpXWRzNDp0TbLqzWWJiG7p+xEtdXXL+2qCFfylewNdHw+USJcqW0w4kNifnQ/5whk+mFJJKH"
    "f6xo0v1vd25aW0wijtCkFMQPpzvxogHpwQe2SdQE1JkiAAicfj5Pp2PAG5tkvz0qeUREDixZ4R/E"
    "RA6J9UJIQ5iUz6veVIeQmoJgkREqAdzhaDa20LaWhQtpawNENSCJz0HrOrA3y7y+1+X/MTgCJ6kI"
    "3Dh7igmBY/QmX1/RI3SdIQIxjA6YP3QPq/ce3PR3InJT7ZlH6/sT+0B8ymrv6tv0gBuUfBFfGkaf"
    "1CP8cTCxlSOlQTIUKssKudMuv79Kc3Ycxa/KBqh7gEi49s1UKCoAFJIRIyEZFe0T5rjd3ahQNfFO"
    "KKUIYZwniR9pL3HPveAAAAAAAAAAAAAAAAAAAAAAAAAAAA77n3/ZgAAAAAAAAAAAAAAAaAAAAAAA"
    "AAADbxb2L4UPCRESKIlHyr5Bym/fAAPAiYaIO4IvgFpUDbPHvC7lSP/2b7rxCHuTBvBxxpf2whCE"
    "PYxFmqSSSX6kPc58q5hYNwPeazUTyOYD9KeA0r60L081BLjn0Pd7OYM2CfuLOZ1jfIdHvB7iKKko"
    "eiNHzBHju/SJ+W+KbQxsXk6jDoFyv8lsIpiqyFSeT7KX1LtLbMLLPccRCk2T39jOo/rLq4RmOYZA"
    "gocr5LCdNZk2Ruj5JnkaN+vM3uQ/qCIeiAprGBGoHagIHyHeg/GzHPEfZ756ufQRhFKfOmf6Z9pD"
    "ZJKhNzRtNmEhDfVxfIEcEkj7nzUD7JgffesfiHPbxqRTpBhChMCd22sE1KzT1jBpXI9mTmIaCGB1"
    "hISFC6QyOAWuMRby9yQmkHR28nemESEGJCMIMEknKeg1eoOkpKKnsftsJQUGIhUqbiN/PtN1JuEd"
    "vQKsVhAObHG6nRAzwGTJvbbpb2Rz0wqb5VJS+5ym/osWy7zmbA5d3tZqkjJY9Hcep5xGKIb71fJO"
    "Beh4GjWT0w3xF/93z+5QL3l3GeEkNrsNjCKVKUC1znFS1zc5uCUBfX6l83y3x7hLuai3eilGdV8h"
    "V+cKyQfKtEZCQ/BvEfPnc4p0NPCLkPJFaZv6bxzEeLuPAZ2qfdFc1OqFYtPi53Ga9KzWUfyob3WL"
    "23TJAle4hEBCYR6SnhhXYRqgS2AQub0J0b87UU3uN8X0Crj/8+ICsMlFf+rdIh7R8VYgYJrH4U0A"
    "fqsEofM6ByC2GCvaI4JiGAl4IbF/FS2Ta+lfW+h+E2+UL5IAMXSPD368OZmZmZmZcczMzMzMzxdf"
    "tqsoFtNw80ZwEomI/Yl/BI/Um29DdTwVar7Kbc/iE7TR8Bfd1rtfaVeZL0va20tuEc9rWZmZmZ0T"
    "WvZ6WS+Qd/ep3p3obZmCHkoWzBiiFJQwQDmrFWSG2lLDzhT9wk0gVmNQwDekCiAe/LHOKv+gMzP6"
    "GSJ2tn5cxJRj7rTcIwURadbsZkQUWScf8n1D9bnu6SkVY7nsjTWFIIPx0LEEZUK8tuWjoOjeB/Do"
    "OGSNJqWFBzT+eUQsP7P9MtLeO+98cqd5m70txdBdjnrSCDNMOyQML2U649EJBGB0Ud37ZOL8LOZG"
    "IE/q98CCIIielB+rN6wqBARPQiwvZgtlKLbkNAgZoWbETzPeKMbREvS5dfFuV1PUbQuB9ErJOyF4"
    "gcIO2rQsTgRFnMG+hKc1up5bUOpKD+c+5y4mEUgh7NBM4iUTTQyZQuGZo3liXHGCFSHQ6faYNq+M"
    "pB8srYjftSCwlMg3tTTEH51y+fUNv2OUjPanf7nSX9PLTZwGI4hgf0ah9uz+KWKuQe40Xj7cVPaV"
    "6pb1mISAW5dVTJKY+kdWg4CKs+Z+Bklpd+NqcCfvfe9Ae1T0BvD3XIEvmv0UIZiKvdMtLUjlX/YQ"
    "TwsEytMlkZSPw5hAUW9fPuQ8Gqgw4EJBKso5DH5z6XDgMN8x6D4BR3kiH6YLwaR+ZHGbwIkl4RRO"
    "n1/lVBWqaZnWIehzDdL00bzrRfrUEyRfDTgMJ5K8xOANqPCYXnECw0bUzpZKCAGdADYOblSyGg/n"
    "ggng+f/NMOk9nx/nvsm8vsh/NwFJVa357k/7ft+/9f/f9/Vr4fo/s/T+z8X7/5fR/B/X8FRH3UUk"
    "D9hLvct8JCQkJAQvAhcrE/3P+Q+iJyv6v0lu77Sj7LB/I8MXzp936+LJtK9gwUZPwnX62RHreoYb"
    "+H3ht2gLT1cKIkSuk6iB0kEAQO6KDEFAoooo/SzcxjGMYzxtW7cxRijFGfxXblGijRCwUF2AOcQD"
    "o4nIEXOcemhUGOqwORP5w+Q+oNhw9hYsH3i0YL/CKuQLF5ARP4QP3TTx9LsSIb7X9CfpbDJ4HOHp"
    "SV5EEzZSx86fzD3WdMxD4D7AHQRMq7r0pZpD4/yZZHzG0rY/GYoEEQjmcE7hKwpGGsDMRY2MdScQ"
    "5YFTt6ztO0/YJ77PrfxML+L6gyUTX0i36jPmPqL70/1nn8AW2qIq4eTANaKqIqto0W20Vk8h3/gD"
    "RYfQn0EA9g/KLJPhBwzRhJJ+UfyoYnm6PYdfv+Sqo2hYK9TQhYD0/rk+ulkkJCm5ELkPWnvIJ+ci"
    "Jet48jtQiRYnxbgFPA7diimifBdC2kCqKTjAxKiBInrSNpBPA4Lua7blQJyyBPqK3kR6zd88MIWH"
    "cAdT38Wg6R4iF+Bgc5MTY6zYWfA0CiYDiYBGEGRhNyHyTidPfHJmZcI+hKTTTVy1ZC4ZlRZqUX8Q"
    "SEgS95qKRxrTCsJ7hC8NcqysKK2ACO0IiWDqM6GnkENbiCpsKCjLHczMfIrxeNV7wAAASAvG9le1"
    "RIGeA/8ewTr0XqhkFxCK6SxzIYbSJtm+h63acYHl8/XbUttbRtaNto0atLcnGB5jiGL06xG8rENK"
    "tNBoLNQ9sOY7F/jSiliXHBQ7U4gzc5R7FXngXOkbkMTBAOgOgSEAVmgi0GNwb2GDgFZA3ni8fkwG"
    "4NtpVVVVVUGPadB4znRVNPEss6oj5shyBsyhcTqI4e8oqEs6c42hDxqqIgZBh7WlYiL4pZwDvBOg"
    "HqLAcJpwqqV3nBOL0k1mAZLdFnUXkJJQwhaBRAvmgc3ds9mFyCcAe0s9xgZufeuXG35tlKY60pnl"
    "rtBi0u5F8TCUgjCLBFhFptdmLnMjQGps6CZB0APN6hHwFMcg9vBBu58+dE2GbRmwlTTTV3q+++u3"
    "EmzPuYRRQ9tVlkWI0U7XvM3vByG3gg+wWhiHcd0UPxPyaSQxomNINqlmbVDccWZ3cjotkdN+idOn"
    "Tp06dOs5zU0uhoxMSnTqrTE3sRcca1ptd7EvKSHE6dOnTqqXG/EyhaJ9eF2STiL1isd4S1lCYc4H"
    "j4qNL6uO975iV0UVJNYWQhFOQHvOSwT1DYeKD3aXYUQCiXmo0wGlD7OySSQAYXi+u93fGrxrz8wA"
    "AIAAAgAAD39eL016trGrZEO5PUbvOkYc8ciMJy8gFFlrGoCVu3bYDg44MncKhN2lAMUFggrfd4lD"
    "gZWYxxMWhtYmvrX4bUOgdwDB41dn4Iw8geUPGAekSHWyG8S0PAw56NXVEXYPoFJSRO3plqWWvLbL"
    "ddqK0ELDykeE9tQgIjInw1aSDBPppRjegGf3pvCQOHfg6+WrxTqZJCJCAKm0rapZamyzaWUp3brU"
    "0MsoZYikmu/P3xrvk7beeqGAoGwTgH9kEs719oMQ+I53+kf2/kpuG0uqDuU7YgbDeCc+Qec2m8NJ"
    "pCzlhmhglq3TgoAzKirYdIgnAioyBAgSQYCSKwEiAeIhKHLQzClQ1eR3ABVSAcdepGIWDUjADHdY"
    "IlXwkzYqBvK9iZFUUmUb0Mo12JB0BgAB6CID2XJJdTXs2zDW1swqTsicdLPAHDa0qu1JjQmcDOoA"
    "nHYj8vcOYQOXQ5hR403O4KRE5GxZ7IxVbJrD72x5WGFaLsB2+0AmrLCSKAOOm6yvKg6jaMNoi7Z0"
    "yjqMA5y694iotLksRg7wif3sUq/CzemDQFd0FNgPHcLiGri502bU5qhFr/fQ2s01UlFghRHnnFXV"
    "yIgaiCldJBD8gG0jJBIqSAEACRRKyD25Ts2m9Sxa82sc5DEIQmdCB4SzA0mDQaZGPyRPYNtH4Moz"
    "lNdEkDNIIbJKQQqpKnJh8SZCTlaRYB/Jf72CJ7aoQvjuPkSVjBP5kTSIkBD0Klh74RbEkoKpaZFP"
    "dTPHdAsJA0IBloDjDClDJcSrREpSLOR27UVCELTCsjkKJM0qMEGlHxrbaUQpLA1/OZrXh8iBQWMj"
    "8KQCARArQxg8yciceYPjCQiMJCCQgoHHlSAbyhLgkCN8nzhtxNkPz8gcn/m+i9G4t/k08Mleg0uo"
    "76oGuQBUg5AXT0Bci5dRzjIgrnixDJAOZuoUf92pD7CF6L4wykooRYkLDC1bajBg/0RPQmCqcUNo"
    "m80kqCtZKAsIySpphYIT7QAybbGgIpP1Pfsaz8INByCAgkmvG/Zyv1P49aQDAssDn9Gi0Pxn//1z"
    "8LfVBu6uENivv1U5QRL/AKGEkUlGSDaWyiMlRgikUL1bZwYHU8HY4bYTUZEAdgVYp5LY6F46XNvI"
    "Uni/aa0m1GnZgLbNS9CePva7dz4lHHvBrnNFyYMg55xs+JLy1+UnA9vA53HIavlVGBxTSENqCHj6"
    "wUc6NxxJIPaQdlxtQ1k3Ldfb/4GjTKJ6slBYibUFWCKoUiTeTEqTciUy6c6bLMtKE32NYamI5Vm2"
    "GGaRcxtmRYGGZlomSpQLEcmYbbhvrUk0ibBkBgmKLZTYaYWjSsIQpkEhSIY3JIoTLKSGkJqTJiHq"
    "ydJ7yO0pUdtOwAMKiqMdEimaAgW6CLYABTATDFHTr6kSHnVrJ1y+PNrckii2eHLW8A6CSQ4CBwCA"
    "2pAYJACBQ875FUvyXo+o3KrizrLIGA/IGvAOCAREPZAEX+LVTUkWL3yHT79lQNnl+Xp5dGZ6RAzE"
    "0EOYLjBj+uGkZDAEvcpRc9hMQ6GvmvCo9Se+BCBacpuDl1mymcQsgDl6zTVEM1Pfyvk9eKScXF4B"
    "Bkgd1jc6RaFLMaxgQQ3/QfdfTevv9nWX1g04cKZDxmWPx6BdcrrXtGkWJE+v7LjtnrqO1cSQJIIQ"
    "CCQRIcG6qOjKLScUmsTMyW2Y6MbKXMlEiW5g9AYecwNYmDNjQbTRaUm9AwQyDIs4iEg2ghFQKWzQ"
    "JMMpIKAd3Z4rQHWdbMWEq1jQ+RqNqL6ubS/2vl0DGq30cizlGptaHyVh3GcSXNgB+em2N3Q7qmJD"
    "WG/czrdYtL8mVVO0O6Dn2PPPKgawg12tfTRrPWhoYrlT0I2FNn4RfVxjmJIIY422k03xFxCffhla"
    "sLnJzxbOxlMk0W1ykT7Rp2T07Oxtd2A6c7wiU3Q2rpwhcgCCECTCBKBwVN1WR5M7cNpRhvlwr12F"
    "VXi9I5szZNO4i6GMCpt3UxjpsrDUxN95ymHFNndJwxu1JvLk0wLqybTShvwSzabUMsNVgoSWCACA"
    "kgTWgyKxm2G+onl48vHn53pdQAAAAAwAgAAAAEAR6b7E1myKhrTZrZFgQIb2qqqqqAAABQAAACoo"
    "qql1lm2/0vVy8+M3eZTrJ3HKak0ZvSDxici+ZbTNIpzRVw2iUqxSLGQQgkIyAMgwJRvBKzEvG7hu"
    "7bS6yZxl2dRdRgyKCwYixYMGKQYgpCyNTNJcIjmGjF1sbUWYcg2JJ0GjSKKKHNKqKpKMME8II1eu"
    "89Jkt65JnpeVeaCOmtbRCjRKzfvFTiBNoQNyYbGQaSOSJCiO8CQjkJQnBgNvC0INqDUaNtjJWLUY"
    "t5Xpt9ROvaToCHR4gOF6z9CKRYoVyhRSQxIsGy5QsMLAokYCKRB6SAlQZCRnioJ2ZDs8Q3yxRuxH"
    "LdTZU5k1mewwffPxlvAfv07l0p5HHd2H9kzKKHTJedTV9dK8nhjGQwrQ5mNXQhMGSXIB0DDCTMQ1"
    "gdpETTyNRLKACgBFA2AZwDjn4r5Y6ecLiIVZpgZyaXQwIItcrOwh4wyA8LAmGcyxASEVfpWQIsBJ"
    "EisBqymtIRTK2DbUts22wUQRS/KNYIEb7YCQgB0qL3aPbDt4WbyFz1TPOAAJ1cA1b7k2GnF2GYdA"
    "SJEgRSQAIgUry6yoRSGoaAlKUbjIXinqQZoGbmqDladWPePKg6EvzonDs2C4EK/ft6+oMZ4lefJM"
    "PRHkIZbNhETxKCdhZCYEcIG+hRBzFoHdipBA3hoEA0cNadOZmHQfgSEAiKEFEiIgRQ6xsvUQE0Jt"
    "FYwJm53cX22dCo5s8oEoro5abolfTRfprAnisUDw7G7IZCLCqkRFCQOdu7MYbnMbBYE0X0IBk49+"
    "oHaUG4J+iKE/jPHCwMLEsIxy/dmJM8LznMgIN5HBCgiFawR/qAYDVhD0Q7KOs+T5OCKBzgSfH1Gw"
    "zOv0SSQAAAAAAAAAMAAEpJJJJJJJJJJJJJEmJJCEJCT4Oc833D0lojYFbyj1kHAIQ8ywSiTzutf4"
    "gf9ANiiN8DMRvXNAzHOHlJBpoO1MFgZ1NfYfoPIiD9hBFMPT9B1CI8BQbNfXvEX1D9YRVirG8vy7"
    "kBUhtIdM0CBC70BSqdfvkREp8YH7YYkfMAfh7/OagVBSzgCdeThufIekMVELQoSfORovRcia+k2B"
    "d23tERE/DWSaYNyLIgESAsICF0AUHYgvJe/855QQMFwG/PCDCCgyMIpzwqCEHHSNBmCsa1C2UkPY"
    "rAbJsnEEkmwKqDIC3EEqIXhqLhQpCvVoVc46/5OYwgD8fU5km4bD4Xxla63pEOo6wpO+rkkkzExZ"
    "dfqzLMYciL+4R5tkEDmEPX1+bMNSE1GTiYwKiF6XhUvvQeWCImzlR9cpmGRNruNksUk4umibGALP"
    "dmD5oslRtkoBlxwiIIQiT5shSlRTBAcRBShaHcTHx0pk3zo1NJpLNrWi2LNs1tXnV1univP01dtl"
    "vny0bYjKbNQBM+YxAZEQkQJ+5M7D49fdqR40K6F7PDH2w0DIONEjoXnkxCJGDoELlZFKiVHKUtH2"
    "xe/wKByrKg9Ee0Mj4oveGEUOMVnvoc7noUS0FHF+YB8wyWDrXlcJ2m6YutV1dkgy8a9cV1uwB060"
    "iK1xzNzyNtnSfUcdXqlu/48VkVJBYjA3HsD1eUCiEPyFBQELHHzKLSF0dFIjKxQUQexNfjMNG1rP"
    "v8p6C+aTuiokNhzJugN20iADVAPTEJAwopuVW7ZazLNabVn2vW5q2IMWqJNrUlMtNYUltXzrTvAy"
    "DKxPrHmPm1wDeODYNc4B7916Tg8X0dKAXj6ooXgBmYTLA7DxvDddBFkAHkhpr+ax8pL4eUc0eMEl"
    "zaZJIIl2PDT+maCfwvFsZo60IZFqkPNJ8UH7IaiDIFiCwjKiqT21VU98Y/Z9JkULhZtSyf4iwpEM"
    "pszNxFgUEEGI4lm9uU4ZJ89uz/vSP1+vnqKHEjy4czJqYyy6VuycnE1utc9W+ZwxDJsUEU1ZTGfk"
    "cQ69z/pSCWnfTutuSizsX6C1BbQ6xDymp56FDpJIiyKecdmTbVL7m4QMZyXB4yMISJUjUir18XsT"
    "+/faVrx4qP1m6a6L5+p7vEfE+AxZUC6eF1JZJLmqpycS9QlInOVjlCuO5PtymapnJMD1hjGjhmy2"
    "AbnyzyEUUKiMkODJiDIkUQU1yCYTmUBOjnPHzvJBv59JvPNhwXTirlYpcELgb/4KHBnh2bwGkNCy"
    "kog/rDTF4h3CCQiikRcGYUIUQCMOB/fmg5eFNHriJC9VkKwTgTmkFgeHy/aJzYSpVaMqowZ0CTQI"
    "upqhkSKZlxAa2KarSmFFzlrCLCRNrU9q/KcDRzLKZm+aZUy7jpNHSlhIG1NMPKmt2EIauSFkSKCB"
    "8Poho3zmlIZiSihgbh8wfVnXq+siaNKe8J+17V6rXwTazbW00g6iLynHituxvBIgT+VWbkhYgVRw"
    "EycY+WjrLek6d8lPP9/jXnnGDLoGoUXdlkWR49lZYq+iyz34iZR0IjGCBhYVDEcqCmSlYYNNQhYQ"
    "sJSShAyaNGDBkGCw5EDzUzSVjKhJCxJGCBv0RMxLQDQgghmc8RNgiH6IkAzxNe9b0PJA3YqmqxJI"
    "Qic0oIOpCYBuIdiImceiI2ggcpRAPaFVdeAwNyEWmDGQfIAeWBAUSCvjcJuAO+IMIpECALg6LsGW"
    "NnKEA2Lz2NW3NZcJV223LU9WlabbKbF4qDQKvfwxmEswZC0o5kl9+OMrO2C0dOmB6drkBIqLlCe3"
    "I6NhCmM2gZy93bvHm7zEPSCD2XB4TOyHvEIO4mYgUOAdw3WUEEiYknL28jOSHK5TTu56UXQYBAxE"
    "VvmPO+jJOeZqZyrlja5mM8sIAXxGCjEEIEYcnRAEM+k/HkKWHXwOi7+bpDMcEIHbDQI8j1FBMmI9"
    "yiXCLnvJ3jrNEKIRO9O/a17++HiCQBQFmxavY0RsNSte570+H3bwt4XNJSu7ClcCmbouZ0zuV14t"
    "82W2VJISDURJpMoyIpkpNoYmqNFpau8lvIxm4EkYcrdWTQtINSyoFKUaWJIyiCBSykoUVJCgBhAC"
    "Ow6GBfNwlKK8OCAZwhDjt3HdlQHBXgNnqJzzO4UQNVB/N106NHUImTQIEM4g9rFFvG+ogXYbNISA"
    "Q84dqYclXo0Q/tu9jY8QyOKl2SGcqIsIbGKWOVsGNBRQxLEZ0NGORqMSFrWMMfn1qZJtkFsGjXwn"
    "KQBnKkz7Wm9ZgChx7hKbVYTMMV75+AIaJYzqzB36C9L7fM/kNB5/+fU9Lku75HfpE/Vohl0bKIFO"
    "ntDYVQjYVBkE8ACL+c0eakFe6EigXn2hAu0AxmVa2DEMhGobMFgXw5DaBE6AdixDAAqREKC4o4jn"
    "3iKLgX9hi45E6ySjBAVIAgSKrril8pMavFJC3+KOKkCSPEsrYdW6KWnVimlmQWSQgQdYnABSlKRR"
    "uTOUigRcKwBSRUWREYKNrF5Kt2k16O2sWyt47bsqoqSSSkkm8qvHi1zatvBdmESNqH0hEAyQzIIZ"
    "2qDRohjE3z/lFypyQ6w1xD6Yq9sVkfBiIecUud+aU5wOfk02R/ysTcYiHzgfwkFVIQTvIIC7DXSZ"
    "4qrd7S3hswADeeiK09soKnkRLSQAhvBAzhl/CKn28eRX/XE51SRQkWCJUAIQShgBeuvJe3EVqklm"
    "rXVpV2lVJrev6ujtt4tcjCVBQKhTxSmCSIE4tIYBmcDbRbKLAgyIiEkUgyComnPmPLVAzBADOJIG"
    "x+RUctQ36Dlvu/N42r2Movy6m218ikEJ/5y4CyFhWKqqwdXBYDA++w22uiLIWFZGFUaQkWA89rfh"
    "VupeeEzbXdLvcgmWjt6c9miqmA8GKRYEHv+2zayEP0z5KYwdFxwneXHIcclhONSAlUVUOxLHcOlw"
    "gVx2Y81OJJcIDExALLTMn2hgDKC5KuTAFTc76uqE4fJWDgQM3QfeAJYcyAgQVTKJcDpmcMV6uGkR"
    "/KidounrmjJuzLj2+Lk80ANHRhYFCPS7QEqhyo/givJBAKgB6UKJBhBAh4cLMGIyVAkrAUGDCB0p"
    "OKHfW/ANSaPfuOWUBSOUqBCBIsCe3obOsTzGQWaamwDgiAGiBkCBaHEgpQqGhAAMx8qBe7ex667y"
    "WYsYpUNIiYpGNaJNpmlLbLSptrUpGK0pNNpJaBrVN5TQCaE1BsBDFTGXhkSSkw1IrvzVGNHMmzlt"
    "u8TIAoJFs5G6cADfRFA35LumIHXFPeLGKSLwKIED6ix3pFSJIkQP3T9gT2GIRwxJGrPwwrjBRRon"
    "R5qdKGySB8EC/lNyCVAeiHQG4HLAKCI0O+HpDMwkZBlkCjBHvin5sGTUjCyjq5ZF2xLvqvX5oWB2"
    "ezxHIP6BS4G8gPYfgoO7LQpvreEbhkZBkGXQBKVnpTq3PNJwqCGo04BkwuSvNuBwV4tKIC1C4hmA"
    "UASjNNgrkkAtRODMysjFmeizEWCMNWn6DsERERgXiziSbQsEJQsqVvMXWBqaMEMQEbdYmGpVhRTW"
    "CCwILadn48bwZLm2QlSC3IrIRsgtE4kE1UzPjUyHA1KQnUTQTDuKTTFHBAjRgFiJEWKvv8EE9oRC"
    "QQZJEIEEM7ufPzBYH1ENg5pBhJFYBy9IJ4/ujAIByUVNwhD5WACpRNDsLlVX3uElWMRdoZiJIg8Y"
    "FRSQ0jl+IwyoYAcO3ntI5adSIcjpkAMjkZwt7swi65nx1wLqiVeFi4UwpkxqFmOCMWFlLMYXK4zL"
    "MW5THEM0TW0gcjpJ88VkOsMiHjGCiB3cXm9ndl3rzCin7znGjADe4QDfk/5nsKPhfnKTzL1EMwlm"
    "YMywFZMspZCW2BKH7/6RRRTl2SAKQk2LYIARdeo8t4J1XXBOAdIcX9MeTQk85SvVKkbVsVYOWqqj"
    "BBgyYITwmpYzD/Hn2jWmyJFgHyv0aHtyHLaURhIffCoSanXTcuS7EsY20VVEjEFUIkL0WbJDEgh1"
    "IA8qwQ7iDAJCcyB1tNx5kLhEgB5GB6sqhEH9kSgi5MiN16FBFM56dDWAIqZI4MKiRo758+MK1Ehf"
    "SzEsjh2/Bb0fTtR8MDkkxZEsWRnOKlrWxjRFef4c5qnh8iFmCSXj2i1Q9bvaGNVU1TwyWu+75nb8"
    "9pzbBa+0a8GGLJs05tceqvG9Na9Nvg1l8MCd04rNrgq1XRw8qHNKeEzg7OpZOb6Eb5LscufIyfHt"
    "w5dGc+VOpR59Q0bFYrFUbayltpWzbV1pbVJYW0tpbWyjDhZLgUW7US3MuZlmCYBYxkpZ0b9WuShC"
    "w+uj4dqZaa1yqFNPRa9KCRJod3q0FmKwhmZtkmUOO7ju6vV8aBA1r3h8u1O1UQBw1pQYWeWRCHtG"
    "K0YiN0ISZDEOhQ9s9jB0Zu5/vozpYfZsSb8pISU/XJ3A4sCSkxnGLOz5cXNaQrFyHHByFar87XMT"
    "QsTUGAgSktKEpKVsNW6kiQg3sPU83wcQeU1x4DDmqoyKgrw4cAhvEJuAWBQDgbQDtCHbRSxSK/Nm"
    "HSd/LkhbFBn9DkPLt0Ojd2ALtQAjSkQO/NHkW0FkN0NOc1FBCSUSJ2yjIIGSexBc4Cm4PMRUUMw0"
    "IDCEQJDVmIhZjm2AV3iGOk5GNEcE89USVJHhIEDlBMQCx4Alb4RP2j9TowLyugonvJ4Jld1Ug7vK"
    "Mjukz9zkr3KdnBxy+Yy0ECvV1t/BME+/Tg7047ary6bO9MAIjIzBP3Js9xPIJEJBE5UAsRpThZ+H"
    "CmExieDmeLlkeKgRjmBkROYQgsEgIyIdoWASIh9wFBEyLUtCGHhwN4PuFAiIyHjSskWZQP7uu7gh"
    "pT8FOCeVdE+ZmEDbLf43fB6Pp9+JrcPTuiWRQNV2ghzBK3UOMblkGPTPRHtDAtJLYlRQkJEGaTnR"
    "kR4NYO9qoEBgRj1U8SFk0r3beKe4ESDgJHpTQIIpYQQ+kigWAer21fvdMwJ1iKqTQJTxidoIIkk6"
    "7vH2uqw8nPY4R1DZvqpoNozNWOFDmwmbRKgwNIcNc97IXbJVXEmfi30KTUYNLIiCyiIiwqVNihYa"
    "1Zw1TBgbTNzLEg4oQozxVrIsBwPEKSmAmCyvZscbTOaCSiA5WhpEQt/f0aDYgbxTo5UObUGDIoW0"
    "N2AUeQnIQJ0CTQIRGNtQ1HLL7gd10HFsknPiHLSXNOrCKyO1PQDtM5LhaCABYBxnBIZl0CzhXffc"
    "R4bKtDZWE+IMRc0wecjSvhNpE1YjzXWWgl7l8kVTnzqmqcyYUbUXEBBCDiIksBEWJ02dVrrRgFVz"
    "i7PKGpuBxMghDEkw45gJxBFJNMgMS6zLAwYlUmWm81tIAlFShJEOwqwMOZAggQkGw6gmpgdC81gR"
    "mGWFBTZGBaxpA7EEgORIKxVtwhzNmAfEWGDTCbon3nCg2NgNGvtaDIg1FFIKJBR0gZia0CFIrV1V"
    "NBECDby4XDjVThWID0e8qeeKyAEr4yAbIEQiFC5tCGq1tJmbXjiBvn1ZWvlMZ2QLE19xz7UuSKBm"
    "ALzwMB5Z8kAOQqkN8KNqdzJjBtgOh7yigiRlEs/R5KQ86H9Se4Ps/6ts0JxiHAlKro64Gx3iot2M"
    "YEZJM/11ab8FyhYZIECEYvIoNV9Zi6qAUc70OB2xIUkVZCAiOw0E42MvOSOtEIerAschbYlMCmlA"
    "JEgQhEiRROZTAHsSddj0nak0w0hgqWw1lZiILBBNYCxwMDpclAzgYj4AgZJsXJDKGzWvC8SXdbtM"
    "qRmkrp1lcxLBqFkFMBtDBASAyT1eiG84pJCk7hgJyeBlke6PmAJIIpmwUy92kdiBQsQYXvrx4Q5p"
    "wvM2qBiECiEkZGUzLMhA2mspkm02ijNa0xZtm0tJWyFvdq3bL+r+2Q8v9pmbooIhugImz08agh0E"
    "EtA3xLREqNXUAVBiQEh4mkHAn0QWw4Dsy5jIIDgHKOUCX/CshOFNBHFJ1CMayWGYAn2FFUVTDIQ5"
    "z39qKLP0Oul8pvpPFQvl8W+/8cVXOEwmQsKXpdt0xRm2dxdDKSVKmXVm+rqT+Rn0nv5viUDgfjPT"
    "4qOmBPQqnMgFoy4UAIhPApKVF5v5WrEE/gRPvJGIkJACCLightEd7905e+pJOghYKI6PmTGO516w"
    "Pb0P92DkQ9hEXCLICsSmQp+w04g5jnX46uTaHBf506W9P4PTgdocgBk8kDReqKzIQGzzwWjI4wo6"
    "7kIQeRYKeSBOhnrKoNAgXqWhmFk8QSfn9joAfbrW1pGAAIRglBPAITB7+JxA5+Sg/wGgaHb8poDq"
    "CUnehVk+OFNUK/dpg9MP7KZ3AtBktAryg4w2k+8IsLGpZYkLCiSxSMePlD4DsPpEJUww1gJd9i1t"
    "INwa0hsFMM4WOzko2yAXAfMQwRcYIQ0oDxBEE7C91CBAIL4rmCqK02mm0oUisWzZWaWlpWWzU1Kt"
    "N5V6tGlcFBUlqRGGkSAT6iK3AId9Gd9VBZNGmt7WbXweOq75na8TK80JC3mkIAEURkGQDAxwc8sA"
    "AaGEPvjxDyIWvdcBLggo8EKMxEvaFLjbtrWSlNEEQP/H1/7A/ayE4nYjOVRgaBqUfCMBN0Cwn88d"
    "Agqh9PjPRrwnqMrl1gumzYogc7ZwXRtpLrY1cfmTWqTMrQhIa48JUc4GNbS1SoYjecX50yKwKF34"
    "xsWLmLq+voFUPRADBFA1ZT+pIGxGti2UKs1TbSa1aIXaGve+Hw1ZzvagDlgtsf41ASKAlqiHxQFX"
    "4IgHrOJx+BESbN92OQ5vOwiJ4/23vfLLrwv/trtr4kBo0WLafT+JV8G/Ovy709PwNjDMbWM5oWvS"
    "tr02zH9YfsMlHOSJIb6agFlQIhrroZfDoCJiO1ET+g4fq9WKpRWtDb+yrpfVFGUyoidB+YXckU4U"
    "JCh7ew8A"
)

# ── Extract + compile ────────────────────────────────────────────────────
_BUILD = Path(__file__).resolve().parent.parent / "build" / "inline_k9"
_BUILD.mkdir(parents=True, exist_ok=True)
_CU = _BUILD / "flash_attention.cu"
if not _CU.exists():
    _CU.write_bytes(bz2.decompress(base64.b64decode(
        "".join(_CUDA_B64.replace("\n", "").split()))))

_ext = load(
    name="fp16_k9_sm86",
    sources=[str(_CU)],
    extra_cuda_cflags=['-std=c++20', '--use_fast_math', '--expt-relaxed-constexpr', '-gencode', 'arch=compute_86,code=sm_86', '-O3', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__'],
    extra_cflags=["-O3"],
    build_directory=str(_BUILD),
    verbose=False,
)

# ── Config ───────────────────────────────────────────────────────────────
def _find_best_cfg():
    cfgs = [c for c in get_kernel_configs("all") if c.dtype == DType.FP16][:40]
    B, N, H, D = 4, 2048, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v, o = torch.randn_like(q), torch.randn_like(q), torch.empty_like(q)
    best, best_ms = None, float("inf")
    for c in cfgs:
        try:
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            torch.cuda.synchronize()
            e0, e1 = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
            e0.record()
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            e1.record(); torch.cuda.synchronize()
            ms = e0.elapsed_time(e1) / 3
            if ms < best_ms: best_ms, best = ms, c
        except Exception: pass
    return best

_CFG = _find_best_cfg()

# ── Public API ───────────────────────────────────────────────────────────
def forward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """FP16 flash attention. q/k/v: (B, N, H, D) float16."""
    out = torch.empty_like(q)
    _ext.forward(_CFG, q.contiguous(), k.contiguous(), v.contiguous(), out, False)
    return out

# ── Self-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    torch.manual_seed(0)
    B, N, H, D = 8, 1024, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v = torch.randn_like(q), torch.randn_like(q)

    ref = F.scaled_dot_product_attention(
        q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)
    ).transpose(1,2)
    out = forward(q, k, v)
    err = (out - ref).abs().max().item()
    status = "OK" if err < 0.05 else "FAIL"
    print(f"K9 [Reducing IMAD.MOV/MOV]  max|out-ref|={err:.4e}  {status}")

    # Latency
    for _ in range(10): forward(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200): forward(q, k, v)
    torch.cuda.synchronize()
    ms = (time.perf_counter()-t0)/200*1e3

    for _ in range(10):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    ref_ms = (time.perf_counter()-t0)/200*1e3

    print(f"  latency: {ms:.3f} ms  SDPA: {ref_ms:.3f} ms  rel: {ref_ms/ms*100:.1f}%")
