#!/usr/bin/env python3
"""
FP16 Flash Attention K11: Encoded Swizzling RF→SMEM  — RTX 3060 SM86
Auto-generated by gen_inline.py from kernels/src_11

Run (WSL):
  cd /mnt/d/GITHUB/Mini-Attention
  LD_LIBRARY_PATH=/root/fa_env/lib/python3.12/site-packages/torch/lib \
    /root/fa_env/bin/python kernels/flash_attn/cuda/inline/fp16_k11_sm86.py
"""

import base64, bz2, os, sys, time
from pathlib import Path

os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")

import torch
import torch.nn.functional as F
from torch.utils.cpp_extension import load

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "py"))
from flash_helpers.kernel_configs import (
    DType, FlashForwardKernelConfig, get_kernel_progression_configs,
)
from flash_helpers.kernel_configs import get_kernel_configs

# ── Embedded CUDA source (bzip2 + base64) ────────────────────────────────
_CUDA_B64 = (
    "QlpoOTFBWSZTWUV2eMUALFV/gG/f/////////+///7////5gZf7x49sCEF2+8u+96ffZ77pu7Oi2"
    "X2UVXWB1oAKg0FtR5Az26OFEvNTvn3vfb5747vCi+OgDtds6F8+3y9880AHGZmu57ivE+999r157"
    "edvvO+2pt6Hu7u51tt71tXnz3vvuy1vmujGXwEO+85HXd3t9733me7dz3nhPa12z0+Iz7nvSu9vX"
    "PIvuvoG+Pss+k7fdXIntslawpZga2V33eMCD4fNqW1veLvWId7c8IO7Nad223aradzNxu7u+73pF"
    "eIzazPrOeB33vcalHmzjuctu5gvu8nongjru9N21Xtzx6kG12s3c66N9u+np9jEPr6q6zLvnjzPc"
    "LlNuXKp3drbfCU0hAAQGiYJpoIGgjIDSmnianqaMQBpiBoYgABgSmiZCE0E0KbINISeEeijyanpP"
    "TU9EAAAAAAaAMQAJNJEhBNTNNDSNU9J7RNNGJMNUepo/Sh6nqfqNCPU8o9IeKZBoepoPUAyBJ6pU"
    "STUwnqZGmUaaNTyI8mkzRG0PUmmRpiN6RoAgMgA0wAECJIiAU9NMjQJNPVPJjTIVPNNIxNTYRqeK"
    "fpBo9RpoEyGQYgaZNBEiQRoQ1GU9NDTRGTU09BMTEKe1TyT9Ueo9lTQeUNDIBoB6jIA3qIAI/siA"
    "onj9wP6xkE/+gVahkaiCk1jYUBeFyZvka5ioxQypIkk1/Q3Sgry5VpkFFy3NOXJJL3PX5fbvk/U7"
    "+j2vX/p+8/sJ6Wd3ZTSxG8uV1cijkTkmQxrjMENENvczjYu7af2kzXO70FYKqCc7YubzCIgnuf8H"
    "9uHZFiqE5IdGGMUKiTREQ4rV+H7eHtP3/8j/ys00Teivwfgnrp9414qDtXN35Hle48IL3JcxG3nM"
    "U03qp8/zUTG1SpUOg45ZvgtzUn9TCrHXPJkFwTdmYIn/KtqGolHHWawKZZWqzLmTEq423l+mQsTs"
    "Nh199Ow584YvOHRVtbUstpe0uYUAKJCFO7ev278nHDKIs2OrGJTpmtaxFf9HVSCOMWW2IsUS2FNU"
    "qoZTMtZmUiOAxiuvuzxeGRXMSzbu4AiCGvLtE0ybw2E1w7nLu0RjwoeOvD2mvblREhJWNRpHd2Em"
    "iSKvW2/Zvjq29pW3Lm4qPdy9GZy55wy8m6C0sx+rVCXRm9Bm0mHXd5Sjwhd2mq8HU6O8NpHsHQcX"
    "kakrllicdMzFaw0mS0sK1REYq9zyZJgahuzgegR2hveOFZbLEUZJxU1RzMKiMOfb4ehrWta1rWta"
    "1znOc5znOc5znOc52c5znKlSqq5lgsYsghJomiC6F6Igf1sanjO0nkmUv5N4GR17mqJncJfcspHh"
    "AS/yOAc6pDIml0EiQzDkb7MJJOkISH3J0KhKGA0w4OhxTkwGIeqTsPexImbHdkYcQNyQ2EkIQg0L"
    "j3Chm7WKhrvtqa2SMK7yffobws2PEFANmGjMoPw/846YGzADIFqJppPngp6GLoIpofBNknh/z8V/"
    "49PdsZeiHQeavpNVB4zOHHZKDdokkhITAkhAkI5H6rPPvYApCbjxVKlWkqST47zGcwWJPQmdOpUH"
    "vff9n15+DulRHxRjZ61e/pQ24yEDCZAIdzeyV7mxQBcOq2RVPnZiGQKgMTys6ZTyZSpFmc6TbzTp"
    "3sUgjEWGJpQ60V1ugJCUfatIqKWoKnogiC4KoREWoAskA5ISe1KwFMtFGU41xIQ7mAPK/ZGBEQhw"
    "wLBQFh2ISUZF6DdtKQlXaH/WqDY3yg3jCB5rGLzcONgfivpI4GytMiE3kKGEXCIbI2IJHV6+armK"
    "MInBmwDbXdm88/ot1e0/97BRFYQ6cigqyjJ6A5EQGjfwOnxzWlzRg20a5XFLeRKyBAxkAKZ68V8E"
    "DtaxRNvi6ZgVCggY2oxcfGWC1BHrLO00DYArXMaOPadBOuQDH+U9tUiGty0K6GGY9U7JTpzNTTc8"
    "d1/VaPUbyXKL491mAQRUjBoD20+v36x81FZ0dRAs64c7MlJnteby+O57T3k6GozayJKcSEk48R6I"
    "xzkZm6ZTROIqxDjlU4Kbn4pK6giiyb9fh4UTdxgQPxRPciFx+eMdLHh+MdHIGwLJdgyTYt2myknL"
    "ry8UHblrHlhVsaolmMx+YzRmlQ84956WAH9kcwYk8Vhoc/8l36qLoHMaQuXmISVJULZy3OfojzEi"
    "YfeOO3VRoFA7ZRpshV+nPQESyoo6cpoV/I5mtAOBy3tpXuAKoefYwxSzMmj5qaiEERIkEXzUolGH"
    "HXi/49vE738NCe9jTnXjrf9H1Gnv6V85mLUtYOcV9ZAqyn6f9OVYwMAzGbp2RJpCXwwoULk+V5a9"
    "7N5sJr00xQNkduHhsfaPRXpfYbNJ8+3y6m1GenMI0QhAVJBDOAAhACkJKhCgFNOOVjz37rx5Ydu+"
    "sCAy3au3YtmmZmZmzVz0b5w5jDAAxa/X4OHXOPnfOOJxEOkrjbIoVvZ0zp2fF+Bz88O7yfN3OeUp"
    "8zeZvg9UWX/vXWf/slMIrCcg+Ga+yzM3ZXVBvXB9HzW+wuWl7ZbgYacgY6bDDMfe/wx8n+v+/4OO"
    "iyLyevEWMY7JJt26YBI6CDucOA5A+dEcqrLSyyGVmnb8zrjyJZ9oZsRNpmIKcdISrzDtQcrLeDVt"
    "QZzdyGrC0tLWfBqayMyqLlCEprREaRM8oO1ptn2xqEZVy82rYtlzNqvP2zCyCRbutdrd+v3/Pwns"
    "165112uzV2OxgQea0w2nDnvu8WJLiYjCMomtFE9x91aTcKbPHWURx0T1EtrfLsuraoXJEIXGJUsG"
    "M6R37Ow8eWsXUmPM2wTL934wSduGemeduBWXdTzNOVlrGmJB56qItINmx9IgIsi5BRZp1nqbrYf2"
    "yk277N8vv5skgHwY0mqLttRY3RJ1UaARc7EvAGGcmZTu8XR3bPLP49pX6Fx9BOxO2XuWVtcM+bPy"
    "YM8gti9sRGvy/DJ8v2M1aREzM2vHQfpon6TP5Py75y/EvGUdMuxZhJCAX2VyWBWCbhahI8Tlaqe6"
    "N7BggOA2WakNBbhr9r1xyWOLV5/Z6dX9b7BnqnbPcLVx0fmdefSk60YwHiu6AzGp5J10qGIDRF2M"
    "igWou5xDy+Xta8UWoSEhEfPZjtu0hN2FwdIF39Nb1vaIzsM+8+Zz47TzcSWU4r5G+nE5xLgQBIFE"
    "SpAov9JfS8nGjrxiM3O3wnsOFFRS1Ol57XmAZcdvtrgUitSBANgsjIi4mcECaTtXOX2p8yfbnna8"
    "p3ECssdkXMO81VqOAdPK/Lo/e+mMiZJLWKve8Wirsky0MTEER0W3oz3Xd1l6bHEecVoKs5Zh+fQf"
    "jmDr2Rvh3Wg7pC28dw0tIty5s467WI0Oyz3y3tqjFDPDy4OFk1mbYsTr2Rdqb2q7dZieltQlJJNY"
    "tOLb46y2BcR7w5oIiHZIE7pCHwQaN2hxdXlo3Y5sXnyd3cbXs28jjIRDjwpUISTGgmTpb/J7WsW4"
    "LdXTmRogUGVaC4XN5ZMVSbgnTJCSTFzF7h2tB1LBASWNbhAywPrE4hnAwmGSGMEuUzpLKiq8YLuq"
    "Owa5cPSmBJJISEkkjBpd8/FEHEeN5q/fjc1dwjn4a7UKuImw/Knd45ndsZ3dmMr53Zw1nFJGrv9P"
    "U3miOI53wviY86qLmJh0Jh2FsYn+v3yY1aqeAaOBaH9RJXE3IpFkz+n0OWmYfkP5GIb2ihrxuxH1"
    "I9qpVVPGjfKYQoqKkvr97E/f8ZIzDnuKb6Wm1w1rCNsI1Pf4wisifVpsg3abuahuINfjlZfg8LkL"
    "fJjgwwxHb0EPdUZjmOw7LOhOiDY5s2adrCRbVFvARgZnL0zEENrg2eibKqBhPPmtgERsGK7lV9Ly"
    "qr2QhH49yNxGNM9+c+XNmv9cnSp4Ka9kCcfwg6h4RICRCLkKohZRc5e9bXY8Hfw3fPlp16+6JerC"
    "Pw6r4uPxUEFTjTQKQUsoOM4hLa7jWcODJmEwYlWWfKil6Z5oxiuVrntkDZc6hkjnnAql6WYCsGAs"
    "pbU+EDWr4U4EMjsa2siTDTepqCDRFTRA/Pi2rZM2UHJuJ0IE7c+l++ZnmC2nXSBqW2YUj3d1Jhgg"
    "QT4pMN6X6vJzyi1xl2GLnDEmi5z03YxUz9ljv8LmH0ymL6K9a19285a3J/YVMDcenpOHAKgKnCmg"
    "FMueMvddlrgmwAUC8zHmGUZbVN3V2TwYJYfMik5cOGmXuofZ6/gr2VHvLe7NvSmsoLB9GnPx01aK"
    "7f2ssbw8DLlmzesebVV7lJ/Xqxv2N2M/NXnx+DRxu3r0TZyeSkHQrw7eumiXqJzk0AsVW2QFhm4f"
    "6+3AzAgPG556H9vU9+nzQuYvHKiLsnE7J2eOBFoMYh4X6L3MLoWNRIOSKKSndCo4EmoLkzIcdMZI"
    "9r1UXHvNtDU6XEh5ZWqoIFZKLGtRGfDbcsvXLjNMqwEiClo6oiJkpbbUbBS4nTvBGhiDZs6xfUXG"
    "M5papozosRjPRCaRHs74901M8SCWi5JAerBsMCcIgmiMr6MaoVU4tOzlDHXvq6vGFdG4yplKqDMp"
    "nMAcBCSV8ZdOiBBlS2jOT0Crvwna2g9FjWNGY1T2V6WrOOeNOLeGMO/IczswvJqlEHUdxgZQ0Ls1"
    "PxMPVhkyzbVe1CWC1o65oNVq1FJuhLdO8pqc+0vb6vDyeS+NExSOGE1BIlBuzhObwExuTZufY8Xa"
    "hiwB1t5129rOmZb7wObQi1d4D0xOhwQdtmtn1QuMF/XRCJ+TvqsuXy2KfeeVOcCWFXowOHCxn8OF"
    "5PP7XYWzuebXdEolqoe7SU3iTfYshDLwgYMY206k08yjNDYjJVU4vv8Bn9+aFmrPrz7kkqqqqqqr"
    "5tYlTt5F7PNc9R4zly5hfKhWmnImBSZiW3Tlrm7mzN4FQWF/EZxqUUSEYZq7lVmmi5di3pmpj7GZ"
    "ii9Q06YVVNeTo0xaJitPmtroDvK3nvY0GlotRY//0i8pcXtlHTu0R8bWKYHMSEOJ0OnfRQQ7cywH"
    "cmaexdEjrfm53TDv4d2rRWjH1L8pHzbj65cw2zTPVMdhR5RHr4Cu6LM+G5rTyToQhl4oqB1lzX13"
    "7qJ7YcKfq4cNJLr2+FeotP0MMddPo+2G3dg1YRz5pcenGi0Ni5PD1FniLPeu32ba3aOPuNeevUUR"
    "pjw4O3UmKjLAw2lRMX6tXSqlrZ4B618RRhJKTjLPy85EeHpo90XwXi+O61ucomdKkd5qennv21Ga"
    "1xmcxe4o4HDbZJbbOA6F4nDUng9F6y+r1ATaNnuIe14MqO0wd4vq17ySxt4vh6c5nsw3NlPcjfMT"
    "kLKZyiLMn3otaLN326/GNzCQwfV6XFscaqRWobdvr2+43TziLviUK87sbS435fRbtNk9MWWEKKWU"
    "wLJD00S93hNCp0+9Q4bBWhbZql2BhjogqSCipuugRN+m7v7SvTw69UNzJIRisQkRkAJEM/eoeXD2"
    "a7zHVzo+zGXO87Z21zOxCaBYCEFlJ6dFcx5JKcKs7NqjokNJhkCKZnzrPcdk3mOJ7rNg93uo7ohQ"
    "QkT3FMkJvg25m1X0r/nz3G9wcSHxxm7FCWa2vdBrIahQye+cpmGppDrHVcEdVdlM8+l9lHlWJHkG"
    "gAdxZeogBam9iTYhLbD99PKzq5Xyvua5mcU8O7W0h1MVZtzbJqijauWxkojGS2iSxaKiPkqbbwKv"
    "qT258Di9eX1vF9fxiP8T3j+JD2UH7vzk/RS2hEyQTOQotVOmI3cf5gLR7QTmAevzFh3X82vbjujn"
    "4Olx+jpx9v67K95e7otRu1S+Ij9XLCUcUUrR7O+qf4/sUPGK+SYfNQ4PaLW5wt3TvCY3fzbc/r2L"
    "C+3YfOGdMcetB5iG0PCAn1dlCBCGv6aLIPpIarR252QP1gaGX9WBlKIgxowf5rMrYGGrJ8bWLIT9"
    "cGFZ/OUlUUd2fJlBAEYFk6iiwHyEfSiEII+iAUvwkEflJ/RWNpL8qEmjZ9G3W/LrRo0aNsaNNLS2"
    "ppfC82V8i0smqVV+Et9db/DNbW9jWLGhSRJAkE7fITun5jvj6b8PXjVT6EUPYS2pRGLUIUtoEv73"
    "KWZhgYVcKf3cw+zvreQJsa77A+IsRt7Mnxo+niydplD6pnSAiIZJoTDDshJuKlYsqcx9FZsXXIX0"
    "tF+h8cqzplGorfNC2lbjl3334dNOzlZjCfLtYhnZ0x1tNjfYSMfj2iUbIdi9XspquCEgReoCCIgI"
    "IiCHsNFyhmlFzqcOHSEwl4DZoc1kbyL0gXyqOVc+9+uKiVvo87nDmOYzmngwlh0WH6k1O+dc20II"
    "rhrTWWVGj6m2jQalrQQJaTiwMYRprHUyShJR24HPwkltCw/ldyBCTX5U1qkYJmUHweTrz7pbCE56"
    "l9T99DAZxfrHXy2juWlZ8Ckuq+MN98a2cTypacHfc3tp/BdMvrhDfFoKopNbleyiR0ALhnIQD7Wy"
    "D9M0zSA2ysOP26J62584NUAsuy0gToc0LfMbey+Qvl7+dsiuo57e6LbxMLJnH9xHQjA50VOmDrAO"
    "/v7p6sO+LZCBAGgZZKRxOsqOCk1AVARgQ+ZGcrjJW6HGN8wNMMQHxKAasrJNsNY9XApB2zR8lewj"
    "ZK53YTISCUbHhhUPkLGZKgjjpmmkUnblolXI+8cvrNZPHV3ddue3vCbYTi4Hm65T/OWwRUEuv6U5"
    "APQg/fTG/vdqUcRFEnPR3yaDNv/C7QqzdIlyZtqYm800DsPIci7ZLNvEzsMduia7+c48sDJk2G9q"
    "dtm7NE8ImKKdnXZjps30Ridovq0yRB0IRsTP5EzO1FcFL+GGnX4w+7bkcsJt6mLvL1V/Lla2FZ+G"
    "aIjDWVrCRaKohNvhPNbQ2vFrbigsJsJkQGqhng4IPN+Gmkqx/mqjls066dBNTnVcMx97Egp9evrW"
    "oXu36Q3CNXrSKK24VRxI1uTPeI1IM97e6yGOGnnt0ns0r1ezxeaOLjrD2x3d5zlg1BzEkinOLbHn"
    "g4REAd3dRCXwtjkoNI7QZyGAPcRfKCoAO0TWmxlWiYfaKUpSlO32aNGjyGGZwhrcSlHphenBy2yT"
    "5+spyi70RPNr5+04FejDnl1McpbTe8LdNKjT02mzGOy2phKV1dJhzpqcIMuPOx7+sSw98F7I3f7U"
    "qzfHjf5vikdWbCezu3oQ4tu2CtM2UwxchLBE4ASXgSOZndLBCd3d2llHU0jrb3KqbQ61hoPHvlmJ"
    "OtRCEI484PWtPMWjv7OuLGp0Ta07+XneN018RFkTLHLNXsdfR0jWtGNWOxjo9TCIljjeiTe3EvfA"
    "heonGHlOQSIhJlwn2LAi76OqIE0d07hMpRKiOTj8d1RBgaxNKcc8UNQYI5cOGv4MRGHZVdbL76GG"
    "BJgftTvhzBmHbLoGIESBAzRSgijR/dSCeM7nLY/WRU/SRXDmESD21BIJ6lRa128fTAAAAAALtCih"
    "gYcB/YDDGdhpfJ5raZHSIvkXFQo5hMLEy4K2LZUFsrZUFsrZUFtbUX1+iX24UDT2JyTrfuCOo0Ox"
    "6K14vy9ugn2N4zqgJdfTpEFTWeAd1A3qn0Wd1+6UQ77kqipmjKjb4smlVK8JdnvFe11lzT2Zu3po"
    "0i+kDj+P2PDs0+Z+3JqngOx0A46i7XSKdpCxweIgddB5T+k6j5Dw4oiabHm+rbhJJIEPdbXSmDmU"
    "CQgBQaJXUqrqr2YplFIYooo+jvg9Lt0s8byoooooopKm+VDQzbGAc6nWCElisHhcL+r2jtABu0Cy"
    "qyqzba3xZes+ZeuOvem95jGMYxjGMYxjGe9bVu3MUYoxjGMUYoxGj3fT1Xu+d6KNFGiiij8v2dvC"
    "jRRoo2Ir0T63u3vAAAAAAAAAAAAAAAA1V5IiIiIiAgICFtUIiIiIiIiIiIgICIiICAhAjqrdVS0R"
    "EtqlqIsREbbW/Gh7qiv4dAoc9EmMOWxxzP019vbVWEt5zQSnnGtUW5MBUJ9K2kGwFWgHFOqlgpyh"
    "Ujd8zUKLdPZMMW8pOeowl+D5ezXbnz38m2aXNGFDvadhVAxaWxJha3npeyaGy8CGmzkI+fk2YKND"
    "0oLNjb3jVmbBk3+e8a8SvftivP7PsPxtxF6MaRq3oNRrtZxuF9etFaa1p6e69+HfH9D1XfS8+fT6"
    "Hu/NyvsewAAYQAAITpwAAAAAkkk4DMVv5EKdjC/Dlw4a9WBSzb6cS9588zZau6GOjQkqsuqg3FUf"
    "yTvVya0hUN1NgbDSOGwl76oweaBM3UuPyA9Ix8/oyHQobVDIp2Hd2LePhzNpQ5RaTm/ymyZW+Ytu"
    "NbhVOYtCuOpCLnI3NCRDg8+8XPh3ny6nIQ4njG+ooeb6cAInjDTOSSSSSAIAAAvFtWvFtWvHgAAC"
    "gAGF87ztWveur2bPl8cPh/dtifJ7JYXDkOTapR9lvjy+d5S255fhUuoEEAs48e2JV5e/ZPKxcTUf"
    "AwH2DXjs0y66Wfv508xHZRNCmyaeHTPGRdXy59k613Pb5IV2YyeFN8d3O+ZrXsweep5V71AlUOqa"
    "IFKaotrXsswypomPO+bDCZ46+2Mo40z0/hDxPV94+lH9R4d1BarK3rtyxvp0Zp1ZbCDpoPRo0LiG"
    "TaGm2lLDqlhpZyvTwjbXo3CaeCuv5vk+z8KVpns46eGnh136/D67ZvV4tfSryEhkuGhRbFyL2YVx"
    "XEnVr6O9J6w53A8DjM6scN9/VtGqzi97zk+4wqXf1bm23uebmcxJkDJkMc7fd7KyB66dJptvlq3f"
    "cyeo8ZcTRoS2tEg8HFcydRgFwmc9RNu2M3VuIlxFqtdgz6TEwz5Y8OMPVFzamXXf1irCQhkOUgUQ"
    "Icn4h6DqSEAUkYixFGJS2i0zZptMyJorYtJIoyASSAfqpAsMW/zH7kRMmix9UkBZFkUUUhJRXVlH"
    "/aWG8urZWuuXZXNuY2Q8zm8NcCXnrTNKqfz6W701iDcuLBKAWrEXBOpCYcEfwSpAyN+/7OTd3L0U"
    "0ZtOWePaPvJTjeUkfRTPjfu8JQA+o+5aJF2gch/IFKQhJqlZogl58jH0NoeEVSyaYwMSlrKxsfAX"
    "/PE7qa5Q+2wAsbTcQ9guaCGiJhkaOA1hSB0kB3w5EdjbkFuhvqj9cKABTw+Hot+L8HBkPw/RF2HY"
    "IOuSLh9X0qqqqrQA7gADqq7gADqq7gAAAALda1eb4PT1eb1+HiaMo9BYwZg0yaa7ZzOJiHKGDxQE"
    "0Rde+kPtREfWPCFlOw7c9Jd8Pz8UR1aZUEY4Q1kzbHgeB4CLV2ukaBq4SJjPA3CBgCDQoAUpAHUp"
    "CoIm/bbr6MlUzND1bKgp5+kydNJK44sfyafUfcv4oLBEh5yBCD9QhxHOKLpSHY8oBqUNO22IuKiT"
    "7NAHeNyIbG0AHyMNRlpH9zJoVMwK22jBLkZGRXacDzEO/HhlleRNiKg+2UQInJXiWbFWFvLeQqVn"
    "MxbPW6ijFETCsxiCI6oqjphiIibiBGqyPrS1uxzqg6BWEQBCkyE+8QVUITUt1KgBgVDVQe56KEuX"
    "VUTNw3P7DjoDAZLBxFjITeej8AE3+/L89SQTG3buPo88oQhD7hwHN7vyLHSEnHHEWF9696/xSeaG"
    "afqREo/igfbd4ExvPu+qpfl9x2pCB8NP+D8NttuoT6gE7T1/SGSfbARARhuUYBFCzoDmqQihwIhq"
    "RAuOuqQpElGYXtttWxsbjtgAdw3EaADqisY3tJkm8LDRm2Do9P32iYRRLDRXo3ZG43VwNkF0wGKz"
    "YaVkIzKgOEQIwS93DLCOkYb6ENUOG8wQdWYADOyG93p0iC/Ew9j7OqOpWwAwCD7Ux9qZtSFQ70yP"
    "3fbXNuogd9Gr34WxpA8cvRnxbLx1fFk/j5tnj0sOjIPK+avy5vXf+LRwW3iVQm/WldIGP0V4XvNq"
    "XhdAG5a9N2pJ+mA7er236riIbERDFL2Jik3zqUwd3MjyWYMx/Reys4O3uEzWSn2xm72cOK8c9Uo6"
    "UzDBrQWbpjPadV/vfPozyK6knoNUIVa5Qi9k4Dpt6DPsaO7ug4KWCgQmVUpQjYXDYmJrT8ejWR+t"
    "PqtPNnHTc70r0h0KxBTk6RambLDGELnSOAIJkVoSO3tekkWZBIg19H2oZtNxcGKtbd9EDHYu1rl4"
    "0Q0rFnldvayLDtejidPJyU48b6k4fgpzFjRGEAdBXc4bovcJ+p4JjpRaQBuJpHZolcYBQ7ltNMWC"
    "yyc3Ia3yRjnjT3dI6a43R4ddy9g9aE8VUvLznSY3NvFa9bQkLSQCoCYFuavB26cffNLuZZG7q1nH"
    "y8sG/2fWvyohCQhBQisZAePI52QuB+TAWoAyDIBAR0VS8mAFHx9kmkMMMYO6tQ9GWPMmsDyXKEkA"
    "8tZM2OiIl5hh/iKqb8olJMUQgbNhUV7/AvaeNAQze56xEV8O6qxZD6aQxZLV2QjiQMtI3AKYLmBI"
    "namAdslni2LdFF/cJJGfuj+1wwUy0yEsUBEICswtlShFH83lMAw3YVAHVKwKyRVtNSVeZubY22S2"
    "8Tlot6ddta/2N0r0TzXbNZpNr5ZW8qpgAbgTtJEiRM6ROJIrEuovn+uAW98VP5+nU9/SWvZxmv6H"
    "Ld9SPX15Th8aZpTd6vF4Di7+Pw+yoUeNDqKkunk9MxVxMhMoOOmYGdva2PbV72X33l+XDaQo+mZ/"
    "Z9VaZXVVWejPVT12+KXdJO78nWUXa0FGbRKDZoCiTWSjEpeaQkN93pxd2M34ECCCA7leLy9Owzas"
    "0u8P0JS88IV5VtXqrcjPqVE7V1iv+HGJGq9P6XR6M1SJIUnIULgM1wzAkzM7gjzedETKuCIl/div"
    "T4k7dq/vvCSHw+k+99WTI9aGm78BCj8+A/eJ8iYgP1e+UFkPzCiRDEoR1/Bqb2fsNi16+Qhh3+sk"
    "hJJLAedJfyA7H59P1wZvecm6bPA3zJB49CTcYrjZCjucmZGADH0ECH/31fjTW/fcMvr+g/KZVZ5s"
    "ut5sQpXWRzNDp0TeXVmssTEOHT7Imavsd+/aCX/CV1BwUd/riRLqltUN5DYnyof4Kln7yUKyh5/v"
    "jRpf0vm8uWltMIo7hSCmIH5c8dyiAHv2QJ1K8QHC2sAAhDX6909/I8gcG8l/gpU9QiIHNizvH6Rk"
    "nrfxoqJ6ilfx/eMU+0Q7g80ryRRjYQhkArhaDa20LaWhQtpbohqQhDxofIezZul/R9D5//ROIUT1"
    "kI3HH2GgmJZ9CZur7MjeToCBGMYHRB9MD4/6Hk0UdKp2qeyYR9v3E/mA9CmV0d7N8YiaCj1YrvSN"
    "PyCPvRMbGZI8URNChVlirsm7p/k4p2+g7S77gNUPoASLj3TVEoKgAUMhEkjGRXwE+zBt6dYoHBvT"
    "eilCGOgJ1kfIQ1Sp5akkkAAAAAAAAAAAAAAAAAAAAAAAAAAA78P63v4AAAAAAAAAAAAAAAGgAAAA"
    "AAAAAA28W99fc1fXNa0URKPOvYHGbt0AA8JEx0wdoQDwhaUa/NSWDbL9ngDDekf5TC+AhDzJi4A5"
    "ctNexa1rW9dLr/KGftUeaWkkknSGgfUPaOQ3mOw6QH4E6hpXxIYJ5ERLnNpfrdfIGfFP6FnO8A4K"
    "aPEHxIoqSw92NHxCPPh/KJ/JfCXcFsfX5xh0C43+mr4TlDfSr30CryfB4pF2hpGWWehyEKTVPRoZ"
    "1H/KXVwjMcRkCChyvksJ1VmTcjLhxgZ5GjfrzNrkP4BAR0iemAdaAgeI5kHwsvriPV6h3deQRhFK"
    "fVTH459BDZJKhNpRwmzGQhuq7gkcUkj5nxqB3CwflnQT6yX4XKgyHAIiUDYPPLFkMSs0+AYNK5Ht"
    "ycxDQQwOsJCQoB0hkdYXg1AcjJ0hOIPDw5etM4kIMSEYQUhJOk901e0OwpKKn2f6LCUFGIhUr3i5"
    "eTmeKk8Qjz7hVisIB2664p4QNoDGJ7rdK9sc+tClvqViV73G1/Kisu9s2phy471TSkmSzz9J33lE"
    "YohuwV604jBD2jTwMDqjuIP/inw/FZD3h5fivoHgZ4BDlTORcjCKVKdV3Oc4qWubnNySgL8DUuy7"
    "xm+X5qLeFFKNCr4xV9wKMkE4a0xkIj49Iw7ZtDnFOhs2D/jk9IvOixM39OA5mHi7jwGdtX89l7aq"
    "ZFzXHBiuNYGbEqmpQfwIY+uxet0ygvLkImBjE+ubuQeUE7EF7QEfNdkxdHHqpxkZPwv1/aKuf/j8"
    "gFZ6UV/RfnEPmH41YgYpwD1JpA+mwSh8pzDkFsMFekRxTKGImAIbF98ILCKfAc+MntxeaSHJJIqq"
    "xSiLj59d+ZmZmZmZcczMzMzMzw7vaqygW04DxjOQlExH9yX6ZH+VN8UOFLnTulvRKr4xGJE9Q/SM"
    "cVxSSqGexYp3cd3gMv0Yu7u7u9nGvX77JfIPL5VPKnlQ3ZmCHkoZho1RLCkRAOpWKskN6UsPWFP9"
    "5BvAKjaVAxDckCiAe1mjoFXzhnZ9DJJjk0G+KoScqMPa5tEblEQ+T/Shs6MhT6KGaAoj/V84/Y57"
    "ecpFmbc9saKgcYQL5nB2QITOgdZnNjU1pg+5YLwzJ2MEA4cF95OIgP+P3y0t4bbXwyp2mbtS3FwF"
    "ZG/GIECOIHSoWV00dDNkUhENqKqvZlRP7m3qMYAz/R9dlpiaPlQ/9eb5w6AgaPtJYM9zIljXIaBA"
    "zQs2RPF84oyZCEM5Y5fk64XvnedExD7rdw8EzSHUk6c5QsTlIh1A33UvUt1PVah2pQfznzdOZzTa"
    "GXiYa1zzSa3MjHJyVvjhMUUIXMoVCpXkOhOz9mWQfRlwMD+GSbGWbafARMyB989H1dg7dblIz408"
    "v0uk0x9HLXBgLxvC4/cyh7+Z/AlhVwD2TIunsvU7Cu9LBuNIoGTffXcLGe0nOUOQirPzP22SWl4y"
    "1UMg/1nVzh3KOcMU78shMJwc9CGcggdMzUtSO5f8JBPbYTc0SWjMj9vgFkw/H4euFW5rJQFsAwzm"
    "TuCfOe3QdsR851Hvhk75gW/RaeBiT9FHph4LEr3rIrHs/MVzRYw13vEo94+tgNhrI3atGlar+dET"
    "JF79OAwndXnJvBlw4wM8jeBYaOFNCWSggBoQA2Dn40pS4fmSBDtfN67Y0nb4/xV2zFrtp9OQqVBq"
    "SqK9u6fv/b+X9P8P1b8NP3/u/i/N9H6vs6un5Ox0w3scdhB+YUfYzSQkJCQkCGAELqxP1P7154vG"
    "/k/GW6foKPnsHpqw5M2f4vYyhnvzmQymY/Wbv7MxDzVhZH6OsaDBwhCDE9y1e3aVSr38Uyiiiiij"
    "5c3MYxjGM8bVu3MUYoxRn8F25Roo0UaKPSq9bADNMrM9BUCMjpT74eufcDWbuosWD6RaMV9oVcgW"
    "MCCiekD3zJxa3MSIaM1vXT42wYOc9gO6krkQTPmLHtp90emzqmUO6fOA6SJSDZ5MODK0PV9VKT5j"
    "YVMfcMECCIRzOCdwlWUDDVhmIsZMdSKApgDoxvMTE/KI8qb8q/Ewv4v0Bkomg/Hf0GflP0F+xOzx"
    "H+AtC20WKB4vi6rz5uBJCSd06OO7oQbEXxX0P81ebtfKvltV99fci2/GrZ74SSST9g/sQ1fjeHxH"
    "f9H1VVHMNdTIMWetsQwA+t+mT5qZJCQpuiF0OpPZIJ8pETBch2OxCJFifDsAUu87NxRTRPC6FtIF"
    "UUnCJIgSJ60jkkE85vXY13bFQJ2sFD65WiQXiND0wuhYOQA2vPpaDYOkQvzuZ3E3C7jqek6i32nE"
    "UTQdxmEYQZGD3wPuTmdvnjkzMuEfeSk001ctWQuGZUJNFp7+AJCQl7jUUDjWF9QTbRC79cqioJ96"
    "AEeYQBsO82Q48hDpdQVOooKN03z8+He5fFXXm86r6IAAASCQw8w3ESBwgP+7wE7+OSoaCahFeTZ5"
    "IHHeJO+caU9y7nOB4+73W1LbW0bWjbaNGrS3JzA9ZzkxezRilZ0DVNBoKtx+sHKdxfeSiliXOJQ9"
    "VN6O1zDhyEIi8sDEdQ6opkCAVF6QwIAZDc5iGDeHrD3iQPYHWQOJ4ej04DcG20qqqqqqDHynYeg6"
    "qWyh2GGHewnvbk2Ew2mDDujNT3ZSo4dmKEPQqoiB0gw9/SxhCTiaMZI5A3InMIdsshpwqqV2m5N7"
    "ecWhQXjwhtyRCScZCIQOIJWo2nr5fDVkE8YeEBkhbxF9JobdviaNR5aFk3SVfiyluOu2MUrRBF8W"
    "hKwIwmoFFCdVV2YuSHJo1A0GalmqAzAG/0iPWbpmvXBD8MwdloWkzbqL5xTDNnpknGMZ/EW+++m3"
    "IoB/BhF7vtO2m0bcLsX0nGMWti8COI27kH2tUi9mLO4Duih+Nm+nWxHPfNjZyQ4MmIuSz0QrMzcE"
    "EiOXLOcUGaqC/Ra7uPvqnTp06dOnTrbOZtK6GjFosnTqatFr0RccaqtV3os9kkOJ06dOnUyuG/C1"
    "kLRPfU52LbZs/HN+muNe4JDMOw5kfsReMaaxrmJXTRUkNaqyEID0AUd7gIj8A4DnDfH6vHiulXTx"
    "6trdlbtq+T4QABheL2b4K7XnyAABAAAEAAAfV14vp69ra1694mr4wPadc7iMQ7mbGI+TxAphkjKg"
    "vZ4+PWFBRQMqldxH3zRE0NiBvru9ppQGVmMcDFgbrE19i+y0DpHYAwe8rufCMTyB2h2ST2jIdyE4"
    "iWh5GHVo1dURdh/GIIkkTt6stSy152y3XaitpXa+Oz2t9UraZKlfa462yX3e3apWCAaIeyboxkDi"
    "7+LwcdYCnbJJJCJCK2TaVapZamyzUspTu3WpQyyhmxFJNd/r3z7vj229NKkEQNgnEH1RCzuXyAxD"
    "ynK/hH93xU3G0vW0oYD6sVNhuBOXIPKcJuDUaks5oZ4ZpZR4p1ogM3Iq2PEUTrIqsgQlITStG2a0"
    "1V8EnW9PavVXQMUNcbBmCmgA4a9SMArGoAAYqO1pVb5M3BLHQZ+SMiqKTMOCGYa7iQdIYorzkAG4"
    "xYkuprmbLVhrGtnCpOyJ46meAOGxpVdEgIAbVAE5NgvnzTpDOIHHd5EUykQ5LMnx0iJybQuz6MHb"
    "EthJkvT6EIYpoYCA+jliwDsQek5jDoEXnPPKO8zTucZO9FFpayQjB3BB/0YpWFYxoXBMQsBXTBTY"
    "Dv2i5A173QOzhWQiz9dDy2aaqSiwQojyzerr7QqGsgLXQQA+JeGQjJBIKSAEACRRK0H07jw5njUs"
    "vI5sdiGGBEjM6BDzyzA0ODQaZGPxRPkJhKfxIUZ0muuSBmlVP66HDDIH7EKC0kGmGiJ9iFkXRVDI"
    "j6aP5xIQXvBAK7aDyQcRiQ2RNIiQEPfVLDwBkwgtlslixC+i4CyED4xgGWgOMMKXJcSmQhCyDI+Q"
    "9PSlREyGiRyFEmaVGCDQj2rbaUwpLXXrP0mi33n4lSktD2pAIBECuLGDonIfV4h9wFEgIowiISQ7"
    "PJYAdaVYFwSBG+T6tzuprgdUP28g5f0ZUZI4L/g09eleU7TwHgqga1gKkHAC1OwLSLhwGtCQRXPF"
    "oGSAcVuoUf8pUE74FbV2F0NMiixIWGFq21GDB/4xPdTBVObNxOJpJUFayUBYRklTTCwQnwAFsm9m"
    "ARZP5nz7NZ/fB7cC6ggIJJv0P1sv8tX6v4d7YH+Vk2GTMgf4tFgfnf6/jeeT4kmZchDcV9+qnKCJ"
    "f4BQwiyDRASoVTQnFkxEiLKyoZ28Ztged5OzkUmRAZI6BVinjbHg5rpc33lh3/bl5PQLQrWZeRO3"
    "zNHeL7289qjlgNc5ouTBkHPONnhS2GXsJnPHnNTfUNW11Rcb00hDYgh2eIRA0C3OMkg9JB2FzhQ4"
    "CbQKv1fUXvAoh9jJQURm6CrBFUKRJxJiVJwRKZdOdjrJZqlLIcaNYamI5Vm8MM0iOY2zIiQwzMtE"
    "yVKBYjkzDfAcYAYibDcBImKLZTY0wtjSiBIUyCQpEHLckihMpKSGkJqTIYh9jJ2H2UdylR3p3ABh"
    "UVQZySKZoCBboItgAFMAMMUdOjjBIeKtZO6X0Zu3JIotnflreQdZJIdRAM4QGyEQIJASBQ63lVS3"
    "LbI940FVwZ4yyBgPqTXeu9AIKHxRFF/l1U1JFi+WQ76OcDc8vr6uXTmeoQMxNBDiGAzY/phqGQxB"
    "MEzUXDuEyvM17mAVHtp7UCEC05TYHLxm5TOIWQXyRTP4DXciGinolfJ68Uk4uDwCDJA7rG50iwKG"
    "bIYEELvkPlXudhHLrPoqz/OCcxLkMYaHZfRYErZe1vUWQkwie79m0c2JlyjmrSSJJBCAQSIJDPFj"
    "o1QWw5smsTMyW2Y6MbKXMlEiW5g9YZ6zA1iYM2aDc0WlJxQMEMgwFnMSSDaCEVkKNZoEmGUBkgHT"
    "pnidAdZ1oamSnWND6mk2kvq5tZ/pyF9Ftl2iRyTQ1qHxdYVxnElxYAfjOuNnQ7qWLBjWzfr6a4Wa"
    "s+7KSbGExx5PPLKhmoQa7VfTRqcmtDQeeMvIjYWk3jdGGlxjkJIIY322sacIMWuIT8N2V5EjC5W4"
    "6ctMRwNEyTQXjbRInl6zbafu106NpuwGnLEIsm6GJ6boXFmCDEFgguFDpeJ22R6meXDiVhyy5K91"
    "hVV6PQc2zaaeBF0MQKm/NTGaYsNTE44qdJdPNK8JOWNNbwnEutopC6snE0occkpody0MsNVgoSWC"
    "ACAkgTWXQaBWM3s41E1ms3s3wYCqgAAABgBAAAAAIAjvV6W8+PRCvPl28+iNWrXq7gAAAAACgAAA"
    "BEAu83Tln/gnHd3XHObyjoHmbnAGC86QeETkXxW0zSKcYq4bUKVYpFYpASCMkAZBgSynJMQxLz4D"
    "h3qXeTOcu3UPOabFGmRjTTFplFrpGpmkuERzDUxdbN0WYdA2STrNGmIivbXCC3TXiXhBGr2700mT"
    "V7ck09V5r0QR5c53SuGiVnHnFTmBNwgcEw2ZCWDNgRKIO0SQi5DkRIWJvYoYXfaEIpBV7k5rq7up"
    "bbmSsWoxbN1E3vRkvBE4dYGldB++EgyMjUkugoCYkWDZcoWGFgUSJBIg9pASojISM61BO5kO5t67"
    "FG3KOa9NlTkHZsNN2A6/tn/xjwH/PnbRdlPYcd3Yf2zSpcodMl6lNVtrPj44xkMKoczGroQhjJZy"
    "AdAwwkzBtZrhDSImnsElmUAEgCJBssA4MceTHKmzt8+wMIiFzAy3GcDS7i6qC1sschA7gyA/Fap0"
    "6cjfEVIQRPuWQIsBDTbKasprSEUy1g21QVighRBFL841ggRs8kRIQAzUXnyJyw5d9msCm73Jom8V"
    "E7nEGvddNhqyuwzjpCRYkCKJEDXZXjoqEUhwDQEpSja4C6U9ZBmQMXFEHhxum3DkOdB1JfqRNtTs"
    "gXEIV/Hb1+MMZ4lebJMPVHHIQlG5gRE8SgnYWQmBHCBtoUQcxKB2GKkEDaGiwDRwFac8zNek/AkI"
    "BBEIKJERAih3ja+cgJwTmKyZAtPBs9hVufizMOS9kyUT0cq03cle8i3TWB6s1x04C5YdsSIiwrFB"
    "EUJA67c43EzNiUEiDgvpQDJx6EqB2NBwAftwGfqN8LAXWA2CDHN+TPnlFitEMQ5TKiDIYkcUKCIV"
    "wCD+MBitWEOch6vX4G/I/Ivhrar4tR+P9O9+9vXzvpAAAAAAAAAADAABKSSSSSSSSSSSSSRJiSSS"
    "I+p7L774h2FkRsBWiUd0g3UCG9YpRJ5L2w7AP9QNiiOEDORwXPAznKHjkg00HGlywGNTL1HxHKB7"
    "sFUhBFLuz2DaojxCg2CvLuUA9YfQEVYixwMM21AVIcJDomkQIX21EZzhFU9T2ZERKeuJ+6GYj4gH"
    "1eHUaIVBSzkCd2TkcH757QxUZaFCT8xGjIANE6TzHUGPDJoiIn6K0nGDhFkQCJAWEEC1IFBxCAdp"
    "ef7JzICYriOGiEWEERkIRHlhUBIOXUSyZkRrRCllJD3qwGybTmCEmwJAEZAW5BKwDWXFCkK0Kucd"
    "f2tJhFT283Mk2DUfNe0rXW9IhzPEFJ3VckkmIl7Fq+XEsXu4EX7hHVmVANQB3tvPiGUhNZk4zLAq"
    "IYJgFTDBB4oIibOJHwymKATa7jZLFJOLpomxgCz4jB9UUCo2koBlxwiIIQUnkwFKVFLkBvEFKVod"
    "Al/BSmFfajU0mksta0WxZtmtq2BSUcDfECyRk/BEgoAooIIESKJjqLwGREJECfamNg8GXzZSBppV"
    "0L3O/H2w0DIOFEjoXnkwCRiRg6BDG7LISFZtslPwsD3fYUgbu7D95D0BuB3BaiHZACfTQ73eUKJc"
    "FHR+wB+MOWiTQewDwMVsEqsUsgFCgiLIkLTeSBQ0iHTrQKrWR2vEo6T6zbR4ZZz/RoWREkFiMXhO"
    "oO91wKIQ+2UFIJh83zFxTS6KREqoqsRfcZr6jDRhVR9nMHOVyLwqokNhvTbBL8JEAGqVOiCSBjRT"
    "eADSwRjBiJFBnf7W5rbEmLVEm1qSktMMJGEFD5hncBkGVifmHifJrgG8b20CuhA77o983vAfV1IB"
    "kPrihkAG9hNxGSdw68A24ERWRQdPa+/Y8+EqpJ2RM8d8El7QySQRL5eLV9M0k9p3tjPHgQhkWqA8"
    "aTyrfrr2SxXiWybcgt9WD7N0+p9asMamYWbpZPiLCkQcTbM4BVECgwQQRxLOLcpyyT8lu2T9fOxQ"
    "4I8uZZnDLLoUVu05OJrha58XGZyxNpqUoQl40Wj80tA1Yn+NCJZOWnQtnBRZtX5S1BbQ5iHaanoo"
    "BO4kiLID+OPVpzrtvtbzar1vm/S23pX2CFMKWkakoHXVPMj/TGFPMiH4NfDCGtgL/kZRmlezvPT4"
    "h1i+I7pmZUTAfBe90vTVU5eYwEzogB4MMbh6q2H26mP46it1YJTHgFCZy+qmAG+L032fdLEVyZtr"
    "1tvCmyxKKCZb0Ch5KKnF4IPR8mU3T0YawSjFVLl6oGhMZ0/uWTRxdKPsmqHJORhSUYfpDTF4geQQ"
    "SEUUiLgzChCmARhvPzzRcvCmj4YiJXGlKiQ0HfBkAtnPt+BnUwlSq0ZVRgzrGaBF1NUMiQUzLjAa"
    "2KarSmFFzprAWEibtT4L75yNHXLKZEzi6bkpwXDSaPjSkIGqMRPJDGZERMWpREiggZ/AQmjfEzsD"
    "gg0KRDqD1h9HAcvfFGCkSPgi7ak9OYyieUijFRSIg5TMIuuatS2DQ4QSIE/crNBIWECqM6mDe/XR"
    "uLOw4dGCnT8m9dc0wZagahRa1ixFkdPHWFyoW4KYe+whtnKIRUGSIyBoBqpiOVgpkpWGDZqELCFI"
    "FJKEDJo1DBIkEUFkOhA8aZpKxlQhCxGQg9tFRgocOqLoJYAakQENDpukTeEQ/XEg55TXyrerv2lM"
    "YqmoESSEImqUEA1oTENpDuIiaB54jaCvGUQP7wW6zQaJiiSxIxSeMA9aCCiRV3t+iJuUO/AWQkUi"
    "BARyOrGjLeZ7wQDmNTnEFqIwqSEAoVqCE0SKkQAea9og0Crj2dmulSWwVMaeMHjfHNvXMC0dOmB7"
    "d3ICRFFyhPgkdGxlAxJ2YQs5crPSXXLebxzVgnrcdCBMiLxCDuLMQSTNiR7oA+sN2+qMozmVadxP"
    "tHnNlNk2PWND5bRDyMkgBiIDfI3nqck6JmpnKuWlrmYzloAYgBEAIKBFYw5d0AQ24n695Sw7+s6b"
    "t49gYjcjA44ZAjuO8UEwYjyKJaEZbqlcRV7y6tiUQQhxQ3Xqpu3JxgKEgBai1e+0RsNTWve+GfL8"
    "68LeFzSUrugyTGVwd1dm6TcnCdyuUzLxb7MtsqSQkGoiTSZRkRTJktDE1RotLV3lYCSMPKt1ZNDu"
    "tLnG5t1107stm6AgUspGqK1aASiAM6E5GiT3upOwMzVVMATIQiykMjKTgVAxUNA6CvU1wogaqD+X"
    "x08OHnEStOAgQ2BHwWKLiOJUQL47NQSAQwOkONMAxVeDKOifHH+re+h1neRZquYKcNYKBNzFLHK2"
    "DGgooYljGdrTVl1GogkLWsYacyUmsgtg2Ne85yASm9HP4Onk30wDZRWgYjvqtYomXyH8gW3hN2yh"
    "2byd9cPuryG8uv671ntpq29C3zZr5tmR8s6IhZy+UOgSEGWFQZBPOARf0Gg8aAR8kJEAvPsCBdoB"
    "jMq1sGIZKm+NwzgyIV4rTNCJsHZYhgAVIxhSAe/0xIdCdnhFEXR00NW9TRO8hKLQFSACEgq64pe5"
    "mNXgkhb/LHFSBJHgYwXuTVuilp1YplZkFkkIEXWJvQUpSgBbj1OrapvLNs21oq2xbWTRqxeVW7Sa"
    "9TtrFsreO27KqAERERBERGaAzCFZAkyZhoAI2ofOEQDJDMghnaINGiGsTxz+eLuTlD0D0wD9UAD0"
    "wAkfaxEPjilznxSnGBr7TTYj84RNCRRPKB+IiCpCCeAgILsOCl0BFAC/jLeHZigG5OeK0EDsIVJF"
    "emqaqmqDcgJoDN7oA/g39r41t+q11aKsbLWuWyWusqvST3OW5qKEAREEUCFhBAsGACMJ1emB5beb"
    "XIwlYKBUKeEpgkiA6yhM03ubzpq9wsIwgMgKBJFIMgqJx2wPLUQzFADOJIG4+kRcuYdflPJ19c+f"
    "0y5syi/Tqb3fSpBCf05cBZC65gBp57xGpq+216enebG12uLEqQlCMWI+S7/QrF7oTfzfFMfOgmtH"
    "qzN0RoKIViOSMiyAJN3hjhSiel9yiyR0XEwnnLjmFKag1YbQNOze8LDUPAsXyIPIsh7N2AuIhGGk"
    "DDIcE+0MAZQXJVyYAqbH2ea8VKE2/HVmxA0dR9ABLDkgIEFU3CYB5Tgmq/B6OPvQR/tInqF5eE46"
    "dey6nq9zp8iAHDzZ2ChH0PiESqHcL9kV5RQCoAeuJRBIiQBfHbTZGEGiALUQkCBAQ4QdVDwo37Y1"
    "Jo+1cc+bJgCknA1BEFggUcmg6jHpJCC+DIDWEABcAkGAhDSQUoVDIwADEedQOA2TOlXgxjRilQ0i"
    "JikYrRJtM0pbZaVNtalDFaUokUhCCSSRECNyKomlNYbFQyqZZgGRJKTHWiu7PUY0TUmYcM2h0uAB"
    "QSLZyNk3gG2gKBv5LsmoHhFPyixiki8RRAgfbLHhSKkSRIge+flCdZeEbsSRqx8t1b3KKMiSq4Oi"
    "nUhsgd6BWHGbUEqIHNDmDajmgFBAaHdDuhoYSMgy0CjMX2xT9mbJ0owsR6OyRecTH9nJfzQsHq93"
    "xjoJ96DgHIgPoPsoPTuoU89p5ws1IsUWOIEKEH4Iezg8ZOVYIajZyDJn13NSvXcgc1ejSjARrC4h"
    "mAUASiG2wVwkAvu5ROjNZWRBZmrMRYIw1aL+Y8oiIiMC82cyTcLBCULCpWzrF1gamjBDEBG3WJhq"
    "VYUU1ggsCC2J2f3uF4MlzbJxq5EcSKyEcEFonEgm4HQ0UyGww0KcRwJZHmQcEYQhZAGUESu0tNrN"
    "tvt/X1a/GpqLVg1KgBs7HzcQsD7CG5OMgwkIDIwDl74hv+GMAgHaUVNAQh1sVRSpCZDiLS38mJqG"
    "XKRhJ5odQgskPShUIp2k6fGVlgoDt8vNCTTd+wZg3bmkAQblIhvaoFJz4PsXqMtG5hYuShhTJjUL"
    "McEYpLKWYwuVxmUMuUxxDNE1uQOh2E+RkimsLMDeMQBDk0urq5MOddQop53GNGAG9ggG3J/jA6zu"
    "s9j8pSWviI5hZmEd4F3HCyKS2wJQ//f9RRRToHuEgSCLgVSRFRe08EOzcidu9wnEHQm99MfJ2Qfm"
    "aAexqzL5ZFg5aqqMEGCBYgO0vRCRsdlukveWYkAgHW+vkOzAcMzYhv8tPgPbQ4eBT+JKi9Z6aY4y"
    "7JYx7ugJZlBWWu+b29FrxpavqWVOVYgd4gwZCc6B0tNzyELQiQA8zA5exXO4RB/2RKCLmyI3XrBE"
    "U4Hr4tZgippHNqiRINOs/OzoJN0ytUsEbu379e379SfNA5YtFIsxSM5xNmqsY0RPl82czLw+RCzF"
    "rPHulnqeD1DGqm0y8Mlrw4Pm23wtbNYKvtGu5gCkGZdtrl4KoiOEtVyW4YNbPhmFa0eJ18zfG+Se"
    "S6cp1buMoWV0K07eoy9uSJM6GSG/Im+NY0y5wSFpwE4nZJMkmSSFbWUttK2bNXWltUlhbS2ltbKM"
    "OVkuBRbsq1zLkzLgmAWMZKWddcLcVCFh9VezaaazxmFaXkq8qCwk0O7zUFMThDMzbJMocd3Hd1eb"
    "40CBqveHTWyTJAG7VmXDKjjkdxyuEZrViIshCTIYh0KHvnmAdAbtf1obOlD7Nixw42ISVv4y3ADe"
    "gSVjGcYp2fLi5LSFTouDkKpvyq5h5JxNoMBYlJaUJSUrYY1cXJEhBxuHxPHlwEnfE7pvyHV0GHaq"
    "oyKivTpzhDlEJ8YaRCKy0LANxmIc0TnRIcLagMk/ZixrOLRngVTIEf3wsnJhpl26hjhQgMooiAdX"
    "o1s7FtBingm+s9woIrRYfWachAyTrEA0AKaAdRFRQxDJAYQiBIasxELMcdwqu0Qx1HIxojgnphRK"
    "kjvkCBygmIBD+f9tTBLyHgiZ8dET5l5TnEM3l9jEwS+/Ddtqlt0nQtWX0U0vgl2cHMwYjLOWFebr"
    "h+5aC3sHuyrEw6zs7dqLCjCARsxJAvOEd5FQkETjQCwRpTis+DGmEyQNR4XO73PCLxqBGOfQDUVO"
    "0QgBBIilwaiFIeoMAJQUiHwgWCJi0WUiEMHTpNUHxAgQkGQ8ErJFmUD/z5bwCHcSbqfTTmnmW6/J"
    "GxA2y37793l+H1spscendEsCgQXgvpIcASttDljdZBjsnTHjC6tDLMCoCSMgjMlBWtGRHQ1Z52qg"
    "QGD5qWndRqkIfqwUO6s9/in0giQcBInMNAiolhGPYJgCAB08X5RwzDYyGBCEkkNEHBxG8jbBoIQV"
    "11izp1UnJnwMjC6YSvDV5AwjMZrCh1pJhuNQYTSHLXXxZC7yVV4W8fo+rzFvOaddslG6SRrlw3KF"
    "hrVnLVwZNhnEpDANUgWcauALImhASdgWFiENGFPs76HZqHJ0QaRXK0NICFu/+7q2G+EjjWgdqohD"
    "fKgMGRQtsOLVBEBOd6CUSTBk6xIUEIjG2oajll+IPNdQ5tIHAg2mAzKHmXVCMiaz2YHarZLtUOMo"
    "AFgoaCQWXAszr2Za5U9dnVeIdWmo/KEFNo6mb3EbV9s5kDKOrBqJIBywVnqJfAvoRVNM6pqnMmFG"
    "1FuARgJLhCDYCIsYzs7a61gSq5zd9KhqcAcyQqSU55gM5goyGmQGJgZrWrAwYlWTLTia3IAlFSkF"
    "geBcA1OBBECEg2HiCamB0S81gRZhlhQU2kYFrBpA60EgORIKxVtwhxbMA8ywwaYTZE+830G43AaN"
    "f12gyINQRSCiQUdIIZia0iFIrV113bYRgEBFr64Itd1W8UDV48QG5oZkgBP6xAc2BAIhQu3EA0u+"
    "JvbyAxF2zDx5WvMXxsQLCZfMTXmsuAKBiALrgXdk64gckQYbYBbB7WTGDd0mQR8pRQkQjRAoPwwT"
    "mgfxJ6xLFFGDA5loqRz9ETWHNFF5i5bowIySb/wq54tF3hYyQIEIxdRQZl7xe1VAKO48Dcc15Cki"
    "rEQRHY0E52JC9UkdYaRAh8egsdQtUpTAppQCRIEIRIkUTepgD3iHTTODzg4iYgWSRqkxdRuECRIE"
    "MYC1wMDm5KBQudBiPmQEwm4sgbTpKTEwRLSWDEBVYwRCjSIVilg1CyCmA2hgyCQEgezxpmGsGQpP"
    "AYCcvabpHwj8YAkgilUzMU8rRsRgcZkAyJN4UaUZLTIqvQUAgfSEhlMyyQpG01lMk2m0aM2rSizb"
    "NpaSswZIBwANKvufmkOz85nbxRE2wBEZARNnSb6ghzEEsQN0S0RKjV6AKgxIIQ8RqBxJ7sFsOI7M"
    "2cyIg4hOMegDv68ij4WUGc4PsgMayWGYAn7iiqKphkIdU+TdFFn5KUT1s/C4jGMGFgqgSYl563Co"
    "Uuu26YoudrhY5yLoZQ6VNOWv3eVPtZ+o+fs+NQPEfrPD4lHjAnkVTsQCyMtCkBEJzlJSour9rVhB"
    "PnRPpJGIkJACCLlQQ4RHc+mcfeqSTqIWCiOn2kywNrwcAHj5n9WLkQ6ogEIGMGQQSJTJtlg9B2sw"
    "Og5Vt5bUm1XjX76dDgnd+0zPAOQBkHIQ0XxxWZIg2emC0ZHAhTwxRiPQsFPVITrZ9BVBpCBe1aTM"
    "LJ6Ak/P7OsBfgWtrSIAAhGCUIciA2Tl5uJxAvkCP4GgaHZ+M0B1RKTzQPpmaH5EstCv3qYPbD/vT"
    "O8FoMloFeqDjDcn3xFhY1LLEhYUSWKRky8oeU2H3SA1srJksgl/QtbSDcNiQ4RTHYLPDlTzXAHyk"
    "MEXGCETSkOYQROwv3K0pUl7HMFUVpqabTQpFYtmzWaWlpWWzU1QBYOA0A0reoKlqUjDSJAJ9hEmI"
    "Ce9TjKAKpESCSe/0ChPu6oF+ChgxDhijnzwYIEEkJFIpDg3ujwlqq8VE/KTUCds8VWFWQJCaQKJN"
    "MS+YLhi271rCUpogiB+z9X8If0MhOZ0wjuqEi6BqUcxgjsgWEJ/xp0CABD5/Se3n1PxGVy6wXTZu"
    "UQOq5k5LTekutmrj8Ljq0eDkYLOevY1nCGueQySFdLbGJ5UwKuKF/gWxYuMXX83Mogc8AMW2q9nz"
    "L9vSNiK2LZQqzVNkhFBSSF2hr5Xz+ypZ0PYgLlkW2P+hRUiipZFQ8sUV7sEDqN4b+6iJOrx410O3"
    "47ERL/pevvkKLh//BoHkEkgySUWLWfo/N2/H3y3+q9Xq/y7GJmNFtDKiSQTFRMRxH8ofsMEHGSJI"
    "aMmUAsqJFNddDL2aAiajzRE/gdf7/XqqUV0odK+H+u1K7uOaGjDDHif/i7kinChIIrs8YoA="
)

# ── Extract + compile ────────────────────────────────────────────────────
_BUILD = Path(__file__).resolve().parent.parent / "build" / "inline_k11"
_BUILD.mkdir(parents=True, exist_ok=True)
_CU = _BUILD / "flash_attention.cu"
if not _CU.exists():
    _CU.write_bytes(bz2.decompress(base64.b64decode(
        "".join(_CUDA_B64.replace("\n", "").split()))))

_ext = load(
    name="fp16_k11_sm86",
    sources=[str(_CU)],
    extra_cuda_cflags=['-std=c++20', '--use_fast_math', '--expt-relaxed-constexpr', '-gencode', 'arch=compute_86,code=sm_86', '-O3', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__'],
    extra_cflags=["-O3"],
    build_directory=str(_BUILD),
    verbose=False,
)

# ── Config ───────────────────────────────────────────────────────────────
def _find_best_cfg():
    cfgs = [c for c in get_kernel_configs("all") if c.dtype == DType.FP16][:40]
    B, N, H, D = 4, 2048, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v, o = torch.randn_like(q), torch.randn_like(q), torch.empty_like(q)
    best, best_ms = None, float("inf")
    for c in cfgs:
        try:
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            torch.cuda.synchronize()
            e0, e1 = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
            e0.record()
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            e1.record(); torch.cuda.synchronize()
            ms = e0.elapsed_time(e1) / 3
            if ms < best_ms: best_ms, best = ms, c
        except Exception: pass
    return best

_CFG = _find_best_cfg()

# ── Public API ───────────────────────────────────────────────────────────
def forward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """FP16 flash attention. q/k/v: (B, N, H, D) float16."""
    out = torch.empty_like(q)
    _ext.forward(_CFG, q.contiguous(), k.contiguous(), v.contiguous(), out, False)
    return out

# ── Self-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    torch.manual_seed(0)
    B, N, H, D = 8, 1024, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v = torch.randn_like(q), torch.randn_like(q)

    ref = F.scaled_dot_product_attention(
        q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)
    ).transpose(1,2)
    out = forward(q, k, v)
    err = (out - ref).abs().max().item()
    status = "OK" if err < 0.05 else "FAIL"
    print(f"K11 [Encoded Swizzling RF→SMEM]  max|out-ref|={err:.4e}  {status}")

    # Latency
    for _ in range(10): forward(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200): forward(q, k, v)
    torch.cuda.synchronize()
    ms = (time.perf_counter()-t0)/200*1e3

    for _ in range(10):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    ref_ms = (time.perf_counter()-t0)/200*1e3

    print(f"  latency: {ms:.3f} ms  SDPA: {ref_ms:.3f} ms  rel: {ref_ms/ms*100:.1f}%")
