#!/usr/bin/env python3
"""
FP16 Flash Attention K13: Iterating Backwards  — RTX 3060 SM86
Auto-generated by gen_inline.py from kernels/src_13

Run (WSL):
  cd /mnt/d/GITHUB/Mini-Attention
  LD_LIBRARY_PATH=/root/fa_env/lib/python3.12/site-packages/torch/lib \
    /root/fa_env/bin/python kernels/flash_attn/cuda/inline/fp16_k13_sm86.py
"""

import base64, bz2, os, sys, time
from pathlib import Path

os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")

import torch
import torch.nn.functional as F
from torch.utils.cpp_extension import load

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "py"))
from flash_helpers.kernel_configs import (
    DType, FlashForwardKernelConfig, get_kernel_progression_configs,
)
from flash_helpers.kernel_configs import get_kernel_configs

# ── Embedded CUDA source (bzip2 + base64) ────────────────────────────────
_CUDA_B64 = (
    "QlpoOTFBWSZTWTHhZpwALFJ/gG/f//7//////+///7////5gZb7zw9s+jCAO7z73p97O+67r46PX"
    "r3sHCqKdNOgGPWbabYXiYU1rbES5unfPfe9fO+Pu+pR9TQ6dWu7JFz297Pd50AEeshOZ22Rz72uu"
    "3vPfXfc+st3u8O821567nPD3256vmPtNejGt8Bvvt7vnFddZWt33Pu1kyvmfLNve58ebzzOi3d67"
    "2a6fe+x9L48ZWfOlKNbss1W7t02YJTJ9wfAh8LyNar7773PlqqfI47Dosve3ed73Kpyz0M6c62G6"
    "Yi4nuO7wTdZjQdzcHduzRtXd7ueaqvArd2cttEPDEHYXWmn23a0kJ9ZA42tbt2LdctxLUru3Jq3b"
    "NsJTSCARiaGiZMgTIJ6JoaT0NQYiephDTQyGgB6Qeppo0GglNE0EBCNExGp6RqbQZExlMmmJlGgB"
    "oAAAA9QMQAJNJIgRMmhoBEwmU8amVNptKep4FPTDSaaj9U0PU0eIRo9T0geoBgJPVSRJqaZT1PKn"
    "tCnplDT1GnqaAAemk0aGgNADQAAAAMgCJIiGgmET0AmQ1GI00E9Ap5U0zKeRsU1H6nlNJ6jM1Rke"
    "oeUepoyeoIkSBNE1NMKn6ap6PQQp+RoTRqekmmaeRR6Y0ptqj9U/VHtSGCMINBkzR2IAI/hBBRPd"
    "+ZP4xkE//QKg2jUElJrFhQF0uJm+g1xixiu3OMqSJBNf8NxQV3cVaYiqSpKwajaIiJ046fnP8n5b"
    "/64cfw/Xf3E8rPB1U0sRvDhdXIo4o8EyGNcZghohs9jN9hdrafaTNcbtoKwVUE42xc2zCIgnLt/a"
    "/v0aixVCcEOSYixQqEgiIhxUr+b57vSfyfaf+VxVom1Sv5fyz05f4Ge6g5rjznEdl7LpBezOKIt2"
    "zFNN4Z4u6iY2qVKhyMuWbbluak/tYVY645MguCbWZgif2VtQ1Eo46zWBTLK1kbopqFyXKK0+1TDD"
    "iZBv1UacTVLk1TZVotKtltvWXMKAFEhCnZtr9+3g33ZRFmw6sYlOOa1rEV/n50DEo1iy2xFiiWhT"
    "VKqGUzLWZlIjgMYcv151dMiuMSzbnOAEQQ12c0TTJumwmuDnHFzmiMdKHXLp5GvLNQSElY1Gkc5z"
    "CZRJFXi2/Zvdq28iJOHFxUezh35nC8d7LwboEZj+TVCXRm2gzZkw6XbKUd7Y7Wmq7nN0eINkj1Do"
    "OBkmPCyxN+WZitYaTJaWFaoiMUXseDJMDUNrNx5BHZDbbHCoWyxFGSb1NUczCojDj1+Tva1rWta1"
    "rWta1rWta1rWta1rWtbGta1rWtt0cWEYgKQF6PRJOknqYB/fh1zvOsngmUp+bbAyOu3VEzt7SmJq"
    "ku6Al/lcA7rYHAd8oLBNw8Bzw1BXtBFPxQ3ZmCUMBldwdDinBcLw9ap2HtQkTNft2EogPig6yQhC"
    "BwNCtAzF7Ezt0rjuabyF1cifnzGQWNJwCgGxdoxKD6v8r7YGlgSKZgtRNVB9cFPqYBpIppfbm6Tz"
    "/4em/7+/sgU8EcDz2ds64PGbhy3Sg3cJJISEwJIQJCfUP7ur2etgCkJtHeqVKtJUknw3iM4gkyG6"
    "kzodSoPP6Pe9zn+RWj4IupyevehthkIGGICHY3pK+BsUAXDlbIqkqFgVAYnazj/+p15SpFnzb8sJ"
    "weSc/GxSCORjE0octFc1wAkJEnwIIqKWUFTugiC3KpREWpAkWScEJPfZWAplooym+twkO1gDwvyD"
    "AiMIbsCwUBYdaElGReQnlOYCc9g/46obhvMN8MQZsbHjHG3P4trlNzxZJhefxlDCLlEPFGyCR4/f"
    "2rBmjCJz2yDfXlmR1+OzneJ06QoisIbcCgqxRg8gbCIDR2+J4+yc0wb5N785XZL+FK0CBnIAUz5I"
    "gfAh4OwkIX4vqNKlBDbKbTb2GBlBnxkNyMhtwWjnC/f5j2hOreADH231pJHU5qGd2GY+bhF4JxNT"
    "Tc0v6rR5GsC5RfL4LMkgIsyYZwO929fY8fU483LxBAyRhAkzCnZCYcfegvA2sdhsMdpElQJCSceI"
    "9JGOojNuzOcTtFYIccroBT6/FJaKSKtJ/u8PCVK8heQPzxPYiGg/yhFdier7SodwdIWmGDJOlcNN"
    "qSeTnr2Qeo1qe5Dwm7tLExP7jGM5UvQPpPSAD4BeT+BX6coH7Z9+yrTAt6xpi5+chNVlgt3Pg59c"
    "esSJj8Rx24U5igd0o1Wwr/VlSES2sp7ec4d1vtgatABzOvNti9gA/o3ie/FNCsY/FTUQgiJEgi/F"
    "QKUTze/9ftmeT7LWPdGjF8nr+G8o7KH9ZMZnUGZDTTM3cIHgdl6v6JeKDAMxy83tUKyJeqLqNlnH"
    "i3Ifdm9F89KJlI2Z3X+G5949Nmt9xu1nzb/NsbYaqsRGUIQFUYkoACIBIItRKBIcOvbCd3PlmvSn"
    "dwrAgMt3rs4mNs1VXbPQ9ro21o11QATFGXluyqp+N6qdJpEOktBvkUq7r7NSdnwfpPJ6IeTy/L5H"
    "PMVedvO3p9UWX/fVYf+slMRYFAr8dNtuLdllUG9+D5fLo9ZoWt7pcAYaggU42swzH1/qp9f2fr/Z"
    "prVQubz6BU006pEo666QSMRBsdjpHIHzIjnXbcW2wzt17/ldcuZLVvDHATa5kFQOkJWYjtSc7bul"
    "rGpNRw5jWBcXFzPwbxZaE2We6iJtsIpkJnmHbY7bdtMhHYZz7/X2rt2Zuvc+w4aQka9FLNTrz/J4"
    "9Z6M+nGeelmavQ7FxB2UmGy147bPFCSwmKRSaHWi9tj9Bczxi67dMwXp01wU7W+fs1ybAvBERqXl"
    "SwXxlHXo7M8eGcWUl+xtAmX1++EjKlnmzyt6Sw0b3m1BYXMZRIPRXTFpBnm+sQFGRsgvpz7jv6Yn"
    "6k7HR1w1L/XiyQH2VdjVMzocyTZIfyuWAiOiDE/AGGcoZUu8XR5N3mo8e409K9j0lmLN4vvLxa5x"
    "jsx8dzHAKXtS8Rn8nvSfJ6MVpIiZmaWjkPyyT8pn6fk2xh9y0YRyw7FGEkIBepcFcVAmwUqJHjOF"
    "K1eyNqBcgNRsM1UNBTXP7XVC9U6Wnw97psfqe0Ksk7VbBWOOj6MsMZp1WxSHQuqAxGZ4J1yrDEBk"
    "izGBQLMXU4h5fD0paKlKiQkIj5aBXVHOoVuwtnSBdfLS9d6RGNWL2beenza27qK8mjngOdmnsYYg"
    "gQQowdIHI+kjg2xSzX1iMWOfbPQa1KxVZnK083mAZb6fgWpVFcyBANc0pJRxM4IE0u2djfV+Sjfq"
    "obSVcCBYWuyNDDvKc4zLgx50X4vteumoTJJZxW1rRSK2ZJlkXmIIjktPJjqs7rD1a+483rkKuMMw"
    "/HkPviDp6I2u7rId0had2wZUkWxY0cdc0vgdWK02fRMzXMausqCgxHC8TBlv1Xo5vdn2ZvTlGYWS"
    "STUKTem1+mWuLce0OZCIh2SBO6Qh7kGTcw3dWlo2Y4sWnwd3cbPo08DeQiHHhSoQkmMhMnS2+PxZ"
    "xTVbKycwNBBBhUoWCxtLJitU2qdMkJJMWL2sHNoOkoEBJQzsEDK4+cTeAcC6YZIYuS5VnSWFFa90"
    "FnVToGsWDvTAkkkJCSSRcys+PgiDceNprbrvsZzENTj256VFXcTYfhV3eOJ1atjZ2YwvldnDOb1S"
    "M3f6Ok2rQcR7O8b0OPs5X2YqOhMOwtzFH0+6TGunpDV0kYPyJG7SaCE0RTP08XIylB7x+ZTBsyY1"
    "ENDEPto+JVKvlRxjIQoqKPp9zE+/7RIxHPYU0tLbp2rTHVCNb6fGEcyjZrtg3ccB+g6204Z3ab3h"
    "oROzBO1ES/T5iFbMjeeQpKZwhKhZ3b9+/M6iRdXFvAReYuaUzEENtg2qmedcC+ijG6ARGvYs0I/O"
    "pjLsiJ+bx7jnjJnhfh0Hz45b/FLpY767sgUD+5DqPcoQJEUcQ7iIHIW3XDP1No2l/jpXnb0JiNmR"
    "H2868NfpoLTR1b8tBMQyZahohJ1VQ6+3tYomDEs3ZbqanqonGMVzuc+KQNu662ZI68gK5elmAzBg"
    "Ltpu54ltF9yOw9ptMihUav3WuQ1BYvB/fwbXnNtsHJ8zuIFDdndp4TZ5hdVsqA2LdMUj2cqi+9Ag"
    "owSYb0v1+Xrzi2gz7DBzpwJxc69ejCKm/Za7/C5t/nwxOTPp4zj05GzPaT8apcbR27TVqagKmqmg"
    "GYnlSfRFFmXJoAFQXYx2DKMNmm6q9E6sEsPVIkX3Xa52Uvn6vXZnWe4u7rOCU7aS0fVlj05V6rLv"
    "ubcNId5tww9Q/OcqJkk/OxjRqbUz4KiW/wrdjXlig8a6+amDpldB29VlVlRScmgFys3yAuMen7Ph"
    "vNQID3tD0Uv8PB9OzzQ0MaRysi7JxOydnjeRaDGAd+nLS5ftGjXkPBF8GPHGRbvKsObI4phyB0x4"
    "kep88bn3j0cYcudFLLK1VBArJRY1qIz37bll6S4zTLASIKWjqiImSlttWwUuNbcTxyZO7xPhveeA"
    "8PA9ffOk24p1p3XxFZKe156e3XFqEJc90kB8PFuPEsFATUGW9+WUZY4tZnLscvJl3emM7+M8WJnK"
    "GZVcrwCAEJJbzXs7UCDOtstRRSK3TfQ11J6LWtaMzZaWa2sOWMacG8MId+Y5qZheXZKIOo8DYZwy"
    "XZsfkX+m/NljvWlqUr1tR1Tg1ezYVHCEuFDynVq3mlvo8PL5dMaZlQ4XzpJEoN2dNBxATHBNjhqe"
    "FDTGIgGUeC162dMy0OIs0IpXrAerE5GqDnRqY9iFvBby1IRPxdda4cthr1faV83LiTCnxkYygV+E"
    "opfD8XoIVtWtTZJhxQdxux2HaKYW2BBCGXhAvYwuq2JqJqM4bkZqurDj4DR+93Z1d/i8vi9Sqqqq"
    "qqqvdrEruPTuueY87TvpB8EFiagiXlRiS3689s/I2LeBWFpp5DONUi8iOHLPZZcq0c24t8NcU+IZ"
    "i+6jnzyybcsjnRqHFa/PdXSHeXPRpYyNbRam1//JGkqcXwyjr4ZR8bmKoHWJEo1K283DLPCaA72T"
    "bxPcp4+Hhp37Zb6O/Norkx9S+xHr2Hzw5dtG8K15oOksTEeXUSsUZ7tgq+adCQy6ETgOqnLOqjZM"
    "lrg4TfJwurkULrunyIy9oMZKv2/IFuyksYRhglpx0zIwamglbyIvCEXonr962yho4ew26r9hTGq7"
    "p6XboTFhngYbysmX6NnbXU1zh8S+UtZJLBvLPw8ZEdvfU8wvdtFr9VKcZRM5Vkd5rPLx251jFc74"
    "nEWsKNTXTRJaIBIXcaZGur1LVw+b1gJpGj2EPS0GFHMudYvpz6yShp3Pd6uYHvUtgyo0I4zKCFtV"
    "BTFmT8UXNFm77tvjHQwkMH0elxbnGrkWKG/f7+/2HCigRo+NQs1OxvNBxz91283UVRZb8KYyZVgW"
    "RD2aJe8Q0KrreruGoVzKatWXYETbBUkFFTPagRMs2jt5yu/VzZ0NDJIRisQkRkQJEMeNDs1e1nyL"
    "7t9Hy3w32nBlm/WdiE0C0EILaj05WTPLJUBXqZtkcpDSYiCWO/dvyO/mb9Z7MOgez2U9CBQRYews"
    "VCqg3Bm2aal+z0aDi4OJD4YT7FCWN1nCDWw2Chm+mgqmNVUHWOrII6LLaqKNb7qfMsCPNjIAdxZ+"
    "ogBqm8iYlJAzu7Hzo4psrPxXClyKuc96ShjJMFtxtk1RSbVxbGTEYyW0SWLRUR8lTbdNX208s3yi"
    "evw9PyepB/efSfvIfiQf6vsJ/dSFkzQTIhRaqc4jdx/6AWj3AnSAe75Sw77+9r3Y745+Z0uX2+3l"
    "8X7rbOJpd0XI4bJfGR+jqvlHBFSy9ffXR7PvqHjFe2YfFYcHpFKcYWzp3hMbP2acffoUF+Cg+Ls6"
    "Y36XDgIsRzQMezY4wCEU+5yAhuoRSzOZzgQP2AaGX9eBlKIgxowf6bMrYGGrJ8LWLIT9kGFZ/UUl"
    "UUdrPiyggCMC09ZRYH5iP2IhCCP0wCl/GQR/OT/FWNpL8iEmjZ7duW+OtGjRo2xo00tLaml63ayv"
    "kWlk1SqvuVviW+dNtrehrFjQpIkgSCc/QTpnzHbHvt3eF86nxIoe0SzUojFqEKW0CX/FwlmYYGFX"
    "Cn4Mw+Pbo8ATXz20B7xQjT04PhR9G7J2mUPmmdICIhkmhQhYizsdnjp3px+3vy0cHtH7pncfNpys"
    "c6Dr1wtJWw5Z9tdOWXRvRi6fDtQhnZ0x00mhtoJF/vUiUaIdi1bUU1rqhIEWrAQREBBEQQ7w0XKG"
    "aUXObhu6QmEu4bGhzWRvAtPkfeeHW/K1Yla4edTTgOXvLlkrOiB6RpbFqXIIrpirUQ6wZXaDBSkE"
    "CV5zoDFkYyjkYJQko53HL/mKk5Ej+F3IEJBferUrIwNEOC1KhRxk47sMNTFnzXwoIAmm/Msokjg/"
    "Qr7yo0ZfMHk3pmziecNYHfub14/a2qvxRHko0LIwdbnZah5gDQM5CAfU2Yf5zma0hTA3ztOX1ZUW"
    "tV29cWsAW7s0EClDmS4zOjsvkL5O/rukWVnXv8kTiJhbmdgmMQ8NK9iTggev3PQ+7qckmCIIE4kf"
    "K7HI6is6VJqQrAjAh8iMSyMldqcY4TBpjEB8CkGsLCTZmwev8xyKwg2qXlt3EbpaXdhMhIJRueGF"
    "Y+YsZpUkcdk5yKjnu1yskfhOf0mZRHZ5Oq7Vd3hPcUC5Hn6pUfMXQRWEuv505APeQfjTHHvdqkch"
    "FMqPV5sAsvZ+im2W/zXNkXpie5hR5T0HcbOjDf2EaRO7Kd35zlz1GbJr+LVcOi7GI5einPnZflXw"
    "sqlI7RfRlJEHQhGaZ/BMztVbBS/LDLZ4w+/dtOWM+CmaPLq32/Ju0HGp+zWiOOxmuEmosiK+KLV1"
    "u3XxbXYuaFeFUQNlGqDgg838NVRXh/NXHPdr21ZTq1KyGJ+HAgqNu3mtguyjGDaxm9coqV01rU3I"
    "zsTPWIzIMdbe0yGNcvHDWX3LP5PDh1xvaOeHtx0dpvlgag4iSRTfFvn67Gu0QB1dVSEvda/BQZRz"
    "BnIYA9pFsIKwAaiNabGVaJh8ZSlKUp1+vRo0eAw3DhWDsw16ITsaVcmPXrHaSCphhjhTxzLTKjjU"
    "5zyMc5bPe0LfodqqmnfStGMZlkoXN0mHOjM1gs485nuaxLD2uWojZ/mlUb4L7+v0y6o11RQ3qQ4u"
    "7uhamO6Y2ZF9KEsEUgBQvAkdZk6WCE7u7tJlDWWw1x7JzlGDqyDQOGcmYka5wghCNOEDqVe8fPVl"
    "ehmck2dXfy+R42TWvEURMt18crXk59/Remls2NGOljk9ZhESxwkobxwK1sIw/gVxh6pyCREJMtp9"
    "KwIs+bqpAmjrncJlKJURxcffdXhgbRNKgc8UN8FRgjr58908BF/bXoul+RMwwJDDfcXIOoNA8JcQ"
    "xAiQIGiKUEUaPzUonqOzot+BFT+8iPSImI9igkE7aiglNuyAAAAAALmp2WrDgP6wYY1MNL2+e6qR"
    "2xF7VyUKesJiwIPASTxbKgtlbKgtlbKgtrai+jvl97BwKLRFkZr4hCoycNFhJOqv6NaBbsb4LK4S"
    "6u3tiCqsPAPJSN6qMrfJp4SiHfoSrK2aNNvjUVyjXvk7PRCeeUnK/eqoMemgsi9NkRx+j0b8rPif"
    "ZUVscxrC8G+8tZc0U2kLDc4EDmoOo/gbj3ju1oiZtJ6vs9OpVUE9mS9sNHcUIIgFCCiFpVXKr0Yp"
    "lFIYooo9vervc3JZ1uyiiiiiijw34i3TNaUg5kOzpKiVBvmGvlmawAbWAMgBkVZttb3MvE9i8Y5e"
    "ebzsYxjGMYxjGMYzz21bm4xRijGMYxRijEaPN38Lzdt3UaKNFFFHx+jm6UaKNFGxFd0+HzXnAAAA"
    "AAAAAAAAAAABqrsREREREBAQELaoRERERERERERAQEREQEBCBHKrcqpaIiW1S1EWIiNtrfxLnyvL"
    "ez+L7QodeUmL+e5xzV27e7ursCXE60EqKGLlFubAVifWt5BrxWIBxUKtXqgpVQ3fNqVFu31zGLuc"
    "nPUXy/g+Ts26tWjm27W5lp1O9x2FcDBpbkmFteip4poNU8BDTRyEfLwbEFTI701Gvp5zNma5g2q+"
    "WxPnkmz93o876I6BcKa4WNwLBqGi411FmqZMrsnXx10HlNuqY++Pbv7Xyt56+L0AADCAABCcnAAA"
    "AAADlWYsfwQqGL9N/Ljx27McCtm4V4l700TbPZ3QwyySVefRSfGVx/poevm1xCsboa83GscNxL3V"
    "xg84E2yKB7wOkY+PjUGJMaxDIm7Du7Ed15ZFDki0mcfMZzVvnLbjY4V0XtCyOtCNDkdDQkQ4vRwF"
    "jbxPTSaBg897VuvTct6t83tVrXtV5PAAACAAALq2rXVtWuugAAqCqqqrFTt1IEOsodkz2ebD3/qW"
    "xPi9UsLhwHJsqUfVS+fh8rwltzw+8r6QQwLe3l3RK/N37qJWrkbD4Bg/ANpH/qTNQuuuaFDw7K+w"
    "XbVOFkrqId2UpGmzq7O2hZ6Hu80LLcZPCrhfLj2X0Noe7B6LHlbmoJyHWLwYTZGua+TTh2Wk9L8u"
    "HDV6dft0mnHDdf4Q7Dze59g++j+w7+2gtVlb1W5Y3zaM06stzKzHq6g3NqaPQUMOqGGliVZc7LNX"
    "ETTgu3oOik+LzpSjLo3y7su7p26ff9mmLVtFLZVtISGCwZFSl7EWowrCsJOqWyd6p63c6geBxmdU"
    "NdtvDSM1i9rWnB9bCmtmTYNb254GAkyBkyGMI/e1TqA65uk09/nr4fezes9MuRlklvaMHg4tDJ1G"
    "AaBM575PhuZujgRNEWr22jPrMC/Vnh08oe/FzemXV1F9gSEMkbhA4iXu/Wt798/SVbRmtmtrEpbR"
    "aZs02mZE0a2LajFrAEkgH0UgWGLfiPrREyaLH0RQkWSRRRSElFdWUf6yw2y6tlQpUsa424xsw7Tj"
    "dNcBLtzdm7Av6tLdtWiDcuLBKAWrGYNdhhQT+KoDM48fwc28nPx0U4689Ue4fiSoG8xI8XId69c0"
    "OwB+Wfw2iRdkDgP8gUpCEmqXkkIafzRf0tw9Qqm2E4xgaFLWzGz6DH/OJ6U5yh9rIAgajIR6yJYI"
    "sTEqGcwLwdgMBA1aNhNmZ7BAWMnc+xDgAzHh594b3vmqQx9XrZKa80p28iOr9D6QAByqucAAOVVz"
    "gAByqucAABVVVVSUhA0d22+jjjgwOJPUYbR2aZNVdh1OJiHQGAc0UNMXk40h/KwhOkmMCynUdeeU"
    "u278u9EdWmVBGOGTTJ1HoPQdoilebpGQZuEiYxqbBAwBBYcAZh0AdSkKgicN9+znkqmZoejdUFPa"
    "8Rk6ZpK13sPwZvjPyL6ILBEnYSQJB/UIcx1Ci6kh7r0AGtQ1cLYi4qJPooA8B7i3Q8oB7WGpz1j+"
    "xk0K2YFddTelzMzMsuOk4COmPOUoYE0kVB88ogRNiussaSrBZ2cSFSsjQXwrroozREyrYzBEeUVR"
    "4wzERNiBGqyPwpaF2OdUHMVhEAQpNCfqIKqEJrQupUAMCoa6D5/roS5dVRNGMT1GxwJDJQDWQKBb"
    "T8f5QFt+6o9DpQTG/fwPt+iYiI+s7xzyO/gaOkJOOOI0N919K+1MeNFWPrhCFP4xD7+Zohrmfj+z"
    "XPT7DzQRD4bPxfftttuj+UCGs6fpCy+sCEAhEwaIgRQscw8apCKHEiGpEC466pCkSUZhe++9bm5s"
    "d0ADvG+FI2AHTFYxxiTJOAWGjN8HPz/TaJhFEsNFee2RsbVxN0F0wGKzYaVkIzKgOMQIwSzbjlhH"
    "SI/uwasOG0wUodLMABjRDeblyiC+5d6Hq0R0mYMDAJj6kx9SZtiFS71SP3/ismcKYHfTs9190agN"
    "0HqTd0h5190D8VKc31OxUmYVD4uvRCUdXzxJju9w7icNaV0gY/015r4G9LxugDZa892pJ+/Ap8PZ"
    "9Uc1wExiIhiy+BBZN8qlMHXyI8qxBiP6bUWvsO2gTNbKjfGfR3tAOS8dmu2cgZgzQXcZGWg4X+58"
    "teUmeST3OuIy8UxR9LAOm70HR2tTye3Dgp4KCGh1SlCNhcNhMTWn4dGsj7k/Lad2b8tp4l7FKnCx"
    "ePlqnUydvn8OXhVPbBJzRT6vkuypdgaCOnt+XmuumiakxvfZWUROE5nMZrZQLyMWeHa9bIsOtOTi"
    "cvBwU3898ybvvU4jDx6zAdBZocOEX0CfoeCY503EAbkax2aJZGATHcpllegUWDi5DU+OL8b5ebKO"
    "Wd9kdvTsQHlQx7zuzdnceU0ocejnSflkKIokgHQMVIXud7tP1lYhTJo3ds2dfJcy9v5V99EIEIKE"
    "VjIDxzOTIXA/TgLUAZBkAgI6apejADE9/hgZWRE1PuZ7h7eyd8cBWRoZkkArJxFsdERLzDD+Mqpw"
    "yiUkxRCBu2FRXw+6aYy525gYX3PQQvHwdEzwYhXDhaYk3phDmWK0jcApiuYEidyYB3yWdW5boCv1"
    "kFY+6P73DBTLTISxQEayAVZhbKlrE/a9N1V1d+a4qjFW7DlNSQYI1FZFWEFsilQcqKRT6Y0QMIS4"
    "UsRiQilyA3gBGABwBNaRIkTQkTlSKxLiL7PkAL+cmNdW7gefKWtRxmt43KdVZHr78pw+FM0pupWi"
    "0B3u/wer48ih256ktWE8vn9eJlx7SEZaioC1FZAI+x3ebLjP60T66NDCHPUq/N957TDu71sy9l25"
    "w3Qoh2F2/d5jkWewcqsThhYDiWkTkx2bekJG2LdU2ymtt5AgggO5Zg8vHcY7MZfiD9SUvRCFmdjW"
    "bLHI0bFTQ1mknJ7N1y+XJK9dQ9W/KGEJhRbPO1XYKEitUCPT8aIls64IiYfRFe/0p2Wr6rwkh8v3"
    "n6P1ZsDwQzaPrEKPnuH3Ce8l4D8flKCxD5kRIhuUhOz8PXNZPtTDNX8wm3wfIKiq4B88HXyg7H16"
    "/pgze46W7d3gcZpB49pJuUVythT5HJsi8Bj5yBD//5vxprb23DL6PnPpMqs7suts2EKV1kczQ6dE"
    "2y6s1liYhu6fXEzV9bt7doJfyFegNtHte5EiXVLa4cSG5P6UP2Kln9CUiyh4/sDRpf1Pd4ctLaYR"
    "R2hSCmIH0513KIAemyBOlXkA4W1iqwhr+HaenI6A3Nsl+ilTzCIgcWLPEP3hknofxoqJ5ilfx/xG"
    "KfIQ7Ae7gxRjLCEMgFcLQbW2hbS0KFtLdENSEIeeh8R69jxy/1/a+z/6JzIieCEbjj8IUzEs/Wmj"
    "0fRI3k6wgRjGB1wfvgfl/0Pe00d6psp92YR+b50/zAetTO6fNo/KImko7orxSNP9Aj9MTGxoSOsE"
    "TQpFZaK7pt4v18k7vA7i77wNUPwAJFv7szolBUACgIkkYyK9wny3OHfyEgHb5YeWEhSBv0B+QZ8o"
    "nW1+aqqqoAAAAAAAAAAAAAAAAAAAAAAAAABz5/w+nAAAAAAAAAAAAAAAA0AAAAAAAAAAG3VvSv1d"
    "XxGtabWEo9i+6HiOXlgAHnImOqDwCAecLSjk+KkgOhU9HnCethN/yppIwI+RirSDXu7P8cRER8TE"
    "QKrnP2/A5FJJJdQWDdJ7DM2k8DqAb7zHlGdX0oYJ7wIlzp1Pk9znDLFP9Czk7RwU0+kPCCipLD0x"
    "o+cI8d36RP0XyS7QWx9PjIVBb2+itrpyrH0K1sgraTt91WaGkZYZ6jiEOxqHhoZ1H7S6uEZjkMgQ"
    "UOi+hYTprMmyMuHKBnkaN+7mb3If2hAR0ieeAdiAgek6UHzsvyQH0dp5eTMIwilPcmP5Z9pDdJKh"
    "OBRvN2MhDlq7gkcUkj8T6lA8ZYPZOQnyEt3WqiRdQREoGwO/C9iF5WKeYYNK5HqycxDQQwOsJCQo"
    "B0hkdgXg1AcDBzQmsHV3bPBMYkIMSEYQUgroeo1esOopKKnx/8rCUFGIhUr4hm3n7jxVOAjv6UVi"
    "sIBz5896dUDTAYxPM78fIOfchS31KhK8+9vCScO9MUuw5ZnetWlJMlAd3lPaegRgiHLgr7icxgh8"
    "Zq2sD0R5SE/90ebwsh6h4fx3vHcZ5AhwpnAuRhFKlKBa1rVASFZWsqIgqqe3AT2aneeVv00W86KU"
    "aVX1Ir84UZoJvrVGQkPl5hLO7x09tqTu7b+ra8h9idTJ/R2lO4urS4SzpfVpeyqzJxfe5eu9bjNe"
    "VVqqD+FDHvsWrsmSBK1hEwMYnwG1yDwgnUgvWAj3XYdZTr8NN8DB9t+T/UiuP+XwAVjmor+FuwQ9"
    "8fUrEDFPEPrTiB+uwlD8Z3joLYwV84jmmoZid61enb6dLZNr8y+Z4H0G3vC90AGUoi4+PXizMzMz"
    "MzLjmZmZmZmeTs95VlAtpuHnjOAlExH2pfvSP+xNt6G6ngrapx/lnZ7RGJM98fujHFc0krBnuWKd"
    "3Hd4DKHOMIXd3d7uNe33GS+gPL5VPKnlQ2zMEO+hbMGKEsKREA5qxVkhtpSw9IU/aJNIFRuVAzDr"
    "SBRANfwu6K/MHBn1skTztt9qsScrL/Y5vEcVEQ+b/QhtSMxUZUs0BRH+n3D9rns7JSLceD3RprBx"
    "hAvmcHZAhM6B1VKrBub5ofPgNLWUmpYUHKf1yiFh/f9ktLeO+98cqd5m70txcBWRwxiBAjiB4lCy"
    "vFR2R6QkEYHSlt+Daj+fp7prQG/3ftYYmJo+sh/97vmDkCBo+RLBnbkSxrkNAgZqKZDDyTrJCLaI"
    "l6XLr17pXU9RtC4H4JWT2JmkOaTlxlCxOEiHMG+lLzW6nmtQ60cF+6enFy6JQQ9WgpS8URSWhkyh"
    "bDNsyptLEuOMEKqZ0O/YWDq/TrIeqdCg37EsZk1aGPcImZA/TPD8PaO/Y5SM+FPlc5nf4OWmDAYj"
    "iGB/L7YfRs/7ktFcg+U0Xj7MVPYV7ktOsxCQC3DhUwSmPlHO0GYhJI/bPXFaorHPVQzD/GejqDx0"
    "dQYp7UshMJt6qEMiCB3zRS1I6F+sgnqsJs0SWjMj6fMFkw/D5vdhVu1pQESE5FvYGPxn33DyDDes"
    "90+wLe2SR/PC87RJ+ojvh4FQleeEVv6fxKxkr3az2mh5/uXDQaiMXZyz3ZvnBEwBe3NqGE6a7CZA"
    "y0NcDHA4gWGjem6WlBEDcADpHh2pSmA+hIEOj9HyNlpx2fyPxJs/Fj9FA4nQzpO7pe2LH2fX/P/X"
    "/v/9xv1/k+/+j+/7/935fT7/6/erCfXpYIf1jr68myKKKKEDYCF1Yn639y9UA8T+n+wt3/aUfZYP"
    "vqw5tGX4/hzhlfPn6jQUW/A5ff0EPirCyP2+4NBg4QhBhI6RLy2lUq9OKZRRRRRR9XNxjGMYxnW1"
    "bm4xRijFGfzXNxRoo0UaKO9V45QbTVnCgqBB4p9QfIf6w5nX6yyw/WLRmvzIroFmRERPsA+c07Ob"
    "sSIb7X8iflbDJ4Hwh5Qlc6CZaCx8yf1D32dczh5T7AHURNAPCTDgyuD1fRUk+JuK2Pul6BBEI4uC"
    "dwlYUjDWBiRYzY6EUhVAHRhpMDA/SI8yb9K+dMP8/6QyUTQfjv6TPpP0l/gnV5x+gtC20WKqrh5a"
    "BrRVVERURG0aLVtoqMkWQkOJy/QFyk+qH1CB1n1kgvrBxyhJJJPzD+ZDO+p1ek7fi+OqozWCqPBs"
    "IcBPJ/fJ+emSQkKMIhhD1p8pBPzkRMlyHmdqESLE9vSAUuR4tBRTRO61C2SBVFJqiSIEieCRwSCd"
    "hkukz6NJUCbMFD5CtMgvMaXvhdCwc4BwerU0G4dQhbscTpJoR2Ol8R0lvqOQomg7GYRhBkYTqQ+R"
    "1OXjjkzMuEfUlJppq5ashcMyos1OHZ7QJCQl7DYUjjWmmW8Qtn5o1FQXVsACbEEA2DtNKGvYIbXO"
    "CpuKCjRHgzmdJxC5fVe2AAAEgLreqvYmlaoD/h3CduvBUMwmcIrsbHQhjwIPBxvIdl2nGB5/T2W1"
    "LbW0bWjbaNGrS3JxA7zVbk4mC5Co7BWLMBYUuB9Ad54L+JKKWJc5lDuTijwdA4c5CIvRAxHWuuCZ"
    "ggFQe8MCAGY5XQQwbp0h1ih2B0IG88nf5cBuDbaVVVVVVBj4TqO8yoqmg1FixwiPXguANjCFiJyM"
    "bvUygurzcK17YJKvY019r2GSPXuXgkcwcqJ0iHYWQ1YVVK8DlTi9ZMjEM1umzsMCEkoYQtAogYTS"
    "OXft9zG6Ccod0BiRDajN75Yz8XQzlxq7IgWEnjolU3z0vch6kW1vGJKCGscwl5kqZ6KZmA8TrwBt"
    "dl4AYgHH1CPWcJtpXSh+nEOzPQGgobhVTXVNhmr1VEr3vjzrfffLTiVAfdmRaz6TplpGmtmLZTe9"
    "6UvaBC3G2ggPvuZui0MUdwHHQ9SN4KL6c5I47YoaOSGrJiLEs9SFRmbVBIjhwxi9QxWsFuT07KXs"
    "6Na1rWta9XLltrZ7jnDWaa1231mrVIsONWtK2epR6JIcTp06dOpla7a0ohZJ7ZnGhTTFH3xblnfP"
    "qCQxDsOGB+hkWi+WcZ1GL20qpxtuFEQnYBT2psDCe+TQdyTzeHXVclXJ14bW5lbm1fR9YAAwur0b"
    "1VzXbsAABAAAEAAAfb66vg15NrXjupq92j0m7zGMDnHIjCdHkAostY1Ak4+TybhQUUDKpXYj6TRE"
    "0NyBwrv9ZpQGVmMcTFgbWJr7y+9aB4h3AMH3FdnzRieQO4O0Z7wyHYhN4loeBhhnPVEXYP0CCIIi"
    "jZvEgJEhqSJKWAoSCFh5hmj6JAUjCAQPkqShWEPqppAgZIB0T5zxsYoeT4N52992JD1iqowRkhGb"
    "SrVLLU2WallKc5uWpQyyhmxFJNeq69zbbtrbSRA2ofq5gkQs8F9QMQ9Zzv3D/1/HTcbS9byhgPji"
    "ptOAJz5h5zefWGs1pZ0QyhilijqnYCA7Iq2PIUTsIqsgQIMJIRICSKxEigb6HHMQUM7sOgUM+YA7"
    "ePihfaGQ5wAEyPBxy7MF2yxlxjIqik1HCGo14JE3DNFe8gA+GEyne8l48vJzDrzBlKYZr8zVgoOd"
    "wy80gEAN6gCc24X49E7wyEDvu84o89F3lpETY2QtY/Bg7olsJMl8XghDFNDAQHw5YsA7UHkN4w3q"
    "LvnZR2mKdLhg8UUWlrNCMHlCD+1ilYVjGhcExCwFd8FNwPHgLmDk4ukd29ZCLPw6LDLNNVJRYIUR"
    "6JxV5Nltq9Erbnvyq+pt6iYWltFUoCRRKzD36Du3nKpYtgb2OkhdgRIzGgQ9qWYGhwaDTIx9+J6x"
    "saPpgUR2cdJIGfZeabtsODDJ1GZodAhipGymKYQsq99UMgP3V/nEhBfKEArjQc8G8YkP2omaIkBD"
    "yqlg7gi2E/CWbUtRYhfLcBZCB8IgGWwHGGFLkuJRaIlKRZzOnhRUIQtMEjkKJM0qMEGhHyLbaUwp"
    "LXXsPxGi34HrVKSyHKkAgEQK1sYOZOQePOHwBIQQhIRGEBU49FIBvGkLiN9D6NnamuJ0w+rYGz/1"
    "hRgjct+5p5s1eM2O09uqBrkAVIOAF09IXIuXiOYkgKueC0DJAOS3UKf2NSHtoXpe8yksWQWJCwwt"
    "W2o00/uy99dQXi3fLw3ZbihxtypEYrULxKSA+QAqlwwLAMi/rnLgXt+EHrwLqCAgkm3e+5l/nq/R"
    "/JtsgGgs/1/6tIYx+qixP2eqa2+7Bu6uENCv06KdEES/9gURGRZKIQqWyib0mIkRZWVmde+bIHje"
    "DscCkyIDJNBRWKee2O5xZeS2HApOHrazTQFUFNYlsCc/W0dovHI86jlgNc5ouTBkHPONnqS8tfhJ"
    "wPi4HJxyGr51RgcU0hDpQQ9nviIG4uDtJIPnIPSYO6B2j4gLr4v1mtIUT+DJQURm1BVgiqFIk3kx"
    "Kk3IlMt6nMlm1KWQ30aw1MRyrNsMM0iOY2zIiQwzMtEyVKBYmTKbbhvgBiJsG0BImKLZTYaYWxpR"
    "AkKXIUhhEFbFkBuhoUxAcLaXA9VvE9+EyaKhMsTJAIlQkkCOiRTNAQLdBFsAAsQDUZCcOzrRIedU"
    "qTsl782tySKSU9V1UrQNxVOAgcAgNoRAgkBIFDzfIql+S9H3DcquLOssgYD5k14AcEAiIemCov92"
    "dTOSLF6pDto3wNDs+Tds24nkEDETMIawuGLH9cNYyGKrgGii4eBNXva/dyCo+0nzQIQLTom4OXWb"
    "KZxCyC+SKZ+4a7Ihop4Zc8q36ZJRPbqwtkCqmGh0ihmzGBA+j2nwLs1ENOUuM4v8YJymTkGKWhY/"
    "b0DqvK617ZpFiMPufdxnLc48Scr1CwVICAkEhBOcWOjVBbDiyaxMzJbZjoxspcyUSJbmD0DPQYGs"
    "TBmxoNpotKTegYIZBgLOIkkG0EIrIUazQJMMoEUCtZc25hXl03JuyU5xkfU0mkls3NKP9GAtktMO"
    "0SOSZGdYe9ldWGcSW7AD7znfR0OSxQL50Y/HlnhYrR9mUk0Lpjfg88MKGaogz0rbLJquTXIyHneX"
    "lGgsptGyu0uMcBJBDG2mlDLWC9LCFrsytQSbhG+OF7RqYTJNBaM8kieHlNNJ+uvLk2WzAcbOiE3I"
    "tPLZC3ZgghAkwgSgcN3q2rsyyTcYKysOGXJXssKqvJ5DmzNk07iLoYgVNu6mM0xYamJvvU5S6eKV"
    "3ScBNqTeXNkUhdWTaaUN+CWbTahlhqsFCSwQAQxCkgTWroNArGbbG+ompmuu/fu8LqgAAAABgBAA"
    "AAAIAjrw727dd0K7dnN27o1ateHOAAAAAAFAAAACKKqpdZZtv/pevl58Zu8ynYTuOU0BozeoPGJ0"
    "F8ltM0inKKuG1ClWKRWKQEgjFAikQaaNIXAuFa5hnNtS2XjLp3i6jBkUFgxEGLBgxSDEFIWRqZpL"
    "hEcw1MXWxtRZhyDYknQ0aRRRQ5pVRVJRhgnSCNXlu+kyavKhleF2rugFxrW0YUaJU38YqcQJtCBu"
    "TDYtGo5AMKIO8SQi5DkRIWJwYoak55ARkBVA6DaWCFtgkkrEQZBCRkHN1E4PPJeKJx7ANK5n2QkG"
    "MWVXKFAmJFg2XKFhhYFEiJBgTWIQqIyEjPcUE7cx28PcsUcM46CLtBmYzGwwLYsBl+Y/cU7x/wSt"
    "rWqbxHHd2H6jKsuVHTJewprXTOe7uvfAXVYcxGboQhjBRywqAiSKHHDoFuRDLOsBkYZYBkAQwB0I"
    "FAnJz4503dnVuDCIhcwM9xm1peUuqgtbrHOQOkMAPRZU25tmUQUhBG+psU2Vo02ymrKa0hFMtYNt"
    "S2yq1clra6+C3O0prHRESEAMVF6sydEOjjZrApu+OaZxAFPDsDn14TpOWr0nAeISLEgRRIgc7V7a"
    "KhFIbRoCUpRwcBdSeZBmYMXFEHx54Tqy7j7qDqS/Qib6nbAuIQr+Kzs6wxniV14Jd3RvsEJRoYER"
    "OCgniLEJcRugb6FEHMSgdxipBA3hosA0cBWbfiYrtPrJCAQRCCiREQIodo2XsIoag3isYEy6XRwM"
    "b7upUowq8ZLYb6N9bcKbPwJru6YPPNb8twuWHXEiIsKxQRFCQOlu7MYbnQaCwJoztgBtNe2lQPE0"
    "GpB/JEZ+w4wsBdYDYIMdH9uWVFjTcxDoM6IMhiRxQoIhW0Qf0gMVqyL1EO6jxvw/CcyiBxQk+DsN"
    "xkG3qkkgAAAAAAAAAYAAJSSSSSSSSSSSSSSJMSSEISEnm5nl/IPSWiP6sAXxlHuEHJQIdyxSiT13"
    "th6gP2gb1EcIGkjguUDI6Q96SDTQcUuWAxqZ/SfkOlfogqkIIpd3fGcqiPiFBsFe/yoge0P2BFWI"
    "scDDRwQFSG8h2TUIEb8KgM6wiqeP2SIiWexh+5OQzzgH0eTmaIVBSzgCdmcEdz7h5gtCSNUFCT5y"
    "NGCrmTadZuC/dg0RET6KzTXBuiyIBEgLCCBalaDmBA2L1fSdKAmK4jhphFhBEZCEB6GoQSceslDM"
    "iNaIUoUkPVWA2TKGoQFyEkQRkBcEErIOZgUKQrdV4Dz+fiYRU9fjcyTcNR8t7ytdbQ8Z1BYei4qr"
    "tpUHDL+e9HWt3cQPoZ18pIAagHm6O6oXELct1F0DoCWJB1MsDc0MNa9Pr1vu3MyATa5w2SxSThKM"
    "FGRYAs+qYPmigURtJQDLcsYQICKT48hSlRTBAcRBSlaHSJf26UwD4CRCJCJCDBESQWQYrEUMAKGi"
    "WDDFClYvzMEkCiKUqaWteHnuysa1GqfTeEB57+q4g0dmZrEYbKn4UWCQ0cSaxFZZAJjBiTgCY3Ys"
    "hIVmzZKfgYHq9opAwrCk+CB4gwQ6Qsoh4orJ7IOTkUKJaCjmfmVPUGa4tw7AOYtJKSFSRkKEChQR"
    "FWCZDmKFJSQO3jZCSS4HO6yjafKaczvlnL7dKyIkgsRi7z0B4e5AojPyFCgJh9b6xcU0uikRKqKs"
    "YSbY3/MWLmFVH8WgOornXeqiQ3HFOEEvvIgA1Sp1wSQMaKbwAaWCMZZrTas+dzW41tiTFqiTa1JS"
    "WmsjJbV+DZ71Xeu/Vr5Lec97PcG18myBXIgdtqPKZOofJuQDAfCA8vGhWPxlFOIAdcR6hiv1D5Ng"
    "79hhJFkCdn81Pn02qk4s86QcxPGKkIa4dD/c8x+Z7mzaPQhDyLVCfCk6YP1Q5kGQLILBkqKpPcFX"
    "4yj5O8MK1MGbUsnvlhSIOMu4KokoMEEEdks3tynDJPz27Mn9HGxQ3I8OJZgM30KK3Z4OJrda57++"
    "ZwxNk1KUEQSs/lcQ69hIQseenJbN1Fm9fUWUFshuEOJnOygE6CSIsgPojtzbqoD3m4gZ5s6RcA9u"
    "QkgMKWkakVezwvSn+OVy9SV83SVYCT/bGiOEX0ewPH5x2C+c73QyomA+F73S9NVTn6DATJIAVZE6"
    "istKV0cyf15GmpqJMz3g1jRz4bWA9uT6+MgyEgVCMVNYtwIsGQgSERy4IFD0KKnJ4oPP2Zcqe06m"
    "i000xzVgaExnL7lmje6UfVNUDSGhZQ0RPtDSsTEDyCCQiikRcGIUIUwSMMj5ZmXDx00eERErXSlR"
    "IcCc0iyZHu83vE5sJUqtGVUYM6DNAi6mqGRIKZlxgNbFNVpTCi5y1gLCRNrU9y/bOBo6SymRM3um"
    "5Kblw0mj4EpCBqmmHnTW4whDWSFGDEEDP3CM0C+RnSGYkoKGBwDvD5cw08Imiyz1o+y4fW9i8bX3"
    "82s21tNYHZRefLktBweMEiBP61ZuSFiBVHBTJxj36Ost6Tx75Kef833F5zjBl0DUKLuyxkWdXfdt"
    "FTO2mHtsIbM4RCKgkA0A2KmI5WCmSlYYNmoQsIUgUkoQMmjUMEiQRQWQ5EDzlM0lWNQESmDIQe6i"
    "owUOPTF0EsANSICGh4rpE4BEPniQc8pr91b1eG8pjFU1AiSQhE5SggHNCZh1EPBETcnpYTEkneUQ"
    "PwBbrNBomKJLEjFHoQOmBAUSKvFv1xOUE9qIshIpECIjmdd8zLO84hAN41N8QWojCpIQChWoITMk"
    "VIqqb15xBoFZr4O/jwq5EimNPPB32349IhlHTpA97a4AkRRcpD3ZHRsMoGJOrCFnDhZ5S6tMTCij"
    "sI8rjoQJkRaIQdRRiCSZoSPaK+6PZ4XtCOpUlHMfgOsyKMhyJuSg9lUQOiKoBiKpfQcD0OSc5mpn"
    "KuWlrmYzlgAYgBEAIKBFYw6O+AIb8j5+BSw7eY22t6twYjcjA8UMwR5TzFBMGI87CGIxz4m+QutO"
    "pJg0SAnkTx6tfH44d5W1FRWi1elojYamtef1vq/LumulxpKbnAyTGVwOcrmbkm4nBHK4pmXVvvJb"
    "ZUkhINREmkyjIimTJaGJqixqWrnZYCSIrpIUIjBW2BWxWVJVtG2JIyiCBSykaorVoBKIAzkTgXF6"
    "8pSCuWSAYsNWgOc58KAyBMhseYnOZ3CiBqoPy9dPHj7QiVpxECG4I+ZYouI4lRAvju1hIBDA7w8S"
    "YBiq7c46X8jP7dtuR0PERZquYKbtYKBNpiljlbBjQUUMSxjOtpqy6jUQSFrYxMS7aHFpJSSmVOo1"
    "UBoywa+jboy2sDIorQMQ4VWsUTL4j9YW3hNt1Dt4Htzj+SvIcCsfsrc9NGKqtiq8d4+HItnS7QgU"
    "6ewNhUSNgqDIJ2AEX5zMOugEeiEiAWxSqQC8irWwYh2inCNwzgyAV1WmYIQyCZFMCwAqDGJQgeG1"
    "wTYePYqIujpoat6mie2QlFoCpBUCRVdcUvezGrxSQt/5RxUgSR4mMF7JqXRS06sUysyCySECLrE4"
    "IKUpSAtx4ObWqbs02zbWi1bFayaAIppkhYIw3bCRSRCZZLEAFAREREEREZqTMIVkCTJmGgAjah98"
    "IgGSGZBDO0QaNENYnXhX+MXQmyHjHbAP5YgHfATzsUD1RS06sUpxgadjTYj9gRNKRRPWB9xEFSEE"
    "9sgILuNtLpCCgF/UW8+7FAOVOqAFBA90jUkV76pqqaoOVATSGj+RVP93HYr/TE6ASQBkWCJUFhBK"
    "GAGC7fJ33bFapJSKtc2pVzTVSQnPywPDbxa5GErBQKhTyFMEkQHPKExTJxd9NW0CwIrICgSRSDIK"
    "ict8D0aiGaIAZxJA2PlQXLUN+k8HTpPl8subGUX72pttfKpBCf9cuAshYViqqsHVwWAwPssNtroi"
    "yFhWRhZCUIxYj0Wt/IrF6YTLe8Jf4UEz0d00dclCiXcnBiyKBB8f8DHZIQ/TPt2TNFxMJ4y45hSm"
    "oNWGyBp2NtsLDUPIWL4EHgWQ9e1gLiIRhpAwyG4/fDQGUFyVcmAKm5+55bxUoTf4Ks3IGjqPgASw"
    "bEBAgqmgS4Oyakzr5vHr4wR/2InoF6PNOWnZuup6PY6fEgBx8udgoR8HqESqHQL8sV2RQCoAeESi"
    "CREgC8tmt1MluSrbjUUpWrzS3jlevkvzDUmj5Ljn1smAKSbjUEQWCDnbIOkY7yQgtcwA1BAAWAJB"
    "gIYNBClCoZmAAYj1KBu3ZJV4MZEkZCVDQiYpGK0SbTNKW2WlTbWpQxWlJptIQSSSIgRwRAU4pzDp"
    "VDVTWZBoklJnzRXr4VGNE5JsOW27xcgCgkWzYaUyANOZRAy2LpTOB3RT2Cxiki8xRAgfkLPUkVIk"
    "iRA+c+0J8BiEcMSRqx/RdW9yijMkqtvXTrQ3QPNArDxHBBKiB3w7w6kdoBQRSh64ekN2EjIMsgUY"
    "i+eKflxZNqMLCPJ4pF3xL/swX5oWD0+z4R0E+lRwDkQHwP3KDz7UKddUdYU6kRiixxkgUIPuw9e9"
    "fPJwrBDI2cAyZ8DmpXpcgcVeTaICNYXEMwCgCVDZsFcJAL6conJlWRBZcsxFgjDVov8x4REREYF4"
    "s4km0LBCULCpWzoLrA1NGCGIEJk4oalaYFKXQkiCSYQ7/p6s0bSbzB67iwcSKyEcEFonIgmwOhop"
    "kNhhoU6yaIYM7hJoYiJggRoMAsEgqMVfj86CesIhIIMkiECAGl9/WXKvjl468xZErGVef4bV7n5r"
    "KlHJRU6QhD4GKopUhNDsLlV+e4YS6uhiLvTIgSKnGBUBkNY6PWY6EMQObu6LSOGauAobHdIAWNhj"
    "Czz4hFz4nnrItVDcwsXJQwpkxqLZjgjFJZSzGFyuMyhlymOIZomtpA5HUT80VIdgWYHEYgCHPqdf"
    "o58OpdYop7HGNFwG2kIBv0P8QHYd9nvPxlBa9RHMLMwZlYVkyyyKS2wJQ/v/pFFFOQdpICkJNi1I"
    "ioux2w93lUOy9wnMHWnF/sjs1JPVKAPW1Zl8MiwctVVGCDBAwQniNURZh7M9w1pyMEBA+Sfw8D2b"
    "E25NiG3009096hvvUU/O1F6HlpjjLsSxjbRVUgxgSSAwStlOEEskEO4VToWIHmIMGQnUgd7Tc94h"
    "aRIAdbHZ7QuNoRB/CJQRcWRG1eAIimo8NbWIIqZo4tUSJBpzz52chJomFlSwQ2U/px8nnxwPZA5Q"
    "pFUUYqjGLzRq1vfJE+HrxiZeHwIWIpR48xR6zq9YYzU0mXhks9dXxTT3mpityttIz2LgVQYl20ta"
    "CtSI1lq2JbW5nR7swndOKrZ3JrNkbPRQ5lLwmcHZ1QSTmuRD64IkxkYIb788OPTOfKnWo8+saNis"
    "ViqNtZS20rZsautLapLC2ltLa2UYcLJcCi3Yq1zLkzLgmAWMZKWdN+vXY4jxvR4UbLLOd5hUl5K2"
    "lQUEmh3eawVYm6GZm0SZQ47uO7q02vkEDVtaHTUwTJAGzVxLhhRvgdxyusYrmxEUQhJkMQ6UPbHE"
    "A5A3N/KhsZVH0a9DXehCSp/KU1A2qCSoXxe9XZ8OLgsoVXRYHIVZtwrYu8zeaQXCBh2IYcYdilbD"
    "Gri5IkIONh6nl0cUHqebl0HDYiclVGRUV5cuUIcIhPhDgwGSOQMAOW5A7oQ7qKdWSoRX6NYdh5On"
    "NC2KDP+yZDzbdTqakDfawAjSkQDn362OpbQYp5E26HaUEVqk+o04EA4PyBAOgEhuDyYqKGYaQGEI"
    "gSGrMRCzHLYVXTEL7jYXzI3J3wolSRykCBsgl4BCj/t+i5ZVXkPFEz5ZqH3l0dWBeV17UYWJfbht"
    "bapbdJyLVnTvv+Pe/HvZQp0w550lYkmuWk2+vFmPiK0ZnrldTblSUKMIBGmLIXPGPcRUJBE7UAsI"
    "0p2W+rOmE0gaj0OTxcoRfEoEY5aQaipziEVgkVS4NRCgPSGAEoKRD8YFhEzbUtCGTx4nKD8AIEFI"
    "p1wqKyN0B/zg8wQaRmk6Pc5SjFKLN9SaAg1KH+0e3P5/JSYOPfyxLKIEF231ENoSuFDnjdZBjunf"
    "HtDABQy2BUBJGRBmlBXNGRHduT0y1BCJPsWSzx061E/y6KTld+fifnCEINwkTeGYIqJYInxEQCwB"
    "5fXXdfbvJ4diAiKqYIaDIUTyjM1KCJJOdZs8/Kk7uGTowwmUr11iQMmNxxZQbwAw2jUGE0hw103s"
    "hdslVcSZ+LfQpNRg0siILKIiLCpU2lCw1qzhq4RcgvNoSwMUIU54q1kWGCSDB4hSUwEwWUfBls8c"
    "OjgSqIjDKxNIiGpz/zcZgc0Wa40J0tETm1BgyKFthvaoIgJxvISiSZEnQSFBUgjG2oajll+qHddQ"
    "4tIG8ZDnxDlsl22ruJyGaugLN9cjhN8pHADiJKCkjiFmdezLXKnss6bxDp01HH3goU3jqaPeRtX1"
    "TxkDKOzBqJIB0YKz1EviXzRVNM6pqt4Ttrbra26VMrTpJbmpIzHlyqYxYNSS9ZltUDDmBqKVBaNb"
    "sI6goyTTIDEwM1rVgYMSrJls3mtpAEoqUgsDyFwDU3EEgCKTA6gmpgdG81gRZhlhQU2kYFrBpA7E"
    "EgORIKxVtwhybMA+MsMGmE3RPpOFBsbLo187QZEGoIpBRIKOkEMxNaRChVq+yqbCIEAw897hyqpv"
    "WIDv0+AD6ILIgT75YHjYEAiFC78gCq5HBvAGIu/AOvK17zOiBQmvyk57WuCiBiALyQLu6e5EDYCD"
    "DXcFsDzsl7mjaYBHqKKEiEaIFB/XBOmB+8ngSxRRgwOlaKkcuuJyBvRRd4uGiMCRV5/ouPi4Scww"
    "ioIIxk6yhyk981lqBR4PicDtiQpIqxEIQmRKCGtMEvOSOsNIgQ+HQWOoW2QsQssgAxIEIRIkUTip"
    "gD2iG2manfBvEuhgrLYaysxEFggmtBkmiId02iBQudBiPlQEwmxZAyhs0NwshCuW5pmxAzSVycs3"
    "GLmnG5IKYDaGDIJASB8HjhuHFIpYfUJATZ5zRI90fUAJIIplipo7tY7hChZtpd98Xj617r197y+h"
    "XjSuaYSGUzLJNItKymTNptGjNq0o0tTaWkrZYbfLq3Ntvo/xyHu/8TJvFEThAERkBE3d5xqCHSQT"
    "BDxsMYQrLqgFSMEgJ8Z1hNx+7BbHMenbgaIg5hO0dgJl7yyEjAjoj64DGslhmAJ7SiqKphkIcp8W"
    "1CN+ny5L3m/LdJmYYWCqBJiXbluCoUuXNuTFFxzXCyLRqKUViCta8Ovj+T0Q/BH8J9fyfWkA8Z+M"
    "8PfUeUCdyqdqAWjLhSAiE7ykpUXX/i1YQT7ET+0kYiQkAIIudBDeI8r988XlqST0ELBRHV8aZ4HB"
    "27QPV0v7MXMh54gEIGMGQQSJTJwlg+w2aAdzyLfx3SdSvav1J5Xlmnp/EaHmDmAZBzENV64rMkQb"
    "PPBaMjkQo7LkIwmxSSHOo6Y+wqQJQiFa5KG1il8QL9vZpAk8i1taRAAEIwSgngEJg+D1dZ1gZsRH"
    "7DMGY4+kzA50Sk8SH0trk9EKaoKnxUweuH/mmeIFoMloFecHGG0n8QiwsalliQsKJLFIx4/Kdp9I"
    "hL23ffICX+xa3kG7tSbhTHILHdrp3LcD1kLkW+hGHCwPCDAh5DOgQQQETsaxVKitNTTaaFIrFs2a"
    "zUEgkBgsQiEAWDgNANK4KCpkhYRODBAftDCYgJ6aeLKAKpEgkF7cgoH5L0BXkoLEYGmMhLe8kSAJ"
    "BRZBkExMMo65ZVXYonsJnAnvL48BwQUeCFGaYl8QXDFt21rCUpogiB+79f5g/ayE4najOVRZOAcS"
    "ncREdwWwhP6KdAiqh8XcenXhPdLqXWLJMSptKIHO5k4LTbSXWxq4++46tHc4GCzjj25Uc4GNbS1S"
    "piN5xPjTIrAoY+hbLLjF5Pz9KiB1QAxRQOTQfckJFkkBS2UKs1TbSa1tC661ePzN8H2nJZze0EXL"
    "Itsf5FFSKKloqHxxRXyxAPQcQ4+VESbuX+GjOdHvWERLXebtkKLQ/ipSmwJJBkGRJBGfj1j8D9R+"
    "Qxx/EsYmY0W0ZxoWvCtrwt4W/hr+qyQc5IkhvpqAWVEimuuhl72gImo9iIn7jm+/wzqlFbUN+Pp/"
    "5XxmaqKMjJETqP/4u5IpwoSBjws04A=="
)

# ── Extract + compile ────────────────────────────────────────────────────
_BUILD = Path(__file__).resolve().parent.parent / "build" / "inline_k13"
_BUILD.mkdir(parents=True, exist_ok=True)
_CU = _BUILD / "flash_attention.cu"
if not _CU.exists():
    _CU.write_bytes(bz2.decompress(base64.b64decode(
        "".join(_CUDA_B64.replace("\n", "").split()))))

_ext = load(
    name="fp16_k13_sm86",
    sources=[str(_CU)],
    extra_cuda_cflags=['-std=c++20', '--use_fast_math', '--expt-relaxed-constexpr', '-gencode', 'arch=compute_86,code=sm_86', '-O3', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__'],
    extra_cflags=["-O3"],
    build_directory=str(_BUILD),
    verbose=False,
)

# ── Config ───────────────────────────────────────────────────────────────
def _find_best_cfg():
    cfgs = [c for c in get_kernel_configs("all") if c.dtype == DType.FP16][:40]
    B, N, H, D = 4, 2048, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v, o = torch.randn_like(q), torch.randn_like(q), torch.empty_like(q)
    best, best_ms = None, float("inf")
    for c in cfgs:
        try:
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            torch.cuda.synchronize()
            e0, e1 = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
            e0.record()
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            e1.record(); torch.cuda.synchronize()
            ms = e0.elapsed_time(e1) / 3
            if ms < best_ms: best_ms, best = ms, c
        except Exception: pass
    return best

_CFG = _find_best_cfg()

# ── Public API ───────────────────────────────────────────────────────────
def forward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """FP16 flash attention. q/k/v: (B, N, H, D) float16."""
    out = torch.empty_like(q)
    _ext.forward(_CFG, q.contiguous(), k.contiguous(), v.contiguous(), out, False)
    return out

# ── Self-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    torch.manual_seed(0)
    B, N, H, D = 8, 1024, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v = torch.randn_like(q), torch.randn_like(q)

    ref = F.scaled_dot_product_attention(
        q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)
    ).transpose(1,2)
    out = forward(q, k, v)
    err = (out - ref).abs().max().item()
    status = "OK" if err < 0.05 else "FAIL"
    print(f"K13 [Iterating Backwards]  max|out-ref|={err:.4e}  {status}")

    # Latency
    for _ in range(10): forward(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200): forward(q, k, v)
    torch.cuda.synchronize()
    ms = (time.perf_counter()-t0)/200*1e3

    for _ in range(10):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    ref_ms = (time.perf_counter()-t0)/200*1e3

    print(f"  latency: {ms:.3f} ms  SDPA: {ref_ms:.3f} ms  rel: {ref_ms/ms*100:.1f}%")
