#!/usr/bin/env python3
"""
FP16 Flash Attention K16: Static GMEM Stride  — RTX 3060 SM86
Auto-generated by gen_inline.py from kernels/src_16

Run (WSL):
  cd /mnt/d/GITHUB/Mini-Attention
  LD_LIBRARY_PATH=/root/fa_env/lib/python3.12/site-packages/torch/lib \
    /root/fa_env/bin/python kernels/flash_attn/cuda/inline/fp16_k16_sm86.py
"""

import base64, bz2, os, sys, time
from pathlib import Path

os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")

import torch
import torch.nn.functional as F
from torch.utils.cpp_extension import load

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "py"))
from flash_helpers.kernel_configs import (
    DType, FlashForwardKernelConfig, get_kernel_progression_configs,
)
from flash_helpers.kernel_configs import get_kernel_configs

# ── Embedded CUDA source (bzip2 + base64) ────────────────────────────────
_CUDA_B64 = (
    "QlpoOTFBWSZTWR0kTzEAL8z/gG///9///////+////////5gbF7x98+dnRj2ejzofM+6WvtT3bds"
    "3GWwqqIo9B0BcPdgHQ2+c6J7AyI9pSd8u57fL3yu96aD76Ggq87dKFnz5545vsAOHWgnZ16z7PfK"
    "ZysY47e4769e81uuW9e7XtdRfHade3HPtdvuw64CfJ9seXi6fT66Pt13LvG693O7O93mV745uz72"
    "N9vu29u4671aBOX08ctQVfRitNVWtawwWIn1yYLdPD3tWudrX3vj4T1Q7t1ht6Wbo93Oq7udt9cX"
    "TnrnvPt3vEzRu7iH2p9zwfeO7vvvfA++s4KW2UlTNm73j3e7mltOxbsu58HirpOg7udBUu9c169D"
    "oahozRMIzED2c4a97vebWoSmkEAmEATCDUxT1NqMmIZU0/RTxANTTNE0MjRoZAZDQYQSmgggmk0B"
    "GjU8oMUp/qaMKelP1TxT0QyPUNGjIGgAyaPUaNPSAYSaSIiEFJ6eVMN6qeKeE9TEj0mNQ8poaGQ2"
    "o9CMI9R6jQBggNMTBJ6qSJBMRqaJsjKemSaekyZGQ9JtQDJoGQA0AAAANAARJE0hNGmIJppojyp4"
    "ATKGR6nop6JtMhiGVHmUxGpsmkaaPUaZDyBEiQTIQmJhEYTU0ybSaU/0amVPU3omkNN6UxqHqPUa"
    "aNpBo9QADQzuqqo/wgACnn+8B/vEYf0oKhaBI1HSmaxYRiulxtM3wtcYjGKGb7iuUQTaMG7OS2zI"
    "k1xXE4uaTMl6nj7Pgvh/P+5114vH9b6Z/wHvj0cdLMpGEu9KxbcIELohNIWlynGYIaIb+jQ42u7a"
    "e4ma6UN6CoIq1JTpxZDHXGYREE6+P/Z/60ajzarKyRQaIhMkyQOhIIh0Kbfz/nw9Uv1H/2sU0frv"
    "Yt+v9dd3YGv8htwoJXU7uhIlGsDpCSRrKTwCInflusob084rxbr4vW5nRcXFeSy5ZvmW4Q1J+ZhV"
    "jrrkyDhRlp2Up96trDmJRx3lNIUyxVmUsqYsTPgAticTCY3N0tzTqNzhckxVSUVU3LuygIUQCUp4"
    "nZp0mrKIs0aYxKdM1rRi/c7KBiFGsWWlgjEFG0KapUMpmWYko4CwEYrZ744YxkrOq4jRV0rgI2Ad"
    "3NEMSulcdLomunOOLnNFy5zH/iux1yPIt5pUEglsWilznKFGBJCSEiGqL9B8g9AC6oC6CpITkz5+"
    "mdLvgQva3UBGY9dUkLozd2yUzttypR3bHdpqvB2OjzgjvuHQcmSYjEVJzEYUqExCCApxxCZJLqV0"
    "DQxQWdrj1CO2b3clpUKyijJOKmqOVMpVGdPB5PK1rWta1rWta1rWta1rWta1rWta2Na1rWtbbo6M"
    "kRGMFkSTebwXcfPBT+qzc4xkITlA/RigwYrocFkJzMJYxJGEHjHpg3HIkqkIZhrKLJJMMCEk+INa"
    "IcBFDTo+b/7cMQwaby5Rsm1lMzlBjOzIjIbKsIJ3odqE4YiGIMgnTEThIwicDUrhjRNBJA4JdzWH"
    "PNrniVRBOEHYn8Vam6YMi3yFjIuC3IpvXAc7G2KYC6uVtQFwUoEx91kA6aSEkhUt2rMl3fo74/r6"
    "emBTtR988bP+51wcjNOHDVKDeQSSQkJgSQgSEe7Z2Hki5C/biBIo3ZimqoklDUVe/z20kdASMUtC"
    "pIVMpY237/l8fgy/079ab+i2rV5LY+mDxgQiKzZXpc8+4vWcxquryc5qNXiXFSi4pGeE64/054s5"
    "wkOOZwLAxAddqTKZQ3+6mi0mRZqTQhy0VzcgVElH09VVat1a1W95tVXzoijIEiCrkXQoABUAGRU1"
    "gAeGNRZC0qMhGjO+aKbooTPQWRdZRSJpEKCQSRLirRFk4ErKsb9Af+++G+riob8cQZA3+v0IG4P4"
    "eWSRjgjT1gibeI4yIBhi7YhZCEQkIJHh59VXMIwi8emg7vPE6GfKpbLd547A4gGQjihweBym5DZI"
    "KtBza3X6ZxNzg58El9ffnNXqS+gIGJACmdqIHdgbOMUSu9PHJVFEDLO9jDj0FgtQJpeBFs7QGvZW"
    "uY048zsE6o6QGP9aboyIanLgs1RT6NA0hqYcSrxP5ZU4GLCpcJOUKQGEWC0Php+z2Vf1UVijYQLE"
    "30cdjJSGNVsPi679IdhoNJBnmSQlFsZHSSlDVMOyUI8xVipUCDJbOQjHy/iSW/sNSlj//8Phirnu"
    "IP4ZPyUSjkf8aqZCHKnh+6VDtbUNoXTJgyTahk2swCoPtwr0IBKWxD0y1wg085mjBeFLzFebXh7w"
    "wEsgwJfAsMNMD/2fc2urCBb1jTEunwH8rBQ+DArS5burk5/JPzCRbyE0N5Y8BR7nqc7wnH0/5d2W"
    "aTbN0vHziLT4+P2WdvMA9R6/E8s94BXz+cdI/ignBWMfdTUIQYIKQIqvuoQaNO//t9mR/03T9y+z"
    "l17+/oNPZPpMhanAPjlDpAG41dM9/82VXgQFOr4jriTkJ2Bz1PSr42a7x3vY8cKSQqA1nO/u2PtH"
    "or0vtNug29+htG2nERnhASKRkAAhDMwwgeEoBTTjmWHVtV+MO7hgAGnbHZuY1zVVdrXPHlnW4ADD"
    "2PfPZ17G39N844OCHIZcj1Thb+fpnTs+L8Dn5Yc5NPv9flc8CXh4NQzz9/zTZf/HVb+5JKYi22kq"
    "BCxsuubssog3mhZDP8ObzlyzvolvYYanPcAM36f8p/9frS/5pPTHNBVCXSqN4J2m9FMI6FqrcEjE"
    "SEI1jn1kPxtqsLbYarNPJcOJHHcGa8TZ5kFQOyVeUUQYPkPIy1XOh6/aNrTcm1fYkhie3TqJvy2v"
    "E2mcSVRN2jmUUz7Kdka0cWLJe7q21XQ25gW19kj4zHNBI47Ju0+Dm/82u7vEWDkm5TW3Zm2228Dd"
    "aDUQerNQGtDwqPoWk3iNdGh5KmN86iO4Q/x7bq2qFyqIxuMlWYNNMXadUNAfJp14VGnYGWF3/UD9"
    "9muKtn8iwzKBmoLC1jO8kPRXrjIN259IgIsksEw4Km7SbjjphL6ydjRng1PyVTSAPkJO2ZFyGghz"
    "Qm0IfvcsZCje7T7mGGcoZUu8XR8m3wo97yFviuXiUBcPV+2vDfWM/ZYvwGl+4YHYvWKjX7bSfgsf"
    "b+GryLMWJLWm05joP00T9Kr+r9u5zKzhHphwlBwrimwR+wJHthHN8We6N5DBATsGUxLswuqWfmbH"
    "3uYQle2/x43P1Pptaw1OYhqjBrJCtcdHzac+iadWsYDxXfAZjU8067LQEBoi7GRQLUXDiHrKqgfO"
    "1y9lmB8F8SJCe9yJSn75C7d1gqRx8jCXJAu/pit4iM6sPxXrc/HNdHEllOKNzR2lest0payWzIly"
    "a4V+RPV3hvE7ydvvgjpKudWtdr1AMtur8y2LItqQIBsNxJixUCZ2TIs7amDuQvHpTbl/IgyaOy3H"
    "ccq1qsat1enGOF3vpjIiglzyFKS3tbGMRMWuyTLUMVENEdiuoN9Z7bu6y92vwPWLaCtgYF1dB+MQ"
    "d/XG+HdZHdIWvjuGk0LcubOOu1iNDrvYvMOtLrgHxaul5rkbNkqgkSwxG7MZLxvBg67u1jwsdt56"
    "bahgSTSTfM8Z7e61hsmYMihc+oi0uE7EzLIRLuouoSERsQS3cHU6xTR1BkL15u7uxr5c4YW46Ekx"
    "lMnS3+z1aX2tvh3DVmggg0UyXDQ3pkFWBISEhILF7ax3YO1rFnS6Dg4LOW01IhaGCAcZlA8xOIZn"
    "AhGSugJDJpSUKaz4wauqKPJMCSSQkJJJFmkVvxRDbjkc638L7msxDdfjprQq4E2H4s9VfUeXpeHO"
    "kOE9iH122HH90Q021zQoSjlVfb5TCiI4jnjDGJewVWBEpQhw3BM+f2xDpyS1OD8iEH6i21bd3YEI"
    "ioRJPxRCMYYC5FMG2EhqIZmIfIj4V1qzqo5RjcOSckj5/axR3+skVjnxU0tXPZfsV5EzwjY9Hmzx"
    "ltMqtU7oN3HAfedjYZbM2Bi8L0LjIOSIl9vglHFqNx2FJTHe2duvdu3ZvCYOKx4yGg6PwmYhDd5D"
    "dd7eGfsnnjHXvASNzY260l8Jzr64ivv4YDnAlLGnDQeyrK/0SdLle02Vj+EHUPCJASIRcQ7igOQU"
    "NkGv1HermnI9MX1Ue8qEFUszITe5WwaOAZvggwgt4Tz218FwljFyCDMwaxx4DjiUXHZpdPSyZhMF"
    "tm/PvpqeqUIQXXe7eNeNANv52DJHPUwcrp8WZgzMzAVNswuh+3esq+A/E4tfaRJs0/O1kVFnFY2j"
    "9Oht3KTb4OU6jiQKG59t/TY1DQoDPtqA2LfIVx8WVRixixRckzVCG88Kufu89kmpNnIxePKt4jnZ"
    "pzYxU352u/wuYfPKZfTZrWvdWZqYJfQzMRGgmw0EDE5TkqpypoBTTrxl+G+JsYzQDwTwGa8HePdP"
    "QSuYJMPVId5GN12qU1Y77Pg1myo9pbzr1JTsvIvn0ZcNE89dvy68Mwdprhq8xlyonOa1WDZjO2dn"
    "xVG3uTGnQZI8aXp5JN5qqM9DUlRxaIXrdOQFplecP1eqBiMIEMK550P6ldfn7yJcxeOViElfIgGw"
    "MWMx5NeIPp8oNmzQeaxmVpGTyJCm+pdEN1EjpsiPUrnvvG3R+Y82qcNqIQoKkahUgQCoDUhEFtqI"
    "nqllpllO2XGaZSCRBRLqopkpS2lWpccMSmA1LcTyExss6yfWZjKgNTVtGhBajGhyT8+6HdKmkiQW"
    "jMkgPftj4mLY4EQmCaIywrythbY02rKWOzlXvzQsp4GzNVpDMrOW5hACEkuKt9H0IEHho3Z1l8C2"
    "453a6k8trWtGZqtLNLWHTlGnFvcxh37BzOwLw1QCSjvNU9kdC56n5GHv4bGWW5YsUpYrWjqdq9VF"
    "eoVdMTfOnfN506H3FZ9HueHhCcikcMJUEiUGc7ONBxATHBNhfi8XawNIB062pMLRJttDuAmmJwao"
    "F0knHyG7lvSmsrfXp4Xvo5nLZs+9crOZKBW9lHOvhDpfsfd9JbS6Sb1lEpOug0Sy8vdtaXlJPFc2"
    "Jx6eaOMlTOGxGxV1Y7+8aPxZQt1Z9WftSSSSSSSSSSSSWUXQ6mKzJ9hFNK+gHwTFaCZEvKTElts0"
    "a9VHa2LdhYFxhyGcapFMhGPCy9e5Zook5fnPNXDzjM1GChn1VVNPA1RbFpZcX0Ua8+FxfTMoTeEX"
    "0BiOXE2dql+2JiUji2emevhZA964HKkXiZIdO9agQdsCIGtASyWhIt0U6nNc4O/RYzyrY+RfKj62"
    "birOiTVMt287W4QdpYqI3PRXJZ8N0WnqTlM7J/Yh4HWXda+l++ih0FOuxNtRmw6+Xa3mP5tZpsY6"
    "MDz9wM2hW+z+IaigsYRjilhlmnHiEWQUF+GEApv6xO8Hrq1eN+ahvSWaOyW2i2sLOmAb0z17UbV0"
    "XundoKBjV1XVlu3brrKqxNZ1xDzr4iqpJKwxk2iGh6x1GPR00GsXpeL4zM9KRVaWo0e17ddu2vZp"
    "a+JxFrCjfXRJaIBIOw5ZNtnovbd9XtAQ+z2uORckhsp+0weAv0a95RJt4vh7OdR9OG6mV+SPvsXI"
    "2zcxI2FHsUhyC1z4+bu+jXM4JrVCH9z8V2leFJ2GDlDWY93f8RukSEZvjUKs7hTtLjX7YvqlCjYD"
    "tmvlvrFKApkNErKtbtuVnc6NKoOQZbmOTnlSCJ0wVJBRU1ugRM9fP4Ferc9GiOskhAisEkBkIASY"
    "JwNcBq+2iozY5OeuWI8oMup+tuxCCziEIHHc+Xs34aHy66VQY6kL68JgSJGkhl1d/A8uxnyPbZun"
    "t9teMQoJInzNMkZUQ4U2YN4BqwrX7O6/g4OJZZTo584S0X28IU64w2vhTIa6kOw917Yo4WW3Sp2P"
    "pp91ZyPWGkATiE27zEBjkhvBaqg9EU2x04o4rZlsqObdxZYgmqMkiPFUlUaS0VcVokxEUm2iTaja"
    "CPhqba6avjaveqyAzK3Sic3g8qAfyPgP5EPson5vnJ/dQFgOND0IRD95DbAm5CjMBeqKXLp/mAiF"
    "o3NmG3AxnAHsIBuh5qNUdyafS6XL28+Xq/hbZw+unwXq/jjDsYFij17qaKfr8KM830IrVWv1eFtK"
    "WF0PeivY9cpwjLiCZiZ6QuHTvCY4f18t/wvJIjFwdByd2PYw4dQFT00gfj7KBSBDT7aCyD6iHBog"
    "J04wgfCR9anwhwU18OfLGYprRgiDGjB/vsyu8A1LLDl4ZAP7gQPumEqjA/nQglE0iFOyHtuwgBC0"
    "KoMJ7SkLoQuB8pH6lQhBH3IBQH4SAv5SfzGVzUq4rSXzoSaNns25V9WqKZRRWSimlSqylew7TA9k"
    "AjJCBIjBXwQfHB8JDYIRFsbRsaFI0UVvk3yvu+fVq6bn0PfyfOOSH0JIQ8w6CtGRawC20kl+d0lk"
    "QQEDpQOftRLBJQwfTGqgE2Pj1jBxyCM3kX7vt5s3emO8ZSe6XVymoXESmSPTNbmTmP3cZkv1D/oI"
    "7D7JUOmUain74Wxaz8miEmQ/Lfbpp2cSxhPm8NRLOzpjt0vdUcthLTuoqXsnN0UOeWzXF44sOiKC"
    "ZmBhmYZbDRmULMPMIWkQRZ6QxITAUSJNM3Hc+5+Of1X6Lez0s53hVHMgi0uWStdEIketcXtgwRbX"
    "NmU5ghx98M5kl0S7QIw9RqmAuIDOkdQhpyJ+3uGDJBn+cv1q9C88uQISDHVw02oYGiHBYV1EnW4M"
    "NiWfZfkQQ1nZP5mt6R7X8Vz5mTj7AzcVjYDj5qyln3t9yqA34b3X2YQ4xaCrasu5bf4NtbodiF8z"
    "q16TIA3jRawfM9wP8sYOiQmANeL4rr+nXolcUir7fJJrQFn03kKUOalymb/JlIXt7+d0iwKzn0d8"
    "W0iYWlnAmJkGLjq9M1DIG4dZu5xCqLjIQgTM1KAQy1qRZyOfYWnKhqwtAhAh7UZy6MlfocY4TBph"
    "gmLCRHHOQiXFoNBtp3j7f5TzLMGoS29uvU29RWLc3HYTISCp5PHRGoWeSVBGvXOcik6dscIn3jp+"
    "yay2Onu6srcWDvCewoF0Hl6pU/KXQRHrRaeKD+ZB0drtSuAimT+PXIg16ZLf9Th0LRdPriYJjcgP"
    "CXad5WX7aDPvEzjXsCYbfpozflOzlqNrJseDVb9/mzaJD5KrHptx02cedUpQWw0yRB0IRBMP3IZ2"
    "vYKbIqf4oaNXj9q6LcsJb1Mzd+W2y3uRxRMI312NF67GwtC8vatbwGG01u2hbayIY3KGDu1D2pu7"
    "6oYSsLYfkNd8tWv8GquVWhWQ0Nizq3NqOOof0v1Q20aPbTibl9ddt8H97mRxk22uu8c4M02/e3ys"
    "hDq4+a3WezSvV7OvzxxcdYfHHh6zslo1BzEkh3CEE7Yp59qOdXY+HhsF/LIa0dVUO99wNFgXshnp"
    "gYspyoRdhAyygSTqsUXPnKKHIggg4GKkkk4ILN0xCYgBo3Jvu1trXY8+sdpoKhgrYYY5V6dpWaae"
    "Vb9L0oaebVcUSV+d6TTd/kmWCyY0KSddrpB16mtGycVGp795oHrBE80dI+fVS3045/b8adS2FKhv"
    "sQ7Lx8YXInr9TgbSL3pLJUgwZi4qnGPeQOw0ulFCd3d21QHLAnjeO2fK1qlRtDQd8g0m9O0HJ5F6"
    "LHB3dH6YsYFzclaCXp7XjdXFWJikWsxS7eNMVXlHsvroGodA6ny4+Cg5cWJOJktYuJeZWMPScgoR"
    "HcmevisC2eeiZZ2l3loEFnU9z8wp6HcpRDJOwJYYKmLDNcmlQON5UDhdU3Vx47fPeYjj8+Di1/ow"
    "ihIg/1TqDuBv1LdAMAQWBA0xSgglCEUIfloFPOHhwcX8fi+Iz/jBT94qvata8u3u7Vpte9xtWubr"
    "3AAAAAAC5Wdlq1yrn2K1Dywm/d/WuHqYJ7rfSt3v1AQa0VsWyoLZWyoLa2ovf5JfWwoGnzJ8pO1+"
    "eI6icJBMG2QcMO8H48bqqEi+fJvrhfD33D3wfDXc/CbN9uOzbx48bhy3Scb5dvrvlsD27bvc2ZtZ"
    "ve/XTlN5tox30FkpU2IW7nu0fGtVZYHiHIapgsMWGnncAqTMYiJDRNIgqTA4dB+wrPMdNzDDFNhr"
    "9dlqSSQI96DPmMGJGQ4MIQA4NrEBIhyV2pqrlV1vTuKZRSGKKKF7N4b1/Fc3JZ274ooooopIEkfk"
    "uM7NyMg5A59iISUF+nXGTu3uN5+RcAHUAYAMAGKo97HU32aORRTcxjGMYxjGMYxjPJbVubjFGKMY"
    "xjFGKMRo8vqc3SjRRoooo/G9Xm6UaKNFGxFeK+Z5vMAAAAAAAAAAAAAAAGquxEREREQEBAQtqhER"
    "EREREREREBARERAQEIEcqtyqloiJbVLURYiI1WZW5z4czFWhKEevOnC0xOe4c3jg55GKVBoszERP"
    "gs5BoioQDimvIuCoKVNjnNtai3P0zGLvJJz4DjdjR+D6unr0X6NBUVo6tJgldvK4GLbJoFW9DvBN"
    "BtUCDEYpw/trv4ezJraCkuOSaLWX9xYwXg1RWZUPr1Fe+il7fYuUchTV9ict7A3Yw0uzbfllpNNd"
    "c+XhQd5rymPfHAlPK4t49EDb0JJJJJJJJkkJJIACE5OAAAAAkkkkk4DMZn7UKpjLK0gzboXFT7JG"
    "w0HOyEKFmM2o8Ym72FNpOmpyBbxbaRkNtbA0Fp1QbaT9sh5yIHQTIYgcQb2dGAZyoYsJuDu4R3Yl"
    "sUOdTTLSg47Zq3wLbjZjTy522Z2qujsyccyclasWjvIFIul66KCtzkRlqys6T3rSoYLxIsYhqHY1"
    "tABjXr/PrxeAAAEAAAXa2rXVtWuugAAKAAaSG2FBOZQeQOhx83ffqkyqmPy/C0FWaEsJbYEFFOba"
    "PLJnHeGPkSW4EFUQtz8OEa/Du2RLlxNRJg9AMfbGwH/OmaldVc0KHuKvqF0Uxrun1w054xlhr8nx"
    "+Urw3jj4xrv0p4z7J9vpxZup9tXup0zrNkf6R88SaJqLCdXpsw40zPcfK+62Pf2xlHPUbPmDcbOz"
    "0n8iF/dqwHdK291uWN+NJozTqy3MrMvX0w+PPOmuHiE17UChgxMSx3cyLdHZRmo6hHzQos795vrP"
    "h8iUIyvyt32ZdnPt+n6Jze15vpV7hQZLhoWJxci8sK4riTqb6O9laMO54EQO8nLfl8u0arOb3vWT"
    "+wwrLw7G6m29/6ePdVV01VrO8uyMvFKCCb8fiyxqA7+KkcdXuauXLa9Z55dRp0pdDRg8HFmZOo2s"
    "GA0nvHInoKeG5m38CJXhJqbblpMjJpZaNuXLph6IuXpl2dZjcEhDOwVRyIFoWUEO7+T2x8YSlkAU"
    "kSKKq2SUkpLY2zNlS1KSJpmtjbUYtYsG353NV1GLH+wf5ERMmyyD6ooSCwhISIrQO3Ny/rmu/XDd"
    "mrlxcyuNXG2aRG41wEmuAv6Ox2unbnJpzrnSQIcAd0mTQdxJnQ4j8J2Vgbjjm4/L1NLv7eHd5tPX"
    "r2GmuE92/c8qSHSRpG8yO/0xEQAD7jej/iEBDSYgmZ+YIUit4gqSu5LIDefOx+hsJPIKpt8uvCfa"
    "NxS67Fj3S/98fbTfKH32K2OctEZESwQ0ZuhZGLDODGQgCpXCasruCwZmqqP9oVzoYUYIUqokQ8Hc"
    "2XbqP0fh8d2t9b6mO9eWU7eNHUtfo/lgAHVVc4AAcqrnAADlVc4AAAABblrV2vX7+Ha8fSAmCkbk"
    "QJMpM4XPcb2mTDYEtoyNSALUGGx8kwfMyELoF5RgpcIOXmENo8qPJOAhRdyDoEJlAgRTNebzebxE"
    "Z7B6wQ0RNeYA4gGxmUKiUgDoUIPDbbv6MlU0ND2aboAL97t6TR4cJCueLP1kPx8P7J9y/RBYok9R"
    "JAkT+cQ9AovFPM+IByUN+28hc1EnN8PhHsMdy/SjzAHvo5dzmK9jG3CoTZs0dCHtVOwgbi4vMhHT"
    "f2SlCQrBB+MQAN5YDgmL2ZsxB1TuTzsFm8BLY1K2ftccswwxT5LDAw3EVR5ZiInAz4WFs0PtTQC7"
    "HX57sPIAkIICFGxFVQ5AWJUU6YmRZDeg0/VaFkBCMQg4JSqicOuz3HdW0HNWQFrkyDmMjST055n0"
    "Ce99IUIQJ0Fr1O5UUxh3J8h719v2szMzp321/guHfb6RuqLSlCGs27J/VOiJ3IYT8CIlHxBGE+G1"
    "wLBYFWfY+NxQ2eU2DIQdruj6Pkd3d3gMePS50Ag+2BDjLUuShCAQiXaIgRB+E2hvEIILCGNxAYIH"
    "ZhEuz4AWUQALGAiePHjXE0Njwij5huI0I+QgsgcsgpNyMMw0Zxy+RidXP9NimSKJYaq9O+RsbbN8"
    "jWnywSQJBJBNOAyrQw01kKTKkOJisYhiZZb88cIhpIVVOtKVFkH8sGiOmwcMaSHPEG1gvY7gBgMn"
    "JAe9dnY8aZFAfdcjUVgzMwCDFB9xA2KEJYRPp9VszjddUu/Pr+b9rTitWDiHGNU3uoe2vuj+/hOe"
    "OXYygLpcJR+KcjLkxcnnrhJYKzoTEbn3q67acTVZGoprErstZAk+GBT7XZ9i3LNhE01SZz0QM4+7"
    "FNpjrmmDEfxWJWyPNNumbWr+qbePwaG87PmXYGY7kGkntma7frP35SwvoLOCT8Juanioa3eGahmK"
    "EHTtKEuHdB/Hq1ky8GGKuVUaqSNhrNUTM0vmwjBl1t9l3MoTqkHBXuh0UOyp2wSa1AYdmMChKHoY"
    "O0k08PjtM4ZMTIid310Pkm+7z7ejJP3ojdxh7l30TFISboqW6Zkht+Tw7med0i3rf1ImvI5UJjTG"
    "EAfm4W3uHKV5B+DwTB11O2YQxSg7hDEnbtA1x3J11zLDaHRyyROPtm/uw/TNbw6eXWWOwgnmqhNv"
    "cOs13N+619KHEh93GcHngiQw6AE1NL+HK6DUfMUwgpzKFSPkLi77sYlfuXoetfUCkCEFCIxhEe1o"
    "eBkLgftyFqAMgyIREeNU6ZBmfg5ZG1oianfuHZpTtx1NZGZgkgFZF4mqXHQiJfMLh3yDUc5W+cSk"
    "mVEIGTYVFYHp85peXRmpa+z1kKELz+bnMYMQrba0xJvTCPQcTAsgEYNi4iBTBTQCRO5MA44xZv12"
    "5iAfWwFj1kKKJJGkaQhVKJUlv9nNNTRP2ubc3blXGsWLWdcOUtRqjWKktuStxrs3JVb7Tcm9dTtX"
    "NNZZKu02uy1M1ozAFwIECCoEGgEDIIswB6viAI95MV07dgbzk8WvN05ULp7lF88dzEls/LiUHueR"
    "Clx7r7kV1OFb/B5vU9pM8F1K1q5dsKfDzd00kkqS7fsEJQcdAwztk2j0no9MDwv4U/S0qZEWTCHp"
    "U/jqeh5J89GfeUKe+3sl3ST4PDuKMNblHDeUHVuFEnQJyY7NsSEjTFuyeia2YEIJiA7wBWY5oXy9"
    "/caoa3Xntzjsw86fpsGkQD/qXKP17Du9rnLRJCItGafhJM5fTPMJYR7xQkAIiPf9aImqYREv8EV7"
    "vjTptXzWvRJD1/sL/T/00f4ZnYhp+E0fOIWPhyD+wT0JeA/c7CgsQ98RGIYKFdv4djez62xa9cpD"
    "Lv+QkhJJLAe6kv5wpP3c/4rHSR9p1t7ej4yc0g+TtJN1RXVbCnu1AwQBisSQkUsjEBj4hgY/dPsR"
    "GXJQIPu8ro++7Okmsg8ZQkUGFd6jjtNWt04TjLrjeaiaQ5dPfEzV75l3qoPgot8ZXkDb4fNEiWVL"
    "7IdohuT8qHlEDJ78LJAKT7r8Tx5aW0zyIpiF86tEA9dkCdCu4DhbWIIQIae7WevI4hmZW18dFQ5y"
    "EIhvJpooIRqqd0/8/BSvX04LJ8USQ3ovvqSkldufE4Jk5rWuoBji2yVrbSg21tkpbVtNQNSCJOeP"
    "bub5b5vs//xN4iPWoZc0DzR6sn9I29K8RNRZ+ZOHxfikfDlU4QgRjGB3YP1QPj/oefXT2CBx0Hlm"
    "UD+Z931pQD3VNDweDT8YicBR78V6EjT+MR9+JixpSPCgjmUqBLKgajuk6f5eSeHxHeXfmA1Q+kBI"
    "uPomoAUFRBKAgyQjCK/YB8jc39/YCHHzpzopy1eHqU+hN+DLzuP3OAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAc975fpwAAAAAAAAAAAAAAANAAAAAAAAAEkkki2TbD50PfkREiiJR7yHoDmOTkgr4iJjXB3h"
    "APEFpRs+KksG+X8nhDLnSBMSMCICkJB9zFmc/mQaI9otEXTodCSaHEChQnT/Yw7N5I+1G6SSSuhY"
    "fH8S+vSYmFrcI949R0HaMt5uOsB/rTxjSvkRcCT0CI3Tp4Xs8uoNWE/oWdLxjkL8T5Q8MJCSDxJy"
    "snFwABVUL74j6X1DyBJ4J+zSMOgWFHyUlBTH7KtnQMXij5PirtDUMqyQ44kyZH4BsB5YM6j+stVo"
    "Rl+IZAgobLbFhN1YJrRlocUDGRm268HBYkPAERXOJ34BzICB5TuIvkZfYsHy+0d995nHoFYRSnsT"
    "M+T6SjcdFrE7SjsOvSQh5cGmcHRLkfqbRH0lh+OdBPsJ6sXKJF3CIlKWD15Yshis0+MYNK5Hkw4E"
    "MxC46ISEhQDnDI5gtc0AORkXiPPW83u+jve+EabAjSVNSmlLbeBllKynKyEQWgKCPJvau/PPvNcr"
    "iQvo/w81uUTCBUKm8gZdG430m8V3dtUCKwgH9XRp0wpNug2TAhDfN2e5K8PHvlU2lVYXwucL0pqL"
    "ZyrSFjMarF5gqSMll6es8L0CsBE5MldA8hkh6uDYQPHHeQ/uh1/Ypek0aC2fxUmZHWCdKZ0KZGQU"
    "qSrZAsK1rVASFWpUajCDJCPdQh5r0EOQ5Zboot4UUo6FX0KgewKM4JvrXGQkPXyiU799HdlQcsH/"
    "JJ6j3e31oImZDN/ZkOLRFDjwGcgrocJLsUYm+tuZo0TbjQLoymWGSx9UExlsjIEmMSEZ5hpCUyPe"
    "WeGFdhGyBLcBC7HoUw5v1u05GT4n73wqgYvl/t6gLt/Zl3hD0j6FYLhOMfImsD6rBKH0nbHMUsDB"
    "Q7BXCaAwJkNcEDmlQ+C6DvX74QWEU/AdWJPZANMkfCSSSSSSCUQkuUQkPu+ijuz5Xd3d3d3bwoiI"
    "iIiIjw6fCzuk0AQYw9VRAexk2RJz9yDRQupn+0zJpJopYOO6dKr1i+NZyJ6h++MpaFmy+WIiIiI1"
    "GkJl4GUfLMRERERs057/eyUcw8vIZ7qdSGnBch00LYveiFJqsEGKUEShgpcqpTKfOyQuzxBoE/Li"
    "Q1kh1wwmgV/SzpgyAXEhKuk9O4d6aI0EwUPLoVAtxz1hhn32SJ2Nn2aiSjBn10dRDyS5Cuh/oQ2l"
    "GcVGilmgKI/n9rP5PX5JQiWucntjTUDgKP37LGIlZXr1zr2bA79BxkjvDk1LPe8BTJ+76+TnU8F7"
    "c7t07Xg7bJjDl2Xm11Tk3rLKDRNNTbYBq+LoYeEdkIIw4pbfR4o/j1dhe4jj7tDUW3mj2a5wyPfd"
    "JAyPHVBAjXvMgtskaMJkEAxiEhoMOAc++/KSEXJES2m0tXizN0Z8f2suUu64toSYIyYxQaoEQ5nA"
    "4OyLgkm0ZGY8UPAEnhLphMv1f+cZxLdmHLzlJmmvb2jqbN0pSBc1kNclFMpnGoVVR5B5fuxg9+Wh"
    "gf7+SYyaQ9hE1GbQ1IQIPz/aQhIOxYen7O0NO9ykZ9Cfjc5i2DZDNL5jkuULifie7+DU/mSyoGQb"
    "DMjGM/GXXxH9igDtJQkBDV+66ph2Teg2GipdGB/on7/e5ZFezB3hhA+KWhMp9/vl2JqRV7membUt"
    "t1A2Q/SQMEJEiEYxjbCaVBqIy0sMAl2d/eGDqex3+glyfKyFAzYSsKOQx949rhwGZvSdx8wflPbn"
    "UyMYRhWfbRxg8BWKsvdKL4/N+5h017tZ7YJ+f6MBsNKzZ3wORGGb2II9+yL3tHCMJ013SagZaHFA"
    "xkdoCw0b01pZPE2CleERDePB2koX52OSP1hARh9PnaBmDp2/geRFD8mPxodiKZ0kI9jsfq/R/R+b"
    "9f7+N+n7/2Pr/n9v7/3bvIyYP7+cEAL1IcEx+cj6maSEhIkFTISGQhA+BDND/RDCj+5/kvV2qX9d"
    "L7pD17B5L+UcP8XgEGEJ5FWb0emIVxnTWVPZH/Aw9Gx0H5T6wwTGlo/q+caMiEDKBDM0LuDB52rz"
    "2lUq+3imUUUUUUfazcYxjGMZ1tW5uMUYoxRjFGijRRoo8m71XlZyMOCgqBF4U/QH2j8YcZ7EIhEI"
    "hz+YuWD9gtGa/eVA0BYyIIj+oD4jPn43SSIb8L+pPucGAydj3h6wld6CbbFn2p/GPst3mpwEfKA1"
    "omKgbPFhwZXB6PsVJPkbitj5zDY4SiQyDLfQSqDHyBwmbqFeEOQwl06oaQ1WCobuM3G4/cdSH/NC"
    "x7kf3T5IlZfkwF2xEPiIDwH8r/kP9Z/aX2J4fPH+a0LbRRVVcPj2Tt2uAkhI5xyLnOcEhsyBDoBO"
    "b8Ae40nph3kE7x+YkF/eDq4ISSST5R+VDQ+l4fOe373rqqM7BVHibCHIJ3/qk+emSQkKLohdDzD9"
    "wgPzkVMlyHYcyEVGRh6/aAWTsPL1KWUahLBlpYE8wM+YEBhmyWvkdAtqGPEfkkdho3oIlggO8A3P"
    "b1tBreMeEQv3HM6CakLsDUd50m0s+Q5CiajsZhGEGRhOtD6XU5djLbu6sZ56UmmmrlqyFwzKizU8"
    "P6gKKL+0eU5KHWZbIhjtkJhvdM01XEGPGEAbAdRwQ6eIhzdQVOgoKOEepnW7naGDHZJJJAAAAdb1"
    "q8k0rzK39XuWvb8/fKGYmkIrxNjnAxvIO9xeQ2Vk6EOfo2VVJba2ja0bbRo1aW5Pih1h8Y6yaPBr"
    "qxcJNwrLGMjAUuQ+oPN8I/nCqGB3jkdyh6E8EdwPK7jnoQgj4wNBzHlAdAglRfP6UzILqdxtJDNw"
    "nUHn27aqp8AobhyGvJvj+x7PVOdTnOcuAABTPXvVvYvPwqmgopHotaLlEDpY4fO0bSQA7pIQi84Q"
    "O7eSQgSbWnRJDQHKKdIh3Sxom1neCAbodbHg3tNS4Y8XbJKSTjIRCBxBecA6th5crIJvDogMkNAC"
    "cKj8KjkmHdgPwmhfv62c1G4vzUi3eeuynai0vVpgLIKolTLQ0BzyC3UGl4r1BYwOhXYPg9xD6jxw"
    "UL2of29A+bZjcs3sxfOLAzZ6s1jGM+9cuXLTagF6xkWs+ta51jXa7NfSsYxM4vCOQ28B+aTV0Xhi"
    "XcBx0PYjlDevWSOfLJJs5QbsmIuUz2IUjNugoRz55zirNm94OrUsLcSEhISNb3mRXBOJETEVQ8OE"
    "vFJ0CEJCRELTbSZQtsvEaHOSdcy++b9WuNe05ArBCDQNB+iMXw343xzErsodbbLYRXrj1AWfA5BE"
    "fiHAZdND3aXYlQomDGijbAaUP3OEkkkkAwu/a9XfErmu/cAACAAAIAAA92urwvbrx7WuDgiHeB6z"
    "i6DGB0RyIpCc/ACiy1i6BK3btsBwccGTuA3WTYYmWCCp93cUOBlZjG5iwOVia+xfvWgdI7gGDuV4"
    "euMTwDvCw8qB8RADoiFsqg560mDG2VEZMw9JAh26CiEhPku6GCEWCYVg0UhICkDS2TtjNT2SIJGE"
    "AgeqpKEYQ/5U0qQMkQ4ognvHNGMgc/hw7+1WvC29yIlJa0lrKtUstTZZqWUp16lq63VqUMsoZsUg"
    "QhE0cpl0KuSKkUQNqH9vaCRCz2D84MAy+g8p+tPzx/bgYJMUJzKSA+qKnGcoJ0ZjvNx+YOI4UsGm"
    "GqGEsRo5gEHUUA7B5CqdpFBJAgRISRgxkUCCkUDroczUiCa8zxFDXQA9PZ5YGOkNh1QRDY++57eB"
    "kh0yzbujIqik1OETJDgNelIm4aIL4kQH04TKeLzXu7R3yTWioyEyx2OBvDQyw729fjkQgvUqqHJs"
    "F97TPbCIZBqQT28jkAQ5qLu6kRObaF2fTjy2UZL0noTECkqmhiID6OWLQO2I8ZuGHGAJul6ON7pZ"
    "7Tl1BzoABQBeiMYI8gk+9GQu7wywDcOAwC+3BTaDz7xcw2c5wDt3LIRZ/Po/hcau0fcuXLyXyCFE"
    "LTpnQgTbxgobSAu5G3dIAfGtpCEkEiJIrACRBKcD1m30cB19qL3KWX79TREjyMmgiRmlPhEA9UwZ"
    "DQ5HAaZGO0T8I2NH6YFEdgxyVD8uMptCpVJpEt5l3gmAgXJBlNFxPCFohIDj+dkhAfsBAK6KD/WJ"
    "eMSf5omcRICH3lS07AgFqUQSEhAry1aSQkD5YwJlsg4wwpbAzGyBS5CEKMEXCFrXq5nTtRXfRRDJ"
    "NBDR4CiXVpcbCkFtA8Fw2lMKS1227T8xquPQedUpLDI+RIBFghIgVsYwcwOMe3Hf4PsJ7wkIgQkI"
    "DCIqdHVSIcolEAkgy0aCBELbWwJjgYzhN8Pm1hs/yyoyRwX/1ae7SvSc3ifLVA1zAVIOQlwKeMKk"
    "HLkdgkgQICLjjMhuKYUDiXix5piGD+iUQkSR9MqHPvLbSmEEkiFIYWsQQYffQ6MxQ0bMQMKNEjGQ"
    "GKUwYEAl0soV+abYMr/eCcbcJYCBEDLmnXaj66n1/j/LjEFwFJ9VhLW/PRZT9vyzS370G7q4ENCv"
    "4dAecRS/4mhhFkQokJW2UTikxEEWsrM33ZtgfFedGhY2wCTFDAokjId1UzM1kxJfWQev0tYmkKoK"
    "a0mTdizt9x7qBz6nwgherrozma4ZIMizKYpo8IWoMtHiZqPRqOFvwjVtlUXG9NIQ+9uQQ8/Yggaz"
    "I5ySD7ZB3FzeBuZyL9glsvH+0ukIeLIKCQgxyoJJARVRlIk5kxA4I1zwDmSzdlKE41rNTGOUWUpc"
    "RG5bDIiEwy4kLS0yYm8AwE1NU3wTjADGJs2AyJii2VXZSjjQaUZIQpgJSgRkSBq2QwlAxk8zgeA9"
    "dHcJSo5NbRSJUkkDNClMICBYpWZoAUAAUwAwxRp06eciPmgHS333lVWSEp7aqpWobiqcADYIDaEQ"
    "IJAWgoIPR4gDc8xo/GblVxZ2lkTAcPseChSnBAIoHNCoqMgqJmpmSLF6ZIdsO7RugaXZ7m3iyOsE"
    "JkBgQ1jYMmP8IcIyGFTINBRcO8TQ9tr2ZNR6k96BCBZOecAOYhn2hwU0iFkF8Ipp7DhsqOinoy6M"
    "q49Ukonw1YWyBVTqOdSGih+wQg1z/IfTPZ1hHlz7bWtP3hZzFnaGKaHZQfnTTl5l/MlCQIgafbfy"
    "N68JohVcSRJIIRSCQFYcDDZRsaasWhywO7c1rVl3TGaRcjMLmSluYNL3BfkGjl3pdhdjODYami0q"
    "cJrY4IFpBJA5EEGVQQGQiNEqOAiWXUitwAqCXKgNZ77xz45jmpRmM6Sv2SxtfGzkL8+gWNbuWWio"
    "rOl5fN1ZXGcS5MALir7iliAq+lB+9nTZaWl+TKbyYTHGnOOeidgvvWMtWhVtMj1pT0jUW1XjkpwC"
    "cY5iSYhjXV1BnfE4q2ycT7tw8sc340vq+5lMkxAnNcpEQHoaZ0tH9bfnw2eTAc8MadN5yck6fkoW"
    "JZA6YlJJgpPJWjrQBNo6W5tROjZzoviuDMVKV1ZdWWR6iLoYyTe6i8bxkTLJMVUNKYsaIZBMQcyG"
    "GkM5c5QlTTA3Gy8bkwmqc2GqwUJLDVAChRBJSQJTQaxUswFYze+O2XbdduvDv3eF1QAAAAAwAgAA"
    "AAEAR1u1uubs8HZc63bujVq14c4AAAAAAUAAAJJJISEkkkPMXhr3/fW9Xi3qY2bWDgboatIYL0u0"
    "Hl91J+w7f4Nznw5iXoGwQTqgjk2VcrZVLSprLaWqVKalLRXGFzOJXKrHOsSN66N8ms8UZsmTIslT"
    "cW45y40maRUyni5a6s6d7IeGZCiCWiUleE6ikJEcgoAMEykkNvKuSS3JrqXSCNXlu+xiAWKBNmFJ"
    "A1RVdmRMMMlpRCiUSpn6YqcgTcIHBMNmQlZsCJRFNlyHIjC0B4MUMLwtCEEJJLXlppXOc01txJtF"
    "qNip4buOomz15hqGi8UTj3gbV1n64SQiyDCjEMAMVBllYUoWBZJSkSCRCcRCFRGQkZ9Cgnq0PV3f"
    "RZRoOpdPWqbxsmsYgMxh+I/gFHEf7krNazzeI47uxVKDkh0CUej/Pedta8fHGM0mwoRmdXQhDGXU"
    "wQzpgUkA13Y5kYYuYxKtLhgyZhwAYB0oFgzAdnzdGg1O7r6tweBxSoZFIYNVDNzSDzF0FFoXfY7Z"
    "A7iGQHnsqb89mqH44Gtcltc1NaWlTUU2VUWUCBpTSaTTCrKWmaSICKZtiNRoyksCTVGKNZas1qrk"
    "rWuvcm5ZGNumIkIAYAE6s06YdPb5btsFZPfmudCiD7fMHHy3DccWgNzqQ1hIsGBABgh02r10VC6U"
    "o6hoCUpRhwLunegztBhwKD3EN+eQcuOU6lDSS3Yia9BzkC0WFUdvYl5YlefJMGQTqjlyEJRrUKCI"
    "m9QTmLEJcRuRiv0ZlFDaw4EuDoGKkeAijJJmsAwXCs9+DC8Z+ckIBARIKJERAihyJZB6iKprDciE"
    "YE1dt3mVtsk6VSGum8e7KhfG+jO+MaLFpP6RBXXtBl9ZrFWB4dsJJI5MnTJJkziSt00XSZuSNbV5"
    "nHibrtyLPFebOgLVSCZN9qAYb4CoHM0GtE+SIz95zwscIMBsIMeH8m21Fm+BzDwNQUZAzJhCgiHe"
    "bbVB+sEiui2SJ3CEDEO8/B8F8bbar4+n4nrXt3lr0/JAAAAAAAAAAGAACUkkkkkkkkkkkkkiTEkk"
    "kR8r1r2v07em6RH5MDfKUewiZBIqEhO9YDRJ7sXl84H+YG4RXKBwFYQs4XVA1dIeiSDTQc6fFnmS"
    "YKaxL3T8x0B7EwAyOAOMMxIwNFp9fWoj0Cg3CvVyqr4R+kIqwFI5OXBzqqpDmJ3vb2IhZy7VRWe0"
    "EUTL1yIiU+KY/0RUIOAB93ZWRGHQJfsUGpBGEKUL20nynyJJiVJApZBqsEbMZCBonUeo8g49mTRE"
    "RPz1rOUHCLIgESAsIgF0DQcwq8S9X9Z0oCYQwPBgOFCloiKQbbYkrfIcWk1LeT0W5XXWcc45AooK"
    "FOqohKXKGmwhGkEyWQRGMFCxBKyDMuKFIVwKuodn4vj4TJFTr5HMk1ppHPu316bCQShDTdd8nIFB"
    "3KtIklaUkCgh/3n2Uy2+AGA3APfltm6/ZgJETma+U4QKgGQGQFTCD2wRE4dqPtlMmSA2uXKk0FE5"
    "FyaJsaor5vUvYxVzLktyq6506sthSerIUpQBtEFLq0OpC/hoHIPtMVNM0lm1tRrGBWWqgMhKGiWQ"
    "5ISEhJjMftwbIEX2QSTaNFKWaWteP0XZbGtFU+w8UB+Cg0zgQt0DBiKbST9tFwoN3EmuRamSQjCM"
    "SMHQINysqBUqOuZRY0H5yK27jek9MDt8wYGjmhdFCoAye7ANJyUKJaIrm+xU9AZ3QLhd6gOUvJKS"
    "XBi5ttcuUyYRuV215YrldpqwU6s6QFazDvR5FB0n5DfR65bvt/liyIkgsRi7jxvZ5oNP5GmgI2PN"
    "5yrSBe5TGZ4wuhMVFVkRcZx9kw0btYe31Dpa7S7kVSHRuO0nJBMt5EAGqTsih3co2ivHy5u61tzZ"
    "G1JGpmyqy2t8xtuKrGUttEyNqospmMtNbIyW1fSs9rbvXfqH3x2Hotoi3vOBsgVtQNlqOs1Gsezc"
    "gGXoiffgpmIG7CbEZVV6j25D25EAAkEHh+qj3ryqkiHaikrTDcSQRL8B+2aifceZs+PTTsQh2lqg"
    "3ROlJ6YDsIMjRCgitAwKqCkOgj6YU9D0c1qcJRDilA/VLCkZjaynpwSoIMEEEeEs6W5S8Mylxv99"
    "3EgoZZQ6EMgvhF0JKLLCiq15OQ42Ke51zNbymJxKUEYJKh3OIYOKiUPlp3W3CAE6kH2liAFodIh4"
    "mp56BTvIiwkiPyflo5aifhbEDWc/HVd7e+QphKyKLLXqcLxp/kwKNsIHtilWAk/TGiKeP3Q73Yb/"
    "EPGgWPo0+OSHYxlRNA5cuvGMJimqp19BkJhgB6QIRBjePcXsPfsD+qwtdXCUzvClM5lXVABvZ775"
    "95rDK4mVbxrpkhZmsmiSSRJGI5bIFK8xAA5PonJU/DlDh6N86aLZqmN1YTQmM7Pds0cXSj5Zqgcp"
    "mWKGiJ9YZ1eXgdIgkIopFG5gKEKYJHUeuZyDl4KaPHERK4aUqJDdwagZFuzf0bl4IjUolEajAhrI"
    "3CEl26wLEgpjIXGi6rSmFFzsCTWApCJreYnp33TZo7pZZkTOKaS5KHBcNCQwfJsUWCJllb4RxoRE"
    "TFoUQYoIGnzEZoF4DkZ2sYWhKEoI7h4h8OYZ94kIkgwZzQk5Kk/XpNAnuEVIqKREHqDYATp58wCg"
    "pHd5QST/krOJIWAFUbqZnbMsvbR5S3rdsKer+DgvOG8Rl0jUou7R37qyISuiiz0wF0jowGSBEIaA"
    "bGKYwwWGSypMGzUIUAlNrImuW3K1dbtdtdSmpa0UIGkQ2lFryoEKgIlBIvPVQgDr44uglqBqRQU0"
    "Oi6RM9god4/uxIOukz8y3wd+MpjFU1AiQkJE4SginQhmHkIelETcfGI3BXtKIB+YKrF4DA3IQaYM"
    "ZB7Qh0QICiQAN3OiZdO1pLgngiLISKRWKDocCHkEMtDLuZ2kIBva30INRSFSQglKNG9IqRQB3p0I"
    "LSIBfw8+iZySzAkYdtJibY1ZBDilEICfoiIAQySh2D5wBSUJoC4vG0KPXNdafAlZa5Xi53YysIaU"
    "USMZEYhiiGkeiqoke6Gb3jd/zRlCbA6TluB9p2GZRmhmTclB89UQOcQQHHxbkKDmYBTPoxaBYxS7"
    "zmWFUygkBWCgJhhMi/agGCy4oEMjjoL4Q3YBMaImQaUZjHkOwoJkxHnUS0IyxKKhStEoghDdDbeq"
    "m3anICKSI7IAVECohJGwpbXqfEfZ9F01025M3OMyZiVwTnNzNyXOacScrlKZl1W179FS2Uo1BkqQ"
    "mmKZmLQkabNUWNS1c7LASRh2Wuak0aLiiVznBFjaBSlKkWSlKCoto0AlIAR4B60Jq5C+beUIrvug"
    "Ga+NFc9w7u7FAbgm42cSdMzuFEDVQfq8ad+IActOIDDcQ2QqkE+FYAJoOjUQMdXIJAIXO8HMnAGB"
    "Xj0Jrnxx/m5ZaTgN4yN6lrRYo1V4d9Lm+hzt05KconblzTM8LTVl1GpqhSGVsYwzK4WGsItYTp8M"
    "HMTMzDQVJn004rMAUOPcJWjvhMzBLxPqCBCIVWADa6zirfnfcVjx/e9h2ORd3qKrda/myLM6Q3Gq"
    "EbOjyhqQQYlhqDIJ8IBF/IaDzoBHzEAbzSqUC5S0LAO4U2jcMoBIvZQZqMMmYKYFiBUGRKEDSiCa"
    "hv2oArmGfpDUNTRIZKqpAESCEQSCGl2PmZjR3SQt/ZHFEhJHcsK63qThiil+u3ZinDQCiSECLtB4"
    "sIgDSlCi3GZUqgUTt7vWuauLctasaxqqTRbYt2yQYIw4aEjqklCapCxkAUBJJKSSbvt11W3Fqq63"
    "XV31BC1D3BEAyQ0IIZlgISCtHBDaJvlX7YvBOn1o/mgIeyKHykUConzwGp1c6U4gcHE1YifOEdTC"
    "JFE9wD9REFSEE5iIKuzaShOAIIAegygW8m0wq8qE5U7kBoIHoI1JEZOuEKpgcqAmsNXvggfR2rbE"
    "ToQkAkBkEIAn5CIxgFVEpAwAbdOMGSoyBCBGEIgUAS4iFkR70N5rKgBIMiMPLSu8B00BgOBxvoNI"
    "JcILIKISRSEjIKicQIa8Dr0KmFFcRUQkCQPqRHGgbdJz22fyd7V5F0Sfbh90fBCAXny6LXK4wDXZ"
    "dFTb4Fdl1jVwKgwI1UlIsWI9FrexWD24TTtd00AZfSgnCj1TbzxoKIVoOsUTs+WBMoAP+OyFIXCy"
    "fkh14GFXLlkowkqRG5iTGIl05SmTZAkzIKdWVISWhAYt4BYsmp9oZZC5KuGAKmx9fovFShN/bVm5"
    "B0dR9ABCw5oCBBVOAhgHnOLqv3j0cu8ij8SJ1i8Tr5NS4OvzGPcFXV04sIsep3KDVDpReyCj62K9"
    "+FMAghEF5LPJbBGQbIiNRYwYEJEXkQeDA7SivSS0S55qtLbfJduMguZKgQgSJAtuaOwT4TILNeBs"
    "CmCKAaAGQC2hzIA0KBowADMfyecEZAkEJ2dm7S5BFg0qGiWiYpFGrEm0zSltlSpq1ShRWkQiQCEI"
    "JIRVY3yKBQeENqHICHAThMh1GSkc+kQTaQj1E5pwHLhu5cnMAsJFwdBumwBvoqga9CDumoHqhX1J"
    "TaZRWNvj3JSuV9eXzaW2QUEA+mez8AX2TbENxBlsdz+PUA1oo5SwnfFck2YDJB2iB5azQwMOJgN6"
    "OgOQXTBKCI0PL4Ro9oNbCRkGXQKM0fJE/dhk2owsg8fakXfEv/jkvssDu9HuDmJ8qDcHIg+2eug7"
    "NVCnLVHIFNS6wjISMqgpFICT2Jk+CEzGBbKPNoGHHyy8gvJeOw7c3xJwr2NCUSLlmYBQBKy7ObOt"
    "Wrntdcl6jcNlG511XURoQb0V9JtIQhCEQrRHQLklJAaCkqFSg5SYlhg9qEyMiigxAEaHicgd89EO"
    "orQIaGsuiCwILYnd+jpvBkIQzepennYtdmG2Ju0quRb03Kupdb6GiljYYaFOocCWR3IOCMIQsgDQ"
    "UhQQSKMVfr9qCe4IhIoyGo0lpTbeXfK89cq+rLx68xZEpkYBw7gTf6IgsAgHCoqbQhDzoxVFKkk8"
    "ta0XKr9F4G9kxQ4RfIm5AkAe1AqAyHCOr1GNSGHsQg83wiHlq3T+2jA8y6eChQ3PLIAYNpiFnpwE"
    "QdWDy13y1UNmXMjVcyZEwKWFai2Y4IkspTcSrplxuglWXLjeBxkIcDpH7mSCdYWwPMMRUDz8Xl7f"
    "HL0JyIkhCEFAfsc40YAb3CCb83+MDuPhs/A/SUFr1kXOMuawLkcLIpLbAlntM97/kUU7A+JAGRUc"
    "FUEFBXY7Y+nlAOu9wnMHU9p/VH4vq+fTIo29vnJr3PXum6c5OAmmQIF2fa3mhFKfNz1jVEEEGIHt"
    "T2+h83ZN9llPbTj69PVPWpOXlf57fCJUrrElGNHMgmk0VlXPR4rra6pqvl1trzIMALOYP3yxgyBP"
    "gQPY05n1ELjGEIAnUx2eNAxaEVf8INBFwyI2rxKgqazxcTWERUzhhgBQ9ljTPts0kl6UOqhmYhoT"
    "yLlDfpn57HxvY+LflmVJYiMKWFhzGmKvlrNjGa19w5b5/y5aSRZHFnXWYdURyeoY2VT/qLPuSzp+"
    "OH0nZoksTRxGnBdgsmxTtvdr2U2Demq90XbWaNajLDJ3Tiuy1sfoLXowhQnchkOgcHR9ztCkSTnL"
    "Qh+WSK56mhDa1z08OdnWnhXxNna+Kq2hRpbajWW22M41daVbLbYoINKwbS2tlGHSwuBRbussuNly"
    "4ZYmJXJbKSwttO62rcuRbqVU5qRrHKWfSm335VaoU09F5TtAk0OUut4chvokknhy2NpbXnfPTtDC"
    "cc85WayU00SBw0Zpwyo3yO45blGbasPKEJMjkwS7kyqFa7dYfARe0HvrzwduJoErm8KtL46nISVV"
    "HcUcmYOSkSZ1d6kWZxZ2T5gXRZhUWhGgOSr2t0tcw9VhUpQYDQaQICQoCgoHAZcHA3CRJCQXGw9r"
    "y58kHtcDxZzNk5SSQgyEJJrrqKZsBg/gQIhQBoyUNwpuokKZAZIVRxHNs0QKpkSJSd+OGKhMKGWV"
    "IAyihgsDXsxmdMlUEZDrhlscyghJKnpqjRBNJ7RV2AU3B5MUFDN0IDCEAIQ1ZiIXjlwAAN4JjoOY"
    "Y0Uwz1Qoppm1QIHOCYIBCj/d77llVdoZDxFc+Wgh7l1DRkzeXz2MMEvoQ3bapbdJ1LV8nuXe7PXn"
    "Fcw0GkkKNGgkRf/JpeFx/imCfqHwytmodacnGcUYQCNMWQ3y8pDoIoMiIZc6AQvEQhTZTms4IdeF"
    "G0UbNE0QNZ5HIC/s/qofF4+AW/ibGxEjDxOfQDcAfOARXOgaEG8AIp6n4YPhDMRbhSo/EBYImpsG"
    "leiFLkhDSm+5yRPSqBEAgGZESRKjagP9eesBA5UDKobKNE55IFwPyxogdqW/lf9HV8dg/j8NHm1G"
    "86bzmiWVQIgWDk31sIbwlctJpj+zJagx5Z4o9AQuLG2gErWgrrAJFDklJyJh9ZQUDE6pSweVkGB+"
    "YgarNQCbJkcchD2e/ewPOtuHD1giVgkTtDQIqJYRFpQp/B779mXSTw6ztHGYhCEkkLIGQWlEMiN4"
    "aCHJSLstmT9KHDiyTVkGZdvHKX9VZSBiKZZrCnayTDceMowm0nO+3mhK7yYq9KnX2fDqLXblyru3"
    "JRbqykjbjUMlqya1ZzrMDYZxKQyTVk8zAyc7xOWKQgZkUg2FJUkRMFlH07Gcca5YhocALBuyIQ0y"
    "wJrlQCR2/Vs2m8JHt5OVvLzkl5HG9Sc02Mfjq8fXDJstq3IUQW2KZkQoJIkI61djURyZDs/xD9Dy"
    "xonGCwmA1yGlIqpVhGUEvLB1CFumxq56UMtHgVQwJBYJcSzOr6L05c1zbfKGW7PI0Lj1hQpqjpNL"
    "3GNlC0dXjS3AkXfK3QSB5IO7jRFUvSqapzJgFtFLiRisuEINIQgwjOPG5jFg1JLMcM7oMGa6C0EE"
    "ZBaMrsI6DAcRQjCwvGMUhZGNIXVZuMkRlyFy0anLdbvLLUo26r008V2nNvNBgRZhmTgWy2EcJGBa"
    "waF7EEghmSCsVbcIcWzAP1lhg0w8DaQU/wm9BsbLy4Jf3NBmRKgCMFEiK8IiaCbUgNCCVfZV2xbp"
    "AocGzhtDYVU11V6B4NfWC+3CQAkRZ7CwG1gQCCb2LOYtVyNm8AYi8dg68rQfFzjRgsFhGh0fATZa"
    "y5KoGFVdkC7th6orxKA/JRxZItmXAPeZMsh1bTII9JRQkQjRAoPXE9qJIHyE+0SxRRkwOlaKkdR1"
    "ROMN6AAb0DLTGECBNUKN+F03ZNEeDlMucrmzzSvHVPvZNl7jscLbVCk0NKtECQICEITEoIaaYrIw"
    "ZGRF8EfLcKZktUULTFppQCQIHVRRBgRROhGs17whtonE74OIuIFkkapcXUbhAkSMMYbTEYMkesyU"
    "CkDSgxH4UBMJqWRyhwaG4dJc5XEqZZIGUluTmm40hSEKjQkjYSqCyKQQgh8nQmugSDIUnqGAnR85"
    "wkeiPvAEkEU2zU4eo5D1KFCwBhDJ69eyHdO3I26IHAIlElMoS0zKRElZspS2WMrWmNNosKzWLbLI"
    "g4wGhU/D+2Q+3/E1N4Iib4giMhwBBBMzm3e0VUEO2QSxA5IloKVGr0IVBiRAh5TiBwTzEFsOE3ay"
    "gwCjkE5l0ATX4FkJoAppI0k6gIxai0lrVL6RBBdXWteXfO765Eb9VcvkN9N0ymWGFg1QJMS7crjJ"
    "Yhly5tclQYuLXNwmylQqEhRGJGpUdOWu4/w+YP32fcfV2nzqBofoPT+AEOUJAkDvQHyqBSMuNRIA"
    "IhO2UlCKwOH/q2sIJ9KJ+wkYiQkAIIuhBCbhHkf7Jzd+pJPGeyrhYjw/dTVA5HbtA9HSf34M08EC"
    "RVhAxBkUEiUTssP1HPgLv4pc/Fdp2IncvnN8k+L+2el6ADAcx0XriuMguAo4PVBaM+JCjsuSSMOR"
    "EkO4AN4+8qQlIIVykobukO0F8+wEnqkqVUoYijAYwoIciA2Tl48TiJfJBfsNA0O35S0JoDNUSPah"
    "9reCfJCmqCie78KWYJzSNeQJKCLBJulXExJsRYUalbLAsKILVhGelensnjPfILstWeLoJf861uIN"
    "3jSbUHHd4AuVxU7VuB5yFyLe5CJnSG4IonFF2hADlO957aUpN3caDaNUxZU2mhRNU2bTSpaVlpZU"
    "CREYOA1A1rdQVLUpSLoBPxkRLPGja6AIyQZBIJ8GwbWJ78qWvTQFhxjIS/axgkgoEERNMt46y0Fe"
    "aifSTUCHrDssJZAkJZpKbY0wi9YSi0lZIWl72Gii4kIB8Gz/t/b8ofTFHUboR3qEi8B2KOAwR4gl"
    "hCUj/qtdAgzMwd/0+r586r3EOoeYEpTtQXIHA0d4VPRZmzd0+rl1aagXkcLbOhC+hbxriwwkLLwt"
    "iJ6AyKuKF/vrYsXGLx/L3AADqivhVtvR5L7ekbBa0WyhVmqZSEEEZIW4XCGvwPo9NToe4EQspof2"
    "CABBAAtUE+iAIHsiCfMRDvO+iJw78kM8GDn89xES6H/w5O9IUWn+6FJefQUFjRtZ9Z6Nvpb9e+vv"
    "Dv+HaMUYyJIiyMqKSQDAqYQwvzpn8xgF0IMhvrwALKiRTXTQ8iGegImo+RET/E5f1Y2BBCBEooDb"
    "l5f33ymKqjSZoaURNz+sXckU4UJAdJE8xA=="
)

# ── Extract + compile ────────────────────────────────────────────────────
_BUILD = Path(__file__).resolve().parent.parent / "build" / "inline_k16"
_BUILD.mkdir(parents=True, exist_ok=True)
_CU = _BUILD / "flash_attention.cu"
if not _CU.exists():
    _CU.write_bytes(bz2.decompress(base64.b64decode(
        "".join(_CUDA_B64.replace("\n", "").split()))))

_ext = load(
    name="fp16_k16_sm86",
    sources=[str(_CU)],
    extra_cuda_cflags=['-std=c++20', '--use_fast_math', '--expt-relaxed-constexpr', '-gencode', 'arch=compute_86,code=sm_86', '-O3', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__'],
    extra_cflags=["-O3"],
    build_directory=str(_BUILD),
    verbose=False,
)

# ── Config ───────────────────────────────────────────────────────────────
def _find_best_cfg():
    cfgs = [c for c in get_kernel_configs("all") if c.dtype == DType.FP16][:40]
    B, N, H, D = 4, 2048, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v, o = torch.randn_like(q), torch.randn_like(q), torch.empty_like(q)
    best, best_ms = None, float("inf")
    for c in cfgs:
        try:
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            torch.cuda.synchronize()
            e0, e1 = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
            e0.record()
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            e1.record(); torch.cuda.synchronize()
            ms = e0.elapsed_time(e1) / 3
            if ms < best_ms: best_ms, best = ms, c
        except Exception: pass
    return best

_CFG = _find_best_cfg()

# ── Public API ───────────────────────────────────────────────────────────
def forward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """FP16 flash attention. q/k/v: (B, N, H, D) float16."""
    out = torch.empty_like(q)
    _ext.forward(_CFG, q.contiguous(), k.contiguous(), v.contiguous(), out, False)
    return out

# ── Self-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    torch.manual_seed(0)
    B, N, H, D = 8, 1024, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v = torch.randn_like(q), torch.randn_like(q)

    ref = F.scaled_dot_product_attention(
        q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)
    ).transpose(1,2)
    out = forward(q, k, v)
    err = (out - ref).abs().max().item()
    status = "OK" if err < 0.05 else "FAIL"
    print(f"K16 [Static GMEM Stride]  max|out-ref|={err:.4e}  {status}")

    # Latency
    for _ in range(10): forward(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200): forward(q, k, v)
    torch.cuda.synchronize()
    ms = (time.perf_counter()-t0)/200*1e3

    for _ in range(10):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    ref_ms = (time.perf_counter()-t0)/200*1e3

    print(f"  latency: {ms:.3f} ms  SDPA: {ref_ms:.3f} ms  rel: {ref_ms/ms*100:.1f}%")
