#!/usr/bin/env python3
"""
FP16 Flash Attention K10: Removing CSRZ + Opt Softmax  — RTX 3060 SM86
Auto-generated by gen_inline.py from kernels/src_10

Run (WSL):
  cd /mnt/d/GITHUB/Mini-Attention
  LD_LIBRARY_PATH=/root/fa_env/lib/python3.12/site-packages/torch/lib \
    /root/fa_env/bin/python kernels/flash_attn/cuda/inline/fp16_k10_sm86.py
"""

import base64, bz2, os, sys, time
from pathlib import Path

os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")

import torch
import torch.nn.functional as F
from torch.utils.cpp_extension import load

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "py"))
from flash_helpers.kernel_configs import (
    DType, FlashForwardKernelConfig, get_kernel_progression_configs,
)
from flash_helpers.kernel_configs import get_kernel_configs

# ── Embedded CUDA source (bzip2 + base64) ────────────────────────────────
_CUDA_B64 = (
    "QlpoOTFBWSZTWf3/riEAK5d/gG/f/////////+///7////5gZF7zw9sCED663vvvEuOeu7OjJfYE"
    "O2SFD1VNQu3pTqeYGe+4aONvfZTvnc+9898XugD4p0D57zqi9887327zoAceWQn2HvMd58dc+3nb"
    "73PtpnudbnPbtqp9719breSeL73XrUb7QFvr31ntle7du93vM9N3e557tzo7O53x3vPue7es293v"
    "edtaffQ9e3zfXO0uPtio8tkfdwHvc4NRnbg8OwfDzarb7tvu89eJLrOFo6U9b1vdc6pc43Dbrbdy"
    "Kjrdldc9n14PN8z7OHXk4dj3vPPGt7ePaUvBNDZpiPGpUd657N7dX09yNDIQ3tnWs+7sbXdbiZpb"
    "ldrpu7MsJTSCATCBomEGiaBoEymmmTSbSaAAAZAAyDQ0ABKaCCE0I0g0yTTU0eQaU20aQPSmhiAN"
    "DQaAAGgDEAwk0kREJlMjI1PU9Cek01PaSeqPTNTU/SPSjaTYp+pqPKaPKaeKekAekDIBphJ6qSQU"
    "0ynpkFPIaNTI9T0npD0mg9T1GgaANAaAAADQAACJIiNT0TEABDVU/xqp+U9lBoAKTejCanmio3qb"
    "RNqh+pPKHpBsoPUbFBEiQTSZBpoFNM0mhk0TaqfqemmqbU9T9UfpQafqQeiA9Q0AAGhoBngQVB/b"
    "BFBO/4Q/pGQT+cCrUMhUQUmsbCgLpcTN8jXFYxQypIiTX+zclBXZxVpgqgpUlQalRERO3pp/fPvf"
    "iv/jnp+D7b+0nts8O6mliN55urkUcicpkMa4zBDRDb4M42Lu2nzpmul3oKwVUE6Wxc3mERBPY/4v"
    "9WHdFiqE5Q6sMYoVWZEQ4pt+X7WHmvx/5n/ts2aKvYt+T8ldNPxGvFQdi5u7oS7L1XSC9WXGI27Z"
    "imm76ev6eSxpSpUOo45ZvgtzUn/5hVjrpkyC4JuzMET+mtqGolHHWawKMXFZlzJiVcbbz+mQsTuN"
    "h2+zTuOnSGL0h1VbW20S2lbSgBRIQp4a1/VvxccMoizY6sYlOma1rFX+frSCOMWW2IsUS2FNUqoZ"
    "TMtZmUiOAxitPyjhjIrjEs25zgBEENdnNE0ybpsJrg5xxc5ojHSh1y6eDXklREhJWjSOc5hJokir"
    "xbfsXt1beCtvDxdCfK8Pa6znpnDLy3QWlmP4dUJdGb0GbSYdt3lLxQu7TVeDsdHkDaR7h0HF5NSV"
    "yyxOOuZitYacltK1RYxV8HlkmBqG7OB6hHaG9lMZbLFRIsDipqjmYVEYdPF7Xma1rWta1rWta1rW"
    "ta1rWta1rWtbGta1rWtt0dGEYrIISO0R2X0RA/lvoOfQPBuivyysLZjqxRM72+FljwgJfyOAeS0D"
    "bzlBYJx3mkEsJLiCEj7rHFmYKQwGiBIwKslYDpq8xhzvRsZOnm6kKIT2EnRUREOw5LoGYvNM7dK6"
    "N5vxIYV2J/Z0Ngs3nIKVLLtGJQer+N9sDMgBoC1E1Un2RQ9UEzIJY3mWKXj/d6I/6dnfAp4I4Hps"
    "6Trg8ZuHPdKDd4kkhKahKJe9/75fp+61Ra3dnfwuLhy1SSfFegzoCxBYL5nbh9j+v935N+XTfl57"
    "db7Lx6UniIiEGICHe3tK97YoAuHZbIqnysxDIFQGJ7DOuU+zlKkWf/OtJw9V5PYYtJkYxNKHLRXL"
    "cgJCUfU1qrW11ba2vebarbtWyBAkqSEWAcpCfXagKZbFGUxviqG2CE0V6CKkIoYxCkkAkTVAWiLJ"
    "kSsJRkGGesP48tng2YWfXtY7tSbDrKHafr2ZF9p0ZxhbH1yhhFwiG6NiCR16ZYkwyEX0yDJzuVRx"
    "5wKdpusBxMzIRfIcHgOSbQGgTAM7Gz32+tXmFsiFuCfWoeTD1ggmkAUz7Ir7YHT1Cidvv9cyKhQQ"
    "M7ozc/zFhBwR6SAaiwbAFc5jT39aOgnXWAx/jRdXIhm54g7ekJD+7zF5Toamm59Tdf1Wj2G8lyi+"
    "fwrCwCUSQYjT5qfL46v7FFY0biBYN1FxFKuGsNHrgvE2jd5sMtpElQIQk7oeI9MY6SM2785xOaVj"
    "pOOV0Ap9vkqCCsl/94+FE/C+ED4oe0/vjjknt/yFQ7w6gtMMGS66ljaknhx15QezSs9qHhN3JY4/"
    "1kJRoeb6CHkwBD3SxDAnFX6XP+ZeGunRA7BpC5+ghJFRWLPl1Ofkj1iRMfgOO2+dOoUTpOMrYV/l"
    "00hEtrKe3nOFnzvlcAdh18W1/EArf07mGMlYR9NVEIIiRIIvppRKMOSvP/59/E8n780+O+jgrire"
    "9PuaPHor2cRallg4xXykCrFPtfjhUYjAMxl07ozkL4QpUdCfO8ue9vThO9NMpGzO/Dx3PvHps1vu"
    "N2s+5v9GxtmmrIQ7uKkghnAAQgBSElQhQCmOq1h3ZVo6ZzZVdAGWeSuPIvhWZmZmbbGDv3zd8YGA"
    "GJ06e/w6Zx8/XGmdzkIdJb8CRVo7umpOz5PyO31Q8PP9Hg56Cr0t6W+Htiy/67bD/xkpiLAoIPhl"
    "fbbk3SyuDe6D6vou9+jWrpcAYaggU5WjDMfk/LT7/zf6/nvrVQubz6hU006ZEo666QSMhBscOQ8D"
    "bVZaWWQ22avo581HHML7xNpmQVDiQivIg1Jzt48Wsak0nVzGsC4uLmfBqrIzVZoUITuRCpM8YO1x"
    "ur3RrEZ2S9Ozct2hm2Xn3jC2CRd1RoaO2z/bhdLTZqqsstoZrdbsWw4eOrQ2nDnvu8SUXExMTUnh"
    "Ri+p91dh3Ct1z4TE8+l9Cu1vsePfVtBe4iI3MUqYMZ0jw7aQxEqyi/ibUKp+z5Ao6YZ7M9Z1jHeb"
    "HDtemyWN2OkkPfXEtQeLxP0EBLI4oMbdPAd/ZFfQnOvpDTj7edJAPxzpOEXldFnbEnuo3hDjuM/a"
    "CORozV3i6O/d56PX0LfWufqKGKGz9qzushVuq91JVgEaaI0whZ7/fo9fw5tNCKqqm8dQ/Von6qr2"
    "+vfOX4l4yjqy7EsJIQC+VclgUhVwmwkdxym1nujeQwQHAaoCaZoEbrPtdkMFTe0+Hq52Pze0KtSc"
    "q2CscdH39WOU06rYpDqWyAVQsOtOspwYgFaKGKhQFYLY4h6fLzN4sTYSEhEfPIQC7LtV2FwcZeHq"
    "1tbeYjGwz7143PjmubiSynFHE0dpXUmIQIBhA4mHSByPaRybdpu2OERm52dtdZwsWiy1Oq9dj1AM"
    "uO32VwLItqQIBsG00S4mcECanJl9yfJPv0zbQU8CBWWOyLmHeU5xmYhl10YZPtfTGRMklrFr3vEx"
    "a7JMtDFRBEdS278+C7usvZscR6xbQVs5Zh+fUPxzB0643w7rQd0hbeTcNJoW5c2cddjEaHXL3y3n"
    "VjFhnh6cHCU0s2xJWvXF2s3it2a1FdU6hSSSaSaxO+OlNgXEe8OaCZlig2qJehh2Tyh4V53M74eO"
    "HO/fttJr17eY40EQ48KlCEkxoJk6W/yeLWJ4LdXTmSZg4dXWHIcnfuMOOGeJrFFWHJ055C+UUHRQ"
    "USa3CBlgfWKxDOBhMMkMYKcs1V6uccejDmvB7JOTme6wFVViqdDs5vX5Yg4jxvVr+HG5q7hHPt12"
    "sK3ETYflZ3eOZ4NjO7sxlfO7OGtYskau/2uhvaRxHn4xxk5+fTG7Fh0Jh2FuYo+z6ZMbNlWPINXI"
    "lB+ZMowL4TRFM/Li5KLvzH8xiG4FhsxuxH0I9iytM+5jvqwhSil9z2sW9HzkjIc+RZfU09sNqwjd"
    "GuV/lCKzKNmu2Dd5w7VDgQa/HO2/B4aELjJjkwwxHf0EPorMjtHYdlpQnRBscssqGtJF1cTxWBk5"
    "emYghtsG00zzcwlldS0RsCu5VfoPKu/dCEfn4Sc4EpVSv0n5csr/dJ0quSneyBOP4w6j0yQJES4h"
    "3EQOQt/DDP4G2bTbPrq9/iQz6MI+3Rezo99Bc8OvdqTINzLoaISeVUPp9LFhMGJnpznQ+U5xjFdd"
    "rnxkDZ9tYyR26WauXsGAzUA1ZPJXHY5ZstltLcx43XmXxXH2HSWbky02/dudm6bZwcnzOhAobt6X"
    "8Zs8wuq21AbFvmKR8vCowwQIKMUmG9j9XndrTZ3XucbycXOzTbfFTft6nf5nv0ffnQW058k5MueG"
    "/pt8opcbR2GeYVAVM6aAUvlGXqhFV5QACYLNjMZQqaxNsnplcwSYe6QpGF12uXypz93ws3Vn1F3f"
    "l6Up2Ulz6tennrr1WXfXnjeHiZ9eWXuHqbWveyf3dWN+tutn5q9eT39HG7OnUmzk8yoHQrw7e6qm"
    "XtKDraAWqvfIC0y5fm+OBkCA8tD0Uv8ep79fpjdji+kuJ04nJ5ENLOm5h6ePTi/LeNmxQeZGM57o"
    "0PKU2DdMyHHTHiR7H0xufQduAz2OJDs7O1VBArJRY1qIz69luWXtlxmkqwEiClqaoiJkpbbUaCmG"
    "K6d4I0sQbLSsX2GgxoNbVtGhFuNMIU93mp8J1URIJatCSA9uDYTCAKAynjfPBpM5Njso3+XLRTwM"
    "6pSrgzKbm0HZkIUYrp0QIM6W04lGQrL8KGupPXa1rRmbNFN1uxrTnpjXS3jjDzZjmlmF59kog6jw"
    "MDOGpd2x+Zh7cM2WW9XtSlgtqOycGr2bCo4QlwoeU6tO8vb7PHz+e+NMyocMJ0kiUG7uVBxATHBN"
    "ljpeFDTGIgHSe5dnYzoZb7wObQibeEB7MVocEHZLTn3IXGC/u2IRXr8NrZe+WxZ96rZyWeu+jqqM"
    "+mpS9nz/ERo207HlEol1Q+ykpxEndZcIM91nUnhw3d0dO927+vcXtvJ6no57vwW59b09e16/p+aA"
    "AAA7oxRZiPZi8NpuaiikHwQbk1BEwKjIlv157Z+DZN4lYWl/MZxqk0Skwys0KvKcXNGLeydUfezM"
    "U3qGvXCutryhGuLRMVr9N1lIeYsei9jUa2i1Nr/9yLypxfGUdfDVHyuYqgdqSdM71psR2Zo5LFIl"
    "fpNcoO+/ns3nsn4T8Yfd5Fb91GrjHbE5GR53fr6CaVDDXU9ar606EIZdSJyiQVTlnZTsmS1wcJvq"
    "cuskULttmuajL6GGNVf0fcC3ZSVMIxxSvyvmRg1NBK7mReEIvRPX67bKGjj8tumzYUxqjy5O3Umr"
    "M8DDeVl+zZ0qpa6yAfIvrGMJJUcaZ+XcR2+Wxb3h7Pa/ZM8qRVXtQ71PPydLqoxbTScPawo2221S"
    "WurgOhdptqVwe2cavUBMxs9hD5cyrdDB4DsIINFXj2c5HxYbky0xwlz4tDUv8NtxphZXohxcL8/H"
    "6frxxSQQ/qfCieNDtkWKG/f7t/yOFFAjR9pQs0ux1Gg4/dt3mc6Ysr4UUspQW8y8TN3m4zHit7+M"
    "odwcdhrunG7AhDwSSEgoqZWoETe0ZeDmK7NXHpQyZJCMViCTDJACTBPa42i3wprI45P88ZZQnBlm"
    "/adyE0C0EILaj2arJnnkqAr0s2yOqQ0mGQIdlPJ55HJN4vrO6xm93dR0QSghIncUyQm9Z6l5NmS/"
    "P6jQcXBxIfHGfcoS+WnRbxgXQ2lUd0cKbKBrKw7R1Xzi5xtuoo2v1UepaSPYGwAdxb/cQAtTc0NI"
    "QNVSfph1R20rqnbjUvOju6cZQTaMkgtQUtRRtXFsYojGTWiSxaKiPkqbboVfQnknpcu3Pi9/4fj+"
    "9kf4H9Z/Ah7iD9v2E/4UtoRNEE3iFFlU2xGhBN/MBBhswYyAPDgQDfDupzjvTT63S5/X05/L/62z"
    "iXu6LkcNkvnI/Z14Sjiipavh5q6Pt/hUPKK+iUHqnBweYmecLd07wmN38e3P4ZJF7ZHzhnTHHo4d"
    "wjVHnAT7+6hAhD8IUQfWQ0Wjw32IfxAYJL+rAylEQY0YP7LMrYGGrJ8TWLIT9cGFZ/QUlUUd2fHl"
    "BAEmQ+MpgH0kfvRCEEfVAKX5SIn1E/lAZFIQ/DhJo2e1blvjrRo0aNsaNNLS2ppr2Xay+RZY1Sqv"
    "uVvgW9+a2t52sWNCkaKLXt+5TonwHgj2YX8Xlw0qe0ih2ks1KIslQEoqqAZ/q3Z2iCAgdKBz9CIP"
    "grZXBNjbfZ8RJG3q6n9xP4fCNm9iXtZVMYOXJWVhCxFngqWJVnMfZtmS65C9rRfrPzqUumUain2Q"
    "tqW45d99+HVp18pYwny7SQzs6Y6TUm+wkY+eYpbIdi9ryqtbghIEXtAQREBBEQQ7sSPDhEpCUaKC"
    "ylA0DPYKJFEwye4/lgXyqOVufifpi0Ut9Hrc4cxzGc2eDCWHRI/Qq1b51zOhBFuGtm2p9FOr7FtG"
    "g1JmCBLSsSDGEaax0MlISUeDA5+UonQkc53cgQk1+Vmm1DA0Q4LorqeunHdhhsSz+JfMggE1n8xr"
    "ekLuXYuJ15N9Prh38Z1ZxPWWuDv5G9mfv72X3ojvloWhk8LmvjxR7wBoGchAP1M/yzm0gN8rTn+p"
    "qosbp2wasBZ91xAoQ5qXGZv7r5C+jzdt0izNHbv8INxEwtzONP94cbTkJx1ihtpW4HKneu6LWJmg"
    "IQJmCqtD7lM5nYanlVNkNQJgj7SOhrNLfscY8tgawxA/EwDWFhI3mY9dIJsYeevcRslc7gmQkEo2"
    "PC+sfNYTSpIrVKUCk788pVyP1jr/AayiPV4dl2V3mCeZQLkensw0fGa7Q3gw7JQd0D7Imvp7bBlD"
    "rIZQ7u27Zer6XCFmXbEvTNuTE/ROB4HiczRuljwTsMdNM9H8Ry54blmybHjws4aIaYnmiZIq3224"
    "67eNMYnQX39ckQdCEbkz+KZn2Kq2Kn+5DZR64fguzOvCfFTNHn6rPt2tfWftSiIv2FavkWi3Qnxg"
    "UTupbbi12gpLSeE0QGrhpg4IPR+1VUV4/w1xz3a9tWonVpVkMj9XEgqNu3sWxdKMoNdCx51wmTtu"
    "nMvIWUEpbRFhAq2t0ZDF1fCDULwoft8NPBNGCamHuju9JQPZBzEkinZBxr6LOF3YHd3Zlye916pZ"
    "tfMGi0A9kNN0DOwDgQxiUxqShMPpKUpSlPF6dGjR3mHB3J0xhZCewmc7NWtMevsHakzaMMMd2O/x"
    "Gxbvw55uhjlTab3hbpqUaeWaljHXOphKl0dJhzq1OEGXHrY9OsUw98URRof55KLeynR8fKQ6i1Ke"
    "Lu3rQ4t++CuMs5jGhCXJFwApeko851ulyQnd3dqZR0NI6T9K1qmHVkGgdW2TMSNU4QQhF+MDsW4g"
    "+3TqoiVmTuVzd/N3PHBNbHGKRamJze8nTv5xrbRjVjqY63tUIimON7FG88S98CF7hWMPScgpEJLl"
    "XqWBF30dWIE0eCtwqkopRHNx+O6xDA2yarjnxobByR18uW34YibDur0XS/YQwwJAx9a8A3hUNpUW"
    "AmBEgQMoDQQBo/PQod54eex+wip+JF3d8u1pb3tq0tfP42rXN17oAAAAABc1Oy1a5Vz7+ta9eE38"
    "/yeLrs9Wh+dKc+oNj7BlwVsWyoLZWyoLZWyoLa2ovn8svwYUDT2pynYvcIUWTh2qpJOpv6rohRub"
    "yoVIS7OnSIKqzxDwwN9W/Tb6nHuqQ9G6WhozTWNvjyaWtS7adnvFvF0pzT1bvTkau2hVFfF9Wnly"
    "r7q56myeY7HEHHUXa6RTwEQGiaRBrcOo/OYnkddzDDFFhw+VlqSSQI9WS+xDR5ChBEAoQUQoIAUA"
    "8IqZRSGKKKPa3p7rm5LOt2UUUUUUUd++qt1t5bxrl7F7HV0k1z1PHQNPV4HMAHmAMAGADFUe9j4+"
    "peMcvNN5mMYxjGMYxjGMZ5ratzcYoxRjGMYoxRiNHl7u+8vbdyjRRoooo+Pz83SjRRoo2IruT6Pl"
    "8wAAAAAAAAAAAAAAANVdiIiIiIgICAhbVCIiIiIiIiIiICAiIiAgIQLnOcqtyqloiJbVLUQkMkJC"
    "QkzMw34kPUV/NqFDt1SYv57nHMum3v767AlxO1BKiga5RbrYCsT6luINgKxAOKhVrBUFKqY802pU"
    "W8PfMYu65Oe0wl+z9Hdtu06b+bbtbmrCl34HnNIObV40mF4Xvl5TQ2XgQ1S5CPrcmzBY0PeQS2Nv"
    "QaszYMm/1rxxK9MXru9XxPvO4u/Gkat3mo1DRcbKizVMnXZOvlsoPQZ6pj9UYylqt0Mg896SSSAM"
    "IAAEJycAAAAAAOVbXq8+knjr1vP63vfO+dt2YlTNxqxL3o1TbPV4Qx1aklXn1UnAraP46B2r62uI"
    "VjdTYG41jhuJfVXGDzgTbUUD4Achj7XGoMiY1iGRN2Hd2I9W/EtkhyZcUHH0S3ektYoiYNCmOtCL"
    "HI2NCRDk9HEvx5HspOoYLjSNDWONk3ZEBhr2K8O8AACAAALq2rXVtWuugAAKAAYhtuoJvlBsbd3P"
    "Y8nZVMPP1tJVjQSzhJChcXHn5Qmzwffj0SXUCCAW8+ffEr9Hm3UStXM2HwYD8I147NNdlTP5u2rt"
    "Ed1M4VWzoh00xkaLOvt7qFt0Pd54WW4p6r6OPbfNrntweit5WcVAlWVUxKkFZdYvfhnoqkeqrLCS"
    "ht74wwpbb90Nxn8D6kL8Zq0OCTpJnT2O8HZV3YLxMU1V3UbrXt7Z6g73k5+JuSpuRy8jfz9OOGvT"
    "uE14l9+PnfJ83wJTVdfHXt07enHp8Huzm9rxN9LXoKDJcNCxOLkXlhXFcSdTfR3snthzwA8DjM6i"
    "XaNHO2FiqpooolUfWwprbqbFre7diYiTIGTIYxj97TOoDsm6TT3eivh97N6zylzNWpLe0SDwcWgT"
    "qMA0CZz2k+G5m6uBE0EWr22jPrMTDTnjy5w9sXN6admzsJmGBBkOcgUQIc36B6jzhCAKSK2zW1iU"
    "1o2mWabTMiaLWKtGrFRV+TzVdV26v477OtQ3KYT1MgLIsiiikJKK6so/7bDeXVsqFWpRCslYsiK6"
    "azGFFRNU0zSqn9Glu9NYhbVgmAFKISgJ1JMOCP25VAZnHj+Hrbw6/XVTlrz0x7x+JKgnr381z4n9"
    "7hLJJ+E+1aILtA5H/EFKQhJqisogl59LH1NoeYVSyaoxxpa0sLflL/74njNkpPgYrY4TiIekuZkM"
    "4mGho2mwKQOogO0OMd5v4hbobVR+MKQEOEVQfP23k9f97gwPv/NF2HcIOuUXD8P0KqqqrQq5wAA5"
    "VXOAAHKq5wAAAAC3LWrtenv6vHwdRDSPUWMGYNMmqus6HExDnDB44AZxdnLSH9+Iv1GCcdx4s9su"
    "+H5eKI6tMqCMcMNIbY7TtO0RNux0jQNXChMZ4G4QMARccAUpAHUpCoIm2/fzwqmRmfJsAinXsN2L"
    "oqVrvYfZ0e6fMvngsESHWQIQfwEOM6RRdSQ7nnANahq4bYi4qJPjoA/qHxENzamY+2BTnrH+TJoV"
    "swK66nrMzMtORwEctHXKV5E2IiD7pRAicFaNigp4dxKlbjUxgytw0UXREwrSYqCOqKo5zEREyIEa"
    "rI+9LW7HOqDiiwgAIUmhP2QVUJOC4UqAGRUOFB+mKWWACmvVg+B20BIZKAaSFAtZ+t+4Atv1qO50"
    "oJjdu3n1emUIQh9ZxHODvyLXSEnHHEWl96+lf4JjqRNj62GGHP4kPozNENdh/H81c9HyHuQRD7Fn"
    "4Pottt1CfyAJrOj4wsveBCAQg4NEQIoWNgcCpCKGoiGkiBaOnSMKRJRiFs886zMzI8IAHkNxGhA6"
    "4rGN+yTJNgsNGb8HVj9VgS6KJZ0K7NmBkZVqM0F0XC9aTRRprghHigdzAGJDOO7eoTlhPnSbyh37"
    "wzUwwAVWobvyyhAovKXifCxGosABgEH6SY/STNsQqXeqR+nXLqogeD6/pvtsqAzg9CbpIedfSHFH"
    "6u6U+O1JtFJrXZU8ryxy/HBmVVcSqE21pXSBj9Neq9jfS9F0ruWvO7Uk/VAp9X11znSQdbpLL4kx"
    "ZN7FdMHh5keZZgzH9N5W3ldvmEzbVfyTbyM4c1656a460zDBtQW8JGmk6r/pfTq0yLK0npNkIV7Z"
    "Q1e7kCs9KHk8819X4coO/YcMmVUpQjYXChEImV9SSYZeZvvO51RbNN1pcUh0W2gM9rtwTNnhjCGh"
    "0jkCCaLUJFOp5pIiyCQgr4OzZ2FsVPzrKYY6NVRtlwpJMk3JWWyBtllQjDRQkTzfaia29kCpMapQ"
    "gzoLUdUH0Cfe8Ex3UcCAbyngHZpNJgLDuTppiQlZObkNPyRjnjT6WkMrKdCN+rQURDrQx53dm3dR"
    "mTiadcFpBIdJAOgYiQ3P4cXaf1lEIKUinGlXctESvv+THkwwISEtqbZit7XhvJi7W/d7rbirFiqA"
    "jvql8MgMz4csja0RNTu3hp8e5PGNhWRycCoF3NMmE5hCGcBqfxWvZthYOqJA3thUV9PkaYy6cwLX"
    "2eshef0cZngxCttrS8mdMIbCwrSNoBTBcQJE5kuDngs5by3QUf7xFGPrJ/3llkhdUWJTIBBCArML"
    "ZUsgo/m8ZkMN2FQB1StXG2DlNSVdpuNsbbJbdSpBSbpSEPxsozaOgsjCMEZD6SK4gBGAB2gnFIkS"
    "JskTmkViRAZvm+QBHxFN+GWo8a5NRFxmo4uR2zkPP0yTh5IaSDaqIUQDm7/Z83vrFHnS6ipLp5/Z"
    "Mr55iUHHSg0/c9fzbccv37y+7DaQo/PPL+f+itMrqqrPRnyU7W8pd0k8vs5lGGsFGu0oOvYKJOkl"
    "GZS+UhEbYt2TbVNbb4EEEB3LMHl7Nxlsyl5g/IlL1QhZtsazZY5GjYqaGssFf82MSNd6f2Oj15Vo"
    "khSchSuTMaBQkVqgR6vcRE0rgiJf4or2fkTrtX1XhJD833n2/howPIhoy+sQo+G4f3iesl4D7vjK"
    "CxD4BRIhiUI7Py629n32xa9feQw7fQSQkkUAPiwo+QOx/fr/BBm+o626bvE4zSDy6Em5xXO2FPg5"
    "ZkcgGPYMDH/ni+6ia9xQQ/b7D75DpJuqHmooQpXWRzNDp0TeXVmssTEOHT6YmavpcPDVBCvnK84b"
    "aO30RIl1S2uHKQ3J/ah/xVMn5YUkkoe19waNL+l8njy0tphFHcKQkLgH7L7blEAPZZAnWrwAcLaw"
    "ABE6fd6vwbO8ODeS/ipU9wREDoxZ7I/QMA6J80JIQ5iip83tFpD0CbAmKRESkDgcLQbW2hbS0KFt"
    "LWBohqQhDz0HnOvE4pf1fc+5/+E4xRPKhG44+loJiWPUmXn+ORvJ1BAjGMDqg/fA+j+R62dHYqb9"
    "PdMI/B8Kf6APUppc/Jl9AiZlHiivKkafpEf64mdm5I8ERNChVlirvTd1ft4J4eo8C78gPHV9WrTb"
    "t9N461yuKq5omkZjL4hPfucPZsFA28qcqKUIY5hPQR9YhrlT77gAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAHPu/o+jAAAAAAAAAAAAAAAA0AAAAAAAAAAG3VvQvsavgRESKIlHuL3ByHFxQADzETHVB4QgHuC"
    "5R0/bSWHKY+r2hl3pH/3MsZCEPtTNyB1pdn98IQhD3MRZqkkkl/yh9DnwXYFg3I+RmbSeJ6wH8U+"
    "gaV96GSfWiJg8uh+T6fANs0//Fuz1E3IdvrD4UUVJYeiNHzhHpw/lE/JfLLuCTsvH0GHQLjf22vh"
    "OWG9qvfQLXo9/yJF2hqGesvBREsOkPe5OKz/SZcRjrxEUEkDvvisJ11mTcjLhwgZ5GjfzZm+5D+M"
    "ICOkTzgHNAQPeeSD7mY6Yj9HpPZ06CMIpT5pj9E+4huklQnCUcBuxkIcVXcEjikkfae9gHvGB8z4"
    "D90c9/GpFO4GEKEwJ5N6wTErNPlGDSuR7snMQ0EMDrCQkKAdIZHMLwagORk6QnAHo8+PzJnEhBiQ"
    "jBJBJJ1noNXxB3FJRU9f++wlBRiIVCpyI5ePYcqTkI9nkKsVhAPDXXFPRA3oGTJujZT7RzvgpN91"
    "RJLzXxo65k6neNUZsOUDvji4SRks9PYdrziMUQ4sFfQnGYIe6atrA+iPaQn8lHy/NSnoJp+uu4mZ"
    "HmCaUXoVbEYlSlAta1qgJCsrWVVEFVh4UId13kOWX6KLeZFKM1XvFX4Qo0QTge1MkJHz6xh2y1Oc"
    "06Gywf8UnqF6kWpm/mwHMh5dx4GdtX7pXnVqoXNccGLcbYGbFKzWUH4UMfJDnjvYoLzyImBjE+wb"
    "uQeYJ3IL4gITsrImLo4ddOMjJ9r9/4Crn/5+wCs9KK/8X8Yh7A96sQMU2j501Af4WCUPrnQOgWww"
    "V7BHFNIYiYAhuX5AgsIp+U6cZPgi9EU9xVVVYpRFx9rXs5mZmZmZlxzMzMzMzPL4fAqygW04Dzxn"
    "IlExH3Zfokf0JKbhNI0OndLiiVfziMSJ7R+kY4rmklWM9qxVtLbhHPe1mZmZmds108vwRc7w9Hok"
    "PRD0QOvBoTz0kw0aolhSIgHYrFWSG9KVOgKP+hBvAKjaVAxDiSBRAPdyjmKv3Bsz+6yRPNt+/Yko"
    "2Or7qPIh6JghXhX64PKGYqNVLNAUR/s+kfuc+PbKRblwe6NNYOMIF9xwdkCEzoHWazJqa2YPtyF4"
    "Zk7GCAcOC/EqIWD+P6JZLOrPO2rCnOYudLaLcKwN694ECN4G1QsVto2MzRSEQzoqq7cKJ/bn/qL3"
    "A4/g+7hiYmj7KH/ryfKHUEDR8iWF9jBbKUW3IaBAzQs2RPO+0KMmQhDOccvx7yuTyN0LgfuSsk5w"
    "vEDaDu1aCmGgwkdAT+RDmiTy3id0HBDgvwHqzgwikEPZoJnpmk1uZGOPfJM8WoapSBjtKlb5zwnm"
    "/FvAPaw1XH1YBmYYlnyRxIH1zw+7yDnxuEjO9On23RNF/a39Ny4XjeFx+fSHyZP9yWFXAPbNC6u6"
    "9TuK+WWHaYhIBblyqZJTH2Dq0GhCSR/hnwitUVjpqoaB/pPP0h4aOkMU7ZZCYTb00IbxFXsmVLUj"
    "kv3EE81gmTRJZGYH1eILEu9/i8sKs5WSgLYBhvGjwifYfBQdYj7h5z5A0dpRH88L0NFH6qPLDwSU"
    "vRKLY9X3Fc0WMNd7xSPQfTwHQOIbtWjStV/SiJki+nToGE8q+MmwMuHCBnkd4FjR2JvS0oIAb0AO"
    "sdu5KYaD9UEE7/p+1MO49Pm/z30nEvph/PyVqSraX57p/n+79f4/v/n17eP7Pn/w/b/r/n9HT5P9"
    "3jqI+mikgftJf0rhCQkJCQEMAIXVif4v+a9MXkf1fpLdn3FH2WD+B4GvnT7nrwGk+QuYMn9Z0+rk"
    "R8r1DDfg+Ebg0BZvR4cksuOy81q8tpVKvTimUUUUUUfp5uMYxjGM62rc3GKMUYoz+S5uKNFGijBQ"
    "XYB2RAO3odQRc7I91CoMdWIcU/gD7D+sHWc/eWWH7RaM1/QKugWZEFE+8D5DRy7nIkQzyt7KfQ2D"
    "B3jYHjSVzoJvZFj4E+0eyzrmkPGfYA6iJkDw4JQM1h7Hy5SPkbitj7xggQRCOTgncJWFIw1gZEWM"
    "2OpOgdcCp4/A8Z4z9YnrZ+t/Awv4Pzhkomg/w385n5T85fjnd5x/EWhbaLFVVw9uga0VVZISTnJy"
    "OHOchBsRfbXsfjRcpPrh9YgdR6iQX2Acd6Ekkk/OP50NJ3vd6z3fufatp5A6dDYaw+GYQNger9i/"
    "TYqilmEQwh9CfnIJ+RETJch3nchEixPbvALOw83UpZR9/KSZBC0sO5gsAWHwpHBIJ1m8uZpyzKgT"
    "fwUPeKzkF4zN7IXQsHMAcL06mg3DqELdbidBMhcjc7TcWfMcBRNB3GYRhBkYTkh9jqcO1lt3dWL9"
    "VKTTTVy1ZC4ZlRZqc+Hugoov755ikca0vrCe8QvNtlWVhRWwAJsgTDEA5FiGvfENrpBU3FBRlHhZ"
    "xuZyhRcugckgAABIC7b016k0ryq39XvCenhkqGgmoRXiWeKGfIicnPEh1Vk6oef0eFtS21tG1o22"
    "jRq0tydAPqHQMXu1iN62IaVaaDQWah6g8570n0QpYxLnGoeJOVHhch5kXngYOsdcExCAVAPWGRAD"
    "Y7TDaeQegUPjDYQzefd32ErBttKqqqqqgx8Z2nmOylss7jDDlEfRkOQNmULicmOH4mioSzouQE7p"
    "JIQgGSRPDeSMIScbToDiBOgQ6yyHRlVUryO1O99BOkzDS/K3iZEJJQwhcCiBlN47evq9+eEE7Q84"
    "DJC3gL6zQ3+HJo1He7ZSmOulM8ddoMWl3IviYSkEYRYIsItNqGYoMGhWDSaqsTIMgDj7BHuOE2vX"
    "JD8sg7rg4Fm7sXzizDNnqyVjGM/UW+++m3IsA/awi932rbTaNuF2L6VjGJnF4OI28EH19Ui8sS7j"
    "uiw/GfbrJHPfMmzlBwZMRcpnsQpZm4IKEcuWc4sGbWgv1LXdx99U6dOnTp06dbZzU0uo0YmJTtd8"
    "azXPBnJScca45vBq6VKNa1rXe3xd/CZQtE99TnJO2Zfjm/VrjXwBTZUJhzI/Wi8Y0ztniJW2ipIa"
    "aqxCEB2AeBusE8g2DghPc5zAogUc4kJYhLIH3vKqqqqrC6vPvTXNduwAAEAAAQAAB9DXV7uvDa14"
    "7qauZPGZuxIw2RwIwm/zgUWLLGoEmrn58woKKBlUruI+w0BNDeQNq8vcaUBlZjHQXsBlYTT2r22Q"
    "No5gFzlVyfFGJzhzByAHwCQ8GQ4iWh3sOzRq6oi7D+UQRBEUbOIkBIkNSRJSwFCQQsvbs8N9AraZ"
    "KlfFw5bZL9bm5qlYIBn7acQSBx9uLt5KwFOtkkIkIqMJtKtUstTZZtLKU5zctTQyyhmxFJNc/Q3r"
    "3Pb227tbaCIG4TjD8IhZ4l9YGIeuc7/eP+Xy03G0vXIoYD5xU6ztBPHQfE7DtDgcEt3Q2hml1ynN"
    "EBm5FWx4CicyKrIECBJIRICSKwEiAdhCUOWhmFKhq8TMAKqQDlt2IwCwakABjvsESr4yZsFA4FfN"
    "GRVFJkOCGQ14Ug6gxFXpIgPhumU+J4r4d3V3vDQNpTDTHc1YUHi5bfLInONAdqgCeHYj9209YbxA"
    "78OyKakQ8LMntpETi2hdn24PCJbCTJer1IQxTSSRQB8O/ewByIO04BhsEXgnXKPAYp0N8HlBRaWt"
    "JGD2hE/4sUrLO2hckzCwK9cFNwPLwi6A2crmm7gWQiz9lDz2aaqSiwQojzzlV2b4qGwgLXUQA+UD"
    "gIyQSCkgBAAkUStA9mR4uA4lLFsDgY5kLoiPFIB6XDRLDRySxYz1sPjJkp9LKM6zXbJAzSqn9lDh"
    "JkD9qFDFSWJnE9+FkXOqGRH76P9IkIL5AgFc1BzwcRiQ3omkRICHsVLDzCLYklBVksWIXzXAUhA+"
    "IYBloDjDClyXEuQhCyDI957fWlREyGhZskIPCVGCDQj4LbaUwpLXXmf0TRb9J9CpQWMj7kgEAiBX"
    "BjB0Tinh4h9gSEEISERhAVOjjSAb5QlwSBG+L8mWy7Psc0fr7hv+OnKYaSP9mduy7+Q3bkeh3Bn4"
    "gKkHAC1O4LSLhtNiEiiuN7IGCAeKZUp/S1Ie6he2+YMpKKEWJCwwtW2owYP/KJ6EwVTozcTiaSVB"
    "WslAWEZJU0wsEJ6gBk3s0BFJ+x9rZrP4gaDkEBBJNeZ9/K/ofw/j3tgf5mTYZMyB3f49mQP5n+z4"
    "nrk+FJmXETsL/L0IeCBDPyBSIyKSiEKlsojJUYIpFC9+85YHieXZyUmRkZI6BVinuWxTEqYpQlvH"
    "Y0+xnoVQO4OzzISFnwZ+QzbazxUcsBrnNFyYMg55xs9yXlr9RNj82xwccBq2yqLjemkIbkEO78gi"
    "BmLc5CSD2EHdc4ENpOFav5/wLl40Q81mgkYQwoJJERVCkScSYlScESmXTndZZlpQnGzWGpiOVZvD"
    "DNIjmNsyKQwzMtEyVKBYjkzDfAcYAYibDcBgmKLZTY0wtGlQJCmQSFIg5bkkUJlJSQ0hNSZMQ/cy"
    "dx60dylR3pyACJUJJAjokUzQEC3QRbAALEA1GQnPh4kSHnVrJ4S+bN25JFFp5XVStA3iqbCBsEBt"
    "SIEEgJAoel8VUvxvR+U3lV0M7SyBgP0JrsGyAREPfAEX+LVTUkWL8Uh6aOyBueP39fHqzPkEDETQ"
    "IawuYsfxhrGQxBMHIou+EmkOhr4cAqPWnuwIQLJvzMHDiMlMYhYiDS6FFLDBNmOctEnrwSTi5PAI"
    "MkDusLnSLQ1U7xCBfo/dPtnsrp7fjxdfeEo00otO4umfpwC663WveNIsRh/B/DjOvHToTre4WCpA"
    "QEgwIJ2RY6NUWk6JNYmZktsx0Y2UuZKJEtzB7Qw+oYGsTBmzQbmi0pOKBghkGAs6CSQbQQishRrN"
    "AkwygRQK1lzfYFevbwTiLvtzsPvtRtRfVzaX9v29AxquGjkWco1NrQ+SsO4ziS5MAPy02xwdDuqY"
    "kNYb7+dbrFpfiyqp2h3QcubzyyoGsINdrX00az1oaGK409CNhTZ90XbVxjkJIIY322k04Yi4hPw3"
    "ZWrC5SY5ZvGxlMk0J2VJEe0rxjlLHFrLmAywpgiKbIplloQrxggYgsEFwoO54rI9WePDcrDjLkr4"
    "WFVXo9w5tm008CLoYgVN+SmMdNlYamJxxU6ynRNvCTnGmt4TiXU2kLqycTShxylNDuWhlhqsFCSw"
    "QAQEkCay6DUVjN7ONRNZrN7N8GAqqgAAAGAEAAAAAgCOd/dbt13IV27Obt3I1atd/OAAAAAAFAAA"
    "ACIBc7dccs/4Zw3eVxzmxR0j2G5wuC86QeiJxL4LaZpFOEVcNolKsUisUgJBGKAyDAlLymMxL0vA"
    "cO9y6yZ0l26i6jTYo0yMaaYtMotc2cTNJcIjmGjF1s3RZh1DZJO00aRQivIuCC3JrqXSCNXku7SY"
    "iTsERjwaDaKoumtbRCjRKjn2kkNQHJEMxsyLRpI5IkKI75RN3bXLXkyt1vJ1qTag1GjZZGEBkEJG"
    "QbuK5OzBcwTPjA0VsP0IpFihXKFAmJFg2XKFhhYFlmpFlPLalxrEZ8O1a+f4Xz/X+GxRw6RyvTZU"
    "5k3bjVdA+4/oaOgrkzynBhVyiqdh/dMyih0yXlU1fXSvH24xkMK0OZjV0IQx1NUwKhCCkDJwFmhN"
    "bug2ajgBsAhkDqgUCcerv03J19IXEQqzTAzi0uhhVBa42cyHeGQHusUz3m6ICQiu+vsU2Vo02ymr"
    "Ka0hFRgLJIqEFYqoUQRS/IawQI2OSIkIAblF5tDyQ5OOzgQu9cznGKidfGGzium416Xcbw6gkWJA"
    "iiRApXk2lQikNg0BKUo4XAXUnkQZoDFxRBwtOWPSeSDoS/Wibc9wXAhX9y3t5BjPEr15Jh6o8RDL"
    "c2EROxQTmWQmBHCBv0KIOIlA5sVIAGcNAQDQ3a0bsTENp6iQgEEQgokRECKHgGy9ZATUnYKxgTbx"
    "d3Izx1+SpRlWIyXl2UZ40hifPDTyduDc302Fyw8USIiwrFBEUJA7KrONxMzYlBIg4L6kAycepKgd"
    "xQbwT5YoT/E5YWAusSwRjl+reJM4YHOaAQcCOKFBEK2iD+kBitWEOmHho8D7PsnHtqr3Kj4vdvRe"
    "Tet8wAAAAAAAAAAYAAJSSSSSSSSSSSSSSJMSSSRHvee+b+Xb0XWsNgKzlHlINxAh1LBKJO+9sPQB"
    "/2A3KI5QNiOS7QNjxD6pINNB3JgsDOpr9B+Y5wPhgqkIIpd3eycIiPGKDZr1cQi+UfUEVYqxwMMu"
    "FAVIcBDqmoQIX4RekLKp4PbkREp9ET/KGRHnAPo494uJSClnIJ4ZOTg+8fAGKjLQpB+cZTZF0Jt6"
    "jcF/Fg0RET4q0TXBuiyIBEgLCCBagCg40F316fjOhATFcRwzhGIkIRYjIedKhBJ08RKGZEa0Qqmh"
    "TqqISlwhpCCuASKgyAtyCVEMA2FxQpCvLqVcx2/2ay6Knm4XEi1DI3fGyfGIumDrOgOx5HhJJKwx"
    "MEP+tYgvdwIv9hHXkqAawDy8XViGkhNho5TTAqIbhsK73AnmSEIePzQnxtjEVVRkOcNksUk4XJom"
    "xqje/up7kWSo2yUAy44REEISD8uyQskFLkBvEFKVocxL+alMA9gkQiQiQgwREkFkGKxFDICholhl"
    "nq5tlvjloqiMps0q13+a7KZEQkQJ/Smdh7tft1I9FCuhe52x+ENAyDuos5M43GAwYk5BMbsskIVm"
    "2yU++yej0lCbu7D1IeYNnxMnoDRCB7aAP3KObnQoloKOl98B7w0XFuHgXkbEpI0YpQgULERViZDs"
    "FCksAPH0qIrWrEzOds2Nx7xq0vDLOf3alkRJBYiyeyesPh+yhRE/jKFgJh7f7pcU0uikRKqKrEX2"
    "E1/IYaN2s+51noL55PJJIQTccycMEvwEQAaoB6ohIGNFN4ANbLWZZrTas9/mtxrbEmLVEm1qSktN"
    "ZGS2r4rPmVd0ZWJ+6PA+vXAN42bQK6QD1XXsNnofk60AyH5ooZABswm6B6j6cg5YIisiA8YcK/gs"
    "+4mUPqibR74JMXDSSCJjXnw/bOgn6HvbNo7UIaFqkO9J68H7YbCDIFiCwi1BVJ6hV9ZR9/4DDGoZ"
    "hZulk+EsKRDKbZnAiwKDEGI4lnFuU5yT8du39KR/X83ZqKHQj157DJqYyy6Vu06uJrha58XGZziG"
    "TZQRTVlMZ9LiHhwf7qQhkPRTvW3JRZzX7C1BbQ7RDyNT10KHoJIiyKd8d2jgql9LcQNM3+sXAPRI"
    "whJBUjUir1eF6U+1muXpSvxO3v1rt3QSf3RojeL63a+PuHYL3HlMmVEwHz3slrtVTr5GShKFPQVu"
    "2SvLuT+/uNqm8kzPeGsaOO3qdVbtvvPVLEVxM214NulNliRIXyQLDrUBNTmg7/sYTKeG7VyUXqpa"
    "W1QNCYh1+iyaOLpR9M1Q5TkwpKMP1Bpi8QPAQSEUUiLgzChCiARhsfqmg5edNHtiIlcKUqJDQdoM"
    "gFs7O/5ZOxhKlVoyqjBnaM0CLqaoZEgpmXGA1sU1WlMKLnXWEWEibtT1X3Tk0dsspkzjNMuSnBcN"
    "Jo+JKQgaoxE8IYzIiJi1KIkUEDP5SE0b4GdgcEGhSIdgfXD7vAc++KMFgg+VUn+HU0E+wijFRSIg"
    "6Goi8Z0dC2GxlBIgT/grN5IWIFUbKZOMfTRyLeo69+Snr/LuXpnRBl0DUKLuyyLI9HOssVfVZZ6p"
    "rXc3hlYU2ybV22cF0nXFFbRUSyUYRKRKRoWgQtwYLIkYMFh1IHuUzSVjKhCFiRRIiyChntiYiWAD"
    "QRAQxNkRMgiH5okHPE18lvR8Y72KpqBEkhCJwlBB6UJmHIh6kRN4+URuCvcUQD6wqsXgMDaQi0wY"
    "yDzoHRAgKJFXlb9cTiUPniLISKRAgI6PDGjLOzvCAdg09LVtxrLglXLbcWp4aW01UPYvgINAq/P3"
    "azOWwZC5R4pMstdZW9sLR06YHwbuQEiouUJ6pHRsZTGd2EKc82e2XXO83jmqCfWtYgxM5zEPMahB"
    "RVSUXgA+mN2e5GUJsDpOcW+E6FDklaioPqhxtAQMRFb4mx8jknTM1M5Vy0tczGctADERiAEQQisY"
    "cfKAIb+B9+sdmRy1mEIevEJjREINiKATajoOCkyYfBRLhGX9ErmVjEwrZKIIQ5w7cVU7e1vaq2oq"
    "NUWr0NEbDUrXm9mfY9a6W6XGkpXOYUrgKZuRcZwTnFcurfDLbKkkJBqIk0mUZEUyUm0MTVGi0tXO"
    "y3Yxm4CSMWoShEYK2kGpZUClKNLEkZRBApZSUKVUoBEQBnUnJoX0bSkFdtkAzhCHRu8DwyoDYE2G"
    "z5SdMxtCiBpUH3eKnVq6xE0ahAhmCPiYouA4VEC+O7WEgEOwORLhgq7dCH8rWyMjyEWarmCnDWCw"
    "hsxSxytgxoKKGJYjO1oxyNRiQtaxhj+PWpkaoYSdhOJ11mWYBnKkz59OFZgChx7hKc5piiYesfrC"
    "za6ZZqHJvE8FavnrnN4q/86zPHReqrIquC1+/AszgcoQKdHcGQKJGwVBkE+MAi/qNHhQCPhCRALz"
    "7ggXaAYzKtbBiGQjUMokiFcrTJBhvCZFMCwAqDCBQL6tym4ejmqIujnmat66J6SSi0BUiqBIKuuK"
    "XyZjV6EkMn+pmqoKzuNaM6w6TKWSzpGQ3hsMFhAg6xNkFKUpVG5M5SoBFwq1rRbWxrWSjaxdlW5p"
    "Nd7m1i2VuubcyqipJJKShCOALsSooLbdmAAjah+4EQDJDMghnaINGiGsTtn+6LuTjD0j1RfxgAeK"
    "KyPmYiHfFLTpxSnGBs32mxH7WJmkRD1wPvIIqQgnaQEF3G2lzCAgF+8t5t2IAcR0xWnxSgqdxEtJ"
    "ACHEgJmGXxAD93Lv80F+uJQJIAyLBEqAIkKRANyexzuaihAERBFihQJAKSABCI7d4HXVaypbEagS"
    "AVAo5tFkFgDrKEzDZzOymr3CwIMiIhJFIMgqJw34HjqgZgABZMJBk+YYZqwGvI311b4/CzxRDiX0"
    "S1U/hSNK32uudUbXNcYAadudRqavwiYYVcZFKSosSpCUIxYjz2t8SsXnhN7geGX9KCaaPFMuqNBR"
    "CsR0RkGQBH2v3GbshD9E+9TEjouOE9ouOYUpqDSbQNOze8sNQ8pYveg8lkPTuwFxEIpiAWWmZPwD"
    "AGUFyVcmAKm8+KrqhNvfWDYgZug+kAlhwQECCqbhMA8JvDVfj58BH95E8xeHpnRpy2XXz+l0/MAB"
    "0eWdgoR63gESqHJH3orvwQCoAeOBRBIiQBeVlNkYQagC1EJAgREO5J0Q9qt+Uak0eu45ZQFJNtQR"
    "BJhAvi5NB0GO4oIL4MgNImAC4BQMBaHQQUoVDRgAGY+SAdR1zZKxDMaMUqGkRMUjFaJNpmlLbLSp"
    "trUoYrSk02kloGtU3abbWvLrz16JA0qaZgGhJKTHYivFvVGNGtMnDLN1OABQSLZxN6bAG/RUA38V"
    "3pqB6Yp+cWMUkXjKIED5yx2pFSJIkQPkPwCecvCN2JI1Y+q6t7lFGhJVbeqnWhuieOBWXcckEqIH"
    "lDyDkDugFBEaHth8gZsJGQZZAoxR7Yp9OLJtRhYR2cki8ES/z4L78LA7vyegdAnqQbg4EB8J71B2"
    "ZUKdtdoRwsjISMxAEpQnyJ8eZ4rpUBDUachkwuSvY3A5V6NKMBahcQzAKAJRDTYK5IAWonLMysjF"
    "mfUsxFgjDVp/MewIiIjAvRnQk3CwQlCwqVvYLrA1NGCGIEJk6MNStwKWXQkiCSZDy/m7s0bk4mCN"
    "VG5FZCNkFonQQTUHM9ymQ2GGhTgOAbOwocRkJZAGURApgkUYq+35kE9YIhIIMkiECAGbmevrCwH3"
    "kNycFhJFYBx9gh3/jGAQDioqbwhD6WACpRNDmXKqvycJKsYi9gbECRB74FQGQ4Du+BnuQzA5+fjc"
    "jlpXIUOJ1yAFnEzhb4ZhF1zPdWxdUSrspksowpkxqFmOCMWFlLMYXK4zLMWrUWloFrjfBQyNQ/Sy"
    "RTYFmByjBRA5tTr8/Nh0rrFFPmcY0XAbZhAM99/2PGUfO/ApPQvIhmEszBmWArJllLINVSDQf0/e"
    "SEhIZbVAkEXAqkiKi77th3cQJ13uE4w6g5X9Md/Uk75SvXKkbVuWRJaqqqMEGDJghPZNSxmH2c+s"
    "a04MEBA+Sfa5Ps7Jvq2Ib/NT1HwUOHgU+lKi9p7dMcZdksY20VVEjEFUIkL31wglkgh4lVOdYIeQ"
    "gwZCdKB2NNz1iFoRIAdTA3+0XG0Ig/8olBFxZEbV5QRFNR5dbWIIqaI4tUSJGnTPhVxEsqoZmIZG"
    "7t+G3n9NqPZA5JMWRLFkZzipa1sY0RXm9mc1Tw+RCzEy8e8S9q4PaGNVU1TwyWvDg+Z2+BpzbBa+"
    "0a7mGLJs05tceqvHCmtem4YO3V6QG1o8Tt6G+N8p33TlOzdxlCyuo04aEcMj0Z0yQ32KvnWNMucE"
    "hacBOJ2STJJkqNtZS20rZs1daW1SWFtLaW1sow5slwKLdlWuZcmZcEwCxjI47a24TxUIWH1V5bTT"
    "WuNQpp6LXpQSJNDu9cYcQ30SSTuWOUtpbXnfPTsDCcc85Wa6yqIA3a0oMLPHIhD2jFaMRHBCEmQx"
    "DoUPbPNg6mbsf91GdLD7NiThxkhJT8pPADewJKTGcYs7PlxclpCs6Lg5CtV+VrmHorFTBgLEpLSh"
    "KSlbDGri5IkIONw8nh7Ogbexl593ep4zXlBNhDx8fCtd+VvgrwIRWWhYBqZoHIE5USG+2oDJP3sW"
    "d55u3sQtigz/q5Dz77nRw7IF3SARpSIHmzR3LaDFPaTxdp7BQRWiw+s05IBoncguYCmYOsiooYho"
    "gMIRAkNWYiFmOG4VXfEMdZxMaI4J8kKJUkdpAgcYJiAWOwJW/CJ8D8nRgXldBQ+9D3YbzLVLbpOp"
    "asvlpp+PdlClOeudZBAr1dbfgmCfU5dWcxUus7O3REDMMhAJoYkgYnWPcRUJBE5oBZGlO23250wm"
    "iJ5nJ5HKReRQIxy3gagpyiEAIJARkAtDzDACUFIh+IFhEzKLUiEMHPM1QfyKAQUinHCorI2oD/fB"
    "5ggvGaTo+lylG1KI34U0BBpUP849u/9DpSYtj2cUSyoBBdt9RDaErhodMbrIMd07I8gXFpJZiVFC"
    "QkQZomxGRHNq70tqCEQYz2bO4TB5v2+vkfthCCTQLPGGgRUSwifYRALAPZ9NerHW9OBCEJJINhQU"
    "Q7iN9YUEIK9NZs8+FJ37ZGjMQ237F0objM1Y4UO1JM3EqDCaQ5128WQu8lVcSZ+DjQpNRg0siILK"
    "IiLCpU2ULDWrOdXBk2GcFIYTVEKcb1YCRYDcdQUlMBLlivNhkarpy6INEJvIHLCBk/JzKHUZ29LI"
    "dtoidjUGDIoW0OGAUeonUQJ2iTQIRGNtQ1HLL9cPJdB0bJJ2dA66S9d14E31LN3YFmtdTmcZSOAD"
    "0CkoKSNwLc6+bLGsp52dd4h11pNR+sIKb46mj4kbV9s7CBlHcwaiSAccVnqJfQX0oqmmdWWzgdSE"
    "yQkxAYhBxESWAiLGPcnitdawJVc6O3qGpwB0JCpJTpmAnQERkNMgMTAzWtWBgxKsmWnE1uQBKKlI"
    "LA8pcA1OBBIAjBsOQTUwOgXmsCMwywoKbIwLWNIHNBIDkSCsVbcIcGzAPYWGDTCb0T8jag3G4DRr"
    "8GgyINRBSCiQUdIIZia0CFIrV1VNBECAW8drQ1VU3qvAdvgAeyCyAEr1yAbmBAIg4zabMHGI4GjR"
    "Q0oNbddQzdpNoEEDGPWcd1LkqAZgC9MDAeU98QOKqkN+FG1OZkvcyuG16SigYMaIU/dBOiB/CHkJ"
    "1/Nha5DQwOpaKkdXgibg4gUXiFwyjAkVe76bj5eZOwMIqCCMZPAodZPhNZagUbXc3HK8hSRViIQh"
    "MCUENNMErZWYsxCAJ7cBTMJVUpTAppQCRIEIRIkUTmUwB8Ihtpmp4Il4l0MFS2GsrMRBYIJrQYTR"
    "EPJNyAUk4oaZ6YBDUOpgzadZSYmCJbbmmVIzSVycsrjFzTiubEhYSqCyAQQivt7UzDWDIUnrGAm/"
    "5jKR7I94Akgim9ipl2ax3IFCxDLu30vH2V7b2e68nnV40rkhjKZlmQgbTWUyTabRRmtaYs2zaWkr"
    "ZC3rVbm23yfwF9P+G8mxFETlAERkBE6/k76gh5EEuB2xLREqNXoAqDEghD0GsHEnxQWw4j17tjQQ"
    "HMO4dwEy9qyE500EdUnxoRlMlhmAJ7qiqKphkIdk9e6KLPx0svlt+O6TMwwsFUCTEu1JVQFQSlko"
    "xQUrYVUCtGQokjAklSppw1/q/En4M/pn2931qByPxPP3qPCBOdVORALIy0KQEQnSUlKi6/3NWEE9"
    "SJ+okYiQkAIIulBDgEeJ/ROTyVJJ5yFgojq95NMDhdu0Dv6H8cXQh54gEIGcGQQSJTIUH9o4ag7H"
    "it/C6TsV5r+xPQ5J7PwMzzDiAZPEQ0XlFZkIDh9ZJKbO5Ke1iiI9SwU9uQnaz5iqDSEC+JaTMLJ5"
    "Qk/N9XtAfVWtrSIABAYkKCG+QGxOnUagNm+CPqNAaDk9BoCdAhYeiB9+ZofjSy0K/bpg+KH9dM9k"
    "FoMloFeyDjDcn3BFhY1LLEhYUg0yDGaecPXNx9pAa3Vo0WQS/qWuEg3DrSHYKZ7ws8+NPYuAPgQw"
    "RcYIRNKA7KbWvauvV2pSpLzuMFUVpqabShSKxbNlZpaWlYLEIhAFg4DQDStlBUlqRGGjSp8c1ulS"
    "+by7+uVQWTRprdIyH72UC+qwwYhtijnywRABkISQZAMzXN3yxVehRPuJqHfAqp2VYQrBBR5QozGJ"
    "fGFMMW3etYSlNEEgH/X8PpD/nFHSbYRyqEi6A0lH9QwRzQMB/azkEhIH2/bPg6dj8JlcusF02bKI"
    "HZcycrTekutmrj9dNao8F5EU6a9LWcIY1tLVKmI3nE+CZFYFDH6xsswxen9/ydar5iq762q8/qX2"
    "dI2IrYtlJAGIEVIRQUkhayGnpevtqxseRUHLBbY/5lASKAlqKHwiCvsggfQd53+xESdfbjXQ8PzW"
    "IiX/I8/TIUXD+UGgeNBYKLFWfX+Vt9Tfn35l39/4GxiZjRbRnGha77Wu+3fb96v57u1bvCSG/TUA"
    "sqJBNddDL59ARNR7ERP4zn/i+bSqUVtQ4P2VeYVRRkZIidB//F3JFOFCQ/f+uIQ="
)

# ── Extract + compile ────────────────────────────────────────────────────
_BUILD = Path(__file__).resolve().parent.parent / "build" / "inline_k10"
_BUILD.mkdir(parents=True, exist_ok=True)
_CU = _BUILD / "flash_attention.cu"
if not _CU.exists():
    _CU.write_bytes(bz2.decompress(base64.b64decode(
        "".join(_CUDA_B64.replace("\n", "").split()))))

_ext = load(
    name="fp16_k10_sm86",
    sources=[str(_CU)],
    extra_cuda_cflags=['-std=c++20', '--use_fast_math', '--expt-relaxed-constexpr', '-gencode', 'arch=compute_86,code=sm_86', '-O3', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__'],
    extra_cflags=["-O3"],
    build_directory=str(_BUILD),
    verbose=False,
)

# ── Config ───────────────────────────────────────────────────────────────
def _find_best_cfg():
    cfgs = [c for c in get_kernel_configs("all") if c.dtype == DType.FP16][:40]
    B, N, H, D = 4, 2048, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v, o = torch.randn_like(q), torch.randn_like(q), torch.empty_like(q)
    best, best_ms = None, float("inf")
    for c in cfgs:
        try:
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            torch.cuda.synchronize()
            e0, e1 = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
            e0.record()
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            e1.record(); torch.cuda.synchronize()
            ms = e0.elapsed_time(e1) / 3
            if ms < best_ms: best_ms, best = ms, c
        except Exception: pass
    return best

_CFG = _find_best_cfg()

# ── Public API ───────────────────────────────────────────────────────────
def forward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """FP16 flash attention. q/k/v: (B, N, H, D) float16."""
    out = torch.empty_like(q)
    _ext.forward(_CFG, q.contiguous(), k.contiguous(), v.contiguous(), out, False)
    return out

# ── Self-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    torch.manual_seed(0)
    B, N, H, D = 8, 1024, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v = torch.randn_like(q), torch.randn_like(q)

    ref = F.scaled_dot_product_attention(
        q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)
    ).transpose(1,2)
    out = forward(q, k, v)
    err = (out - ref).abs().max().item()
    status = "OK" if err < 0.05 else "FAIL"
    print(f"K10 [Removing CSRZ + Opt Softmax]  max|out-ref|={err:.4e}  {status}")

    # Latency
    for _ in range(10): forward(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200): forward(q, k, v)
    torch.cuda.synchronize()
    ms = (time.perf_counter()-t0)/200*1e3

    for _ in range(10):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    ref_ms = (time.perf_counter()-t0)/200*1e3

    print(f"  latency: {ms:.3f} ms  SDPA: {ref_ms:.3f} ms  rel: {ref_ms/ms*100:.1f}%")
