#!/usr/bin/env python3
"""
FP16 Flash Attention K8: Reducing IADD3/LOP3/SHF  — RTX 3060 SM86
Auto-generated by gen_inline.py from kernels/src_8

Run (WSL):
  cd /mnt/d/GITHUB/Mini-Attention
  LD_LIBRARY_PATH=/root/fa_env/lib/python3.12/site-packages/torch/lib \
    /root/fa_env/bin/python kernels/flash_attn/cuda/inline/fp16_k8_sm86.py
"""

import base64, bz2, os, sys, time
from pathlib import Path

os.environ.setdefault("TORCH_CUDA_ARCH_LIST", "8.6")

import torch
import torch.nn.functional as F
from torch.utils.cpp_extension import load

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "py"))
from flash_helpers.kernel_configs import (
    DType, FlashForwardKernelConfig, get_kernel_progression_configs,
)
from flash_helpers.kernel_configs import get_kernel_configs

# ── Embedded CUDA source (bzip2 + base64) ────────────────────────────────
_CUDA_B64 = (
    "QlpoOTFBWSZTWWVPJEwAKrj/gG/f//7//////+///7////5gYl7zx5AxZAXz51ednvPr3vd0eU7C"
    "okUKACOtu4UG89wLvu6USX3tw89i+cL1KKeJeg+5TIu+fOfXPuwA4JCQ9eRz7x1vnneu8u2M7Hzr"
    "Zu2qe9R4nXtb1zzp9YeuAmn3suLdb23Xnsa9995e073TMxvj3H1ofG+313ns9n1HX28+9cXL6+ql"
    "SvNbe+7vGjEKmjfewhsH1PNqtvu7fd3e2knvceEPuyvtvbtVqu07hw7dlvueO0ZtI3fcd8F91ZfW"
    "h7N6mMmmNmcTqHBtJkqqp4Z1haSbnX20eTb10J0JGpny1Zuqu2y3Nwq7str4SmkEAmIAAIJkZU/U"
    "xqNKbJmiZCaaGmgA0NAyZGmmg00EpoIITRNNE00E9Q1J5pMp+lPAE9KMh6hoAAAADQD1A0BJpIkE"
    "IyNBNDU0xTwVH5U3qPVPU0/VNqNGn6U/UyjBHpGh6jQbSAaNAwSeqklNTTTJiGjQJqMnpPTJNPUa"
    "DaTNIGjQ9QAAAAABkARJERoho0ZGpijyTaU/RMk2kyaaYU2BNNpGENE8p6GkNA09RoG1BEiQRoRo"
    "TFPSZomU8hoaj1M1NJPFHqAP0pk0GnqaaAGnqAGTQ06QUAfsioIni9Z+6I/1iFoWiESEDGwoCJm+"
    "RrjURQakIkqSgrs42tMjRrjkwoNSoiInXlp+w/Y+6/z8uf7X1v6Selnk7aaWI3lyurkUcickyC1m"
    "CGoG3yIcbF3bQucrrQW2f2nFUE52xdcZhEQT/z/K/7bMSga6DREJkgdJNERDim3/H1Ymv9/8T8dZ"
    "tFYsW+3rxGf7iN1B0XJ3dCRKMqEJJFxOmSFk1GKDBnA+bwmYlSodBub4LmoCsbyyZBcE3ZmCJ+mt"
    "qGolHHWayVRi4hiYuLx/nDGRidhsOvhTsOUKvJegLa22iW0rbQAokIU79a/7b7uOGURTY6sYlOVu"
    "Kv5+6wEcYstsRYwUthTVKqGUzLWZlIjgMYrb5p2drsyNxEs245oRBDXTmiaZLpsJrg5xxK4jHSh1"
    "y6dzeCVESElqNI5zVisYKIigc0n7p6QJOSEmHIedqSr7436W+2saqWFongHdwdA0QRpIS0gT+OKO"
    "EvQ/2JwSVTEDurm6J6BSGXEUhZ7ktK5ZYnHTMiaLFXUtpWqIxFnmtw5WSYGQ3ZwdAl2hveYLLZYq"
    "JFA4qM1mW4ojDn39vqa1rWta1rWta1rWta1rWta1rWtbGta1rWtt1zEkYkUIKdUh1J7yE/pzqdg+"
    "zxPLknlnHlzkmvv3kXbqO/DdN014Nyyx4RL+ZwDz2gbeWUFgnHeddTS+Aoin7cPCSBSGA0QJE2wR"
    "BktQYl7smL1JQmbHdkYogPVB1khCEDeaFaBmL2pTppw2NsSGFd5Pw0N4XseQKQbMNGZQfs/nx0wN"
    "iDoEHVrh++gD8CGLBMxY3csUu//P1R/T190CnejeeFnonXB4zcOWyUG7hJJCQmBJCBIRz/+t8eCY"
    "BSE3HiqVKtJUknz3mM5gsQWC6VJQO/9X2PCWiKfyosjKt58ENcMMmQCDInsHWRWKALh1tkVT6mYh"
    "gFQGJ3odMp8PXLixvvejy3c9FeD1mNSTYxNKHLRXLcgJCUfiaqqtrrUgnoiqo4KpVQWoIMiOkVPX"
    "KgCmWxRUpxrgIHeyA8r/WEIIyBwkLBQFh2oSUZF6DdtOgb7O4P6PVk58ahvhiDVjc8o43E/h3wTx"
    "PHomRFvUOMhM1JgwTQEMJraVAkMIRkpkGLnVUb+MSnSa7AcTMyEXyHB4DkmyBkEwDOxo9lvjeYcp"
    "ELcU+mW8aVoCJipT5KV78DVwiieDrkgXDC1GDS8SBBwR6iAZisLwtRpp7eaOwTroAx+ei6uRfyUc"
    "Q21RT36MmkHUw4lX4ZVP89UTeZU23VF9flsTAIUYklGP63xZ+qmt07xDA76SMKsx0Dg/we6do3oO"
    "w6u0kq4hCTuh5HxM8yM27NU4nalY6TjldAKfTyVBBWS/b3+iifbfCB8SHtP5cY609n8ZUO4OkLTD"
    "BkuulY2pJ38teuD1aPPUiE4uSxx/wISjQ83yEPJgCHhLFsCd6zO5/3HtndRA6DSFy9JCaKigWrju"
    "f8seYkTH3DjtsnTlFE7JxlbCv83GkIltZT1cpwsWNrM3M5b2z+YBU/p1sMVAw9GVEIAiRIKPo0Kl"
    "GGyu37fVxPO/npT2L5tdevWjyenmxh5MEbLEwgvYQKsU+t9eFXuIDMY9fVGcjzhSoXJ9WQyP3t4Y"
    "TvmUjaztw79j7R6rND7DdsPX7nh2u3jy1kKqiZy0GgAIQAUhJUIUApjvWsPFlWbnnNlV0AZZ21sM"
    "i+ecuZVWbhnJ5uOmHzgYAYnXs9O+L/N15xwOQh0luSX29v0Zk7Pg/E6vGHo9Pyehz1FXg3g3n64s"
    "v/Olh+xkpiLAoP2D45sLrszdltcG9sH0fLf55NKulvBhqCBTmtGGY/N/rT5/p/V+u+tVC5vPeKmm"
    "nNIlHRXSwkZRBpcOQ8DVVZaWWQ1WZ/l5kMNQZMgmyzILm4kIrykGpbnbw4NY3Kps5v5jbBubm7P1"
    "NptNlo71wRGEPMO3A78989QjxrWve1bVtyBam1X/ThbBIyQm0NNn/O+6VWZXVWWTZpJiM3DXNobG"
    "vHbZ4kouJiYmpO1FsLU+xdZ5RW6p7DE9vXfQrxs5tlsC9hERsXJAvfEdmmYYiUPf2G0DNP1+oKOe"
    "GezPWdYx5TY4dz02Sxuxzkh764lqY8ggdkXIJ145jfmhL505jlg0afoqoSA+3N2LkzOhzKmF3uVg"
    "i6kn3Aw0ihlS7xdHbq9NHj1lvwrh4l2Lt4vUvFwfHdj4bmOQTvecRGvz+7R8XvZtNCKqqm8cx+ei"
    "fnVev4t85fiXjKOeXYlhJCAXxrksCkKuE2EjynKbWe6N5DBAcBsgWTNBPDX5/CL8ne9p7/m5WPye"
    "0Ks6cq0iscdH1Z8cs06rYpDctMAqjU8E652hiA0RdjIoFqT25eJvFibCQkIj55CAXZdquwuDsLxc"
    "9bW3mIxsD7143PfmupxJZTi4kwuaY1QIBhck0CCAcn6yOpuLThs7xGbnZ31scLFostSLQ4Nwjs1+"
    "8tgtoWEA1tZ6SjMnITOCBNFygvuT5VtzTvp3wrFYWsSnOU8Q5+F+rrfPijGRMkltVr3vExa7JMtD"
    "FRBEc1t5s9t3dZe2OI9YtoZyzGOroPxzB0643w7rUd0hbeTcNJoW4XXYxw0OuXvlvaVjFhnh6cHC"
    "U0s2xJWvXF2s3itPZrabc51Ckkk0k1ed8dKbAuI94c0ERDskCdxD4jQ7A4l6ad2Opi9eDu7ja9e3"
    "gcaCIceFShCSY0EydLf1d2sTuizmBngUGFMFgscKZMWsm2TpkhJJi5i9wfsFB0UFEnK4QMsD6xWI"
    "HAwmGSGMFOWZ0llRa3kgu6sdY1y7edMCSSSTJJGDS75+7EHEmJ3i1/Fjc1dyOrv12sLiXXKnd89R"
    "27Gd3ZjK+d2cNaxZI1d/X0N7SOI9rjHGT2uemDdiw6Ew7CNjFH1/NGTGnTVjxDPxJQfkTKLy+E0R"
    "TPx4OSi73D8ymBcTYqhkZofOvNVKurlTwlMQookvr+Zifd7iRlHP3Cy+pp6oalhG6Ncr/KEVrKNO"
    "i2Ddp1HCG8g1+Ou2/B4coTDlDzoifI6JnXrIVx0OZ8xSUzqhKhbhjjjQ1xIyVxO9YGDl6ZiCG0wb"
    "LTPU5hLLdS0RsDTgsznfxRFfT3053lYtW/M/F1dW/w06WPLbiyYUD+5Dq/bgskLxRUhZRc5dtteR"
    "4O/hu/Jlpp7oNaMI9mZde94KC05uLLOTAMmWoaISbqoenpYpEMTXm1zofLOcYxXK1zzkDa+lYyR0"
    "zAVy8hgLGGAtqbS+iBqV8KsCGs6musIzZp/A1JBoiqph+XFtOyba4OT5H1kChursv4TZ5hdVqqA0"
    "rbMUj5fRUYYIEFGKTDeT7u92tNPXe5wvJxc6Zrb4qb9W53+F78n1ToIU2aZty3Q4M9veELjaOo06"
    "WoCppooBS+u+HpWuq8sAAmC1saxlCobTLNG0CTD2yFLC23RL3U6/Z52bKz5i7t0+CU7KS58+jNy0"
    "V57LvfrxvDvNfPLl9g8oznRRNP0sYyZmzM+Kolu9NbjaM5lRVUc1IHQqIO3sqpl6yg5tALVXtkBa"
    "ZeP6fiwMoIDyyPRS/xbnv0eEMjF71xcTpxORwINFnTYh33573wyQtamQc0U1Vb4VnEk6nKLCionf"
    "D7q368j9J4ahu8lEhTTUohAQKyUWNakRnx2W5ZeyXGaSrASIKWpqiImSltt/XtwFNGLW3E6MQ3X0"
    "XN/EcTnc7W0abo4c8RGPR7uPctm8kJdm6SD2YNhMIAoDKeN+EaHZ2cmx1Ubvg5ZKeBsqlKuDLtc1"
    "tSzIQpSUu1Ag10tmxKMorL8KGupPK1rWjM05KbrdLWnPNXS3pxhqEZWMM/fAHUH3GBqozrrofiZs"
    "ns1M+OxZClLBaUc5wavRoKjdCW6h5TzbC9vr7/T6ckcJlQ4YTpJEoN1ZeFJwAXig4Js+bQ8KmoGI"
    "gGmPBatTOhlhhActgiM1rAU2JVlyDVFo1coK+BR0mQRXx+O1svfLYs+9Vs5LPXno51HpmEvl+b4C"
    "Mtlc260w5Lqh9dJTiJO2y4QZ89nQnfx3dsdM5jOzumnk8HvfBbn2fL163qeX2wAAAOcXkXpeS56W"
    "Dw2GtqKKQfBBrTUETAqMpsz6tMu5srcSoLC/kM42U0mDlz15LTnaXN+pvhzHxszF+Kjs7IzluJdH"
    "ZLRMVo8LrKQ7yx6MWM5oaLU2v+z3Pho354+VrFsDoknTO96bEdmaOVYpEr8xolB326K2hOtj519K"
    "PdtHsqcpaZ6JjrKPCI9nYV3RLPybqWngnQhDJqmCFhyvpRonneSzOV0k11WSXJRl5gxmq+T5Qy6K"
    "SphGOKV+W+ZGDU0EruJF4Qi9E8/lbZQ0cfd15rNJTGqPHi7bk1ZrwMNpWX6dPZVS11kA9q+MppSS"
    "kXyZ8N5DbxmT7B5va/ZM8qRVVJd6nq8nS6qMW00nD2sKNtttUlrq4DoXebalcHtnGr1ATMbPYQ+X"
    "Mq3Qwdp2EEGilstcwPXS2DKukgjdMoIfPVSURZk+9FzRZvRd4eUczCQzfV8Di2ONXIsUNu32bfcb"
    "6KBGT41CzM7G4yHD57e87rYllxi+GVQu8h7NFPd4TQrOn3tDhsFtCd5xwpBE1QVJBRUytQImjNl5"
    "nMV172zOhuZJFIkikgBIhn3UPLh7N5fPqr444dV5wy7n9o9tCaDYEINsnq6a2PTSuGnWzds9KGph"
    "kCHZTyvOo0qsjceMCxvHxc2oYcSQkHiOySK4NvZtN9S/X4mQ4ODiQ+OM+tQl7s2S3hAuhqKo7I4U"
    "2UDWVh1DqvlFzhbdRRqfdR4rMR6NpAHcWz2EGa1NyTNIQM7ux8iME1dD4LPGkhNzTfKTBWgSLbjW"
    "NUUbauTGpLaTYtFRH16lumwVfPngnqOT4/o/F9b6mp+09k+0h6iD8n6CfuobJmgmghRZVNURtaN/"
    "cBBhtYMYgHo3kA2w66dcdqafN0uXv7OXu/bbZwL3dFyN+mX7hH6umEo4oqWfz7q6Ps/dUPKK+SUH"
    "qnBweMIxxgsjp3gmMj7LcfCJEX2oj1U80QTGGhw4CLUMx6u2hAhD2oUQeshitHNosIfWBcjX91gy"
    "lEQY0YP+2zK2BhqyfK1iyE/RBhWfyFJVFHdnz5QQBJkPnKZJ94n8UtSWt8yrlvzpWv05/6rG0l+T"
    "CTRs9e3LfWrRo0aNsaNNLS2pprzO1l9dpYqltvfb4GvoytreNUWNDIxRa8/sz2nufJvv+9297398"
    "wP14SB8g5K0ZFqEKW0CX9XlLMwgIHSgc+/EHvVsrsmxtvs+Ikjb4MnqR6+LJ2qhL2MqmMHLkrKwh"
    "Yix8t34dNpyp0+3jSTC6hetovoeqlLplGop+U2Nyxd99+HPPXyljCfLtJDOzpjpNScNhIx80xS2Q"
    "7F7XlVa3BCQJy4wMMzAwzMMthouUM0oudXDh0g0DPYKJFEwye4/ngXxqGrl3dL1XBRwvBtyKubU6"
    "IHzG1s6S5iBYicvKFGFWTpaYLuQMi1ZLWtVWLCXSYBjCNtY6GhSElHbqOf8lE6Ginhypgizl38TX"
    "GyBMyg+LydefdLYQmEEsu5fIggE1nPA1vSXlRuc8HDP0B5t511e2jYB38jfLp+vvZfZEeaWhaGTt"
    "c17sUegA3GdiID8Pi/PObSA2StOX389FjdnVBqwF12jk0OZlr2m3qvkL5O7pdIs1o6bfRA4CYWxn"
    "Gn/IOzZsonHWKG1Fbgcadq64tYiAhAhgqrQ+xTFIORSB0LDjNkp/V0NZpb9lyBjz3BrjQPxKA0Ni"
    "jvO4fTAJuqPTp4yda4O4JkJBU6vHHQfuXKyWCV0qoMH3O7nKuR+A5/WaCiO70dLst3cE9ZQLierp"
    "Kj7RdBFYS6Jw8IH54m/z9+wZQ6SGUPH37tl6IFaOLrucEXmiY+CcDtO44l2uWG5Owx15Z6P6Thxw"
    "itTJsN+6vdcQyxPRExRV9+23PZwoyxOwX29zOSYRsTP3pmfSqrYqf4oaV9ZbqJy3SNRZ33fZsaqe"
    "U/DOQizOVq71zbXCdcCjIUtowbITKyWEkQGphjBwX86a1vD+KzC0zPl/oulq16aO7STrWc/BmIKW"
    "vL0WpdtGEG64WTr2woKLs9FBgQtoJS2iLCBVsO1iHLf126T26V6vb2eaOLjrD6I7vIUD1QcxJIsc"
    "0NJrnyScIiAOyzn3WwOZz0BnIYA9CL9yC0AHARMp2Q7iIP1Bxxxxxzh4SSSblmZwhrcSlHphenBy"
    "2yT8vkKcohvRE+Xo3ebuOB5s5PDoY6qbXjeOLtSiExbByiujpMPGDSC/ngi3A7PSok1sxnGlSjd/"
    "psvhzy+b1LMthSoPyU4vJ5IK4z65s2RCRlWqkAJrvJnUaXSxQnd3dpMoaiyGiPXOcowdWwaBu2yZ"
    "iRom8EhCMDpDcZ31rNPJ1S5mnZ4Xgo1TTfhFIlmIxaOe7mZuxhjixye2tpU2C9gk8vi3L3wJX8Cz"
    "mEhEoISXGw9xxy0ZdQQJo6VuFUlUw0b7K8MDaJrCPUhry9HLhw0fDiJsOld10v4UwMCQMfQu0OgV"
    "M0GAwWJAgZ4DQQBo+GkQ8R5m638SAP7xbeza13W97atNr53G1a5uvcAAAAAALmp2WrXKufi1rHmh"
    "N/b289H0Bv4AwfIZcFbFsqC2VsqC2VsqC2tqL6fPL+LCgaeick+1+sRRZOHNVJJ1N/GAT1t5TVAS"
    "5dUAq7w7JjeuWWMWr67ttEQ7LUqIeUyiF1PbJ2UtOVFX2KeG4paqgdx9vjRs7K+Mrt1N6eI7zkDj"
    "pLtdIp9RCxwdZA76DcfrMTyOdzDDFFhwrsQmEepXhAxHBhCAOVom5SquVXp4plFIYooo816vqXLk"
    "p1uyiiiiigErt8SYgbYwznQ6QQLS2DuuF/PqdAAboAMAGADFUe1jruNSSjiR4xkZGRMYxjGMYxjP"
    "FbVubjFGKMYxjFGKMRo8Pe7rw9t3lGijRRRR8nj5ulGijRRsRXeT5/h8QAAAAAAAAAAAAAAANVdi"
    "IiIiIgICAhbVCIiIiIiIiIiICAiIiAgIQLnOcqtyqloiJbVLURYiI22t/GHqK/POKHTPJi/jrccy"
    "+vV29ldgdOARnMLo8hgWdbCDYCtQDioVSwVBSsjHdP0R9Ehi7mi+H4fl6tOOXLk4trzuZsaXe46V"
    "wwaWtJhaXoqeKaDVPAQ0ouQR7sGqgTKzrUabe0sZmpMjVnuoe87Awo9EqqN/h6q4YSOFNcJtwKxs"
    "rRcbPRZpmTrsnXxwoPlNmiY++MZSz5GuDR4wABhAAAhOTgAAAAAByra9LnwJ32ML8OfHjq04lTNw"
    "qxL3ozzbXn7YY586Sr17qTeVtH8dA7V82uIVjbmwNhofYS+euUHzkiMwOIx7uFAYkxqkMibsO7sb"
    "tuBbFDkjh6YbPUVsXxNjQyRrRCtoRIcXnwMnE8qDcM20yjQ0DjYt0iAwxmCiaSSQAEAAAXVtWura"
    "tddAAAUAAwvH22rXinDI0PDs6JuDSb7MCYoNJIQ4t7k/J5s8H14diS2AggHLjx7Ylfq191ErVxNJ"
    "5sB94a8dmmudbP3dtXUI66ZwqlN+zNHIZLOqVnXZ6YVV3q6fS2bVvdYnnS/XLZZVkeZLfyrRRZMm"
    "guL7l7bteFUjxqzXyUNXbGGFLaveGw1eZ+NH/WePkoLVZW9luWN9OjNOrLcysy8/HOuQamzNPYVM"
    "OqmGltLNHGN1mfgJqIRfqvwVR8PqSlNdfHXv07+nHp73szm9rxN9LXoKDJcNCxOLkXlhXFcSdTfR"
    "3snthztB4HGZ1Jtvv7G0arOL3vWT3sKa1Z2xa3r2YmIJIGTIYxj9OadQHSbpNPZ6q9/0a3rPKXIz"
    "50trRIPBxZBOowDIJnPWT37GbdvImQi1eq0Z9BiYZtbceXrzxSNp0v6CawJCGSNgi5KXn/dt7l9K"
    "kq2jNbNbWJTWi0yzTaZkTRqxVo1RIB+SgCwXsfuP1IiYNFh7sUJFkWQUUhJoVcGl/4WG8urZUKta"
    "WxZKxZoSxrWYwoqJqmmaVqfyaW721jN5mLBNAFKZbrDMcYUMz+DfSTWcOH3ebejn9iqnLo15o9o/"
    "AlQN6pfE8O5e2aHGG9aPughdoHIfyhShJJ+4CBCbwvVCQ2h/klh2iqWTejHClrMwt7Zf64nnGqUH"
    "rMFscZ2EPgYNibRMtGjoOgKV6SKSb4co7G3ILdDfVH64UgIcYqg+j23b9P35lh+r7mTIOAp29BOr"
    "9D7IAByqucAAOVVzgAByqucAAACqqpKQgYebjDnycGBzJ7xhubqWLa/A2tMmGwJNoQMX6nYPeyEt"
    "qYRKwthqHlN+riiOrTKgjHDDSTsPYew9gmuPRVOobUGRE3cTkFiAXoUAKUgDqUhUETRp08l1UwMT"
    "u6AEU6dRxYuapW/ew+TN+H3l8EFgiQ6SBCD9QhsO4KLvJDxO4A31Dh13mLmok/RQB7R8S/kexT84"
    "Gvf5CvixvesCuup5Gs1lpxN4jjk6pShIVYmGBu9OIExcrToKCnf2kqVkZy5cytx0UXREwrOYqCPC"
    "Ko7TMRE3ECFVkfmS1uxzqg5AsIACFJoT+GCqhJxXClQAyKhxp/egllgApr04PedlLkMlh1l6E8h+"
    "z/EBNXvUdjpQTGzZtPm8JQhCHvOA5vd+Ja6Qk444i0vvXyL9CY3Imx72GGHPpQe+ERiFZ9XxOobv"
    "A1sIQ+Sz/B+O223UJ9wCds9n7IZJ9ICICJNtMUIoWdAdSpCKHAiGpEC4GuowpElGYXtttWxsbjvg"
    "AeA2RGhA5xWMb9UmSbwsNGJtg6c/wsEwiiW6K9HGjJl9jVgZryS+C7mHsMMkBsmATIYrbEMNdMN9"
    "KGqHDeoI6DDAGNkN9znziC/Ew8TzsRnLGAGATfeTH3kzaVU7p4n7tUt+ED0XaPtYXbaMa90xhN6L"
    "D319Fp8y/TynJTZ8bjD4frdd8Wnp+CTMqq5FFCb9SldIGP3vGt5OPChOOKV3rXou2YS+0g1wzq8X"
    "kmpi7E14oJImmDTiQ5KmBTD8lEVZsdvMQWSo2x2sg4o8ZZao50zDBqQb4mag3Xevr6dcmmiT4Pni"
    "G7lr3Win4YAdN50HPLT52HnkoMtxTChLBw0Jia04ZY+/PutO/Pl+XfnXypDonbAKtjtcmNWGMIZH"
    "SOIJmmi1CRTneaSJZMdnle4mNvM7NubblT82dYYY4rta9446uFJJksqaavQGRBWoJsuNCRPY+xEx"
    "dHalEHcHTGiOyH2E7uB7dtCAbznYOzSZmAsO8+LOJIqovcg0fZCm+mvrrhhZTkRfjkIBzQ1KZJJm"
    "0bDkRiZc8MrMkkMzRNMH7d7tP3lDwlIpwqV27JEr7Pcx5IhCEIQUIrGQHZmDQSNx/bgLUAZBkAgI"
    "7VS92QGZ7+vI32iJ9mwZ7682SbmOAViZjEkgFYN4thzIiWxC77dVN8TKgpJiiEDZsKivyZ3jlkBa"
    "zH0bTGDEK0pLk1phDgb8Cti4gFMFzAkTyJgH05LOexboqP+QgjHxJ/5llkhdUWJYoCMkBWYWypQF"
    "H9/vMhhuhUAdWVgVJFoMBEDQypIskiMkwZCpN0oEPvSiG10FkYRgip+BFcQAjBHrBOSRIkTekTpS"
    "KxMKj9vxAMewmdeHV2Hs35OmKF08tGO7PIrP3dwnGIogtSnGcA3u/1fD7axR8KXUYyh1d3wUFfLW"
    "JQcqAtQCEVj9zrvv8L/L92G0hR9s8Pv+NaZXVU9rsvac0huaiHYXf3oTECEiBy+fl5aBQlxE5QOz"
    "bUhI1RbpNs01pvgQQQHcuweXlrPZq2y7w/ElXvxGvj1bXxauTHbjFzXUXH5OqSdeKf1Ojv56IpEy"
    "ovWedTkKEitUCPm+5ETVckRMf1Ir1+FOm1fFeEkPc+g/P9WbA7yGbLyiFH47h+kT0ExAfj6igsh+"
    "cESIZlCPR+vi4t+9svFfxEJd3gJISSUAPiZlHyBw+o+v82qEWb5zo3bt9JxmkHwdpJucVzthT3OT"
    "ZGIDHuGBj9mz7iIy5qBB93xn7plVnmy63mxCldZHM0OnRN5dWayxMQ4dPtiZq+138FoJfyF+gO+n"
    "y/12DDUkM7k5SHEn5kPsRLPyJQq0HJ6hKJRX1TXxWqirTCKO4UgpiB+9njjRAPiwQfCSdwE1JkiA"
    "Aic/2Oj8WzyBwbyX76VPWIiV32N6s+WWr7aEvYnM+3+NcL6dr06d2GEIWAeDhaDa20LaWhQtpawL"
    "iXUROag8B0YnHL+L531P/ROQETsQjccfSKCYlj40y8HsSN5OcIEYxgc8H9cD3/6miHmom/T4YehD"
    "1vxp/8A9Cmd0+dl8AAaSjqivKkafhEfZiY2MkjvqCZihVlhV0plw/t4p3+J3l34AaofABIuPdNVC"
    "gqABSSESMhGRXqE/Fc4+vUKBw8qcqKUIY6SfDN+FLxOPqcAAAAAAAAAAAAAAAAAAAAAAAAAAAA58"
    "P0PLgAAAAAAAAAAAAAAAaAAAAAAAAAABbDxQ+NDtkREiiJR6a+INpyckAA7YmO9B4wi9oWlQNc8/"
    "vhfakf/JyXwEIeRMXIHXWmvx3d3f40wu6SSSf0QrjR+aegNh8x8TuNpjxHUA+2naNK+BDBPGoJc3"
    "bz1+HmDRin9SzoeEcFNPgDvQkJINBzsom4GZ8Z8hD89bGpiE7Lx9Bh0C439eLlMVWQqTx/Sl792l"
    "tmFmXlVESw6Q/B0OKz+My4jHXcRQSQPJnAsJxViTJG1HhmOBmbdmJptIfaEQ7sBTPGBGoG1AQPCc"
    "6D2svqiPg8072rMIyKWfhhx+R/hE8Faj55TzHhwonjdG1BnEFX6lA8Sg+3kfEu/TcqDIbBESgbB5"
    "3RC5WaesYNK6Hz5OYhoIYHWEhIULpDI7AvGouRk2aUTghw8ft9iZxIQYkIwSQSScp7pq9wdpYUVP"
    "e/lsJQUGIhUKnGQw3azjpOMR19wVYrCAc2fPeh3oGqBkyb22529kc9EKm+tSUvwcZv4WLZd5zNgc"
    "u744uEkZLHP19juEYohyYK+JNhgh2m9wk7sPFRf6L7PjoF8S8DPOSG7sbGEUqUoXOOOOFS1xuONw"
    "JQF7upfF2eQ2S/NRbvopRpVfEKvrBWaD4q3oyEh6vIQvn89Pa1Jx5dUz6E6sn6PIU7y6tLhLOl9m"
    "nwVqoVi0+LlcZr0rNZR++hvSxe3BMkCV7iEYGME+M3cg8oJ2IL2gI992NTu7+Nm5+J+P6BV1/9+8"
    "Cs9KK/mv5RD7B9ysQM06R9qcAP22EofrPAdBbGCvoEc01DMTIEOe3y0tk2vtXt9x+Q29oXnABi5J"
    "cfHXnzMzMzMzLjmZmZmZmejy/CqygW04D3IzkJRMRf2ZH86a3Q2p3Var7yb6fiE7zR9Rfk1rvfaq"
    "9SXt76W0tuEc9uszMzMzsmNez5mS+QeHgp4J4IbszBDvoWzBiiFJQogHVWKskN6UsPcCn6RJpArM"
    "ahiHIkCiAenlHSKv4A0M+Zkiea2fU0ElGHnabRF6iLRqdjKiCiyTj/T9kfwc8+kpFWG17I06A4wg"
    "X0ODsgQmdA6zWZNTWzB96QvDNKTUsKDjP+UohYf0f45aW8Ntr4ZU7TN2pbi4CsjfjECBHETpULK6"
    "aOhmyKQgG1Ond/RTi/R18CZAv9PzQQiESH/fV8AYBASe6iwvlwWylFtyGgQM0LNkT1vnFGS0RL0u"
    "XXs3ldT1G6FwPySsk7IXiBvg7tWgsTkRFnUG+xKdVup6rUO5KD/AfR05nNNoZeJhrXPNJrcyMcfJ"
    "JM7tQ1SkDHaOh0+svbR9cpB7ZWxG/ekFhKZBvWmmIPvrj8WkazY4SM89Of0nNLeTgzZNwvG8Lj7m"
    "cPayflSwq4B8DReHuxU9xXrlvYYhIBbl11Mkpj6h1aDMQkkfgnjitUVjnqoZh+6dvOHm0c4Yp35Z"
    "CYTh56ENBFXrmVLUjkvyEE7bBMmmSyMpH3uYQFFvHn2oeDVQYcCEglWUchj758bhwGG8z0nvCj0E"
    "iH44LuaR91HGbwIkl3RROn7H21QVqmlZ1iHzOYbJemjedaL96gmSL5tN4wnyV8pN4N0fPM8juAsa"
    "OpNktKCAGyAHMd/alKXD6UgQ4Ph8jY3jp2/NXSYtdIfszEg1JKlfiuH+/8v2/X9v3dPDs+P6fo+z"
    "2vu9/n739vnVEfSopIH2Ev6S4QkJCQkBDACF1Yn7n+Y88Ta/s+gt1/MUfHZ/U8GKKq/q9tM01ctx"
    "SSKj8hn9dQjzd2G/F4DXNAJHdPkllx2XitXhtKpV6mKZRRRRRR+pm4xjGMYzratzcYoxRijP5Lm4"
    "o0UaKIKC7AOsQDs5nQEXOsUFBiZYhvp8oeQ98OE2eEsWD9otGK/hFXMFjAgIn6gPyGbbwuRIhpyt"
    "5E+BsGDoNQeckrmQTRlY9ZP0D12d+Zw84/OA7xEyXjwSlm+Ho+7lJWs3GjH3zkgQSE83BO4VqYGG"
    "1DmSx3MeRGAysFQ4tRxHEfwIeGP1T3Ile59IWaIX+Qkr9Zb4D85fmn+I9nkC21RFXD1YBrRVRFVt"
    "GiSqqiSLynJ7AXKTyw8ogdB8ZIr98HHRGEkn5R/KhnPG73hPM9P0aqjWFgrsaELAd365PipZJCQp"
    "uiF0PAn4CCfmIiYLgPAbUIkWJ97SAU6DbkUU0TqgtJAhE3oFyogSJ+JI2kE8xvXY13bFQJyyBPiV"
    "tIj2Gz6YYQsO8A63y8Gg5jwEL8xmfITU5vScy35zgKJmOpmEYQZGE60PyOpw7Pel1NZnwb1sj76U"
    "nDTi5ashcMyos444lWHMEhIEvjNZWONkMbQnvELv2SrKworAAj2BBCw8TZDjyEOp1BU6ygo3R8jN"
    "5566utV7AAAASAvLXfmIG0B/3+kT0cMlQ3i6hFeJZ4Dn1ETqc8D5Xc5wPZ73ltqW2to2tG20aNWl"
    "uOdDcZwtJvXtCVlTAvJJRduFN05w5jqX2UopYlzYodacoM43IepV3QLu+O/BJggHQHUEhAFZnItB"
    "jaG9hg4BWME56PT6sBuDbaVVVVVVBj4HYek60YztMMPOwnvbJsDArDzjPdE0jh25ytCXrgkq6017"
    "3YZI825vQr1q17W17tADQrpu7szZzQxqbeLAmFENsGvJCEk4yEQQOIJK0avqx8JxYGNINzIN0Jle"
    "zOzlA12DVJTHSlM8ddoMWl3IviYSkEYRYIsItNrsxQYEKwaTVViZBlAOHrEe0kxeHXSQNvPnzomw"
    "zdOfGsYxn3FvvvptyLMz97CL3fbOussTfG17zN7wcRuEEH0FoYh3HdFD7z69JIY0TGkG1SzNqht9"
    "7M7uRzWyOfDmnTp06dOnTrOc1NLmaMTEta741muXBnIpOONccrwaulSjWta13t34bzKFon13XVJO"
    "IvWKx2hLWUJhzcdNzcvHXtte2YldNFSTWFkIRTkB53JYJ6xsOqE9fLMCiBRziQliEsgfb6FVVVVc"
    "Lq9zyb1a613u8AABAAAEAAAfQ11d2vQ2td/dTVzJ3jS6kjDVHAjCcG4CixZY1Ak3t27SDg44Cdwy"
    "JvQXBi5qINH7/SXcCoJnYmyGVhM/YvfsocI6QC5yq5PVGG55g2gHxCQ8rIcRLQ8jDro1dURdh+YQ"
    "RBEUbOIkBIkNSRJSwFCQQsPWR5T4VCAiMifXVpIME/epSM3ADs9ROQJA2d/F4dtYCnSySESEVGEU"
    "gOqUtTZZqWUpzm5amhllDLEUk1z7m9W559tu9qrNVq4hNgfTBLPIvoIQfRNz+kf5e7TcbS9QeNTq"
    "QBiZwY2UDbDKZwuLgg1SK0TYg+ZaGABmSKth3xBNhFRkCBAkgwEkVgJEA6iEoctDMKVDV5Hei7tQ"
    "Dz922HCGkc4gCdmkhho6cF4ZY6DRzRkVRSbhyQ3DXikHgGYAHlIgPjhMp5Xkvf0dzvYhlKYY32NW"
    "Cg3OGXekTkjQHGoAnLxI/H0jvEDt4O8Ue6nD1hSInJsp8xGSSUuLPy5HfEsqUSZAc/ECGKKSSKAO"
    "vG9ldqDqNYw1iLrnRKOkxDcXweVFFpdLIwewIn7mKVlnbkmbQHpsA5g93WLqGrldKcWtOaoRa/hQ"
    "2s01UlFghRHdOVXVwIgaiIldBBD3QNZGSCRUkAIAEiiVoPo3Hj1HYpZeR1MdiGIQhM6EDpli40lz"
    "MNMjHwxPANmj4o0Ryb6VQzSCG0lIIVUlTow/EmQk6WkWAf5b/+YKfCqEL6bj6mFYwT+aEOTCCCHz"
    "Klh4hFsSSgqlpkYeyF9tYCQJA0IBloDjDClDJcS5CELIMZwG3KioQhZLqyOAokxSowQaUe5bbSiF"
    "JYGv6TNa830gFBYyPtSAQpqueHMt59enr2PPXx0TWRLSWwG27sAapxiEMIE0bt7IZ2OpH4dw3+2n"
    "KYblv5tOzNXOb7qO/VA1wAKkHAC1PCFpFy6zoGRBXPFiGSAcW6hR+6VBPPGtq7QykooRYkLDC1a0"
    "YMH/rE91MFU5obicTSSoK1koCwjJKmmFghPwgDJvZoCKT9D47NZ+0DQcggIQW+2dVqn658F7wAsF"
    "NIaPLcsh8s+7snls96EzLiJ0L+XnIeRAhn5gpESKSjJBtLZRGSowRSKF7t5yYHc8nZy3hNRkQB2C"
    "rFPVbHQvPS5v3Cw830y8npTl6MBbZqXoTu8rXbse1Rx5w1zmi5MGQc842e1Ly19xN59W86HHIavl"
    "VGBxTSEOpBD3fQCjsjg7iSD6CDzwdSHSTrWsfP/GYMQonttoKIm6CrBFUKRJxJiVJwRKZdOdtlmW"
    "lCcbNYamI5Vm8MM0i5jbMiwMMzLRMlSgWI5Mw3wHGtSTSJsMgMExRbKbKYZRpWEIUyEEoYFyrVkB"
    "umhTEBwttwPbbwPnR3KVHenYAMKiqRnKDIcQCAW6CLYABTBDDFHTo4wgnhJKi9DXbclKyElPXdVK"
    "0DYVTeIG8IDaEBgkAIFDqdyqW3WzPeNJVcDOQsQLh9oa7w3oBEQ+iAIv8mqmpIsXyyHPxsqBueX3"
    "c+XTmeoQMxNBDiGDNj/phxGQzBMncUYfEmoeDX35BUfMhScZvBx1mqmcQwQJv4zl9kIHEh+Dfk3e"
    "verR9twMiha9/c6RaFLMahgQQ3/Ge1db35+EYP8QJyihyDGkg7L6JBKcvM+wShIQmPp+qE2bYwNl"
    "9hIEkMCAkEhBOsy2OjKLSc0msTLHLMdGNlLmSiRLcwewMPYYGsTBmzQbmi0pOKBghkGRZzEJBtBC"
    "KgUtmgSYZSQUC2y5vqFenZxDgXfZmh62o2ovq5tL/V9egY1XDRyLOUam1ofJWHcZxJcmAH5abY4O"
    "h3VMSGsN+rnW6xaX4sqqdod0HLqeeWVA1hBrta+mjWetDQxXGnoRsKbPui+rjHISQQxvttJpwxFx"
    "CfhuytWFyk5YtnYymSaE7KkiPUV4xy44tZcwGXCiCIpspbLLkQrxmgYgsEFwoO53WR6M8MNyjDjL"
    "hXy2FVXm9o5tm008CLoYwKm/NTGOmysNTE44nSYc028JOWN3ScS5NMC6sm5pQ45JZuboZQ1WChJQ"
    "QASJIE1oMisZvDjUTWazezgoKqqqqqgADACAAAAVVRVVReONk1m0VDWmzW0WBC13c4AAAAAAUAAA"
    "AIgFzt1zd7u/YeL0fa6bObyjoHqNzhcF50g8InIvitpmkU4xVw2iUqxSKxSAkEYoEUiDRvJKzEvO"
    "8Bw73LrJnOXbqLqMGRQNMjGmmLTKLXNnF12c6sHM0Yutm6LMOgbJJ2GjSKosOqVUFuTXUukEavBd"
    "7SZLeCSY8Gg2iqLq2toyq0SsePEVOYDkiGY2Zlo0kchCFEdoEhHISjXgyt1vB1qTag1GjbYyVgQk"
    "ZBuYrk6sF0gmnYBmrUfPCQZGQK5QosIYkWDZcoWGFgUQYCSBAnAQhUBkJGe5QTx0PH3B2Syjr1HK"
    "9NlTmThNNhD5j+hj3CtujZNeFXKKqkrrMroodMl51NX10rx9+MZDCtDmY1dCEwZJcgKhCCyGTgLN"
    "Ca3dE2ajgBsATYOoNAHLp7tNyc+gLiIVZpgZyaXQwIItcFjYQ5QwA7bCGOkyiAkIq+2sgRytGlZT"
    "VlNaQimVsIqEFYKIUQUS/AawQI32wEhADiUXmzO2G3ZZwIXemaZsABOnYGrkunEb+rzN48AkSJAi"
    "kgARApXt6SoRSHQNASlKOsyF4J60GaBm5go5WnXjzncQcxLdaJo2ZBaBCvjs8nGF8byuvBLvDHgE"
    "MMmwRE1qCbCxCXEboGnMUQcRaB2YqQQNoaBANHDWnPMzDpPwJCARFCCiREQIoecbXzEBOCdQrGQL"
    "Txt1lR1d7Mw5s8oEorm5abolfkIvz1gT5vnsLlh3RIiLCqkRFCQOtvDMUxNBKSRBuW4UAwb+bUDa"
    "UGkE9yKE/ccsLLdYlgjHL9egk0wwNxmBBwI4oUEQrhBH9IDAasIc8PNo8w8nk2CIG4A+P3by3g3k"
    "9sAAAAAAAAAAYAAJSSSSSSSSSSSSSSJMSSSRH33jvc/Mt5brWt1Vz0nLsINxAh0LBKJPHe2Hngf5"
    "gcSiOEDQQwXRA0G4PFJBpoNqXLAY1M/gPcNwIP44Ipd4vIcYiOwUGzXxciC9g/EEVYKxwMMuNAVI"
    "ayHRN4QIX5wpVPM9OREYdvBB+VFKbYAfRn2kWB0CQ7UAi+DUTPkOsMVELZVgP9sZTcJOUO/3jwDX"
    "wblGEE9es034N0WQEIkBYQULUAUGwBeBef2DuKAYriOGmEGEFBkYRTdCpASc+4lDMFY1qFspIe9W"
    "A2TcM4QVwURkBbkEqIYBqLihSFfi4Kuw9P9XiYQB+frcyTYNw+a+ErXW9Ih1nYFh7txVXghrDL9/"
    "BhrU2Mn94Z3dCSAdwh2cnRiGchNRm5TPAqIYJgFTDBB2wRG8vr630nMwyJtc4bJYpJwuDBRkWALP"
    "kmD7kWSo2yUAy44SECAik+zIUpUUwQHEQUoWh2tdvg5td7XxxqaTSWbWtFsWKxFDICholhlmhSsH"
    "7yCSKyEZTZpVru8V2VitRqn2nd1Xwd/6vfo8KFdC9zvx+qGgZBwokdC88mIRIwdATG7LIEKzbZKf"
    "3WT3ffKE3d0PhZ6Q2e2L5QwCh3RWfbQ7O1CiXBR1fvAfrDlge2T0nBYUoxSkAoWIirEyHUkChpAO"
    "etIitcMzY+Rts5n5jhq9ct2/h4LIqSCxGBxnhDs8UCiEPdKCgIWOX6SmKaXRSI1igog96a+4w0bt"
    "Z9nR5yty61USHEcyccBvrIgA1QD0RCQMaKbwAaWCkYMRIoM79DUQcQYtUSbWpKZaawpQUPxjPKBk"
    "GVifnHifZrgG8b2wa6ADxuvUb3g/NzQDIfxRQyADewm6B4nuyDrxBFkAHlDjX8Fn3Eyh9Ud8e6CT"
    "Dc0kgiY18nH/LOBPi9zZvj0oQ0WqQ+tJ74P78OggyNjJEZKiqT4VVU+gY/B8RkULhZulk/ULCkQy"
    "m2ZwIsCgggxHEs4tTlZPvt3u/6Ej/q/s9dRQ6EeXLqZNTGWXSt2nRxNcLXPl4zOWIYGygimrKYz8"
    "riGrE/jQoWTnp0rZwUWbF8hZQWyHIIeBqemhQ+UkiLIp9ceenVVL8HAgazlgPcZISpGpFXg4XlT/"
    "He/WuuqpPljRG8Xx9j1+ePnnnGdlQLztvSWSS7VU5uUwUJSJuKz5BXLxp8+RoqaSTE8AZ40bNGVm"
    "rtvp+kWIriTbXoNulNliUGNwNjxUBOnoO7oeShfv0m0+XDgunFXKxS0iIQa/W40lpbLRIXRcgdhx"
    "DfxBeYlHcIJCKKRFuYhQhRAIw0HrzMOHTTR2RESt+lKiQzDogkiHHzdY6IjUqLRlVGCdgk0CLqao"
    "ZEimZcQGtFNVpTCi501hFhIm7U/BfxnI0dSymZxmmVMvA6TR2pYSBumkPWmuGEExVqWRIoIHs+aG"
    "jfQaUhmJKKGBpD0A9XEM24iSJAmySE/VnMwnkIoxUUiIOoi8pw4LbuNoJECf8VZsSFiBVG8TJv3d"
    "hT0m/VT0/3u5eU2gy6Fhd2WRZHbyVlir6LLPGImUdCIxgrhYVC4OVBTJSsMGmoQsIWEpJQgZNGjB"
    "gyDBYdCB7lM0lYyoSQsRZBA06omIlkAzEEEMTgiJkEQ9yJAM8TXyreh3wNmKpqsSSEInGUEHoQmI"
    "ayHmoiaR3RG0EDYUQD0Aqr2uFxtIRaYMZB5ld0CAokFeVunGAeyIMIpECALm8MZss59oQDmtTnEF"
    "qIwqSEApVqCE0SCERVOa9yg0Cr7PJrM5bBkLlHekyy11nO+BgKo7dsD4t3ICRUXKE+GR0bEKYzuw"
    "Zy9+2GTzd5iHpBB7Lg8aA7QyIxEIJJQEYOUOAdo3UUEEiYknMjeozEhyuU0keCONioBiArfE9L68"
    "k6JmpnKuWNjmYzywIuURgoxECBGHLwgCG3E/r6FBDz+Q6bv7OYZjghA7YaBHkeugmTF71EuEXPnT"
    "xHWaIUZBPFPHdr4+MPQEgCgLNi1eVojYala8XmnzeS6W6XGkpXORKVwFM3IuM5M5xXLq3xS2zSJE"
    "g1ESaTKMiKZKTaGJqjRaWrnZrsYzcBJGHFblZNC2A1LKgUpRpYkKUECllJQoqSFADCAxyHMXF6NE"
    "oAA0aEAxhCHDd3nflQG9XeNnrJ0TO4UQNVB+PZTw4dIiZt4QIaRB6mKLgOFRAx4g6w2pZ1VenND/"
    "7d6nPqHFU1UuyQzlRJETIuQscrYMaCihiWIzsaMcjUYkLWsYY/frUyTeQWwaNfOdJAJTejp8O/jl"
    "usCE0C47TWKJl9h+0LbwGk12UO3BPQ/D7H8ZoPP/r6nocl3fI784n4KIZc2yhA7X98MiqEbCoMgn"
    "mAIv6DR40gr3wkUDOPSCGZADXBckwIwNkJU2wWBfPaZIMNgmRTAsAKgwgUg6o6jt2CKLmZeJq66J"
    "5ySjNAVIAgSKrril8CY1eCSFv8kcVIEkeBZW4dW6KWnVimlmQXUqQgbih3RN4ClKUijiPQctapt2"
    "2yraNtbGtZKK0U0hCwRhybIRSRCZZLEAFAREREEREZoDMIVkCTDMNQhG1D4BEAyQzIIZ2CjRqhui"
    "dk/4Rck4IeYHDEPbir1RWR7WIh44pac+KU5wOjk02R/gYmwxEPeB/EQVUhBPYRAF4jhpNMVVv6Bb"
    "t4sQA5DdFaeqUFTxES0kVhyKAaQy9cVPn5eBXywNwpIILIkIVkiJCkQDcnfy3NAoQBESMCFCCBYI"
    "AIwnX1AeFvNrkYSoKBUKeiUwSRAnNpDgOs4PNS9wsCDIiISRSDIKicdsx5aoGaAAZxJA3H2ojlqG"
    "3Scttn7O5q8i6JP04d7vqUghP+eXAWQsKxVVWDq4LAYH2MN7uiLIWFZGFUaQjIhPczPXVvS7oTRr"
    "eOX9JBMqOro02aKqYjmjIMiEHx+Zm7IQ/in20xg6LjhPEuOZSmoNJtA07N7yw1D0FXyIPIsh7+6Q"
    "XEYETEAsszJ+oMAZQXJVyYAqbHlq6oTf9NYN5AzdB84BLDigIEFU3CYB4zYNV83k4iP9xE9AvHzz"
    "hp17119HudPrQA4eGdgoR6HWAlUOQPqxXggq1FfOgUQRIDCB58LMGIyVAkrAUGDCB2pOaHjW/UNS"
    "aPouOWUBSTbUEQYsCfV0tnYJ8pkFmmpuAcEQA0QMgQLQ4EFKFQ0IABmPggHSc5vCsQWLGKVDSImK"
    "RjWiTaZpS2y0qba1KRitKTTaSWga1TdpqrXh1468sIaqazINEkpM+hFezfUY0cU3OW7Z4GQBQSLZ"
    "yNk3gG2giBtyXZNQPPFPtFjFJF2FECB75Y76RUiSJED8h/EJ9BiEcMSRqz8MK4wUUaJ0/LTxQ5yQ"
    "PVAw2nGglQHuQ7gcYOUAoIjQ8kO6GhhIyDLIFGKPfinw4smpGFlHVtkXXEv7+C/ihYHi8PnjmH4x"
    "S4OBAfN9Wg68qFOSuQI3CRkGQZeAJSs7qdOJuXNUCBeNOQZMLkr1bgclebSiAtQuIZgFkiUZpsFc"
    "kgFqJyZmVkYsz3bMRYIw1afwneIiIjAvNnMk3CwQlCypW9RdYGpowQxAhMnNhqVuBSy6EkQSTIej"
    "9/tzRuTiYI1STFiyFlC0TgQTVTM+dTIbCCPEbByNZQ3jISxAGURApgkRYq+n2iJ9gRCQEZJFIEEN"
    "nY9/ELA/MQ3BxkGEkVgHL1And+uMAgHJRU2CEPcwAVKJmNhaVVfmbpKsMRdYaCJIicsCopIb45ff"
    "MckMQNnVutI4ZuNEOA4pADZ5DhMnr4Bk58HzXqZaNzCxcKYUyY1CzHBGLCylmMLlcZlmLcpjiFrj"
    "fBQyN4fhZIpqCzA5Rgogc287/g5sOdd8UU95xjRdAtpCAaeB+R2FHffvlJ0L5xOAcOAHegu44WRS"
    "W2BKH9P7aquXCoEgi4FUkABXh1Hi5ATpvcJsDoD1T87PJ2wfpaSe+1Zl8JFg5aqqMEGEWxAOMu0R"
    "seK3WXvLESLAPPfJmPFg4ZSjEU+9Ki8zxsxxl2SxjbRVUSRgSSAwStNOEEskEOlAHasEOsSICj64"
    "B7ZZo+kTEYIB7kQ+PdRgP2RKCLgyIzuiCKaTu7zWAIqYxxYVEjR3562eFaiQwpUuw4Kfox6u/jge"
    "nYouXi0uJiyM5xUta2MaIrz6ZzVPD5ELMEkvHslqh6bZ7QxqqmqeGS102fM/J7rTm2C19o13MMWT"
    "Zpza49VeOFNa9Nwway+GBO6cVm1wVaro3eVDmlPCZwdnUsnOGhHDI9GdMkN9FXzrGmXOCQ9e4aNi"
    "sViqNtZS20rZvV1pbVJYW0tpbWyjDlZLgUW7oluZcu6bIWBTGLRTtnxx0S4TWtt9a05M37ZdGVut"
    "3Zxy24aFmW3fGHEN80kk7VjlLaWur1fGpA1r3h8u2rtVG7WhBlacciEPaL1qxEaoQkyGIdCh7Z6m"
    "Dmzdj/sIzpYfZsScN5ISU/ETwA3sCSkxnGLOz5cXJaQrFyHHByFar8rXMTRcfFWgkIGHYhhxh2HZ"
    "mgMNFVgiTOhPPO74O0J5JrnyGHVVRkVBXTTQEzYDmAUhQBoZIHME50SFEhFfyZh2nj06IWxQZ/0c"
    "h699jo4dkl3QAjSggeOaPUtoMU86d3YeUoIrRYfBKNBA0n0gLsApsDxIqKGYaEBhCIEhqzEQsxx3"
    "AK7RDHM5GNEcE9NULVZ1UEPIkNIGE6hC9moQ+k++cohm8oUfaHvw3mWqW3SdC1ZfRTT+puyyjl8x"
    "loIFeru4/pcpcHL1LrGrt1ogAZCZoWIf4wwnEO0goSCJsQCxGlOSx38aYTPE+86Ha5SO1QIx0AyI"
    "nKIQWCQEZEPELASIh/WAoImRaloQw6NBpg+kiBESKbYVFZG1Af01ViEC8R8rlCNaURvuJoCDKofo"
    "j1bvo86TBp9MyYgMMBfjgQ7wlddDrHCyDHnPTHtDAtJLYlRQkJEGZpqRkR0NXOdqoEBgRjx08CFk"
    "0r4buqfAESDgJHmmgQRSwgh+QigWAer3Vfn5tg9BCSSDgIUdpDmECEFeis2ePGk7t+RozCZSvZRg"
    "MmN4pllB1YTNxKgwNIctdeLIXeSquJM/v8aFJqMGlkRBZRERYVKmyhYaxTpiiyIZN5l2JBxQhRni"
    "rWRYDgeAUlMBMFlfPuOFpnNBJRAcrQ0iIWfLmaDIgaYppyoNEqMSLIFVSYxAo9BOggTsEmgQiMVQ"
    "1HLL8Yea6DCcANMBmUPmnVhFZHanoB2mclwtBAA8wpKCkHSGTi/JvQz0eFxPC8P1BzI75m/IRpX5"
    "51ETViPG6y0EvYvkiqdGdVLZwOpCZISYgIIQcRElgIixO2zutdaMAquc3b0hqcAczIIQxJMOeYCc"
    "wRSTTIDEusywMGJVJlpxNbkASipSCwPQXJNTgQSAIwbDrCamB0LzWBGYZYUFNkYFrGkDyIJAciQV"
    "irbhDi2YB6iwwaXTSifCaKDIyAzNey0GBBqCKQUSCjpAzE1oEKRWrqqaCIEG3lvuHCqm+sQHp86p"
    "6YrIASveQDnAiEQoXfwQ6Lvib28hxA2z68rXwMZ2QLE1+B0bqXIRAzBFsPCfTADiKpDfhRtTvZMY"
    "M9w1POUUDBjRCn5eWhO5A/nHo929nMwMRoqR09MDhdaKLfNGBGSTR+arTnxXILDJAgQjF4lBqvrM"
    "XVQCjk9Dgd2JCkijEQhCZEoIa0xrerMYET22FMtKqlKYFNKASJAhCJEiidynAT2wnlse08EmmGkM"
    "FS2GsrMRBYQIYwFjgYHNyUDOBiPyqAZJuLkhtOksMTBEtJYMQEWMEQo0iFYpYNQsgpgNoYICQGSf"
    "J7IYueDIUnUMBODtMpHqj4wBJBFNGKmXVvjxIFCxBhg9ufZDmmzA0aoGcIFEIYymZZkIG01lMk2m"
    "0UZrWmLNs2lpK2Qt5EClX6PpkPqMm0UEQ1wETh6ttRQ3ECYh52GMIVl1QCoDBCCfOdoTgfXgthxH"
    "hy0GYQHENg5ATDsWQnJTQRzwfeIMayWGYAnvqKoqmGQh1nzbsRvucuS9lvldVC93hb6vXCq44JhM"
    "hYUu65tyYozbOcLkkYEkqVMtWj3uhPaZ+Q9Lm8agbD2zr8KjvwJzqp3oBYMuFACITzFJSovH+Vqx"
    "BPjRPoJGIkJACCLnQQ1inI+/NvZUkngQsKI8Pimset6ekD6/B/1ZuiH0ERc4sgKxKZCnym/nB0G5"
    "fv1dNYbF/QnQ4J3u7megOQBk8kDReuKzIQGz0wWjI4Qo7MURHoWCnqgTsZ/cKoNAgXuWhmFLsBfk"
    "6NIE7tSpVShiABAYkKCHAQGyeXgcAOjkoP7DQNDt9xoDqCUnlQqx+ZLLQr9dMHth/PTPMC0GS0Cv"
    "SDjDcn6wiwsalliQsKJLFIx5+sPqO8/fIDUzz6QEx/fWuog4DpSHMUz2Czx5Ua5ALgegQuRb3IQz"
    "UBrCIJsLaRCEqS8bjBVFabTTaUKRUazZWaWlpqWzU1NajgNENK3qCpLUiMNIkAnxIrcAT3acZQBV"
    "IjBYMJzjIfXlAv4bDBiG1FM+mCIAMhCKRQODnxOxwAA7ZCH2DzD1IWrQTzYIKPJCjMRL4BTF3lia"
    "NEEQP5v4/3A/4shOZ3onSwkDQIewYobIG9n7o6BFFD4dx82u+esyuXWC6bNlEDrbOS6N6S62auP3"
    "JrVJmVoQkNceaVHOBjW0tUqGI3nF96ZFYFC/tjYsXYur4u4Koc8AMUUDVkfOkDYjWxbKFWaptpNa"
    "tELtDXyvm9lWdD2oA5YLbH/QoCRQEtUQ98AV9UQD6DuO71IiTn2Y10O/67EROv+N5vnFy6X/21za"
    "9OA0aLFtPzfTo8j8B5THH01kZIxkUZGVEkgmIiYrmP7Q/2mSjnJEkNtNQCyoEXXXQy9mgImcdaIn"
    "zGz6OzOqUVwoa/31eYVRRkZIidw//F3JFOFCQZU8kTA="
)

# ── Extract + compile ────────────────────────────────────────────────────
_BUILD = Path(__file__).resolve().parent.parent / "build" / "inline_k8"
_BUILD.mkdir(parents=True, exist_ok=True)
_CU = _BUILD / "flash_attention.cu"
if not _CU.exists():
    _CU.write_bytes(bz2.decompress(base64.b64decode(
        "".join(_CUDA_B64.replace("\n", "").split()))))

_ext = load(
    name="fp16_k8_sm86",
    sources=[str(_CU)],
    extra_cuda_cflags=['-std=c++20', '--use_fast_math', '--expt-relaxed-constexpr', '-gencode', 'arch=compute_86,code=sm_86', '-O3', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__'],
    extra_cflags=["-O3"],
    build_directory=str(_BUILD),
    verbose=False,
)

# ── Config ───────────────────────────────────────────────────────────────
def _find_best_cfg():
    cfgs = [c for c in get_kernel_configs("all") if c.dtype == DType.FP16][:40]
    B, N, H, D = 4, 2048, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v, o = torch.randn_like(q), torch.randn_like(q), torch.empty_like(q)
    best, best_ms = None, float("inf")
    for c in cfgs:
        try:
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            torch.cuda.synchronize()
            e0, e1 = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
            e0.record()
            for _ in range(3): _ext.forward(c, q, k, v, o, False)
            e1.record(); torch.cuda.synchronize()
            ms = e0.elapsed_time(e1) / 3
            if ms < best_ms: best_ms, best = ms, c
        except Exception: pass
    return best

_CFG = _find_best_cfg()

# ── Public API ───────────────────────────────────────────────────────────
def forward(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """FP16 flash attention. q/k/v: (B, N, H, D) float16."""
    out = torch.empty_like(q)
    _ext.forward(_CFG, q.contiguous(), k.contiguous(), v.contiguous(), out, False)
    return out

# ── Self-test ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    torch.manual_seed(0)
    B, N, H, D = 8, 1024, 16, 128
    q = torch.randn(B, N, H, D, dtype=torch.float16, device="cuda")
    k, v = torch.randn_like(q), torch.randn_like(q)

    ref = F.scaled_dot_product_attention(
        q.transpose(1,2), k.transpose(1,2), v.transpose(1,2)
    ).transpose(1,2)
    out = forward(q, k, v)
    err = (out - ref).abs().max().item()
    status = "OK" if err < 0.05 else "FAIL"
    print(f"K8 [Reducing IADD3/LOP3/SHF]  max|out-ref|={err:.4e}  {status}")

    # Latency
    for _ in range(10): forward(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200): forward(q, k, v)
    torch.cuda.synchronize()
    ms = (time.perf_counter()-t0)/200*1e3

    for _ in range(10):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(200):
        F.scaled_dot_product_attention(q.transpose(1,2),k.transpose(1,2),v.transpose(1,2))
    torch.cuda.synchronize()
    ref_ms = (time.perf_counter()-t0)/200*1e3

    print(f"  latency: {ms:.3f} ms  SDPA: {ref_ms:.3f} ms  rel: {ref_ms/ms*100:.1f}%")
